Remove mentions of point of contact & update FAQ
hackclub/hcb pull request #1102
Opened 2020-12-20 08:20 UTC by garyhtou

Added a FAQ about international projects. Let me know your thoughts on the answer below.

> **Are international projects, events, and clubs (outside of the US) eligible to use Hack Club Bank?**
> We are currently in the process of building out our support for international projects. As a result, we do not have a definitive answer. If you are interested, we would love for you to apply so we can hear what you're working on and whether we can possibly help.

Also, in `application_helper.rb` I added `help_email` and `help_phone`, not sure if those need `.html_safe` 🤷‍♂️. I'm new to ruby on rails :)

Haven't been able to test these changes since I'm having issues getting Bank to run locally on my machine.

2020-12-30 01:08 UTC, motdotla requested changes
great stuff. thanks, Gary. just one request to fix up spacing.

2020-12-30 01:08 UTC, motdotla commented on app/helpers/application_helper.rb
> +		link_to '+1-360-502-2935', 'tel:+1-360-502-2935'
can you clean up the extra spacing here - and the methods above.

2021-01-06 02:47 UTC, garyhtou commented
let me know if that fixed it!

I ditched vscode and used rubymine to reformat the file (is there a preferred formatter like rubocop? or if rubymine's default formatter fine?)

2021-01-06 17:31 UTC, motdotla approved these changes
that's good. thanks. just update with branch master and go ahead and merge.

2021-01-13 16:25 UTC, merged