Allow users to modify event slugs
hackclub/hcb pull request #125
Opened 2019-05-18 01:52 UTC by tmb

2019-05-18 02:35 UTC, lachlanjc commented on app/views/events/_form.html.erb
> +
```suggestion
```

2019-05-18 02:37 UTC, lachlanjc requested changes
Looks great, let’s just add an explanation of what a slug is.

2019-05-18 19:16 UTC, lachlanjc requested changes

2019-05-18 19:16 UTC, lachlanjc commented on app/views/events/_form.html.erb
> +    <%= form.text_field :slug %>
I would put my event website URL in this field even if I wrote this form code myself. (Sidenote, does typing a URL in here break anything?) Let’s switch back to “slug” & add helper text explaining what this is. For styling, use: https://github.com/hackclub/bank/blob/master/app/views/g_suite_accounts/_new.html.erb#L35

2019-05-20 00:13 UTC, lachlanjc commented on app/controllers/events_controller.rb
> +      flash[:error] = "We couldn't find that event!"
```suggestion
      flash[:error] = 'We couldn’t find that event!'
```

2019-05-20 00:14 UTC, lachlanjc approved these changes

2019-05-29 03:23 UTC, tmb commented
waiting on @lachlanjc to fix spacing and then we're good to merge!

2019-05-31 16:46 UTC, lachlanjc commented
**THE DANGER ZONE**

<img width="517" alt="Screen Shot 2019-05-31 at 12 39 33 PM" src="https://user-images.githubusercontent.com/5074763/58721070-e9fa9e80-83a1-11e9-81c8-9eeb4da794ab.png">

2019-05-31 19:07 UTC, merged