Custom sort for event listing
hackclub/hcb pull request #1356
Opened 2021-03-22 03:14 UTC by garyhtou

#1156

I'm kinda suck

I changed `Event.reorder(:name)` to `Event.reorder(CUSTOM_SORT)` in the new disbursement view to test, but it seems to not work.

2021-03-22 23:32 UTC, motdotla requested changes

2021-03-22 23:32 UTC, motdotla commented on app/models/event.rb
> +                      ELSE name END ASC"
looks almost there from testing the raw sql. but needs a way to still put event names that start with a number at the end:


```
select * from events
order by
CASE WHEN id = 183 THEN '1'
                  WHEN id = 999 THEN '2'
                  WHEN id = 689 THEN '3'
                  WHEN id = 636 THEN '4'
                  ELSE 'z' || name END ASC
```

2021-03-22 23:36 UTC, motdotla requested changes
couple minor changes and then this looks good

2021-03-22 23:36 UTC, motdotla commented on app/views/admin/disbursement_new.html.erb
> +      <%= form.collection_select(:source_event_id, Event.reorder(CUSTOM_SORT), :id, :admin_dropdown_description, include_blank: "Select one…") %>
`Event.reorder(Event::CUSTOM_SORT)`

2021-03-23 18:22 UTC, garyhtou commented
Yay! I think I got it. Thanks for the help 😄
lmk if any edits should be made

2021-03-23 18:46 UTC, motdotla approved these changes
nice work here

2021-03-23 18:50 UTC, merged