Generate ACH Transfer Receipt/Confirmation Letter
hackclub/hcb pull request #1372
Opened 2021-03-24 07:30 UTC by garyhtou

#1191

2021-03-24 07:34 UTC, garyhtou commented
Getting wkhtmltopdf error. I tried installing, but no luck.

![image](https://user-images.githubusercontent.com/20099646/112271565-52320880-8c38-11eb-8c68-5e9f0d0492f8.png)

### My dev env setup:

Docker running on WSL2 Ubuntu 20.04.2 (Windows 10 Home)

2021-03-24 21:43 UTC, motdotla commented
what version of `pdftoppm` do you have?

```
❯ pdftoppm -v                                                                                                                                                                                                                                        14:42:38
pdftoppm version 21.02.0
Copyright 2005-2021 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
```

2021-03-24 21:46 UTC, motdotla commented
nevermind my last comment. that is for png generation.

2021-03-24 21:51 UTC, motdotla commented
Try pulling the latest, running bundle install, and trying to generate again. I added the binary for development mode.

2021-03-24 21:59 UTC, motdotla requested changes

2021-03-24 21:59 UTC, motdotla commented on app/views/ach_transfers/transfer_confirmation_letter.pdf.erb
> +    <%= image_tag(wicked_pdf_asset_base64('michael_signature.png'), width: 300, height: 73, dpi: 96) %>
This should now be melanie_signature (or something close to that. double check the image was added after doing a rebase)

2021-03-24 21:59 UTC, motdotla commented on app/views/ach_transfers/transfer_confirmation_letter.pdf.erb
> +      Michael Destefanis<br />
same here

2021-03-24 21:59 UTC, motdotla commented on app/views/ach_transfers/transfer_confirmation_letter.pdf.erb
> +        Please don't hesitate to contact me with any additional questions. I can be reached at <a href="mailto:michael@hackclub.com">michael@hackclub.com</a>
https://github.com/hackclub/bank/pull/1374/files

2021-04-05 06:39 UTC, garyhtou commented
I'm surprised this is working lmao. Let me if there can be any improvements

hm... idk why the rebase created duplicate commits

2021-04-05 06:43 UTC, garyhtou commented
[transfer_confirmation_letter (1).pdf](https://github.com/hackclub/bank/files/6256709/transfer_confirmation_letter.1.pdf)

2021-04-05 18:00 UTC, motdotla approved these changes
good work here Gary

2021-04-05 18:00 UTC, merged