Job to set all point of contacts to Mel (#1426)
hackclub/hcb pull request #1484
Opened 2021-04-17 02:34 UTC by garyhtou

Tested local and it seems to work.

Run in console after merging:

```ruby
TempJob::EventPointOfContactMel.new.perform
```

2021-04-17 02:35 UTC, garyhtou commented
#1426

2021-04-19 18:00 UTC, motdotla requested changes

2021-04-19 18:00 UTC, motdotla commented on app/jobs/temp_job/event_point_of_contact_mel.rb
> +				e.point_of_contact_id = mel_user_id
let's switch this to `.update_column(:point_of_contact_id, mel_user_id)` just as a precaution to avoid any possible callbacks being triggered from .save

2021-04-19 20:17 UTC, garyhtou commented on app/jobs/temp_job/event_point_of_contact_mel.rb
> +				e.point_of_contact_id = mel_user_id
thanks for the feedback 😄

2021-04-19 21:28 UTC, merged