Add external boolean to Partners table
hackclub/hcb pull request #1678
Opened 2021-06-07 03:22 UTC by garyhtou

closes #1676

run after merging
```ruby
p = Partner.where(slug: 'bank').first
p.external = false
p.save!
```

2021-06-07 15:45 UTC, motdotla requested changes
one small addition. add a spec to partner_spec.rb showing that external defaults to true

2021-06-07 15:45 UTC, motdotla commented on db/migrate/20210607030039_add_external_to_partners.rb
> +    add_column :partners, :external, :boolean, null: false, default: true
well done here with the default.

can you add a spec to the partner_spec.rb that shows the external defaults to true?

2021-06-08 08:06 UTC, garyhtou commented on db/migrate/20210607030039_add_external_to_partners.rb
> +    add_column :partners, :external, :boolean, null: false, default: true
done!

![image](https://user-images.githubusercontent.com/20099646/121147317-9d01fc00-c7f5-11eb-9a48-bef2fe1bebdf.png)

2021-06-08 15:15 UTC, merged

2021-06-08 15:15 UTC, motdotla commented
merging. i will update Bank partner to false once deployed.