Event Onboarding Approval
hackclub/hcb pull request #1681
Opened 2021-06-08 09:55 UTC by garyhtou

![image](https://user-images.githubusercontent.com/20099646/121164585-8616d600-c804-11eb-8a37-97bb56c694d5.png) ![image](https://user-images.githubusercontent.com/20099646/121164734-9dee5a00-c804-11eb-85ff-a5fed2769588.png) <br/><br/><br/> if attempting to transition from pending to approved  ![image](https://user-images.githubusercontent.com/20099646/121164938-beb6af80-c804-11eb-9d23-c90778a686ac.png) ![image](https://user-images.githubusercontent.com/20099646/121165056-d5f59d00-c804-11eb-9e18-0f8f20813b67.png)

2021-06-09 05:51 UTC, motdotla commented
@garyhtou is this ready to review?

2021-06-09 06:08 UTC, garyhtou commented
> @garyhtou is this ready to review?

Not really, it's okay to merge. But I'm also planning to finish up the webhook delivery in this PR too

2021-06-11 04:44 UTC, motdotla commented
@garyhtou can we move the webhook stuff to a separate PR and make this just the approve/unapprove event logic?

2021-06-13 01:40 UTC, garyhtou commented
> @garyhtou can we move the webhook stuff to a separate PR and make this just the approve/unapprove event logic?

oh my bad! just saw this

2021-06-13 01:42 UTC, garyhtou commented
I think everything should be working, but I keep getting `400 Bad Request` for any `webhook_url` i give

2021-06-13 04:51 UTC, motdotla requested changes

2021-06-13 04:51 UTC, motdotla commented on app/controllers/admin_controller.rb
> +  end
nicely done here

2021-06-13 04:51 UTC, motdotla commented on app/services/api_service/v1/connect_start.rb
> +          webhook_url: @webhook_url
can you add `existing_event.webhook_url = @webhook_url` to between line 16 and 17.

2021-06-13 04:51 UTC, motdotla commented on app/services/event_service/deliver_webhook.rb
> +      return unless event.webhook_url.present?
let's raise an error here instead, at least for now. `raise ArgumentError, "webhook_url missing"`

2021-06-13 04:51 UTC, motdotla commented on app/services/event_service/deliver_webhook.rb
> +      Net::HTTP.new(uri.host, uri.port)
switch to using faraday instead. there is some good example faraday code here: https://github.com/hackclub/bank-api-example/blob/main/app/services/bank_service/connect_start.rb

2021-06-13 04:51 UTC, motdotla commented on app/services/event_service/toggle_approved.rb
> +    end
i like the thinking here, but it would be slightly more readable to remove the `toggle` method and instead move all this code above inside the run method.

2021-06-13 04:51 UTC, motdotla commented
Good work here on thinking about toggle. That was not a requirement but it definitely was needed as you dove into the code.

2021-06-13 07:35 UTC, garyhtou commented
Thanks! changes made, let me know if there's anything else 😄

looks like Faraday fixed the 400 error I was getting

2021-06-13 07:44 UTC, garyhtou commented on app/services/event_service/deliver_webhook.rb
> +      Net::HTTP.new(uri.host, uri.port)
fyi, i don't have access

2021-06-13 16:50 UTC, motdotla commented on app/services/event_service/deliver_webhook.rb
> +      Net::HTTP.new(uri.host, uri.port)
sorry about that. you should have access now

2021-06-13 16:51 UTC, motdotla approved these changes

2021-06-13 16:51 UTC, motdotla commented on app/services/event_service/deliver_webhook.rb
> +      res = Faraday.post(event.webhook_url, Api::V1::OrganizationSerializer.new(event: event).run.to_json, 'Content-Type' => 'application/json')
nice re-use here with OrganizationSerializer

2021-06-13 16:51 UTC, merged