Add incoming deposits & pending withdrawals, improve design & accessibility
hackclub/hcb pull request #170
Opened 2019-06-09 20:16 UTC by tmb

working branch

2019-06-09 20:16 UTC, tmb commented
closes #169, #162, #159

2019-06-17 05:34 UTC, lachlanjc commented on app/assets/stylesheets/application.scss
@tmb This is an alphabetized list :) please :)

2019-06-17 05:35 UTC, lachlanjc commented on app/assets/stylesheets/components/_withdraw_breakdown.scss
> +	display: block;
Indentation is wrong on this file

2019-06-26 00:49 UTC, lachlanjc reviewed
Talking to @tmb later but some things to look through now

2019-06-26 00:49 UTC, lachlanjc commented on app/assets/stylesheets/components/_incoming_deposits_modal.scss
> +  width: 248px;
Never put “magic numbers” like this in CSS, esp without comments describing why. No one knows when they can change them & what will break in the future

2019-06-26 00:49 UTC, lachlanjc commented on app/assets/stylesheets/components/_incoming_deposits_modal.scss
> +  margin: .2rem;
.2rem isn’t part of our whitespace scale. Use powers of two: .25, .5, 1, 2 etc

2019-06-26 00:49 UTC, lachlanjc commented on app/assets/stylesheets/components/_incoming_deposits_modal.scss
> +  grid-gap: 0rem;
Don’t put units on 0, & furthermore, just remove this line

2019-06-26 00:49 UTC, lachlanjc commented on app/assets/stylesheets/components/_incoming_deposits_modal.scss
> +
?

2019-06-26 00:49 UTC, lachlanjc commented on app/assets/stylesheets/components/_incoming_deposits_modal.scss
> +  overflow-y: scroll;
`overflow-y: auto` is probably what you’re looking for here. On all non-Apple devices, this will show a scroll bar regardless of if there’s overflow

2019-06-26 00:49 UTC, lachlanjc commented on app/assets/stylesheets/components/_incoming_deposits_modal.scss
> +    text-overflow: ellipsis;
Indentation, friend.

2019-06-26 00:49 UTC, lachlanjc commented on app/views/events/show.html.erb
> +  <action class="stat stat--small" area="deposits" data-behavior="modal_trigger" data-modal="incoming_deposits">
Check keyboard accessibility here. You probably need a `tabindex`

2019-06-27 23:57 UTC, lachlanjc commented on app/assets/stylesheets/components/_incoming_deposits_modal.scss
> +		background-color: map-get($palette, black);
Theo, my friend. Please. What is going on here.

2019-06-28 00:01 UTC, lachlanjc requested changes

2019-06-28 00:01 UTC, lachlanjc commented on app/assets/stylesheets/components/_incoming_deposits_modal.scss
> +	border: 3px solid;
Did you mean this?
```suggestion
	border: 3px solid currentColor;
```

2019-06-28 00:01 UTC, lachlanjc commented on app/assets/stylesheets/components/_incoming_deposits_modal.scss
> +	overflow-y: scroll;
```suggestion
	overflow-y: auto;
```

2019-06-28 00:01 UTC, lachlanjc commented on app/assets/stylesheets/components/_incoming_deposits_modal.scss
> +		overflow-y: auto;
```suggestion
```

2019-06-28 00:01 UTC, lachlanjc commented on app/views/events/show.html.erb
> +  <action class="stat stat--small" area="deposits" data-behavior="modal_trigger" data-modal="incoming_deposits">
^^^ (adding `tabindex`)

2019-06-28 22:05 UTC, tmb commented on app/assets/stylesheets/components/_incoming_deposits_modal.scss
> +	border: 3px solid;
That wasn't compatible with the old layout we decided was better.

2019-07-03 21:28 UTC, lachlanjc approved these changes

2019-07-03 21:29 UTC, lachlanjc commented
Significantly improved the incoming deposits view:
<img width="1440" alt="Screen Shot 2019-07-03 at 4 54 02 PM" src="https://user-images.githubusercontent.com/5074763/60626207-0bdbac80-9db8-11e9-9d98-dc1d6e638978.png">

& made dozens of little changes, improving design, dark mode & keyboard accessibility.

2019-07-03 22:49 UTC, zachlatta commented
❤️❤️❤️❤️❤️

--
Zach Latta
Hack Club | zach@hackclub.com | Donate ( https://hackclub.com/donate )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://facebook.com/crynix ) / web ( https://zachlatta.com ) / github ( https://github.com/zachlatta )

On Wed, Jul 3 2019 at 14:29, Nikolas Huebecker < notifications@github.com > wrote:

> 
> 
> 
> Significantly improved the incoming deposits view:
> Screen Shot 2019-07-03 at 4 54 02 PM (
> https://user-images.githubusercontent.com/5074763/60626207-0bdbac80-9db8-11e9-9d98-dc1d6e638978.png
> )
> 
> 
> 
> & made dozens of little changes, improving design, dark mode & keyboard
> accessibility.
> 
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub (
> https://github.com/hackclub/bank/pull/170?email_source=notifications&email_token=AAHSH6DL2WIU4SFMFDJCENLP5UK5FA5CNFSM4HWN2O32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZFXKTI#issuecomment-508261709
> ) , or mute the thread (
> https://github.com/notifications/unsubscribe-auth/AAHSH6D3Z3RLJQTHUTRL5IDP5UK5FANCNFSM4HWN2O3Q
> ).
> 
> 
>

2019-07-09 18:46 UTC, tmb commented
Some notes:
* Pending withdrawals works (as in, the numbers make sense) on all events except for the ones that have received fee reimbursements for under $1 and haven't had enough money after to withdraw fees (ex: Red Wood Hacks). It also is broken on Windy City Hacks due to the small fee discrepancy.
* Incoming deposits works on all events from my limited testing

This can be merged once we fix the Windy City Hacks discrepancy, and either:
a) Re-haul fee reimbursements so that ones under a dollar don't have bizzare fee structures that are hard to communicate to users
b) Stop reimbursing fees that are under a dollar

2019-07-09 21:57 UTC, maxwofford commented
@tmb grab me in-person at the office. would like to review together

2019-07-18 19:27 UTC, maxwofford commented on app/controllers/events_controller.rb
> +    @invoices_being_deposited = (@event.invoices.where(payout_id: nil, status: 'paid').where.not(payout_creation_queued_for: nil) + @event.invoices.joins(:payout).where(invoice_payouts: { status: ('i
Recommend wrapping. Know we don't follow the 80 char limit convention in most places, but this is huge

2019-07-18 19:27 UTC, maxwofford commented on app/models/event.rb
> +    self.transactions.select {|t| t.fee_reimbursement.present?}.each do |t|
Not a long pg transaction, but `self.transactions.where.not(fee_reimbursement: nil)` is around 15x faster– also wraps it into 1 db call

2019-07-18 19:27 UTC, maxwofford commented on app/models/event.rb
> +    self.transactions.select {|t| t.fee_reimbursement.present?}.each do |t|
Same as above, recommend using 1 db call

2019-07-18 19:27 UTC, maxwofford commented on app/models/event.rb
> +    lcrs = load_card_requests
What is this line used for?

2019-07-18 19:27 UTC, maxwofford commented on app/models/invoice.rb
> +    # inv = StripeService::Invoice.retrieve(id: stripe_invoice_id, expand: ['charge.balance_transaction'])
Was this commented on purpose?

2019-07-18 19:27 UTC, maxwofford commented on app/models/invoice_payout.rb
> +  # before_create :create_stripe_payout
Was this commented intentionally?

2019-07-18 19:27 UTC, maxwofford commented on app/views/events/card_overview.html.erb
> +    <% # Rails has link_to_if but that doesn't support blocks. I feel like there should be a better way to do this but couldn't find one. -Theo %>
Doesn't seem relevant

2019-07-18 19:53 UTC, tmb commented on app/models/event.rb
> +    lcrs = load_card_requests
it's essentially an alias so that the line below isn't super long. if i make the line below multiline it won't be necessary (which i will do)

2019-07-18 20:05 UTC, tmb commented on app/models/invoice.rb
> +    # inv = StripeService::Invoice.retrieve(id: stripe_invoice_id, expand: ['charge.balance_transaction'])
nope! fixed

2019-07-18 20:11 UTC, tmb commented on app/models/invoice_payout.rb
> +  # before_create :create_stripe_payout
nope, also an artifact from testing. thanks for catching this

2019-07-18 20:15 UTC, tmb commented on app/views/events/card_overview.html.erb
> +    <% # Rails has link_to_if but that doesn't support blocks. I feel like there should be a better way to do this but couldn't find one. -Theo %>
I put it there because I think there's an opportunity to make the code better in the future, I feel like it could be helpful for the future? Not sure

2019-07-22 20:43 UTC, lachlanjc commented
@tmb Sorry to make a merge conflict here. I won't try to fix it since I know you’ve got stuff locally. To fix it, use the new CSS classes on each `.statset` item (prev `.event-summary`) & remove the `area` attributes, but use the existing `action`/`link_to`/`div` tags on this branch for each item. Text me if there's any confusion

2019-07-24 16:39 UTC, tmb commented
Closes #182

2019-07-24 21:26 UTC, lachlanjc commented
That merge conflict was godawful but fixed! Now I can actually make the changes I wanted to make 🙈

2019-07-25 21:49 UTC, merged