Add Typeform promotion card
hackclub/hcb pull request #1810
Opened 2021-09-24 08:31 UTC by exu3

This PR adds the Typeform promotion card in the Perks tab as well as the task card on the admin dashboard.

<img width="1433" alt="Screen Shot 2021-09-24 at 2 02 18 AM" src="https://user-images.githubusercontent.com/72365100/134648487-a3dc7e90-5795-45d0-9b8d-671420533319.png">

2021-09-24 20:29 UTC, garyhtou requested changes
Amazing job!

2021-09-24 20:29 UTC, garyhtou commented on app/views/events/promotions.html.erb
> +    Typeform is partnering with Hack Club Bank to offer <strong>30% off</strong> any paid plan to organizers of all Hack Club Bank projects. Typeform is a web-based tool used to create unique online
Link to Typeform so they can learn more about it

2021-09-24 20:29 UTC, garyhtou commented on app/views/events/promotions.html.erb
> + <div class="card__banner card__banner--top flex justify-between items-center" style="background-image:url('https://cloud-m6r7s83e4-hack-club-bot.vercel.app/0blue-bg-2.png'); background-size:100% aut
Can you check the mobile view?
![image](https://user-images.githubusercontent.com/20099646/134735722-e590364e-af3f-4c55-981b-c500e27755e7.png)

2021-09-25 00:32 UTC, exu3 commented
Fixed! thanks Gary :D

2021-09-27 20:32 UTC, garyhtou commented
Looks good now! Thanks!
![image](https://user-images.githubusercontent.com/20099646/134980669-3ba046f5-e5e3-49f0-872e-891e80b8d6d0.png)

give me a ping once the contract and everything has been 👍 by Zach and I'll merge

2021-09-27 20:32 UTC, garyhtou approved these changes

2021-09-28 15:39 UTC, MelSmith104 commented
hey just reviewed this - it looks great. changed the background and the logo on the application form. hold off on merging until we get confirmation from zach - we're looking to see if they can increase their discount. also please move typefom down below sendy as it's not free

2021-10-04 19:07 UTC, exu3 commented
marking this as a draft for now, awaiting confirmation from Typeform

2022-01-21 15:53 UTC, maxwofford commented
This looks like it's on pause so I'm closing it for now. Feel free to reopen or continue commenting here when there are updates.

2022-01-21 15:53 UTC, closed without merging