Show last four in the redacted digits
hackclub/hcb pull request #1908
Opened 2021-10-29 05:59 UTC by tanatorn

Shows last four digits when using `hidden_card_number`
![image](https://user-images.githubusercontent.com/8843960/139383478-b50b82ca-6f5c-477c-8ba6-9c30d9c78d7c.png)

Optimizes one of the query because it made me sad
* before
```
  User Load (0.7ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2658], ["LIMIT", 1]]
  ↳ app/views/events/card_overview.html.erb:147
  User Load (1.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2596], ["LIMIT", 1]]
  ↳ app/views/events/card_overview.html.erb:147
  User Load (2.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2385], ["LIMIT", 1]]
  ↳ app/views/events/card_overview.html.erb:147
  User Load (0.9ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2372], ["LIMIT", 1]]
  ↳ app/views/events/card_overview.html.erb:147
  User Load (0.9ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2046], ["LIMIT", 1]]
  ↳ app/views/events/card_overview.html.erb:147
  User Load (0.9ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1803], ["LIMIT", 1]]
  ↳ app/views/events/card_overview.html.erb:147
  User Load (2.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 34], ["LIMIT", 1]]
  ↳ app/views/events/card_overview.html.erb:147
  User Load (0.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 892], ["LIMIT", 1]]
  ↳ app/views/events/card_overview.html.erb:147
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 892], ["LIMIT", 1]]
  ↳ app/views/events/card_overview.html.erb:147
```
* after
```
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" IN ($1, $2, $3, $4, $5, $6, $7, $8)  [["id", 2658], ["id", 2596], ["id", 2385], ["id", 2372], ["id", 2046], ["id", 1803], ["id", 34], ["id", 892]]
  ↳ app/views/events/card_overview.html.erb:135
```

2021-10-29 05:59 UTC, tanatorn commented on .gitignore
> +.idea
adds intellij cause i use intellij

2021-10-29 07:42 UTC, maxwofford requested changes

2021-10-29 07:42 UTC, maxwofford commented on app/controllers/events_controller.rb
> +    @stripe_cardholders = StripeCardholder.where(user_id: @event.users.pluck(:id)).includes(:user).order("created_at desc")
Thanks for catching this!

2021-10-29 07:42 UTC, maxwofford commented on app/models/stripe_card.rb
> +    "•••• •••• •••• #{last4}"
That's great! Could we keep this hidden this in transparency mode? I'd like to see the last 4 digits when looking at a list of my teammember's cards, but I'd be sketched out if I saw these details when looking over someone else's account.

2021-10-30 08:33 UTC, tanatorn commented
When not signed in:
![image](https://user-images.githubusercontent.com/8843960/139525984-e3f37ea2-8358-496c-8010-73ae5ce84512.png)

When signed in as an organizer:
![image](https://user-images.githubusercontent.com/8843960/139526029-03be993e-f290-4772-98ed-1b0b304288ea.png)

2021-10-30 08:33 UTC, tanatorn commented
PTAL @maxwofford

2021-10-31 06:57 UTC, maxwofford commented
This looks good to go– thanks!

2021-10-31 06:57 UTC, merged