Fixes donation amount
hackclub/hcb pull request #1986
Opened 2021-11-08 03:27 UTC by tanatorn

New donations now don't transition to `Deposited` until the fees are reimbursed. This should solve some confusion about the donation page not matching up with the balance.

To test, I went and two transaction states for John and Josh locally to `:in_transit`  then ran 
```
irb(main):044:0> DonationService::Nightly.new.run
```
in irb to make sure that we don't update it to deposited until everything's settled.

I also added some convenience functions in canonical_transaction_grouped and the made the `linked_object` work with Donations created on the TransactionEngineV2
 
![image](https://user-images.githubusercontent.com/8843960/141215838-cd86611d-3227-416f-8f7a-d66cdf753f70.png)

2021-11-08 14:29 UTC, maxwofford reviewed
This is a good start, but the total event balance shown to an event is off. If i receive a donation for $1, my transaction list shows a $1 deposit, but my balance will only show $0.68 until the fee refund comes in. I'd like the balance to only go up to $1 once the fee refund and the payout have arrived.

2021-11-08 17:28 UTC, maxwofford commented
[Here](https://hackclub.slack.com/archives/GBXBFEED9/p1636389051038900) is an example of something that could confuse the user mentioned in https://github.com/hackclub/bank/pull/1986#pullrequestreview-800190994. It's an admin in the Slack comment, but users don't have access to that transaction-specific breakdown.

2021-11-10 04:51 UTC, tanatorn commented
@maxwofford I think the bug here is actually the fee reimbursement engine hasn't been running for awhile so there's been no reimbursement. Since there's no reimbursement, they _are_ displaying the correct value. @garyhtou said he'll get that reimbursement portion working - I'll stop working on this in the mean time to see if the issue self resolves.

2021-11-10 04:52 UTC, tanatorn commented
For context: https://hackclub.slack.com/archives/C026RKHLPNJ/p1636518674031100?thread_ts=1636517056.026700&cid=C026RKHLPNJ

2021-11-10 16:34 UTC, maxwofford commented
@tanatorn you're totally right fee refunds are delayed, but the underlying issue is still there– our UI expects either (no payout nor fee refund) or (payout and refund). It doesn't handle (payout paid but fee refund pending).

Right now because fee refunds are delayed the issue is worse b/c the UI is confusing for a week, but regularly people will try using bank by donating a $1 to themselves, and when they see the funds come into their account their total balance shows $0.32 right above a TX history that just shows a $1 donation successfully paid. That confusing state can stay there for a day or two.

2021-11-11 00:44 UTC, tanatorn commented
PTAL @maxwofford

2021-11-11 04:58 UTC, maxwofford commented
Requesting @garyhtou's review before merge for his experience with this part of hcb codes & transactions v2

2021-11-11 09:12 UTC, garyhtou requested changes
good work so far!! couple organizational and design changes

2021-11-11 09:12 UTC, garyhtou commented on app/models/canonical_transaction.rb
>    end
I believe `Invoice` also has fee reimbursements.

also, extra `nil # TODO` on line 183

2021-11-11 09:12 UTC, garyhtou commented on app/models/donation.rb
> +  end
Edge case: when a donation is refunded, the `amount_settled` would equal 0. In that case, `fee_reimbursed?` would return `false`. Should that be the case?

I think `true` might make more sense bc it had a Fee Reimbursement. open to thoughts on this tho

---

**preferred method:**

a more robust way to do it may be to look at the donation's `fee_reimbursement` relation, and check if `fee_reimbursement.canonical_transaction` is nil.

there is a `completed?` method in FeeReimbursement model, but it's using the v2 engine. would be best to update that to use v2

2021-11-11 09:12 UTC, garyhtou commented on app/services/donation_service/nightly.rb
> +        next unless donation.fee_reimbursed?
how about something like `donation.fee_reimbursement.settled?`

related to comment on Donation model

2021-11-11 09:12 UTC, garyhtou commented on app/services/transaction_engine/syntax_sugar_service/linked_object.rb
> +        nil
combine with `likely_donation`?

2021-11-11 18:53 UTC, tanatorn commented on app/services/donation_service/nightly.rb
> +        next unless donation.fee_reimbursed?
i made `donation.fee_reimbursed?` a convenience method for accessing fee_reimbursment.ct

2021-11-11 19:01 UTC, tanatorn commented
PTAL @garyhtou

2021-11-11 21:02 UTC, garyhtou commented on app/models/donation.rb
> +  end
whoops, typo: but it's using the v1 engine*

2021-11-11 21:08 UTC, garyhtou approved these changes
good to go! thanks for making those edits

2021-11-13 19:17 UTC, merged