Check sending / ACH
hackclub/hcb pull request #200
Opened 2019-07-26 04:07 UTC by tmb

2019-07-27 07:12 UTC, tmb commented
TODO Tomorrow:
* ~Allow users to edit address before check is approved~
* Allow users to void checks
* ~Build a barebones create page for checks~
* Test transaction auto matching for checks
* Build CSV exporter for FRB

2019-08-02 22:15 UTC, lachlanjc commented on app/models/check.rb
> +  scope :pending, -> { where.not(processed_at: nil) }
@tmb This column doesn't exist, so the syncing never runs

2019-08-03 00:16 UTC, lachlanjc commented on app/models/check.rb
> +    select { |check| check.approved_at && t_transactions.size != 2 && check.expected_delivery_date < DateTime.now }
`pending` through this method should all be rails scopes :)

2019-08-29 14:43 UTC, lachlanjc commented on app/views/checks/new.html.erb
> +        <div class="check__field check__field--memo truncate" data-label="Memo" data-behavior="check_memo">　</div>
Would not recommend using a utility here since it's a singular exception. The check is also used on the show page, for example. Copy the source of this utility over to the memo class

2019-08-29 14:43 UTC, lachlanjc commented on app/assets/javascripts/checks.js
> +	if($('[data-behavior~="fill_check_words"]').length == 1) {
Please. Use Prettier. Omg Theo. :)

2019-08-29 14:43 UTC, lachlanjc commented on app/assets/javascripts/checks.js
> +  		amount.split('.')[1] == undefined ? false : true
Whenever you're writing a ternary with `false : true` or `true : false`, it's unnecessary, because the first part of the expression evaluates to a boolean. Here, you can significantly simplify:

```suggestion
  		amount.split('.')[1] !== undefined
```

2019-08-29 14:43 UTC, lachlanjc commented on app/assets/javascripts/checks.js
> +  	let cents = amountHasCents ? amount.split('.')[1].slice(0, 2) : null
Use `const` everywhere here, unless you're re-defining the variable. Using `let` indicates these values might change, but then they don't.

2019-08-29 14:43 UTC, lachlanjc commented on app/assets/javascripts/checks.js
> +          `${cents.length == 1 ? `${cents}0` : `${cents}`}` +
```suggestion
          `${cents.length === 1 ? `${cents}0` : cents}` +
```

2019-08-29 14:43 UTC, lachlanjc commented on app/assets/javascripts/checks.js
> +		$('[data-behavior~="check_characters_update"').text(`This will appear on the physical check. You have ${40 - characters} characters remaining.`)
I told you this elsewhere, but I'd way prefer `x/y characters left` instead of a long sentence here.

2019-09-04 03:48 UTC, lachlanjc commented on app/assets/javascripts/checks.js
> +		"change paste keyup input",
Theo. Turn on Prettier in your editor. With no semi/single quote/two spaces (Hack Club style across all repos). Like. I’ve said this like a dozen times at least.

2019-09-05 02:04 UTC, lachlanjc commented on app/views/checks/_new_form.html.erb
> +      <%= form.number_field :amount, placeholder: '500.00', step: :any, min: 0, required: true, data: {'behavior': 'check_amount_field'}%>
```suggestion
      <%= form.number_field :amount, placeholder: '500.00', step: :any, min: 0, required: true, data: { behavior : 'check_amount_field' } %>
```
Btw you can also do `’data-behavior’: x` without the braces

2019-09-05 02:04 UTC, lachlanjc commented on app/views/checks/refund_get.html.erb
> +	<strong>Transaction Memo</strong>
Still have weird whitespace in various places like this

2019-09-05 02:04 UTC, lachlanjc commented on app/views/checks/show.html.erb
> +<link href="https://fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">
These two lines can be combined for faster downloading of the fonts—I think you can just comma-separate them? (Also apply to the new page)

2019-09-05 02:04 UTC, lachlanjc commented on app/views/checks/new.html.erb
> +    <link href="https://fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">
See other comment about loading fonts. Also, put this at the top so it’s easy to see

2019-09-05 02:04 UTC, lachlanjc commented on app/views/checks/index.html.erb
> +<br>
```suggestion
```
?

2019-09-05 02:04 UTC, lachlanjc commented on app/views/check_mailer/undeposited.html.erb
> +    'The hivemind known as Bank',
Todo: standardize this helper

2019-09-12 03:54 UTC, tmb commented
@thesephist ready for final review

2019-09-12 04:31 UTC, lachlanjc commented on app/views/checks/start_void.html.erb
> +      <li><strong>If it hasn't been deposited, you'll get your money back in the next few business days.</strong></li>
Missing rich quotes in several places in this file

2019-09-17 00:08 UTC, thesephist requested changes
Reviewed halfway through and gotta run somewhere until 10PM -- but I'll finish it tonight. 🚀

Left some comments, 50-50 nitpicks and questions i have about existing code. Not all of them are code changes that need to be made, but please read thru.

2019-09-17 00:08 UTC, thesephist commented on Dockerfile
> -ENV EDITOR=vim
Why is this removed?

2019-09-17 00:08 UTC, thesephist commented on app/assets/javascripts/checks.js
> +		"change paste keyup input",
+1

not a dealbreaker, but it's useful to be consistent. @tmb not sure what editor you're using, but VSCode has a :100: extension.

2019-09-17 00:08 UTC, thesephist commented on app/assets/javascripts/checks.js
> +				amount.split(".")[1] == undefined ? false : true;
I prefer that we use `===` over `==` wherever possible (which is essentially always).

This is especially relevant when comparing to falsy values, like `undefined` or `null`. `null == undefined` but `null == undefined` is false, and I've seen lots of bugs caused by accidentally converting values by using `==`.

On a separate note, I think this line would be easier to understand if we said

```js
const amountHasCents = amount.split('.')[1] !== undefined;
```

or better yet, here's how I'd probably do this part of converting the string into number, if you're down to some rewriting...

```js
let [dollarsString = '', centsString = ''] = amount.split('.')

const dollars = dollarsString ? +dollarsString : 0
let cents = centsString ? +centsString.slice(0, 2) : 0
if (centsString.length === 1) {
  cents *= 10
}

const words = `${BK.numToWords(dollars)} ${cents > 0 ? `and ${cents}/100` : 'and 00/100'}`
```

I think this also more cleanly covers edge cases like `.35` and `24.`

2019-09-17 00:08 UTC, thesephist commented on app/assets/javascripts/checks.js
> +		const amountHasCents = amount.split(".")[1] == undefined ? false : true;
This conversion logic from line 57 to 68 is a repeat of what's above, right? I'd wrap this in a function and use it in both places, instead of repeating a probably bug-prone bit of code.

2019-09-17 00:08 UTC, thesephist commented on app/assets/javascripts/checks.js
> +			return $('[data-behavior~="modal_confirm_words"]').html().replace(currentAmountVal, '$' + amount).replace(currentPayeeVal, payee)
`.text()` seems better than `.html()` here, since it does a more specific thing.

2019-09-17 00:08 UTC, thesephist commented on app/assets/javascripts/checks.js
> +	$('[data-behavior~="submit_check"]').click((event) => {
If we can match a string exactly (like `submit_check`), let's match it exactly instead of doing a fuzzy containment match. i.e. `=` > `~=`

2019-09-17 00:08 UTC, thesephist commented on app/assets/javascripts/numbersToWords.js
> +      "nonillion"
Very minor nit: It's probably fine to drop everything from quadrillion and down -- we won't ever use them, and it's best not to ship code that won't ever run.

2019-09-17 00:08 UTC, thesephist commented on app/assets/stylesheets/_dark.scss
> +  .menu__toggle[aria-expanded='true']:after,
The spec-compliant selector for pseudoelements is `::after`, with double colons. Let's stick with one style `::` rather than using the `:` that's supported for backwards compat reasons.

2019-09-17 00:08 UTC, thesephist commented on app/assets/stylesheets/_dark.scss
> +  .menu__toggle[aria-expanded='true']:before {
Same here re: `::`

2019-09-17 00:08 UTC, thesephist commented on app/assets/stylesheets/_dark.scss
> +    &:before {
Same here re: pseudoselectors.

2019-09-17 00:08 UTC, thesephist commented on app/assets/stylesheets/_dark.scss
> +    filter: invert(1) hue-rotate(180deg);
Hmmmm not sure if doing this is the best way to support dark mode. Does it look good? I'll leave this up to you and your tastes, but in my experience doing a hue-rotate/invert doesn't reliably produce good dark mode.

2019-09-17 00:08 UTC, thesephist commented on app/assets/stylesheets/_utilities.scss
> -
Are we sure we never use these?

2019-09-17 00:08 UTC, thesephist commented on app/assets/stylesheets/components/_checks.scss
> +  background: $bg url('data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 56 28" width="56" height="28"%3E%3Cpath fill="%23D3DFEB" fill-opacity="0.75" d="M56 26v2h-7.75c2.3-1.2
I think we might be better off saving this in a SVG file and loading the file by URL instead, but I don't hate this -- it's just less readable. I'll leave this up to you, given timing.

2019-09-17 00:08 UTC, thesephist commented on app/assets/stylesheets/components/_checks.scss
> +  &:before {
same as above, re: pseudoelements (`::before`)

2019-09-17 00:08 UTC, thesephist commented on app/assets/stylesheets/components/_checks.scss
> +  &:before {
ditto -- see above, also a few below.

2019-09-17 00:08 UTC, thesephist commented on app/assets/stylesheets/components/_checks.scss
> +  font-family: 'Space Mono', $mono;
More of a question less of a comment.... we use Space Mono? Where? I've never seen it on Bank.

2019-09-17 00:08 UTC, thesephist commented on app/controllers/ach_transfers_controller.rb
> +    ach_transfer_params[:amount] = ach_transfer_params[:amount].to_f * 100.to_i
I think we want the amount to be an integer in cents, right? Should this be

```ruby
(ach_transfer_params[:amount].to_f * 100).to_i
```

(i.e. float times integer is a float, which isn't exact cents)

2019-09-17 00:08 UTC, thesephist commented on app/controllers/checks_controller.rb
> +  before_action :set_event, only: %i[new create]
This is really for my own sake: wtf does this line do? (specifically wtf-ing at `%i[...]`)

2019-09-17 00:08 UTC, thesephist commented on app/controllers/checks_controller.rb
> +    check_params[:amount] = filtered_params[:amount].to_f * 100.to_i
Asked a similar question above about floating point numbers and currency denominated in cents. I might be wrong -- but good to check.

2019-09-17 00:08 UTC, thesephist commented on app/controllers/checks_controller.rb
> +    if @check.amount > @event.balance_available + @check.amount
wait... what's happening here? Should this just be... 

```ruby
if @check.amount < @event.balance_available
```

Right now this just simplifies to checking if `0 > @event.balance_available`, right?

2019-09-17 00:08 UTC, thesephist commented on app/controllers/checks_controller.rb
> +      flash[:error] = "This check has already been issued!"
super minor nit: I prefer not to use exclamation points excessively in UI... kinda feels like you're screaming at the user, and this doesn't feel like it warrants it. Up to you tho.

2019-09-17 00:08 UTC, thesephist commented on app/controllers/checks_controller.rb
> +    check_params[:amount] = filtered_params[:amount].to_f * 100.to_i
Made a comment on a related line above.

2019-09-17 00:08 UTC, thesephist commented on app/controllers/checks_controller.rb
> +    # TODO: figure out why I did #includes here.. not totally sure why that would be needed -theo
probably should resolve this.

2019-09-17 02:54 UTC, lachlanjc commented on app/assets/stylesheets/_utilities.scss
> -
I think you misread this diff?
![AB13E627-4A82-4B0C-982A-0BEBBC2C3AC0](https://user-images.githubusercontent.com/5074763/65007704-f533f480-d8d4-11e9-97be-8946e9b0109a.jpeg)

2019-09-17 02:55 UTC, lachlanjc commented on app/assets/stylesheets/components/_checks.scss
> +  &:before {
Sounds good, I’ll leave these for @tmb to handle

2019-09-17 02:56 UTC, lachlanjc commented on app/assets/stylesheets/components/_checks.scss
> +  font-family: 'Space Mono', $mono;
I believe it’s loaded in the HTML templates. We don’t use it on Bank normally.

2019-09-17 02:57 UTC, lachlanjc commented on app/controllers/checks_controller.rb
> +  before_action :set_event, only: %i[new create]
That’s Ruby shorthand syntax for an array of symbols. We set an event here because we need @event defined for many reasons, like generating the correct routes in the event nav template.

2019-09-17 02:59 UTC, lachlanjc commented on app/controllers/checks_controller.rb
> +    # TODO: figure out why I did #includes here.. not totally sure why that would be needed -theo
Keep the includes & cut the comment. includes preloads data while reducing the number of SQL queries, & anywhere we’re loading a creator bar (which is index, show, etc) we need that user data. Highly recommend: https://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations

2019-09-17 03:01 UTC, lachlanjc commented on app/views/checks/show.html.erb
> +<link href="https://fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">
Could be cut for sure. I found it to be closer to what I saw on various check designs, but not very important

2019-09-17 03:03 UTC, lachlanjc commented on app/assets/javascripts/checks.js
> +				amount.split(".")[1] == undefined ? false : true;
Didn’t take the time to write this up but fully agree. Double equals has messed up lots of code in my past 😅

2019-09-17 03:05 UTC, lachlanjc commented on app/assets/javascripts/checks.js
> +			let fieldName = event.currentTarget.id.replace(
Not critical for this PR, but would be good to use const/let correctly. let is a keyword to explicitly label a variable that its value will change, otherwise use const.

2019-09-17 05:26 UTC, thesephist commented on app/assets/stylesheets/_utilities.scss
> -
Oh lol never mind, I can't read. 👍

2019-09-17 05:28 UTC, thesephist commented on app/assets/javascripts/checks.js
> +			let fieldName = event.currentTarget.id.replace(
Eh, I think

>let is a keyword to explicitly label a variable that its value will change, otherwise use const.

Is definitely a matter of opinion/personal preference -- some JS devs definitely prefer let over const.

That said, my personal style is also to default to `const` until/unless a `let` is required. Not a huge deal though as mentioned.

2019-09-17 17:41 UTC, thesephist requested changes
Reviewed the rest of the PR -- mostly questions and comments, a few things I think we should fix before merging. 🙏

2019-09-17 17:41 UTC, thesephist commented on app/jobs/sync_transactions_job.rb
> +      account_ids: [account.plaid_account_id]
What do we need the account ID for?

2019-09-17 17:41 UTC, thesephist commented on app/mailers/check_mailer.rb
> +    mail to: @emails, subject: "We're voiding your check to #{@check.lob_address.name} for #{render_money @check.amount, ''}."
Let's resolve this TODO and shorten this up. How about:

"Voided check to <name> for $<amount>"?

2019-09-17 17:41 UTC, thesephist commented on app/models/check.rb
> +    "#{event.name} | #{lob_address.name} | #{status} - #{ApplicationController.helpers.render_money amount}"
Why is `render_money` not auto-imported here?

2019-09-17 17:41 UTC, thesephist commented on app/models/check.rb
> +  end
I think this function can just be written as

```ruby
def voidable
  return !deposited? && !pending_void? && !voided?
end
```

Which imo is cleaner and more consistent with stuff above, but I think it's fine as-is if you want to keep it

2019-09-17 17:41 UTC, thesephist commented on app/models/check.rb
> +      RefundSentCheckJob.set(wait_until: send_date + 31.days).perform_later(self)
How did we get this 31 number?

2019-09-17 17:41 UTC, thesephist commented on app/models/event.rb
> +  has_many :lob_addresses
```ruby
has_many :checks
has_many :lob_addresses
```

Are these duplicates of below?

2019-09-17 17:41 UTC, thesephist commented on app/policies/event_policy.rb
> +  def transfers?
What's a `transfer` in this context?

2019-09-17 17:41 UTC, thesephist commented on app/views/ach_transfers/_form.html.erb
> +  <% if ach_transfer.errors.any? %>
Let's update this error block to use `form_errors` from this PR: https://github.com/hackclub/bank/issues/228

2019-09-17 17:41 UTC, thesephist commented on app/views/ach_transfers/show.html.erb
> +<% title "ACH transfer – #{@ach_transfer.recipient_name}" %>
I think Rails will unnecessarily escape this if there are HTML special characters inside... maybe do `@ach_transfer.recipient_name.html_safe`?

2019-09-17 17:41 UTC, thesephist commented on app/views/ach_transfers/start_approval.html.erb
> +  <p>(<%= link_to @ach_transfer.creator.pretty_phone_number, "tel:#{@ach_transfer.creator.phone_number}" %>, <%= mail_to @ach_transfer.creator.email %>) of <%= link_to @ach_transfer.event.name, @ach_
Can we split this line into multiple shorter lines that fit on a screen?

2019-09-17 17:41 UTC, thesephist commented on app/views/check_mailer/undeposited.html.erb
> +    'The hivemind known as Bank',
Yes, but since it's not too relevant to this PR, I'm going to close this comment and make an issue or something.

2019-09-17 17:41 UTC, thesephist commented on app/views/checks/_edit_form.html.erb
> +  <% if check.errors.any? %>
Let's use `form_errors` from this PR here - https://github.com/hackclub/bank/issues/228

2019-09-17 17:41 UTC, thesephist commented on app/views/checks/_form.html.erb
> +    <div id="error_explanation">
Repeat of above: it's a quick fix to use `<%= form_errors check %>` here a la https://github.com/hackclub/bank/issues/228

2019-09-17 17:41 UTC, thesephist commented on app/views/checks/_new_form.html.erb
> +  <% if check.errors.any? %>
See `form_errors` comment above.

2019-09-17 17:41 UTC, thesephist commented on app/views/checks/refund_get.html.erb
> +	<strong>Transaction Memo</strong>
Given timing, I'm not too worried about indentation error in template files (indent in JS files, more so, but this template is readable). Up to @tmb though we'd eventually want to fix it.

2019-09-17 17:41 UTC, thesephist commented on app/views/checks/refund_get.html.erb
> +<p>Make this transfer from the Hack Club account @ SVB into Hack Club's</p>
wait... from Hack Club's account to Hack Club's? You mean Hack Club's at FRB?

2019-09-17 17:41 UTC, thesephist commented on app/views/checks/start_void.html.erb
> +      <li><strong>If it hasn't been deposited, you'll get your money back in the next few business days.</strong></li>
Not a dealbreaker for me tbh.

It's good to have attention to detail, but I anticipate that once we ship this and test it other smaller cosmetic fixes are also going to crop up that we can fix together. Given the timing / size of this PR, I'm ok if we merge with simple quotes.

2019-09-17 17:41 UTC, thesephist commented on app/views/checks/start_void.html.erb
> +    <p class="bold mt0 mb0">This should be used as a last resort, read ahead & proceed with caution</p>
As a general note, let's not use ampersand (&) in prose text that's supposed to be read. We don't have character limits, and "and" reads better than "&". We do that several places in this feature, and it's not a big deal, but I do think it makes instructions a bit more difficult to read and seem weird.

2019-09-17 17:41 UTC, thesephist commented on app/views/static_pages/index.html.erb
> +      <%= card_to 'Pending Fees', pending_fees_path, { badge: @active[:pending_fees] } %>
This is a duplicate from Pending Fees below. Let's remove this ilne.

2019-09-17 17:41 UTC, thesephist commented on config/credentials.yml.enc
> +yviy6np+V/NDac2RxIELqZFj6VZr4SrM0lfx78lPmxp6wcUL+EKat+Yq8SP/hdDmTLjWNz/d3r2JUrOkI2Pyf9v88A/p7buKjh0po3b5anqYcqcg6bsnJ1yoh7yWXHqMxaXXOc5TTSOeKL99rwVmdPTPz7pIQH/5HXilj5hYeEeF3d8s6CUHFmLUt9UedDIdtC5g1/f
Is this supposed to have been changed for production?

2019-09-17 17:41 UTC, thesephist commented on config/routes.rb
> +  resources :invoices, only: [:show, :index, :create, :new] do
Why did we add these routes?

2019-09-17 17:41 UTC, thesephist commented on db/migrate/20190726232637_add_check_references_to_transactions.rb
> +class AddCheckReferencesToTransactions < ActiveRecord::Migration[5.2]
Not super critical for this PR but for future reference: it would be nice to squash these migrations into a single migration before pushing to a pull request. Makes the migration list more digestible and a little faster as we grow.

If you're so inclined, I think given the number of migration happening in the PR it would be nice to pull these into a single check sending migration.

2019-09-17 19:28 UTC, lachlanjc commented on app/models/check.rb
> +    "#{event.name} | #{lob_address.name} | #{status} - #{ApplicationController.helpers.render_money amount}"
In Rails, “helpers” means “view helpers”, so they’re not loaded be default in models. Not sure if it’d be more performant to `import ApplicationHelper`, but I doubt it makes much difference

2019-09-17 19:29 UTC, lachlanjc commented on app/models/check.rb
> +  end
`return` can be removed :)

2019-09-17 20:37 UTC, thesephist commented on app/models/check.rb
> +    "#{event.name} | #{lob_address.name} | #{status} - #{ApplicationController.helpers.render_money amount}"
Cool, that makes sense :pray: I feel like these kinds of methods belong in view helpers / controllers anyways, but for now, think it's fine.

2019-09-18 01:18 UTC, lachlanjc commented on config/credentials.yml.enc
> +yviy6np+V/NDac2RxIELqZFj6VZr4SrM0lfx78lPmxp6wcUL+EKat+Yq8SP/hdDmTLjWNz/d3r2JUrOkI2Pyf9v88A/p7buKjh0po3b5anqYcqcg6bsnJ1yoh7yWXHqMxaXXOc5TTSOeKL99rwVmdPTPz7pIQH/5HXilj5hYeEeF3d8s6CUHFmLUt9UedDIdtC5g1/f
Adding Lob credentials I assume? Idk

2019-09-18 03:22 UTC, thesephist commented on config/credentials.yml.enc
> +yviy6np+V/NDac2RxIELqZFj6VZr4SrM0lfx78lPmxp6wcUL+EKat+Yq8SP/hdDmTLjWNz/d3r2JUrOkI2Pyf9v88A/p7buKjh0po3b5anqYcqcg6bsnJ1yoh7yWXHqMxaXXOc5TTSOeKL99rwVmdPTPz7pIQH/5HXilj5hYeEeF3d8s6CUHFmLUt9UedDIdtC5g1/f
Ah okay, that checks out.

2019-09-18 12:01 UTC, lachlanjc commented on app/views/static_pages/index.html.erb
> +      <%= card_to 'Pending Fees', pending_fees_path, { badge: @active[:pending_fees] } %>
```suggestion
```

2019-09-18 12:08 UTC, lachlanjc commented on app/views/checks/start_void.html.erb
> +      <li><strong>If it hasn't been deposited, you'll get your money back in the next few business days.</strong></li>
```suggestion
      <li><strong>If it hasn’t been deposited, you’ll get your money back in the next few business days.</strong></li>
```

2019-09-18 19:53 UTC, tmb commented on Dockerfile
> -ENV EDITOR=vim
oops, I think this is some merge something? anyway it should stay

2019-09-18 20:13 UTC, tmb commented on app/controllers/ach_transfers_controller.rb
> +    ach_transfer_params[:amount] = ach_transfer_params[:amount].to_f * 100.to_i
I think you're right but I'm going to leave this till later considering that it's also what we do in `invoices_controller`

2019-09-18 20:13 UTC, tmb commented on app/controllers/checks_controller.rb
> +    check_params[:amount] = filtered_params[:amount].to_f * 100.to_i
same as above

2019-09-18 20:14 UTC, tmb commented on app/controllers/checks_controller.rb
> +    if @check.amount > @event.balance_available + @check.amount
fixed you're right this was stupid lol

2019-09-18 20:15 UTC, tmb commented on app/controllers/checks_controller.rb
> +    check_params[:amount] = filtered_params[:amount].to_f * 100.to_i
same answer as above

2019-09-18 20:15 UTC, tmb commented on app/jobs/sync_transactions_job.rb
> +      account_ids: [account.plaid_account_id]
this is to make sure that we're able to silo transactions into their various accounts. this came from merging master in afaik

2019-09-18 20:26 UTC, tmb commented on app/mailers/check_mailer.rb
> +    mail to: @emails, subject: "We're voiding your check to #{@check.lob_address.name} for #{render_money @check.amount, ''}."
done!

2019-09-18 20:28 UTC, tmb commented on app/models/check.rb
> +      RefundSentCheckJob.set(wait_until: send_date + 31.days).perform_later(self)
We were using this to say "1 month after", I fixed it to use `1.month`

2019-09-18 20:28 UTC, tmb commented on app/models/event.rb
> +  has_many :lob_addresses
yes, fixed.

2019-09-18 20:29 UTC, tmb commented on app/policies/event_policy.rb
> +  def transfers?
this is a mislabeled page that we should fix later. the route for send money is labeled "transfers"

2019-09-18 20:31 UTC, tmb commented on app/views/ach_transfers/start_approval.html.erb
> +  <p>(<%= link_to @ach_transfer.creator.pretty_phone_number, "tel:#{@ach_transfer.creator.phone_number}" %>, <%= mail_to @ach_transfer.creator.email %>) of <%= link_to @ach_transfer.event.name, @ach_
not sure, let's fix later.

2019-09-18 20:31 UTC, tmb commented on app/views/checks/refund_get.html.erb
> +<p>Make this transfer from the Hack Club account @ SVB into Hack Club's</p>
oops, will clarify.

2019-09-18 20:34 UTC, tmb commented on config/routes.rb
> +  resources :invoices, only: [:show, :index, :create, :new] do
I think this is from merging in? let me just double check

2019-09-18 20:36 UTC, tmb commented on config/routes.rb
> +  resources :invoices, only: [:show, :index, :create, :new] do
nvm yeah didn't mean to, removed

2019-09-18 20:42 UTC, tmb commented on db/migrate/20190726232637_add_check_references_to_transactions.rb
> +class AddCheckReferencesToTransactions < ActiveRecord::Migration[5.2]
ok smashed

2019-09-18 22:50 UTC, merged