Show holiday feature field only when transparency enabled
hackclub/hcb pull request #2145
Opened 2021-12-26 12:27 UTC by exu3

Wahoo! It's 4:30 and I had a thought! 

This PR adds an event listener on the transparency mode checkbox; so when the box is checked, the holiday-features-in-transparency-mode checkbox will appear, but when the box is not checked, the holiday-features-in-transparency-mode checkbox will disappear.

https://user-images.githubusercontent.com/72365100/147407969-e810ae96-6093-4d9c-8ac3-d652612f0712.mov

2021-12-30 11:57 UTC, garyhtou requested changes
Heck yeah! cool stuff!

Can you handle the case where transparency is initially on? (at this moment, when the page loads with transparency on, the holiday features checkbox is auto-hidden).

There are a couple of ways to solve this:

- Remove `autohide` css class and use JS to hide holiday features (on initial load) if transparency is on. this could cause some layout shift (similar to [CLS](https://web.dev/cls/)) on the initial load if the element's being hidden. but it might be far enough down the page that it doesn't matter (not in viewport on initial load)
- use ERB to add `autohide` css class to the element `unless @event.is_public`. easier, but it's kinda tacky because now we have the "same" logic in multiple places

2021-12-30 11:57 UTC, garyhtou commented on app/assets/javascripts/ui.js
> +    })
```suggestion
    $(transparencyToggle).on('change', e => {
      if (e.target.checked) {
        holidayFeaturesTransparency.slideDown()
      } else {
        holidayFeaturesTransparency.hide()
      }
    })
```

2021-12-31 05:58 UTC, exu3 commented
I added it in the ERB!

2021-12-31 06:43 UTC, garyhtou approved these changes
just these two small tweaks, then good to merge! ty for this!

2021-12-31 06:43 UTC, garyhtou commented on app/views/events/_form.html.erb
> +      <div class="field field--checkbox" data-behavior="holiday_features_transparency <% if !event.is_public? %>autohide<%end%>">
good! just small formatting things

```suggestion
    <div class="field field--checkbox" data-behavior="holiday_features_transparency <% if !event.is_public? %>autohide<% end %>">
```

2021-12-31 06:43 UTC, garyhtou commented on app/assets/javascripts/ui.js
> +        holidayFeaturesTransparency.hide()
```suggestion
        holidayFeaturesTransparency.slideUp()
```
https://api.jquery.com/slideup/

2021-12-31 07:13 UTC, exu3 commented
Thanks for the fixes!

2021-12-31 07:14 UTC, merged