Export donations as CSV/JSON
hackclub/hcb pull request #2186
Opened 2022-01-06 06:59 UTC by exu3

This PR adds the ability to export donations as CSV or JSON similar to how transactions are exported. Code of questionable quality.

The button placement: I wasn't sure if it would be better on the donations page or main event page in the same dropdown as the current export button, so I've put it on both for now (which can be seen in the staging deployment).
Tangentially related idea—what if the export button opened a modal, and the modal had a description of what kind of data gets exported, etc., and at the bottom of the modal, a field for selecting what to export (All transactions as JSON, all txs as CSV, donations json, donations csv).

I did see #2033 but I realize it likely refers to Partner Donations because it's on the Givebutter task board. <img src="https://emoji.slack-edge.com/T0266FRGM/catclown/ab296701d2b4d5c1.png" width="20">

Here's what the export looks like (CSV).
<img src="https://user-images.githubusercontent.com/72365100/148341456-fec60120-834f-4ef7-9de6-e53cbde5c1f8.png" width="400">

This is what it's like currently on the donations page. One flaw with this is that the user might not understand it's for exporting data unless it says "export."
<img src="https://user-images.githubusercontent.com/72365100/148341684-b31c169b-4540-400d-889d-c3921d74df53.png" width="500">

What it looks like if it's added to the current menu:
<img src="https://user-images.githubusercontent.com/72365100/148341898-50fad249-2a46-4a58-a07d-5cbea7f4e885.png" width="500">

2022-01-06 19:05 UTC, maxwofford commented on app/policies/donation_policy.rb
> +    user
```suggestion
    record.event.users.include?(user) || user&.admin?
```

This method is run to check if the route can be reached. If we use just `user`, any user could start an export of any event's donations.

2022-01-06 19:07 UTC, maxwofford commented on app/views/events/show.html.erb
> +            <%= link_to 'Donations (CSV)', export_donations_path(event: @event, format: :json), target: :_blank %>
Let's remove the donations from this dropdown and add them to the donations page... the transaction export will also show donations, and we want to reduce confusion

2022-01-06 19:29 UTC, exu3 commented on app/policies/donation_policy.rb
> +    user
Ah I see, thanks.

2022-01-06 19:35 UTC, exu3 commented on app/views/events/show.html.erb
> +            <%= link_to 'Donations (CSV)', export_donations_path(event: @event, format: :json), target: :_blank %>
https://github.com/hackclub/bank/pull/2186/commits/007a205b21da102d7ba7dde3f51c4d213837cf65

2022-01-06 19:49 UTC, maxwofford commented
As per #2033, this feature should probably also export PartnerDonations. Up to you if you want to do that in a different PR. Events will probably only ever have Donations **_or_** PartnerDonations, never both

2022-01-06 19:54 UTC, exu3 commented
https://github.com/hackclub/bank/pull/2186#issuecomment-1006887819 I can work on that in a separate PR!

2022-01-06 20:34 UTC, maxwofford requested changes
Nice work! This is pretty close to done. Left a couple comments. Additionally, this shows refunded donations in the export:
<img width="911" alt="Screen Shot 2022-01-06 at 15 33 31" src="https://user-images.githubusercontent.com/5891442/148447987-aef889d1-8e4f-4348-ba50-b0cb360c7e5c.png">
<img width="512" alt="Screen Shot 2022-01-06 at 15 34 41" src="https://user-images.githubusercontent.com/5891442/148448051-77df844a-4f33-46eb-be04-98ee7c169de1.png">

2022-01-06 20:34 UTC, maxwofford commented on app/services/donation_service/export/csv.rb
> +        ::CSV::Row.new(headers, ["date", "donation_from", "amount_cents"], true)
Could we also have a link to the hcb code show page in here? It'd certainly help our accountant to have that info & I bet users would want it too.

2022-01-06 20:34 UTC, maxwofford commented on app/services/donation_service/export/csv.rb
> +      BATCH_SIZE = 1000
What does this do?

2022-01-06 20:34 UTC, maxwofford commented on app/services/donation_service/export/csv.rb
> +      BATCH_SIZE = 1000
I'm cool with it in here, but want to sanity check that it doesn't prevent the user from downloading all their donations if they have over 1000 donations

2022-01-06 20:34 UTC, maxwofford commented on app/views/events/show.html.erb
> +            <%= link_to 'ALl transactions (JSON)', export_transactions_path(event: @event, format: :json), target: :_blank %>
```suggestion
            <%= link_to 'All transactions (JSON)', export_transactions_path(event: @event, format: :json), target: :_blank %>
```

(typo)

2022-01-06 20:34 UTC, maxwofford commented on app/views/events/donation_overview.html.erb
> +    <div class="md-pl1">
<img width="325" alt="Screen Shot 2022-01-06 at 15 22 24" src="https://user-images.githubusercontent.com/5891442/148447203-f3fba367-a2f3-466e-bf95-93fe71bbf851.png">

The icons look pretty similar and they're right next to each other. Could we tooltip this or something?

2022-01-06 20:34 UTC, maxwofford commented on app/services/donation_service/export/json.rb
> +          created_at: ct.created_at,
Mentioned already, but it'd be nice to have a link to the hcb show page in here

2022-01-06 20:34 UTC, maxwofford commented on app/controllers/donations_controller.rb
> +  def stream_donations_csv
Seems like https://github.com/hackclub/bank/pull/2186/files#diff-ffc09b43f46260b97fd886063b4d5bdd45981eb81ce208c1b0af8e11f536950aR110-R145 should be `private`

2022-01-07 02:54 UTC, exu3 commented on app/services/donation_service/export/csv.rb
> +      BATCH_SIZE = 1000
`batch_size` supposedly reads the csv file in batches; it still downloads all donations (tested with HQ's 21194 records). Performance-wise, it also feels alright without this line though even with 21194 donation records.

https://stackoverflow.com/questions/2962134/ruby-read-file-in-batches/41069373

2022-01-07 03:15 UTC, exu3 commented on app/services/donation_service/export/csv.rb
> +        ::CSV::Row.new(headers, ["date", "donation_from", "amount_cents"], true)
Good idea! https://github.com/hackclub/bank/pull/2186/commits/28ecf504a511984330f62e54155307f8ebda88b1

2022-01-07 03:20 UTC, exu3 commented on app/views/events/donation_overview.html.erb
> +    <div class="md-pl1">
Agree, I also thought it might be better if the design of the export button was more consistent with the existing export button, so I moved it a little further down. Do you think that makes it more clear?

![Screen Shot 2022-01-06 at 7 17 55 PM](https://user-images.githubusercontent.com/72365100/148485922-8484bd25-9190-467f-bf86-1ded0bea6e58.png)

2022-01-07 03:37 UTC, exu3 commented
> Additionally, this shows refunded donations in the export:

Would this be useful information to know? For bookkeeping perhaps? I've added a column to show the `aasm_state` (pending, deposited, refunded) so once exported, the user can easily create a filter to filter out refunded donations if need be.

2022-01-07 15:33 UTC, maxwofford commented on app/views/events/donation_overview.html.erb
> +    <div class="md-pl1">
That looks nice! It feels a little off center and isn't consistent with the way we show price amounts on other pages, but it feels like it's getting closer.

2022-01-07 15:35 UTC, maxwofford commented
> I've added a column to show the aasm_state 

@eilla1 Perfect, love it

2022-01-07 15:37 UTC, maxwofford commented on app/services/donation_service/export/csv.rb
> +      BATCH_SIZE = 1000
Cool! Let's leave the `BATCH_SIZE = 1000` then. I think we'll want it not to speed up downloads, but to prevent the process from using up too much memory– if 21194 donations are loaded into RAM when I click "export" that's potentially RAM away from someone else trying to load a page or download their own export.

2022-01-07 15:38 UTC, maxwofford approved these changes
This looks great. I think we can still improve the "export" button placement, but this is totally functional and I'm cool with it getting merged.

2022-01-07 17:18 UTC, merged

2022-01-10 10:18 UTC, garyhtou commented
amazing!!