Hide pending deposits to Emburse in the global Emburse tx list
hackclub/hcb pull request #232
Opened 2019-09-12 01:32 UTC by thesephist

This is a PR to fix something Michael pointed out, where Emburse has started syncing Pending transactions for deposits from Bank accounts to Emburse accounts.

This change does two things:

1. In the global emburse transaction list, hide any transactions that are **pending** and **amount > 0** (are deposits), since they shouldn't be processed until they're complete, to be conservative.
2. Don't count any pending deposits as defined in (1) as "under review"

2019-09-12 01:47 UTC, tmb requested changes
Otherwise looks good!

2019-09-12 01:47 UTC, tmb commented on app/models/emburse_transaction.rb
> +    self.event_id.nil? && undeclined? && !should_be_ignored?
You should just be able to do `event_id.nil?` here w/o the `self`

2019-09-12 01:47 UTC, tmb commented on app/models/emburse_transaction.rb
> +    :pending && self.amount > 0
Same here, you should just be able to do `amount > 0`

2019-09-12 02:22 UTC, merged

2019-09-12 02:22 UTC, thesephist commented
Just gonna merge since it's minor and I think I addressed the changes 🤷‍♂️ sorry @tmb I robbed you of your opportunity to make things light up in green

2019-09-13 16:06 UTC, thesephist commented
Undoing since it seems like there are unclear things about which things are syncing in production... we need a better way to be able to see the hidden transactions.

2019-09-14 00:07 UTC, thesephist commented
(Note to self): We should also have the dashboard hide notifications for the hidden pending transactions in the root page.