Documentation + Codespace setup scripts for Solargraph
hackclub/hcb pull request #2321
Opened 2022-02-23 05:20 UTC by exu3

Solargraph seems to work quite well for me in Docker/Codespaces, so this PR adds the stuff from #2227 to the Codespace setup scripts. I tested it out a couple times, and everything seems to work.
<img width="1305" alt="Screen Shot 2022-02-22 at 20 47 25" src="https://user-images.githubusercontent.com/72365100/155266227-1cf5e2c2-e1f1-499f-a70b-f80747d251eb.png">

2022-02-24 21:27 UTC, garyhtou requested changes
Yuhhh! i'm glad this is working for you!

2022-02-24 21:27 UTC, garyhtou commented on README.md
> +Run Solargraph in Docker: (You may also need to install the [Ruby Solargraph](https://marketplace.visualstudio.com/items?itemName=castwide.solargraph) VS Code extension)
Can we note that this is optional? And explain what it does?

2022-02-24 21:27 UTC, garyhtou commented on codespace-config.sh
> +
Can we use a command line flag to activate this feature? I don't think we should force/automatically run solargraph. it should be an explicit choice since it takes some set up and might not work for everyone

https://stackoverflow.com/questions/2875424/correct-way-to-check-for-a-command-line-flag-in-bash

2022-02-24 21:27 UTC, garyhtou commented on codespace-config.sh
> +
Same thing with `codespace-start.sh`

2022-02-25 07:48 UTC, exu3 commented on codespace-config.sh
> +
Good point!

Running the command with the flag `--with-solargraph` should activate this feature.

2022-02-25 07:48 UTC, exu3 commented
I tested it out, and it seems to work:

```sh
$ codespace-config.sh --with-solargraph # sets up the Codespace with Solargraph
$ codespace-start.sh --with-solargraph # starts the dev server along with Solargraph
```

2022-02-25 07:50 UTC, garyhtou approved these changes
great! ty!

2022-02-25 07:52 UTC, merged