Include sender full name in mailer
hackclub/hcb pull request #2332
Opened 2022-02-25 08:26 UTC by exu3

Closes #2329

2022-02-25 08:33 UTC, garyhtou commented
Can you test this with one of the Partner's representative? (representatives are just users)

here's a list of them:
![image](https://user-images.githubusercontent.com/20099646/155682086-73d32f0b-e2be-4ebf-98b3-25e071bd1bc2.png)

---

more info on reps if you're interested
https://github.com/hackclub/bank/blob/8810a5343c394cf746016d334c1519d5f9220dcd/app/models/partner.rb#L59-L67

2022-03-02 18:53 UTC, exu3 commented
I tried the following in a Rails console, but it doesn't seem quite right. I'm not sure where to find what sort of value(s) go with `invite` or `@invite` or if I'm doing this right at all

```ruby
::OrganizerPositionInvitesMailer.notify(invite: 123).deliver_now
```

Pointers would be greatly appreciated <img src="https://emoji.slack-edge.com/T0266FRGM/rayge/ae47ee41abadec93.png" width="30">

2022-03-03 21:45 UTC, garyhtou commented
It's definitely not easy to tell which type it takes, but if you look at https://github.com/hackclub/bank/blob/2afdbd66d6e63c5b3144dfe90dc734803549ac3c/app/mailers/organizer_position_invites_mailer.rb#L3-L10

you can see that it's calling `.email` and `.event` on `@invite`. That means it's gotta be an object. In this case, it's a `OrganizerPositionInvite`.

Try this instead:
```ruby
::OrganizerPositionInvitesMailer.notify(invite: OrganizerPositionInvite.find(123)).deliver_now
```

2022-03-04 02:24 UTC, exu3 commented
Ah thanks for the link; any idea what I might be missing here?

```ruby
irb(main):013:0> ::OrganizerPositionInvitesMailer.notify(invite: OrganizerPositionInvite.find(1234)).deliver_
now
  OrganizerPositionInvite Load (0.5ms)  SELECT "organizer_position_invites".* FROM "organizer_position_invites" WHERE "organizer_position_invites"."id" = $1 LIMIT $2  [["id", 1234], ["LIMIT", 1]]
OrganizerPositionInvitesMailer#notify: processed outbound mail in 0.3ms
Traceback (most recent call last):
        3: from (irb):12
        2: from (irb):13:in `rescue in irb_binding'
        1: from app/mailers/organizer_position_invites_mailer.rb:4:in `notify'
ArgumentError (unknown keyword: :invite)
```

2022-03-04 09:06 UTC, garyhtou commented
ah so since the code is getting `invite` from `params` instead of as a method parameter, we need to pass the invite using `with`.

```ruby
OrganizerPositionInvitesMailer.with(invite: OrganizerPositionInvite.find(123)).notify.deliver_later
```

`param` (instead of method parameters) is sometimes used in mailers to get arguments because it makes them easier to call from controllers. In this case, we aren't calling from the controller, so the mailer doesn't have the context/arguments it needs. we can use `with` to provide it those arguments

2022-03-05 06:50 UTC, exu3 commented
Ooh got it, thanks for the explanation.

User:
<img width="500" alt="Screen Shot 2022-03-04 at 22 42 41" src="https://user-images.githubusercontent.com/72365100/156872090-8c2654b0-f0df-4514-836b-471122cf4dca.png">

GB:
<img width="500" alt="Screen Shot 2022-03-04 at 22 46 28" src="https://user-images.githubusercontent.com/72365100/156872095-356d229d-6e7d-442a-a157-4c3fc6b0abac.png">

Dev:
<img width="500" alt="Screen Shot 2022-03-04 at 22 48 11" src="https://user-images.githubusercontent.com/72365100/156872097-a1b4005f-11ed-4cb1-b151-ccb50a2ed198.png">

2022-03-07 21:33 UTC, garyhtou requested changes

2022-03-07 21:33 UTC, garyhtou commented on app/views/organizer_position_invites_mailer/notify.html.erb
> +  You've been invited by <strong><%= @invite.sender.full_name %></strong> to help manage <strong><%= @invite.event.name %></strong>, which is running on Hack Club Bank, an online dashboard to store f
"you've been invited by Givebutter to _help_ manage `<event name>`" sounds kinda weird since Givebutter users will be receiving this email when their org is approved or when they log into bank for the first time.

Thoughts on removing the word "help" or updating the copy so it works in the case it's a rep and a normal user doing the inviting?

2022-03-07 21:34 UTC, garyhtou commented on app/views/organizer_position_invites_mailer/notify.html.erb
> +  You've been invited by <strong><%= @invite.sender.full_name %></strong> to help manage <strong><%= @invite.event.name %></strong>, which is running on Hack Club Bank, an online dashboard to store f
If you'd like, you can also do have a conditional here (if it's a rep, then show a different copy)!

2022-03-07 21:44 UTC, exu3 commented on app/views/organizer_position_invites_mailer/notify.html.erb
> +  You've been invited by <strong><%= @invite.sender.full_name %></strong> to help manage <strong><%= @invite.event.name %></strong>, which is running on Hack Club Bank, an online dashboard to store f
> Thoughts on removing the word "help" or updating the copy so it works in the case it's a rep and a normal user doing the inviting?

Yeah, I think removing "help" => "You've been invited by Givebutter :sparkles: to manage Butter Foundation..." makes sense for both cases. 

When a Bank admin creates a new org & sends the initial invite, it would also say something like "You've been invited by Liv Cook to _help_ manage DevHacks...", so I think removing "help" might make more sense.

2022-03-07 21:47 UTC, garyhtou approved these changes
Looks good, thanks Ella!

2022-03-07 21:48 UTC, merged