WebAuthn login
hackclub/hcb pull request #2365
Opened 2022-03-09 15:35 UTC by cjdenio

what's this, fingerprint login???

Thoughts on the "security key" terminology? I'm not sure if there's a better term

<img width="597" alt="Screen Shot 2022-03-09 at 3 35 27 PM" src="https://user-images.githubusercontent.com/34525547/157531426-4353a1ea-f154-4251-ae72-521c1750230b.png">

2022-03-09 16:50 UTC, cjdenio commented
<img src="https://user-images.githubusercontent.com/34525547/157490147-e9c7f5e2-dfce-4c99-97fa-e3c32119a7be.png" width="200" />

2022-03-10 21:56 UTC, maxwofford commented
@cjdenio sorry for the deploy issues– i think it's fixed now & will deploy correctly on future pushes. I removed the old app and am setting up a new one that should be live in 10-15 min (rebuilding from scratch)

2022-03-11 08:21 UTC, garyhtou reviewed
ahhh!! i love this so much Caleb! amazing work on this

a couple suggestions:
  - move `beta` badge to the right side of the count badge
    - we should maybe also added one to the Login Codes header to keep it consistant
  - I wonder how technical our terminology should be
	  - the "Security key" and "Register" button might sound a bit confusing/vague for those who are unfamiliar (I think you were briefly getting at).
	  - "Setup" might be a more friendly term for "Register"
	  - I honestly don't think there's a better term for "security key". it's still pretty new so we want whatever term we choose should be easily searchable. I do like how you provided context on what a security key is with:
	       > Sign in to Bank using your fingerprint or a hardware security key.
  - I've love to know which sessions a security key as created (doesn't have to happen in this PR)
    - can you add a `UserSession` `has_one` `WebauthnCredential` relationship? (similar to the relationship between UserSession and LoginToken)
  - it would be nice to be able to easily identify between similar platform keys (there's no issue with cross-platform because you can set a name). would it be a good idea to maybe display the last few characters of the public key?

2022-03-11 18:17 UTC, cjdenio commented
Thanks so much for the suggestions! Here's what it looks like after a few tweaks:

<img width="810" alt="Screen Shot 2022-03-11 at 1 13 39 PM" src="https://user-images.githubusercontent.com/34525547/157925836-ddcdcda0-9d25-4af1-a47e-19337d150bbc.png">

It's not in the UI yet (probably something for another PR), but sessions are now associated with the security key that was used to sign in.

---

> it would be nice to be able to easily identify between similar platform keys (there's no issue with cross-platform because you can set a name). would it be a good idea to maybe display the last few characters of the public key?

Hmm, what if you could name devices instead?

<img width="543" alt="Screen Shot 2022-03-11 at 1 15 33 PM" src="https://user-images.githubusercontent.com/34525547/157926102-ed8edd59-28b3-467a-a2f7-2e6eabdb388f.png">

2022-03-11 21:47 UTC, garyhtou commented
> Hmm, what if you could name devices instead?

Yeah, that might be a good idea. and have it default to what you had previously

2022-03-16 18:31 UTC, cjdenio commented
This is ready for review once y'all get a chance.

2022-03-16 19:54 UTC, garyhtou commented
I can review this early next week! thanks for working on this!

2022-03-23 07:21 UTC, garyhtou requested changes
good work! The main request here is to move the icon svg into the assets folder so that they can be easily reused

2022-03-23 07:21 UTC, garyhtou commented on app/controllers/users_controller.rb
> +    options = WebAuthn::Credential.options_for_get(allow: user.webauthn_credentials.map { |c| c.webauthn_id })
Try using `pluck` instead of `map` here (it's more performant)

2022-03-23 07:21 UTC, garyhtou commented on app/helpers/static_pages_helper.rb
> +        "<a href='/my/settings#security-keys'>☝️ You can sign in with your fingerprint!</a>",
🎉

2022-03-23 07:21 UTC, garyhtou commented on app/views/users/edit.html.erb
> +            </svg>
Can we move this into `app/assets/images/icons`?

2022-03-23 07:21 UTC, garyhtou commented on config/initializers/webauthn.rb
> +  end
`Rails.application.routes.url_helpers.root_url`

2022-03-23 08:42 UTC, garyhtou commented
Also, there seems to be a database migration issue with the staging deploy (it was working properly at one point 😖). Let's make sure we figure that out before merging into main

2022-03-23 16:18 UTC, cjdenio commented
Hmm, it looks like the production > staging transfer is erroring (but somehow not stopping the deployment)

```
pg_restore: while PROCESSING TOC:

pg_restore: from TOC entry 4556; 2606 16703 CONSTRAINT users users_pkey udo99a4o8ejlir

pg_restore: error: could not execute query: ERROR:  cannot drop constraint users_pkey on table public.users because other objects depend on it

DETAIL:  constraint fk_rails_a4355aef77 on table public.webauthn_credentials depends on index public.users_pkey

HINT:  Use DROP ... CASCADE to drop the dependent objects too.

Command was: ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS users_pkey;

pg_restore: from TOC entry 248; 1259 16614 TABLE users udo99a4o8ejlir

pg_restore: error: could not execute query: ERROR:  cannot drop table public.users because other objects depend on it

DETAIL:  constraint fk_rails_a4355aef77 on table public.webauthn_credentials depends on table public.users

HINT:  Use DROP ... CASCADE to drop the dependent objects too.

Command was: DROP TABLE IF EXISTS public.users;

pg_restore: from TOC entry 5103; 0 0 COMMENT EXTENSION citext 

pg_restore: error: could not execute query: ERROR:  must be owner of extension citext

Command was: COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';





pg_restore: from TOC entry 5104; 0 0 COMMENT EXTENSION pg_stat_statements 

pg_restore: error: could not execute query: ERROR:  must be owner of extension pg_stat_statements

Command was: COMMENT ON EXTENSION pg_stat_statements IS 'track execution statistics of all SQL statements executed';





pg_restore: from TOC entry 248; 1259 16614 TABLE users udo99a4o8ejlir

pg_restore: error: could not execute query: ERROR:  relation "users" already exists

Command was: CREATE TABLE public.users (

    id bigint NOT NULL,

    api_access_token text,

    created_at timestamp without time zone NOT NULL,

    updated_at timestamp without time zone NOT NULL,

    session_token text,

    email text,

    full_name character varying,

    phone_number text,

    admin_at timestamp without time zone,

    slug character varying,

    pretend_is_not_admin boolean DEFAULT false NOT NULL,

    sessions_reported boolean DEFAULT false NOT NULL,

    phone_number_verified boolean DEFAULT false,

    use_sms_auth boolean DEFAULT false

);





pg_restore: from TOC entry 4556; 2606 16703 CONSTRAINT users users_pkey udo99a4o8ejlir

pg_restore: error: could not execute query: ERROR:  multiple primary keys for table "users" are not allowed

Command was: ALTER TABLE ONLY public.users

    ADD CONSTRAINT users_pkey PRIMARY KEY (id);





pg_restore: warning: errors ignored on restore: 6

config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:



  * development - set it to false

  * test - set it to false (unless you use a tool that preloads your test environment)

  * production - set it to true



RAILS_ENV=staging environment is not defined in config/webpacker.yml, falling back to production environment

DEPRECATION WARNING: Initialization autoloaded the constants Util and BankApiService.



Being able to do this is deprecated. Autoloading during initialization is going

to be an error condition in future versions of Rails.



Reloading does not reboot the application, and therefore code executed during

initialization does not run again. So, if you reload Util, for example,

the expected changes won't be reflected in that stale Module object.



These autoloaded constants have been unloaded.



Please, check the "Autoloading and Reloading Constants" guide for solutions.

 (called from <main> at /app/config/environment.rb:7)

== 20220306231017 SetupWebauthn: migrating ====================================

-- create_table(:webauthn_credentials)

rails aborted!

StandardError: An error has occurred, this and all later migrations canceled:



PG::DuplicateTable: ERROR:  relation "webauthn_credentials" already exists

/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `exec'

/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `block (2 levels) in execute'

/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'

/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'

/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'

/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:91:in `block in execute'

/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'

/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'

/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'

/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'

/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'

/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'

/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract_adapter.rb:721:in `block in log'

/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'

/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract_adapter.rb:712:in `log'

/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:90:in `execute'

/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract/schema_statements.rb:315:in `create_table'

/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:890:in `block in method_missing'

/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:858:in `block in say_with_time'

/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:858:in `say_with_time'

/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:879:in `method_missing'

/app/vendor/bundle/ruby/2.7.0/gems/strong_migrations-0.7.1/lib/strong_migrations/migration.rb:10:in `block in method_missing'

/app/vendor/bundle/ruby/2.7.0/gems/strong_migrations-0.7.1/lib/strong_migrations/checker.rb:278:in `perform'

/app/vendor/bundle/ruby/2.7.0/gems/strong_migrations-0.7.1/lib/strong_migrations/migration.rb:9:in `method_missing'

/app/db/migrate/20220306231017_setup_webauthn.rb:5:in `change'

/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:828:in `exec_migration'

/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:812:in `block (2 levels) in migrate'

/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:811:in `block in migrate'

/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:471:in `with_connection'

/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:810:in `migrate'

/app/vendor/bundle/ruby/2.7.0/gems/strong_migrations-0.7.1/lib/strong_migrations/mig [...]

2022-03-23 20:53 UTC, cjdenio commented
@garyhtou STAGING WORKS https://bank--pr-2365.herokuapp.com <img src="https://emoji.slack-edge.com/T0266FRGM/celebratoryrat/40083cdca0584aa2.png" width="20" />

2022-03-23 21:36 UTC, garyhtou commented
> STAGING WORKS

HECK YEAH!

2022-03-23 21:38 UTC, garyhtou approved these changes
Good to merge! 🎉 

---

Also, fyi
![image](https://user-images.githubusercontent.com/20099646/159799942-41fce97e-c6bf-4e58-9fca-c73ce3fe451d.png)
This seems to be a non-issue, but I just wanted to make sure you're aware

2022-03-23 21:42 UTC, garyhtou commented
Once merged, let's have some users test it for a few days, then feel free to #ship this!

2022-03-23 22:52 UTC, merged