Don't show shipping if card status is `shipped`
hackclub/hcb pull request #2372
Opened 2022-03-14 03:00 UTC by exu3

`shipped` is the final status of cards shipped without tracking. ([Relevant section from Stripe docs](https://stripe.com/docs/api/issuing/cards/object#issuing_card_object-shipping-status)) Currently, the cards page shows the shipping info unless the card's status is `delivered` (which isn't possible given the way that physical cards are shipped currrently.)

With this PR, the shipping info won't be visible if the card's status is `shipped`.

Fixes #2022

2022-03-14 23:40 UTC, exu3 commented
Hmm I think a another way to fix this might be to only show the shipping info for the card if the card `eta` < `Time.now`. Not sure which would be better.

2022-03-23 07:31 UTC, garyhtou requested changes

2022-03-23 07:31 UTC, garyhtou commented on app/models/stripe_card.rb
> +  scope :physical_shipping, -> { physical.includes(:user, :event).reject { |c| c.stripe_obj[:shipping][:status] == "delivered" || c.stripe_obj[:shipping][:status] == "shipped" } }
I think we might be able to use the `shipping_has_tracking?` method

See if something like this would work:
```ruby
scope :physical_shipping, -> { physical.includes(:user, :event).accept { |c| c.shipping_has_tracking? }.reject { |c| c.stripe_obj[:shipping][:status] == "delivered" } }
```
I'm putting the `accept` first because the `reject` makes an API call to Stripe for every object (`stripe_obj` calls `::Partners::Stripe::Issuing::Cards::Show`). This lets us prevent unnecessary API calls

2022-03-23 07:39 UTC, garyhtou commented on app/models/stripe_card.rb
> +  scope :physical_shipping, -> { physical.includes(:user, :event).reject { |c| c.stripe_obj[:shipping][:status] == "delivered" || c.stripe_obj[:shipping][:status] == "shipped" } }
Oh actually, scrape this.

> Hmm I think a another way to fix this might be to only show the shipping info for the card if the card eta < Time.now. Not sure which would be better.

I like this better

2022-03-23 07:47 UTC, garyhtou commented
> Hmm I think a another way to fix this might be to only show the shipping info for the card if the card eta < Time.now. Not sure which would be better.

Let's go with this. But do something like `eta > 1.weeks.ago`. This way, we show that card for a week after the ETA, in case shipping is slow.

Can you update the count so that it's more accurate?
https://github.com/hackclub/bank/blob/master/app/views/stripe_cards/shipping.html.erb#L4-L4
Instead of getting the count of `@stripe_cards`, we need to change the way we calculate this.

- If the card has tracking, and isn't delivered yet. Then include it in the count
- If the card doesn't have tracking, then include it in the count unless we're past the ETA

This calculation can be performed in the controller, then the value can be assigned to a new instance variable such as `@stripe_cards_arriving_count`

2022-03-24 07:39 UTC, exu3 commented
https://github.com/hackclub/bank/pull/2372/commits/378a1206f8939b0f549944ef35825a85c075e6a1 attempts to address the comment above. However, I haven't tested it because Development Bank doesn't seem to have the full Card object. Is there a way to test it? I'm not very confident that my code works :p

2022-03-30 16:17 UTC, exu3 commented
I think this is ready for another review whenever you get a chance. <img src="https://user-images.githubusercontent.com/72365100/160882621-b64e44c0-b893-4fa8-b30d-e865e263ceba.png" width="20"> Ty!

2022-03-30 19:20 UTC, garyhtou commented on app/controllers/stripe_cards_controller.rb
> +      @stripe_cards = current_user.stripe_cards.physical_shipping.where("eta > 1.week.ago.to_i")
I think we might be missing a couple of things here

We would want to get the eta for every card. try something like this:
```ruby
@stripe_cards = current_user.stripe_cards.physical_shipping.reject { |sc| Time.at(sc.stripe_obj[:shipping][:eta]) < 1.week.ago }
```

2022-03-31 23:13 UTC, garyhtou approved these changes

2022-03-31 23:14 UTC, merged