Transparency for HCB Code show pages
hackclub/hcb pull request #2520
Opened 2022-04-29 01:00 UTC by garyhtou

Unauthenticated users are now redirected to the ledger to view the transaction details

2022-04-29 01:18 UTC, garyhtou commented
closes https://github.com/hackclub/bank/issues/2302

2022-04-29 14:38 UTC, maxwofford commented
This looks great! I love the recording. One thing we'll want to do before this is merged is check for anything that relies on the HCB code hash ID being private– at the very least the receipts upload endpoint (sent in the transaction mailer) assumes hash ID is private. ~~Could you create a ticket along the lines of `HCB hashID shouldn't be used for anything sensitive` to track this?~~

UPDATE: Added it here! https://github.com/hackclub/bank/issues/2542

2022-05-13 00:53 UTC, exu3 commented
This PR should be merged after #2543

2022-05-15 20:02 UTC, maxwofford requested changes
Just tested locally. The visuals look great! Couple things:

- Worked for some HCB codes (0eH9NK), but others redirected to login (PVHxXp)
- I lost the TX b/c the highlight went away and I scrolled. Could we keep an orange border around it similar to how our direct-linked comments look?

2022-05-15 21:32 UTC, cjdenio commented
Little note: you can do the `.hash-highlight` thing with pure CSS: https://developer.mozilla.org/en-US/docs/Web/CSS/:target

2022-05-31 13:20 UTC, maxwofford commented
On a call, @garyhtou mentioned he was too busy with school to close this out atm. @cjdenio want to close this out together? Seems like the stuff left over is...
- Highlighting (switch to CSS solution, and keep highlight around for longer)
- Fix broken cases (PVHxXp) that still redirect to login

2022-05-31 13:46 UTC, maxwofford commented
Ok, just fixed the issue for hcb codes that didn't seem to work (they were all lacking CTs). For the CSS, want to just swap out the current logic @cjdenio?

2022-05-31 13:54 UTC, maxwofford approved these changes
I'm fine with this being merged now– https://github.com/hackclub/bank/pull/2520#issuecomment-1142157886.

2022-05-31 13:57 UTC, cjdenio requested changes

2022-05-31 13:57 UTC, cjdenio commented on app/assets/stylesheets/components/_transactions.scss
> +:target {
Currently this also targets non-transactions

2022-05-31 14:00 UTC, maxwofford commented on app/assets/stylesheets/components/_transactions.scss
> +:target {
@cjdenio if you have a fix for this please add it! I don't think anyone is directly working on the branch rn, so feel free to push directly here.

2022-05-31 14:03 UTC, cjdenio approved these changes

2022-05-31 14:09 UTC, merged

2022-05-31 20:57 UTC, garyhtou commented on app/controllers/hcb_codes_controller.rb
> +      pos = txs.index { |tx| tx.hcb_code == hcb } + 1
`index` should be `||` with `0` since it may return `nil`.

```ruby
pos = (txs.index { |tx| tx.hcb_code == hcb } || 0) + 1
```
I think `index` would return `nil` if it's a pending tx (pending transactions are always on the first page, but aren't in the array)

@cjdenio would you mind testing/making this change?