Hide declined transactions from /my/inbox list
hackclub/hcb pull request #2568
Opened 2022-05-11 13:03 UTC by maxwofford

Fixes for https://github.com/hackclub/bank/issues/2460 / https://github.com/hackclub/bank/issues/2533

I'd love to get your eyes on this @garyhtou. This code accomplishes the intent of my UI changes, but I want a sanity check on how I'm writing it:
<img width="1902" alt="Screen Shot 2022-05-11 at 08 59 39" src="https://user-images.githubusercontent.com/5891442/167856376-aea84ce1-4495-4b49-a96e-bcb322d42ca5.png">
<img width="1920" alt="Screen Shot 2022-05-11 at 09 01 49" src="https://user-images.githubusercontent.com/5891442/167856394-acb240b0-25c1-45b6-b428-cd3c936db22a.png">

Recommend reaching each commit separately– they're each an individual change.

2022-05-11 15:33 UTC, cjdenio requested changes

2022-05-11 15:33 UTC, cjdenio commented on app/models/hcb_code.rb
> +    when :unknown
Ruby's `case` conditions don't fall through (like they do in other languages), so maybe do something like this?

```rb
if type == :card_charge && !pt.declined?
  true
else
  false
end
```

2022-05-23 02:05 UTC, cjdenio commented on app/views/static_pages/my_inbox.html.erb
> +                <% next if pt.declined? %>
Is this necessary if transactions are already filtered in the controller?

2022-05-23 14:21 UTC, maxwofford commented on app/views/static_pages/my_inbox.html.erb
> +                <% next if pt.declined? %>
Yep! The controller filters for missing receipts, but we only have `declined?` context on the actual PT or CT. That said, that should probably be dropped into the controller– will do that now!

2022-05-23 15:10 UTC, maxwofford commented on app/views/static_pages/my_inbox.html.erb
> +                <% next if pt.declined? %>
Just pushed code that should be clearer. Also replaced the `declined?` usage with `receipt_required?` provided by the Receiptable concern.

2022-05-23 19:45 UTC, cjdenio approved these changes

2022-05-23 19:46 UTC, merged