Instantly create PTs for ACHs
hackclub/hcb pull request #2971
Opened 2022-08-31 16:53 UTC by cjdenio

This PR fixes the famed ACH 404 error by instantly creating a `CanonicalPendingTransction` when an ACH transfer is created (which then, in turn, creates an `HcbCode`).

2022-08-31 18:39 UTC, exu3 reviewed
Is the ACH supposed to appear on the event show after being created? I created a couple ACHs but they didn't seem to show up on the ledger or affect the balance.

<img width="500" alt="Screen Shot 2022-08-31 at 2 35 46 PM" src="https://user-images.githubusercontent.com/72365100/187754103-b45d8554-ad92-4544-a29e-d378385da628.png">

<img width="500" alt="Screen Shot 2022-08-31 at 2 36 12 PM" src="https://user-images.githubusercontent.com/72365100/187754114-16450f19-943b-465e-bafb-a78afe42f560.png">

2022-08-31 19:33 UTC, cjdenio commented
oops, thanks for catching that <img src="https://emoji.slack-edge.com/T0266FRGM/flushed-fb/0be3830594ba383b.png" width="20" />

2022-08-31 19:42 UTC, exu3 requested changes
###### wahoo!

One more thing: if the ACH gets rejected, it still stays on the ledger and affects the balance.

2022-09-01 08:38 UTC, albertchae commented on app/services/ach_transfer_service/create.rb
> +      PendingEventMappingEngine::Map::Single::OutgoingAch.new(canonical_pending_transaction: pt).run
It might be worth wrapping this in a [database transaction](https://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html) so it's all or nothing?

2022-09-28 19:00 UTC, cjdenio commented
> ###### wahoo!
> One more thing: if the ACH gets rejected, it still stays on the ledger and affects the balance.

It will disappear from the ledger, just on a cron job instead of instantly. I agree it's not the ideal behavior, but I think it's out of scope since that was the behavior before this PR

2022-09-28 21:16 UTC, exu3 approved these changes

2022-09-28 21:22 UTC, merged