add spending limits?
hackclub/hcb pull request #2978
Opened 2022-09-01 15:42 UTC by bellesea

2022-09-01 15:59 UTC, cjdenio requested changes
This is a great start!

2022-09-01 15:59 UTC, cjdenio commented on app/controllers/stripe_cards_controller.rb
> +
There should be some updating done here

2022-09-01 15:59 UTC, cjdenio commented on config/routes.rb
> +    post "update"
```suggestion
```

This is unnecessary because `update` is already set by the `resources` thing

2022-09-01 15:59 UTC, cjdenio commented on app/views/stripe_cards/show.html.erb
> +      <% if @card.spending_limit_amount == 2000000 %>
What if the user manually sets the spending limit to $20,000?

2022-09-01 15:59 UTC, cjdenio commented on app/views/stripe_cards/_form.html.erb
> +  </div>
I don't know about having this here— spending limits feel like an "advanced" option, and this makes the card order form a bit long

2022-09-01 17:25 UTC, bellesea commented on app/controllers/stripe_cards_controller.rb
> +
thanks!

2022-09-01 19:08 UTC, bellesea commented on app/views/stripe_cards/show.html.erb
> +      <% if @card.spending_limit_amount == 2000000 %>
hmm i'm not sure, any suggestions? cuz this is the default spending limit... or maybe we could set the default to the event balance?

2022-09-01 19:09 UTC, bellesea commented on app/views/stripe_cards/_form.html.erb
> +  </div>
We cut it down from two types of limits to one, maybe that could help? cuz i think being able to immediately set limit could be helpful?

2022-09-04 01:56 UTC, maxwofford commented on app/views/stripe_cards/_form.html.erb
> +  </div>
What if it's a 2 step process– first order your card, then on the "your card has been created!" page giving the spending limits?

2022-09-04 01:58 UTC, maxwofford commented on app/views/stripe_cards/_form.html.erb
> +  </div>
Errr, hit send before I finished– the intent is to make it so spending limits are a bonus thing users can opt-into on top of the card ordering flow instead of making the current flow longer.

2022-09-04 02:50 UTC, bellesea commented on app/views/stripe_cards/_form.html.erb
> +  </div>
Hey Max 👋 Ahh yeah that makes sense! What if it's something like

> Set spending limit (with the link to the edit page)?

2022-11-29 17:28 UTC, closed without merging