Add balance and card count stats to homepage
hackclub/hcb pull request #2986
Opened 2022-09-05 19:40 UTC by YodaLightsabr

Adds total balance and number of card statistics to each organization card on the homepage

Before | After
-----|-----
![image](https://user-images.githubusercontent.com/76178582/188505684-12308a87-2e22-499a-a036-878a8b11b0e2.png) ![image](https://user-images.githubusercontent.com/76178582/188505704-2bf216f5-99b1-4a0d-a3a2-0f892203a382.png) ![image](https://user-images.githubusercontent.com/76178582/188505846-5e96405e-1afe-4f2f-85f9-ce290552878e.png) | ![image](https://user-images.githubusercontent.com/76178582/188505735-0230203b-9bed-4653-aeef-a2d42ddca263.png) ![image](https://user-images.githubusercontent.com/76178582/188505720-fea70dca-526e-4a77-9a66-3dd2fa27d436.png) ![image](https://user-images.githubusercontent.com/76178582/188505873-5d2645a6-ff92-463b-b010-6447b7fcdb4a.png)

Right now it only applies to unhidden organizations the user is in; I'm not sure how hidden orgs work, so I left that out, and I feel like invitations don't need that information on the card.

However, I can add it back to both of those if it would make it more cohesive.

This is my first "feature" PR (if you'd even call it that), so I likely did something wrong or something that doesn't fit with the code style 😅.

2022-09-05 20:19 UTC, cjdenio commented on app/views/static_pages/index.html.erb
> +                  <span><%= event.stripe_cards.length() %></span>
Slight optimization:

```suggestion
                  <span><%= event.stripe_cards.count %></span>
```

`.length` causes it to fetch all the Stripe cards from the database, then count them client-side. `.count` sends a `SELECT COUNT(*)` query to the database instead.

2022-09-05 20:20 UTC, YodaLightsabr commented on app/views/static_pages/index.html.erb
> +                  <span><%= event.stripe_cards.length() %></span>
Oh cool. Let's use count then.

2022-09-06 16:03 UTC, cjdenio commented on app/views/static_pages/index.html.erb
> +                  <%= inline_icon 'payment', size: 16, class: 'muted align-middle', 'aria-label': 'Dollar sign', style: 'transform: scale(2)' %>
Could you remove the `transform: scale(2)` and update `size` instead?

2022-09-06 16:03 UTC, cjdenio commented on app/views/static_pages/index.html.erb
> +                  <%= inline_icon 'card', size: 20, class: 'muted align-middle', 'aria-label': 'Dollar sign', style: 'transform: scale(1.2)' %>
Here too

2022-09-06 17:09 UTC, YodaLightsabr commented on app/views/static_pages/index.html.erb
> +                  <%= inline_icon 'payment', size: 16, class: 'muted align-middle', 'aria-label': 'Dollar sign', style: 'transform: scale(2)' %>
Originally it was like that, but the svg itself has a layer of padding that would throw off the rest of the card. It also helps with vertical alignment, but if you have a better solution we can use that. I agree that `scale` is hacky.

2022-09-06 17:10 UTC, YodaLightsabr commented on app/views/static_pages/index.html.erb
> +                  <%= inline_icon 'card', size: 20, class: 'muted align-middle', 'aria-label': 'Dollar sign', style: 'transform: scale(1.2)' %>
https://github.com/hackclub/bank/pull/2986#discussion_r963975522

2022-09-07 16:04 UTC, YodaLightsabr commented
Aside from these changes do you have any other suggestions?

2022-09-20 02:54 UTC, cjdenio requested changes
Sorry for the delay! I've left a few final suggestions + comments, then this is good to go! (Most of these are just style refactors to better fit the rest of the codebase)

2022-09-20 02:54 UTC, cjdenio commented on app/assets/stylesheets/components/_mini_stats.scss
> +html[data-dark='true'] {
This file needs to be imported in `application.scss` to work: https://github.com/hackclub/bank/blob/342f5aea49b8b4437948a16ade7357e66ce4d526/app/assets/stylesheets/application.scss#L172-L204

2022-09-20 02:54 UTC, cjdenio commented on app/views/static_pages/index.html.erb
> +              <strong class="brand-sans h4 line-height-2 mb2" style="display: inline-grid; grid-template-columns: 1fr 1fr;">
- Maybe use `div` instead of `strong`
- Perhaps use flexbox instead of grid: `class="flex justify-between"`

2022-09-20 02:54 UTC, cjdenio commented on app/assets/stylesheets/components/_mini_stats.scss
> +}
```suggestion
.ministat {
  display: flex;
  align-items: center;
}
```

fixes the alignment slightly (flexbox ftw)

2022-09-20 02:54 UTC, cjdenio commented on app/views/static_pages/index.html.erb
> +                  <%= inline_icon 'card', size: 20, class: 'muted align-middle', 'aria-label': 'Dollar sign', style: 'transform: scale(1.2)' %>
```suggestion
                  <%= inline_icon 'card', size: 20, class: 'muted align-middle', 'aria-label': 'Cards', style: 'transform: scale(1.2)' %>
```

2022-09-20 02:54 UTC, cjdenio commented on app/views/static_pages/index.html.erb
> +                <span style="white-space: nowrap;" class="ministat">
<img width="939" alt="Screen Shot 2022-09-19 at 10 51 45 PM" src="https://user-images.githubusercontent.com/34525547/191156738-47fa2914-166c-4c35-9bab-8e69a276fdda.png">

The layout breaks in cases like this

2022-09-20 02:54 UTC, cjdenio commented on app/views/static_pages/index.html.erb
> +                <span style="white-space: nowrap;" class="ministat">
(let me know if you want any help figuring this out)

2022-09-20 05:02 UTC, YodaLightsabr commented on app/views/static_pages/index.html.erb
> +                <span style="white-space: nowrap;" class="ministat">
I think I'll end up doing `6.2k`, `1.7m`, or dropping the cents entirely.

2022-09-20 05:07 UTC, YodaLightsabr commented on app/assets/stylesheets/components/_mini_stats.scss
> +html[data-dark='true'] {
Makes sense! It seemed like it worked before for some reason though, I'm not sure. I'll take another look at this.

2022-09-26 22:39 UTC, YodaLightsabr commented on app/views/static_pages/index.html.erb
> +                <span style="white-space: nowrap;" class="ministat">
Thoughts on this implementation?

2022-10-05 16:03 UTC, cjdenio requested changes
Just switched "Event" to "Organization"

2022-10-05 16:03 UTC, cjdenio commented on app/assets/stylesheets/components/_mini_stats.scss
> +html[data-dark='true'] {
You can delete this file I think

2022-10-05 16:03 UTC, cjdenio commented on app/views/users/edit.html.erb
> +        <h3 class="h1 p2 my0 color-black">Detailed Events List</h3>
```suggestion
        <h3 class="h1 p2 my0 color-black">Detailed Org List</h3>
```

2022-10-05 16:03 UTC, cjdenio commented on app/views/users/edit.html.erb
> +        see a modified events list on the Bank homepage.
```suggestion
        The organization list now shows additional information about each org
        such as current balance and card count. After opting-in, you'll
        see a modified org list on the Bank homepage.
```

2022-10-05 17:23 UTC, cjdenio commented on app/assets/stylesheets/components/_mini_stats.scss
> +html[data-dark='true'] {
@YodaLightsabr it's still here— you had both `mini_stat.scss` and `mini_stats.scss`

2022-10-05 17:23 UTC, cjdenio commented on app/views/static_pages/index.html.erb
> +              <% end %>
```suggestion
              <% if Flipper.enabled?(:detailed_events_list_2022_10_04, current_user) %>
                <div class="brand-sans h4 line-height-2 mb2 flex justify-between"> 
                  <span style="white-space: nowrap;">
                    <%= inline_icon 'payment', size: 16, class: 'muted align-middle', 'aria-label': 'Dollar sign', style: 'transform: scale(2)' %>
                    <strong><%= render_money_amount(event.balance_v2_cents) %></strong>
                  </span>
                  <span>
                    <%= inline_icon 'card', size: 20, class: 'muted align-middle', 'aria-label': 'Cards', style: 'transform: scale(1.2)' %>
                    <strong><%= event.stripe_cards.count %></strong>
                  </span>
                </div>
              <% end %>
```

2022-10-05 17:44 UTC, YodaLightsabr commented
Alright, I think it's ready.

2022-10-05 17:57 UTC, cjdenio approved these changes
This is great! You can go ahead and merge!

2022-10-05 18:03 UTC, merged