Draft: Restructure User Settings
hackclub/hcb pull request #3209
Opened 2022-11-06 23:45 UTC by InternetRamen

Solves #3127

2022-11-19 17:06 UTC, InternetRamen commented
Does anyone know how to create link_to buttons with form elements? Or should I just create a whole new form for updating these settings.

2022-11-22 01:29 UTC, cjdenio requested changes

2022-11-22 01:29 UTC, cjdenio commented on app/assets/stylesheets/components/_tabs.scss
> +  border-bottom: 1px solid $muted;
```suggestion
  border-bottom: 0.5px solid map-get($palette, slate);
  background-color: $dark;
  z-index: 5;
```

Updated to match the underline on the "Settings" header

2022-11-22 01:29 UTC, cjdenio commented on app/assets/stylesheets/components/_forms.scss
I think this deserves its own PR

2022-11-22 01:29 UTC, cjdenio commented on app/views/users/_settings_nav.html.erb
> +        <% end %>
```suggestion
        <%= link_to 'General', '/my/settings/', data: { turbo: true } %>
```

2022-11-22 01:29 UTC, cjdenio commented on app/views/users/_settings_nav.html.erb
> +        <% end %>
```suggestion
        <%= link_to 'Security', '/my/settings/security', data: { turbo: true } %>
```

2022-11-22 01:29 UTC, cjdenio commented on app/assets/stylesheets/components/_tabs.scss
> +    cursor: pointer;
```suggestion
```

Since `<a>` already has this

2022-11-22 01:41 UTC, InternetRamen commented on app/assets/stylesheets/components/_forms.scss
Yup

2022-11-22 01:42 UTC, cjdenio commented on app/views/users/edit.html.erb
> +        <%= form.label :profile_picture, class: 'fileupload' %>
```suggestion
```

2022-11-22 02:24 UTC, cjdenio approved these changes

2022-11-22 02:24 UTC, merged