Custom stripe card names
hackclub/hcb pull request #3228
Opened 2022-11-18 23:14 UTC by tinuh

closes #2998

## Before
![image](https://user-images.githubusercontent.com/41168054/204167794-bfb56e60-af58-43f8-913c-757401be591e.png)

## After
![image](https://user-images.githubusercontent.com/41168054/204168718-2c1990b8-3501-4f02-ad79-7c1e78c194b7.png)

## Changing the name
![image](https://user-images.githubusercontent.com/41168054/204167823-cabd6333-4319-4490-80ed-88c37beffffb.png)

2022-11-18 23:15 UTC, tinuh commented
not sure how to fix the string literal comment from rubocop because the schema was auto-generated.

2022-11-18 23:22 UTC, exu3 commented
> not sure how to fix the string literal comment from rubocop because the schema was auto-generated.

Run `bundle exec rubocop -A` to autofix Rubocop offenses

2022-11-19 02:24 UTC, garyhtou requested changes
The migration itself looks good! I just left a comment about the other changes

I think we could also put together the other code for this feature as a part of this PR. however, if you would prefer to just merge the migration and leave the other code for another PR, that's fine too

2022-11-19 02:24 UTC, garyhtou commented on db/schema.rb
> +    t.datetime "scheduled_arrival_date"
Sometimes these schema changes show up when we run `db:migrate`. See if you can remove this one and the `raw_pending_partner_donation_transaction_id` change from your PR.

2022-11-27 23:57 UTC, garyhtou commented on app/models/stripe_card.rb
> -  def name
This method was removed and existing references were refactored to allow the `name` field to be accessed directly

2022-11-27 23:57 UTC, garyhtou commented on app/views/events/_event_cards_table.html.erb
> +            <%= d.stripe_name || d.user.full_name if organizer_signed_in? %>
https://github.com/hackclub/bank/pull/3228/files#r1033034311

2022-11-27 23:58 UTC, garyhtou approved these changes
Amazing work!

good to merge

2022-11-28 00:02 UTC, merged