Add legal name 11 21 2022
hackclub/hcb pull request #3237
Opened 2022-11-22 01:22 UTC by InternetRamen

Solves https://hackclub.slack.com/archives/CN523HLKW/p1627483455259900?thread_ts=1627483333.258800&cid=CN523HLKW

This PR:
 - adds `legal_name` to the `users` table
 - adds a hidden input field to user settings
 - adds `class_controller.js`, a controller that toggles classes

**Best reviewed by any interaction with Stripe API and payments**
Payments may not work with legal names. I have not tested.

**Screenshots**
![chrome_GXWqynV5DX](https://user-images.githubusercontent.com/66806100/205792811-cd2a3690-94ac-4d35-be72-626229b63380.gif)
![image](https://user-images.githubusercontent.com/66806100/205792939-94d33818-d2fb-4fcb-b230-1ce7270e35c3.png)

2022-11-22 15:27 UTC, maxwofford commented
Love this! It's been a requested feature by so many people

2022-11-30 23:49 UTC, InternetRamen commented
Need some help resolving the merge conflicts: 
![image](https://user-images.githubusercontent.com/66806100/204932491-5f18e131-bfb3-4a5f-909b-fb3eb57b17b7.png)

Which version should I merge?

2022-12-01 01:36 UTC, InternetRamen commented
Changes to UI 
 - [x] Button that reveals legal name field  
 Mechanics
 - [x] Use legal name only if legal name has a value

2022-12-05 01:29 UTC, InternetRamen commented
I'm unable to figure out how to change StripeCard `stripe_name` field. This field is the one that shows up on the cards page. I'm not sure if stripe_name is even the name legally associated with the card.
![image](https://user-images.githubusercontent.com/66806100/205530022-6e8d71b7-687e-4e85-bcac-636addc814dd.png)

I only changed legal name to "sfv fv" once and then changed it to "" again, yet all of them are "sfv fv"

Will ask Caleb next week :)

2022-12-06 02:25 UTC, InternetRamen commented
Should be good to go 👍

2022-12-06 05:09 UTC, garyhtou commented
just a thought (i haven't looked through the full pr, so maybe I don't have the full context): since the `full_name` field (usually) already contains legal names in the database, would it make sense to add a `display_name` field instead? That `display_name` field would be optional and defaults to `nil`.

2022-12-06 15:33 UTC, InternetRamen commented
That makes a good point but I'm not sure if people set their current name as their legal name or their display name

2022-12-06 18:02 UTC, cjdenio commented
@garyhtou since most places in the UI use the display name, we figured it made sense to consider `full_name` the display name.

also if you don't have a legal name set, it considers `full_name` _both_ your legal and display name

2022-12-13 02:53 UTC, cjdenio requested changes

2022-12-13 02:53 UTC, cjdenio commented on app/models/user.rb
> +                                                      last_name: name[1..name.length].join(" "),
```suggestion
                                                      last_name: name[1..].join(" "),
```

2022-12-13 02:53 UTC, cjdenio commented on app/views/users/edit.html.erb
> +            <%= form.label :full_name, "Display Name" %>
```suggestion
            <%= form.label :full_name, "Display name" %>
```

2022-12-13 02:54 UTC, InternetRamen commented
- [x] Change Display Name to Full Name when Legal Name dropdown is not shown

2022-12-15 02:44 UTC, InternetRamen commented
![chrome_GZtXbveXuQ](https://user-images.githubusercontent.com/66806100/207760206-39980fc8-2900-4813-b986-528858ee209b.gif)

2022-12-18 21:45 UTC, InternetRamen commented
This PR is good to go

2023-03-30 17:15 UTC, cjdenio commented
Closing for now because this is inactive and needs some more work.

2023-03-30 17:15 UTC, closed without merging