Add Flipper flag for disabling Google Workspace
hackclub/hcb pull request #3396
Opened 2023-01-06 13:15 UTC by cjdenio

Only affects orgs that don't have it set up already.

2023-01-06 17:16 UTC, garyhtou commented on app/views/events/_nav.html.erb
> +      disabled: @event.hardware_grant? unless !@event.g_suites.exists? && Flipper.enabled?(:disable_google_workspace, @event) %>
thoughts on making the flag :google_workspace this way we dont need to work with double negatives?

2023-01-06 18:55 UTC, cjdenio commented on app/views/events/_nav.html.erb
> +      disabled: @event.hardware_grant? unless !@event.g_suites.exists? && Flipper.enabled?(:disable_google_workspace, @event) %>
The tricky thing is that Flipper flags are disabled by default, so dev environments would have to opt-in to Google Workspace. It does look weird though

2023-01-12 20:36 UTC, garyhtou requested changes
Let's also remove the reference to Google Workspace here if the flag is flipped

<img width="930" alt="image" src="https://user-images.githubusercontent.com/20099646/212175533-044ee170-01ab-4d63-aae9-477655c6b52b.png">

2023-01-12 20:45 UTC, garyhtou approved these changes
ty!

2023-01-12 20:45 UTC, merged