Require explicit intent to view card details
hackclub/hcb pull request #3409
Opened 2023-01-11 02:27 UTC by InternetRamen

Closes #3385 
this PR
 - Requires button press to view card details such as CVC and billing address

**Best reviewed by code standards?**
I don't know if taking a controller from a pending PR is a good idea.

I would like some help with tracking events with ahoy. What's the best way to do it?

2023-01-11 02:44 UTC, cjdenio reviewed
I think it's better to not even send the card details to the browser until they're requested. One possible option might be:

- Only load the card details if `?show_details=true` is set
- Wrap the card info box in a `<turbo-frame>`
- Make the "Show more details" button link to `/stripe_cards/<id>?show_details=true`
  - (it won't reload the whole page, just the `<turbo-frame>`)
- Track every request with `?show_details=true` on the backend, like
```rb
if params[:show_details]
  ahoy.track "Card details shown", stripe_card_id: @stripe_card.id
end
```

2023-01-11 04:28 UTC, garyhtou reviewed
Thanks for helping review this @cjdenio! 

Sorry. should have given a little more detail in https://github.com/hackclub/bank/issues/3385. I had the same design in mind as Caleb. Let's move this to the turbo frame design.

Also, as for the UI design, I like what Stripe has. It let you see exactly what information will be revealed (and what's currently hidden).
![image](https://user-images.githubusercontent.com/20099646/211717310-3d8a1176-fa10-423a-9d79-7d9969f75989.png)

Only the card number and CVC need to stay hidden. The rest (such as address) can remain visible at all times.

Also, this only needs to apply to virtual cards since we don't have card numbers and CVC for physical cards

2023-01-21 19:19 UTC, YodaLightsabr commented
![image](https://user-images.githubusercontent.com/76178582/213883493-9483a127-a6e6-4409-8bbd-fc8eaffcb596.png)
I'm not able to log in on the heroku deploy

2023-01-26 16:37 UTC, cjdenio requested changes
This is an awesome start! For the UI, I like Stripe's design— specifically, what if there was a clickable 👁️ (`view` or `view-fill`) icon next to the card number?

2023-01-31 19:50 UTC, garyhtou approved these changes
looks good!

just one change

2023-01-31 19:50 UTC, garyhtou commented on app/controllers/stripe_cards_controller.rb
> +    authorize @card
```suggestion
    authorize @card

    if params[:show_details] == "true"
      ahoy.track "Card details shown", stripe_card_id: @card.id
    end

    @show_card_details = params[:show_details] == "true"
```

We'll want to `authorize @card` first.

Switch `stripe_card_id` to use our ID rather than stripe id. we can add stripe's add too if we want.

Also, I made both conditions the same `params[:show_details] == "true"`. This way when track an ahoy event, we can also be sure that `@show_card_details` was `true` and that details were viewed.

2023-01-31 19:50 UTC, garyhtou commented on app/views/stripe_cards/show.html.erb
> +                  <div class="flex justify-between">
not necessary: i wonder if we can use a monospaced font here to prevent layout shift

2023-02-01 19:37 UTC, InternetRamen commented on app/views/stripe_cards/show.html.erb
> +                  <div class="flex justify-between">
Will try

2023-02-02 06:01 UTC, YodaLightsabr commented on app/views/stripe_cards/show.html.erb
> +                  <div class="flex justify-between">
There's a monospaced font that appears on the cards overview page, maybe we could use that

2023-02-05 07:22 UTC, garyhtou commented
> @garyhtou Is this what you're looking for?

My goal is for the last 4 digits to not move on the screen when switching between showing/hiding details. The reason it moves is because the font's character width for `•` vs. numbers such as `1`, `2`, `3`, etc. are different. This can be fixed by changing the font-family to one that is monospaced. Monospaced fonts have the same width for all characters.

<table>
<tr>
	<td>Monospaced font
	<td>Mon-monospaced font
<tr>
	<td><pre>•••• •••• •••• ••••
1234 5678 9012 3456</pre>
	<td>•••• •••• •••• ••••<br/>
1234 5678 9012 3456
</table>

<details>
<summary>Here's a screenshot of what the table above should look like in case github renders it funny</summary>
<img src="https://user-images.githubusercontent.com/20099646/216806770-827356be-81b7-44b6-ae13-5ee224c68d2a.png" />
</details>

however, this is totally unnecessary! so don't let this block this pr. please feel free to merge as is

---

as for the flexbox and justify-between, I'm fine with it either way!

2023-02-07 01:45 UTC, cjdenio approved these changes

2023-02-07 01:46 UTC, merged