Handle force capture transactions (+refunds) from Stripe
hackclub/hcb pull request #3424
Opened 2023-01-13 21:30 UTC by cjdenio

Refunds right now are super wack because they (sometimes) don't belong to a Stripe authorization. This fixes that!

Here's a force capture transaction:
<img width="1438" alt="Screenshot 2023-01-13 at 10 27 44 PM" src="https://user-images.githubusercontent.com/34525547/212422508-639e1bf1-b86f-4cb3-8b81-c6acaefb4fc4.png">

And here's a refund:
<img width="1442" alt="Screenshot 2023-01-13 at 10 28 01 PM" src="https://user-images.githubusercontent.com/34525547/212422550-18402a19-aadd-46dc-9fc0-5da6ec5de7f9.png">

And here's that refund in the ledger!
<img width="1443" alt="Screenshot 2023-01-13 at 10 21 35 PM" src="https://user-images.githubusercontent.com/34525547/212421554-4bed4970-c13f-450f-afe0-81bb0e83b0f2.png">

Resolves #2555

2023-01-14 08:00 UTC, garyhtou requested changes
Glad to see you working on improving this!

Some feedback; the most important being creating a `601` HcbCode type for standalone stripe refunds. This is because 000 should be reserved for transactions that basically have no additional metadata or linked objects.

2023-01-14 08:00 UTC, garyhtou commented on app/models/canonical_transaction.rb
> +    raw_stripe_transaction&.stripe_transaction&.dig("type") == "refund"
I'd move this logic into `RawStripeTransaction` and then call `raw_stripe_transaction&.stripe_transaction&.refund?` here

2023-01-14 08:00 UTC, garyhtou commented on app/models/hcb_code.rb
> +    # note that HCB-600- hcb codes sometimes contain refunds grouped in with the original transaction
In my opinion, standalone stripe refunds should be `601` (or in the `6xx` range ). This is because `000` should be reserved for transactions that basically have no additional metadata or linked objects.

but that's gonna require a decent amount of work. if you're able to make it `601`, that'd be great! but if not, I think this should be okay for now without creating too much tech debt

https://github.com/hackclub/bank/blob/94a91292ec187a16d0f125c55f1e837cdf549144/app/services/transaction_grouping_engine/calculate/hcb_code.rb#L8-L20

2023-01-14 08:00 UTC, garyhtou commented on app/views/canonical_transactions/_canonical_transaction.html.erb
> +        <%= list_badge_for ct.local_hcb_code.receipts.size, "receipt", "payment-docs", optional: !ct.raw_stripe_transaction || ct.local_hcb_code.stripe_refund?, required: ct.raw_stripe_transaction &&
this receipt require/optional logic should all be moved into `HcbCode`, but won't worry about that for this PR

2023-01-14 08:00 UTC, garyhtou commented on app/views/hcb_codes/_rich_metadata.html.erb
> +<% if (@hcb_code.stripe_card? && @hcb_code.stripe_card.present?) || (@hcb_code.unknown? && @hcb_code.ct.raw_stripe_transaction.present?) %>
having a `601` can help us consolidate all this logic into one place and avoid having to handle these edge cases in multiple places

2023-01-14 08:00 UTC, garyhtou commented on app/views/hcb_codes/_stripe_card.html.erb
> +                <%= (@hcb_code.pt&.raw_pending_stripe_transaction&.stripe_transaction || @hcb_code.ct.raw_stripe_transaction.stripe_transaction)["merchant_data"]["name"] %>
Let's move this into `HcbCode#merchant` that returns a hash with `county` and `name`

2023-02-09 02:28 UTC, merged

2023-02-09 03:00 UTC, cjdenio commented
For posterity: ran this to update the HCB code for the affected transactions:

```ruby
CanonicalTransaction
  .joins(canonical_hashed_mappings: { hashed_transaction: [ :raw_stripe_transaction ] })
  .where("raw_stripe_transactions.stripe_authorization_id IS NULL")
  .each(&:write_hcb_code)
```