Donation pages
hackclub/hcb pull request #346
Opened 2019-11-26 19:10 UTC by tmb

2019-11-28 02:10 UTC, tmb commented
will be finishing this up after thanksgiving

2019-12-04 01:06 UTC, lachlanjc commented on app/views/donations/_donation_form.html.erb
> +      <span class="bold muted" style="width: 1rem;">$</span>
This would be an excellent candidate for a helper/CSS class/abstraction of some sort

https://github.com/hackclub/bank/search?l=HTML%2BERB&q=form+amount

2019-12-04 01:10 UTC, thesephist commented on app/views/donations/_donation_form.html.erb
> +      <span class="bold muted" style="width: 1rem;">$</span>
Yep. Probably for a different pr tho

2019-12-06 00:37 UTC, thesephist commented
I'm telling GitHub this closes #81

2019-12-15 06:01 UTC, tmb commented
last step here is testing + doing the front-end thing that invoices have. will be doing within next 2 days

2019-12-17 02:10 UTC, tmb commented
After @thesephist does a frontend pass, this is ready for beta. 

**TODO before merge:**
* Setup webhook on stripe

**TODO before 🚢:**
* Make the fee reimbursement look nice in the list like an invoice
* Setup receipt sending functionality

![image](https://user-images.githubusercontent.com/17188543/71055336-40071780-2123-11ea-89a0-a7b3daea8232.png)

![image](https://user-images.githubusercontent.com/17188543/71055345-43020800-2123-11ea-8c71-8166a2db367f.png)

2019-12-17 03:41 UTC, thesephist commented
@tmb Can you merge master into this branch and resolve conflicts before I take a last pass? to resolve schema conflicts, you'll have to import the db fresh and re-migrate.

2019-12-17 13:09 UTC, thesephist requested changes
Left some comments, mostly questions about failure cases and how things work. Specifically I'm curious about this `stripe_client_secret` and why each Donation needs a separate one -- feel like that should just work like an API key.

I would have merged this, but having an extra unneeded migration in here is a deal breaker. Let's take that out and get to the bottom of the Stripe secret issue, and I'm find with merging other stuff as-is and resolving them on master, or fixing them here if it's quick.

2019-12-17 13:09 UTC, thesephist commented on db/schema.rb
> +    t.text "recipient_phone_number"
This change is (1) unrelated to anything else happening here, and (2) not needed since I fixed this in an earlier PR. Can you remove the migration that causes this?

2019-12-17 13:09 UTC, thesephist commented on app/controllers/donations_controller.rb
> +    @donations = Donation.all
Should this (`index`) and `new` below both `authorize @donation(s)`?

2019-12-17 13:09 UTC, thesephist commented on app/controllers/donations_controller.rb
> +  def edit
This should probably `authorize @donation` and/or throw since you probably shouldn't be able to edit a donation after creation.

2019-12-17 13:09 UTC, thesephist commented on app/controllers/donations_controller.rb
> +    # something something email
Please finish, this seems unfinished. If you can write a bare-bones email I can polish the wording and write actually good copy.

2019-12-17 13:09 UTC, thesephist commented on app/controllers/fee_reimbursements_controller.rb
> +
Can we build this logic into `FeeReimbursement` so that `fee_reimbursement.event` is always the right thing, and fee reimbursements controller doesn't have to know about invoices and/or donations?

2019-12-17 13:09 UTC, thesephist commented on app/jobs/sync_transactions_job.rb
> +    DonationPayout.all.each do |payout|
Can we use the `DonationPayout.lacking_transaction` scope that's a single SQL query and only loop through pending DPs? This (doing `.all`) won't scale well if we keep looping over everything.

2019-12-17 13:09 UTC, thesephist commented on app/models/donation.rb
> +    # raise StandardError, 'Funds not yet available' unless Time.current.to_i > pi.charges.data.first.balance_transaction.available_on
Why is this commented out? It seems like this is the case where it should either (1) never happen, or (2) if it's too early, it should re-queue the job for two days later or something. right?

2019-12-17 13:09 UTC, thesephist commented on app/models/donation.rb
> +    self.fee_reimbursement.save
Is there a reason we're saving this twice, given that we already call `.save` on this reimbursement in line 51?

2019-12-17 13:09 UTC, thesephist commented on app/models/donation_payout.rb
> +  validates_length_of :statement_descriptor, maximum: 22
Do you know why this is 22? That needs to be documented.

2019-12-17 13:09 UTC, thesephist commented on app/models/donation_payout.rb
> +    self.statement_descriptor ||= "DONATION #{SecureRandom.hex(6)}"[0...22] # limit to 22 characters, the stripe limit
Can we make this 22 some global constant like `StripeService::StatementDescriptorCharLimit` or something so we don't have to keep hard-coding this number into random places in the codebase? I don't like seeing magic numbers in old code :/

2019-12-17 13:09 UTC, thesephist commented on app/models/fee_reimbursement.rb
> +      invoice.present? ? amount * self.invoice.event.sponsorship_fee : amount * self.donation.event.sponsorship_fee
Woah, these lines are getting really unwieldy. can we break this ternary down into more if-else's to make these more readable? I would not trust my future self to be able to parse out what any of this code does at a glance. I think it should be easy to just look at this `calculate_fee_amount` and understand exactly what each line of code is doing.

I think a simple refactor here would be to just create a `FeeReimbursement.event` getter (I alluded to this in an earlier comment as well) and use that here to get the sponsorship fee instead of doing this weird ternary thing every single time.

2019-12-17 13:09 UTC, thesephist commented on app/models/transaction.rb
> +  belongs_to :donation_payout, inverse_of: :t_transaction, required: false
This is minor, but let's put this line right next to the `:invoice_payout` line just to keep ourselves more organized.

2019-12-17 13:09 UTC, thesephist commented on app/views/donations/_form.html.erb
> +  <% end %>
I'm being sort of repetitive here these days but let's use our `form_errors` helper here. Replacing this whole block with `<%= form_errors donation %>` should work, I think?

2019-12-17 13:09 UTC, thesephist commented on app/views/donations/_form.html.erb
> +    <%= form.text_field :stripe_client_secret %>
The client secret should never ever _ever_ **ever** leave the server. If there's any way we can avoid putting it in the form, we should absolutely totally do it. Otherwise this is like exposing our Stripe password to the rest of the world. Correct me if I'm wrong?

2019-12-17 13:09 UTC, thesephist commented on app/views/donations/index.html.erb
> +      <th>Stripe client secret</th>
Can you explain to me what the stripe client secret is? Is it not just one secret for all of Hack Club Bank? Why does each donation need a separate `stripe_client_secret`?

2019-12-17 13:09 UTC, thesephist commented on app/views/events/_form.html.erb
> +  <% end %>
Note mostly to self: before we officially push ship on this, we should make a new per-event page where we tell people how Donations works, and give them this link. Putting it in the events form is jank. But this PR can be merged w/o it.

2019-12-17 13:09 UTC, thesephist commented on app/views/transactions/_form.html.erb
> +        </div>
It seems weird to have to go through two drop-down menus to find a matching Payout. Is there a way we can make the Donation payouts immediately distinguishable from TX memo separate from Invoice payouts? Maybe instead of `HACK CLUB EVENT XXX` we use `DONATION EVENT XXX` or something.

2019-12-17 13:09 UTC, thesephist commented on config/routes.rb
> +  post 'webhooks/donations', to: 'donations#accept_donation_hook'
What does Stripe do if this hook is down for some reason?

2019-12-17 13:23 UTC, tmb commented on db/schema.rb
> +    t.text "recipient_phone_number"
think my local copy was out of sync

2019-12-17 13:24 UTC, tmb commented on app/controllers/donations_controller.rb
> +  def edit
this is left over from scaffolding, need to remove

2019-12-17 13:26 UTC, tmb commented on app/models/donation.rb
> +    # raise StandardError, 'Funds not yet available' unless Time.current.to_i > pi.charges.data.first.balance_transaction.available_on
oops- artifact from testing

2019-12-17 13:27 UTC, tmb commented on app/models/donation_payout.rb
> +  validates_length_of :statement_descriptor, maximum: 22
Yup- That’s a Stripe-imposed limit. Will add comment

2019-12-17 13:30 UTC, tmb commented on app/views/donations/index.html.erb
> +      <th>Stripe client secret</th>
`stripe_client_secret` is the unique token for each PaymentIntent that Stripe.js uses to process the payment

2019-12-17 13:50 UTC, thesephist commented on app/models/donation_payout.rb
> +  validates_length_of :statement_descriptor, maximum: 22
Actually this should probably be a constant somewhere in `StripeService` -- see comment below.

2019-12-17 13:51 UTC, thesephist commented on app/views/donations/index.html.erb
> +      <th>Stripe client secret</th>
Ahhhhh ok interesting. So it's meant to be exposed on the client-side but only for like the one donation-maker. That makes sense. If that's the case disregard my other complaints about the secret.

2019-12-18 03:40 UTC, tmb commented on app/controllers/donations_controller.rb
> +    @donations = Donation.all
fixed by removing unused methods

2019-12-18 03:41 UTC, tmb commented on app/controllers/fee_reimbursements_controller.rb
> +
yes but that's for a future PR. @event needs to exist because of the way our views are setup.

2019-12-18 03:45 UTC, tmb commented on app/jobs/sync_transactions_job.rb
> +    DonationPayout.all.each do |payout|
done!

2019-12-18 03:46 UTC, tmb commented on app/models/donation.rb
> +    self.fee_reimbursement.save
yeah, we're adding in that `mailer_queued_job_id` value

2019-12-18 03:50 UTC, tmb commented on app/views/donations/_form.html.erb
> +  <% end %>
sorry autogenerated stuff again :(

2019-12-18 04:13 UTC, tmb commented on config/routes.rb
> +  post 'webhooks/donations', to: 'donations#accept_donation_hook'
nothing. afaik it will just retry—all this affects is payout generation + receipt sending, so if the hook is down, that doesn't matter anyway (because bank is down)

2019-12-18 04:15 UTC, tmb commented on app/views/transactions/_form.html.erb
> +        </div>
Took a screenshot and adding to checklist for 🚢/future

2019-12-18 13:34 UTC, tmb commented
Ready for merge after your pass! @thesephist

2019-12-19 00:45 UTC, thesephist commented on app/controllers/fee_reimbursements_controller.rb
> +
Made https://github.com/hackclub/bank/issues/394 to track this!

2019-12-19 00:46 UTC, thesephist commented on app/views/donations/_form.html.erb
> +    <%= form.text_field :stripe_client_secret %>
I was wrong here. nvm

2019-12-19 01:17 UTC, thesephist approved these changes

2019-12-19 01:17 UTC, merged