Remove Docusign
hackclub/hcb pull request #3885
Opened 2023-05-10 05:21 UTC by maxwofford

2023-05-10 12:03 UTC, northeastprince requested changes

2023-05-10 12:03 UTC, northeastprince commented on db/migrate/20230510050352_remove_partner_docusign_support.rb
> +# frozen_string_literal: true
Don't you do this after the column ignores are deployed?

2023-05-11 00:48 UTC, maxwofford commented on db/migrate/20230510050352_remove_partner_docusign_support.rb
> +# frozen_string_literal: true
Normally yes, but in this case the columns aren't touched by the running app (the few codepaths that could be touched by this are removed in the same deploy). I'm ignoring the columns to ignore the strong_migrations warnings.

2023-05-18 19:07 UTC, albertchae submitted a review, later dismissed

2023-05-18 19:07 UTC, albertchae commented on app/models/partner.rb
> +  self.ignored_columns = ["docusign_envelope_id", "signed_contract"]
I don't think it really matters since you're dropping them in this PR anyway, but aren't the `ignored_columns` in this model flipped with ones in `PartneredSignup`?

2023-05-18 19:07 UTC, albertchae commented on config/credentials.yml.enc
> +ecbgCmXJzYsho6d3nUzpluY9/H7pqW2bZJNaqqY/sHCA+Rmza+ncIJU5MqC8t9CjVhybjjTqWqKBk08k4/IQZTdKYREA5939vvjrA2tm0GIlouyTqQmQD3sTwZH9Pagu5MDW29ndXpBol90B6raGAtZjqAXn8K7QlRFz7pzT/F11bvdaGCojt0K27BA3+xeg59NRHb3
I was surprised this is way shorter but after running `bin/rails credentials:edit` before and after, I can see docusign had some big entries in this file

2023-05-18 19:07 UTC, albertchae commented on db/migrate/20230510050352_remove_partner_docusign_support.rb
> +# frozen_string_literal: true
Normally I'd also warn about going YOLO with db migrations but combining makes sense since these codepaths are mostly dead anyway.

2023-05-18 19:54 UTC, northeastprince commented on db/migrate/20230510050352_remove_partner_docusign_support.rb
> +# frozen_string_literal: true
Can't you just do `safety_assured` and that way you don't have to add the explicit ignore?

2023-05-24 17:59 UTC, maxwofford commented
This is soft blocking on https://github.com/hackclub/bank/pull/3847. I'm more confident this won't affect in-use code once that is merged.

2023-06-23 20:21 UTC, garyhtou commented
@maxwofford is this ready to be merged?

2023-06-26 17:00 UTC, maxwofford commented
I'll rebase this once #3847 is in. I'm 90% confident this doesn't break anything, but that'll go up once partners aren't an active codepath.

2024-05-21 20:00 UTC, garyhtou commented
@sampoder sometime this week, would you mind closing this out and getting it merged?

2024-05-21 20:25 UTC, sampoder commented
Sure thing, let's also look into https://github.com/hackclub/hcb/pull/4412

2024-05-22 02:10 UTC, sampoder approved these changes

2024-05-22 02:12 UTC, merged

2024-05-22 02:20 UTC, garyhtou commented
Amazing @sampoder !!! yeah, let's also close out https://github.com/hackclub/hcb/pull/4412