Allow for preferred names in additional to legal names
hackclub/hcb pull request #4059
Opened 2023-07-06 19:50 UTC by northeastprince

Not quite sure where else we want to explicitly have the legal vs preferred name, so lemme know if there are any other places I should switch it!

2023-07-06 21:53 UTC, garyhtou requested changes
great job! just a couple comments

2023-07-06 21:53 UTC, garyhtou commented on app/views/organizer_position_invites/show.html.erb
> +      <div class="tooltipped tooltipped--s mr1" aria-label="<%= position.user.display__name %>">
Is `display__name` defined?

2023-07-06 21:53 UTC, garyhtou commented on db/schema.rb
> -    t.bigint "raw_pending_partner_donation_transaction_id"
can we remove these unrelated changes?

2023-07-06 21:53 UTC, garyhtou commented on app/models/user.rb
what are your thoughts on adding a validation to limit the length of the preferred name? it may help with preventing broken UI

2023-07-07 01:23 UTC, northeastprince commented on app/models/user.rb
Sure! Not sure what's reasonable - 30 characters? 40?

2023-07-07 01:25 UTC, northeastprince commented on db/schema.rb
> -    t.bigint "raw_pending_partner_donation_transaction_id"
Yeah, Rails reorganized that for some reason,

2023-07-07 01:28 UTC, northeastprince commented on app/views/organizer_position_invites/show.html.erb
> +      <div class="tooltipped tooltipped--s mr1" aria-label="<%= position.user.display__name %>">
Ah, my bad 😆 - thought about naming the column `display_name` but it sounded too username-y.

2023-07-07 18:13 UTC, garyhtou commented on app/views/organizer_position_invites_mailer/notify.html.erb
> +  You've been invited by <strong><%= @invite.sender.display_name %></strong> to manage <strong><%= @invite.event.name %></strong>,
```suggestion
  You've been invited by <strong><%= @invite.sender.name %></strong> to manage <strong><%= @invite.event.name %></strong>,
```

2023-07-07 18:13 UTC, garyhtou commented on app/helpers/users_helper.rb
> +             "#{user.name} is an admin"
``` suggestion
             "#{user.first_name} is an admin"
```
It would be nice to keep the existing functionality of just showing the first name. We can use the existing `first_name` method

2023-07-07 18:13 UTC, garyhtou commented on app/views/users/edit.html.erb
> +        <%= form.text_field :preferred_name, placeholder: "FiFi Hacks" %>
Let's set the placeholder to be their `full_name` (if it's `nil`, then fallback to a default name like "FiFi Hacks").

This way it shows that if a preferred name is not given, it shows your `full_name`

2023-07-07 18:15 UTC, garyhtou commented on app/models/user.rb
for posterity: as we talked about in our sync, 30 or 40 sounds good. I'll leave this decision up to you

2023-07-07 18:32 UTC, northeastprince commented on app/helpers/users_helper.rb
> +             "#{user.name} is an admin"
That's used for the `aria-label`, which is utilized instead of the content of an element if present. We already display the full name to the user, so I think we should make it accessible as well. If there's some other case I'm not getting where guessing the first name is better, I can change it.

2023-07-07 18:35 UTC, garyhtou commented on app/helpers/users_helper.rb
> +             "#{user.name} is an admin"
`aria-label` is used to set the contents of the tooltip

**before (first name)**
![image](https://github.com/hackclub/bank/assets/20099646/c31ddd9d-013d-4ad1-acaf-427d130597d8)

**after (full preferred name)**
![image](https://github.com/hackclub/bank/assets/20099646/e0480f48-c41f-4dd9-a1f0-03ecc429e802)

in the context of the tooltip, it would be nice to keep it short and just use the first name

2023-07-07 18:44 UTC, northeastprince commented on app/helpers/users_helper.rb
> +             "#{user.name} is an admin"
Oh, huh. I thought it was only supposed to be used for screenreaders - that seems like more of a `title` attribute thing. Will it still say "Melanie Smith"?

2023-07-07 18:55 UTC, northeastprince commented on app/helpers/users_helper.rb
> +             "#{user.name} is an admin"
Yeah, [that's what I'm finding](https://stackoverflow.com/a/63726152), so we probably wanna change that instead so we're not misusing an ARIA attribute. It might also make more sense to have some sort of badge next to an employee's name (cause if I have to hover over the name to find out if they're a Bank employee, it's not obvious and would probably be by accident), but I can propose that in a separate PR.

2023-07-07 19:00 UTC, garyhtou commented on app/helpers/users_helper.rb
> +             "#{user.name} is an admin"
yeah, i think we are misusing the aria attribute.

As for the admin badge, there is currently a lightning bolt badge next to an admin's name (see image)

![image](https://github.com/hackclub/bank/assets/20099646/8a964259-5aee-4e12-9652-4f3fd7d1d6e6)

2023-07-07 19:06 UTC, northeastprince commented on app/helpers/users_helper.rb
> +             "#{user.name} is an admin"
Ah, didn't get the meaning of that. Also, since we're abbreviating their name, it might actually make more sense to have the full name as a tooltip if we wanna keep that. Aside from a clearer admin badge in a future PR, is there anything I should change with this for now?

2023-07-07 19:07 UTC, northeastprince commented on app/helpers/users_helper.rb
> +             "#{user.name} is an admin"
I could also change it to:

> Melania Smith (admin)

2023-07-07 19:15 UTC, garyhtou commented on app/helpers/users_helper.rb
> +             "#{user.name} is an admin"
For this PR, let's either keep the current code as is:
```ruby
"#{user.name} is an admin"
```

or, use their first name (which is the existing functionality before this PR)
```ruby
"#{user.first_name} is an admin"
```

---

we can discuss how to make admin status and tooltips more clear in a different PR

2023-07-07 22:26 UTC, garyhtou approved these changes
Great work! good to merge 🥳

2023-07-07 23:31 UTC, merged