Add the ability to hide events
hackclub/hcb pull request #407
Opened 2019-12-23 02:42 UTC by tmb

![image](https://user-images.githubusercontent.com/17188543/71332380-f98b3180-2503-11ea-8cf3-948a7dd594d4.png)

![image](https://user-images.githubusercontent.com/17188543/71332382-fbed8b80-2503-11ea-827f-6edf2d2456fc.png)

2019-12-23 04:00 UTC, thesephist requested changes
yeetsicles

2019-12-23 04:00 UTC, thesephist commented on app/controllers/events_controller.rb
> +    fixed_event_params[:hidden_at] = nil if fixed_event_params.key?(:hidden) && fixed_event_params[:hidden] == "0" && @event.hidden_at.present?
Why do we set it twice? Can't we just determine a value once and set it?

also, this boolean expression is really hard to read. Can we split it into if-else's that makes it possible to tell what's going on at a glance?

2019-12-23 04:00 UTC, thesephist commented on app/controllers/events_controller.rb
> +    fixed_event_params[:hidden_at] = nil if fixed_event_params.key?(:hidden) && fixed_event_params[:hidden] == "0" && @event.hidden_at.present?
Since this seems to be getting repeated, can we maybe move it out into a separate method? Same with `club_airtable_id` and `partner_logo_url` above :/

2019-12-23 04:00 UTC, thesephist commented on app/controllers/events_controller.rb
> +    fixed_user_event_params[:hidden_at] = nil if fixed_user_event_params.key?(:hidden) && fixed_user_event_params[:hidden] == "0" && @event.hidden_at.present?
Can you help me understand why there is a hidden for admins but also a hidden for users? Isn't it just one?

2019-12-23 04:00 UTC, thesephist commented on app/controllers/events_controller.rb
> +    byebug
is this supposed to be left in here?

2019-12-23 04:00 UTC, thesephist commented on app/models/event.rb
> +  default_scope { order(id: :asc)}
pls fix formatting

2019-12-23 04:00 UTC, thesephist commented on app/models/event.rb
> +  scope :not_hidden, -> { where(hidden_at: nil)}
pls fix formatting

2019-12-23 04:00 UTC, thesephist commented on app/views/events/_form.html.erb
> +  </div>
Can we make this only visible when the user has more than one event under their account? Otherwise it would get super confusing.
Also, what do you think about "Hide this project from Bank home page" instead? (and no question, since none of our other prompts are phrased as questions)

2019-12-23 15:31 UTC, tmb commented on app/controllers/events_controller.rb
> +    fixed_event_params[:hidden_at] = nil if fixed_event_params.key?(:hidden) && fixed_event_params[:hidden] == "0" && @event.hidden_at.present?
the two lines are for the box being checked/unchecked. will split into if/else

2019-12-23 15:32 UTC, tmb commented on app/controllers/events_controller.rb
> +    fixed_user_event_params[:hidden_at] = nil if fixed_user_event_params.key?(:hidden) && fixed_user_event_params[:hidden] == "0" && @event.hidden_at.present?
we submit a different set of acceptable params (see bottom of file) depending on whether it is a user or admin logged in

2019-12-23 15:32 UTC, tmb commented on app/controllers/events_controller.rb
> +    byebug
no lol will fix

2019-12-23 15:33 UTC, tmb commented on app/views/events/_form.html.erb
> +  </div>
can do. that wording makes more sense.. will change it

2019-12-24 17:31 UTC, tmb commented on app/controllers/events_controller.rb
> +    fixed_event_params[:hidden_at] = nil if fixed_event_params.key?(:hidden) && fixed_event_params[:hidden] == "0" && @event.hidden_at.present?
I don't think this makes sense to methodize because it's only being used twice (once in `create`, once in `update`)

2019-12-24 23:58 UTC, thesephist commented on app/controllers/events_controller.rb
> +    fixed_event_params[:hidden_at] = nil if fixed_event_params.key?(:hidden) && fixed_event_params[:hidden] == "0" && @event.hidden_at.present?
Sounds good, I'm not too worried here.

2020-01-01 08:42 UTC, merged