Make FeeReimbursement.event & refractor
hackclub/hcb pull request #410
Opened 2019-12-24 21:32 UTC by tmb

2019-12-25 00:02 UTC, thesephist requested changes
Almost there ♨️

2019-12-25 00:02 UTC, thesephist commented on app/models/fee_reimbursement.rb
> +      invoice.event
Tiny nit, but can we be consistent here and stick to either using `return` keyword or implicit return for both cases?

2019-12-25 00:02 UTC, thesephist commented on app/views/fee_reimbursements/index.html.erb
> +          <td><%= link_to "#{reimbursement.event.name}", reimbursement.event, class: 'underline' %></td>
Can we pull this line out of the if-else case now that it's the same across both cases?

2019-12-26 00:26 UTC, tmb commented on app/models/fee_reimbursement.rb
> +      invoice.event
yes

2019-12-26 00:26 UTC, tmb commented on app/views/fee_reimbursements/index.html.erb
> +          <td><%= link_to "#{reimbursement.event.name}", reimbursement.event, class: 'underline' %></td>
yes

2019-12-26 00:29 UTC, thesephist approved these changes
✌️

2019-12-29 04:57 UTC, merged