Blazer Checks: Run Cron Job
hackclub/hcb pull request #4179
Opened 2023-08-23 03:42 UTC by sampoder

Closes #3894, this is how https://github.com/hostolab/covidliste roughly did it.

2023-09-08 16:14 UTC, maxwofford approved these changes
This looks great! I'm fine with this going in but want to confirm it's good on your side @garyhtou

2023-09-08 16:16 UTC, cjdenio requested changes

2023-09-08 16:16 UTC, cjdenio commented on config/schedule.yml
> +  args: { shedule: "1 day" }
```suggestion
  cron: "0 8 * * *"
  class: "RunBlazerChecksJob"
  args: { schedule: "1 day" }
```

2023-09-18 17:01 UTC, cjdenio commented on config/schedule.yml
> +  class: "RunBlazerChecksJob"
```suggestion
  class: "BlazerChecksJob"
```

2023-09-18 17:03 UTC, cjdenio approved these changes

2023-09-18 17:05 UTC, merged

2023-09-18 17:56 UTC, sampoder commented
wahoo!

From Sam


On Mon, Sep 18, 2023 at 10:05 AM Caleb Denio ***@***.***>
wrote:

> Merged #4179 <https://github.com/hackclub/hcb/pull/4179> into main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/hcb/pull/4179#event-10400791087>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJP3VRCICROG4TAFDDWQCXTX3B5OBANCNFSM6AAAAAA322FS7M>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>