Add Multi-Selecting Transactions for Tags
hackclub/hcb pull request #4192
Opened 2023-08-26 21:12 UTC by sampoder

Alrighty! Here's how this works:

1. Command-click / Ctrl-click the transactions they want to select
2. This button will appear: <img width="305" alt="Screenshot 2023-08-26 at 2 11 30 PM" src="https://github.com/hackclub/bank/assets/39828164/f424fd18-3c39-4cc8-acd6-ec8864e80388">
3. From there it works like tags usually do: 
<img width="360" alt="Screenshot 2023-08-26 at 2 12 18 PM" src="https://github.com/hackclub/bank/assets/39828164/659d62d2-b829-444c-a253-103a896ad6a1">

Fixes #4174... I think?

2023-08-26 21:16 UTC, northeastprince commented on app/assets/stylesheets/components/_transactions.scss
> +.transaction__icon__when__selected {
```suggestion
.transaction__icon__when-selected {
```

2023-08-26 21:52 UTC, northeastprince commented on app/assets/stylesheets/components/_transactions.scss
> +.transaction__icon__when-selected {
Actually, if we're using BEM, probably makes more sense to do something like this:

```suggestion
.transaction__icon--when-selected {
```
or
```suggestion
.transaction__icon--selected {
```
sorry @sampoder 😆

2023-08-26 22:46 UTC, sampoder commented on app/assets/stylesheets/components/_transactions.scss
> +.transaction__icon__when-selected {
All good!

2023-08-26 22:54 UTC, northeastprince commented on app/assets/stylesheets/components/_transactions.scss
> +}
```suggestion
}

```

2023-08-26 22:54 UTC, northeastprince commented on app/assets/stylesheets/components/_transactions.scss
> +}
Not sure why the newline isn't being enforced by linters, but whatevs...

2023-08-26 22:54 UTC, northeastprince commented on app/controllers/tags_controller.rb
> +      hcb_code = HcbCode.find(hcb_code_id)
Rails has built in support for a param as an array, so it's probably more straightforward if we just use that. [See how we use it for allowing people to manage locations they've subscribed to for new hackathons!](https://github.com/hackclub/hackathons-backend/blob/af17b783e21009f6b8e87b0ab739bbe2f3e6d2d0/app/controllers/hackathons/subscriptions/bulk_controller.rb)

2023-08-26 22:57 UTC, sampoder commented on app/javascript/controllers/transactions_controller.js
> +			formField.value = this.selectedHCBCodes.join(",");
```suggestion
			formField.value = this.selectedHCBCodes;
```

@northeastprince, does that mean I can just do this  ^ and drop the .split(",") stuff in the controller

2023-08-26 23:06 UTC, northeastprince commented on app/javascript/controllers/transactions_controller.js
> +			formField.value = this.selectedHCBCodes.join(",");
Not sure how it'd work in JS, but you just take `hcb_code_ids` as a parameter and if you're using Rails URL helpers it should work automatically (just make it so that you don't use a singular param, even if it's just one transaction) - I believe the format in URLs would be `hcb_code_ids[]=1,2,3` and you can do it seperately too and it'll just append (`?hcb_code_ids[]=1&hcb_code_ids[]=2`. Then, for the query, you do `HcbCode.where(id: hcb_code_ids)`. Lemme know if that doesn't work!

2023-08-27 00:22 UTC, sampoder commented on app/javascript/controllers/transactions_controller.js
> +			formField.value = this.selectedHCBCodes.join(",");
hcb_code_ids[] doesn't seem to trigger the conversion when it's passed through in a POST request

2024-01-18 22:27 UTC, garyhtou requested changes

2024-01-18 22:27 UTC, garyhtou commented on app/views/events/show.html.erb
> +                <%= form.hidden_field :hcb_code_ids, "data-transactions-target": "formField" %>
```suggestion
                <%= form.hidden_field :hcb_code_ids[], "data-transactions-target": "formField" %>
```

2024-01-18 22:27 UTC, garyhtou commented on app/controllers/tags_controller.rb
> +                   end
```suggestion
    hcb_code_ids = params[:hcb_code_id] || params[:hcb_code_ids]&.split(",") || []
```

2024-01-18 22:27 UTC, garyhtou commented on app/controllers/tags_controller.rb
> +      hcb_code = HcbCode.find(hcb_code_id)
```suggestion
    HcbCode.where(id: hcb_code_id).find_each do |hcb_code|
```

2024-01-18 22:27 UTC, garyhtou commented on app/javascript/controllers/transactions_controller.js
Use spaces instead of tabs

2024-01-18 22:27 UTC, garyhtou commented on app/javascript/controllers/transactions_controller.js
> +				if(this.selectedHCBCodes.length > 0){
condition not needed

2024-01-18 22:27 UTC, garyhtou commented on app/javascript/controllers/transactions_controller.js
> +				clickedElement.classList.add("selected__transaction")
move this into a `selectHcbCode`

2024-01-18 22:27 UTC, garyhtou commented on app/javascript/controllers/transactions_controller.js
> +				clickedElement.classList.remove("selected__transaction")
move this into a `unselectHcbCode`

2024-01-18 22:27 UTC, garyhtou commented on app/javascript/controllers/transactions_controller.js
> +			this.updateFormFieldValue()
Add a `updateTaggerVisbility` method for:

```javascript
				if(this.selectedHCBCodes.length == 0){
					this.taggerTarget.classList.add("display-none")
				} else {
					this.taggerTarget.classList.remove("display-none")
        }
```

```suggestion
      this.updateTaggerVisbility()
			this.updateFormFieldValue()
```

2024-01-18 22:27 UTC, garyhtou commented on app/javascript/controllers/transactions_controller.js
> +	trackClick(event) {
rename this to `multiselect`

2024-01-18 22:27 UTC, garyhtou commented on app/views/canonical_transactions/_canonical_transaction.html.erb
> +    </td>
Do we need this for pending transactions?

2024-01-18 22:44 UTC, sampoder commented on app/views/canonical_transactions/_canonical_transaction.html.erb
> +    </td>
I think we have it in there

2024-05-08 23:18 UTC, closed without merging