Add Filtering By User & Transaction Type
hackclub/hcb pull request #4198
Opened 2023-08-28 05:33 UTC by sampoder

Would fix #3105:

<img width="330" alt="Screenshot 2023-08-27 at 10 33 27 PM" src="https://github.com/hackclub/bank/assets/39828164/e1df6f41-bedf-48f2-91e5-ed6f8a4ac799">
<img width="316" alt="Screenshot 2023-08-27 at 10 33 23 PM" src="https://github.com/hackclub/bank/assets/39828164/3f84e240-6709-4941-aba5-68cd048630cb">
<img width="330" alt="Screenshot 2023-08-27 at 10 33 20 PM" src="https://github.com/hackclub/bank/assets/39828164/0ae63506-424f-44e3-971e-0886f81136de">

2023-11-02 20:08 UTC, garyhtou requested changes

2023-11-02 20:08 UTC, garyhtou commented on app/assets/stylesheets/components/_menus.scss
> +}
```suggestion
}

```

2023-11-02 20:08 UTC, garyhtou commented on app/controllers/events_controller.rb
> +    end
```suggestion
    @user = User.find(params[:user]) if params[:user]
```

Maybe use `find_by_id` so that it doesn't 500 when the user id is invalid

2023-11-02 20:08 UTC, garyhtou commented on app/controllers/events_controller.rb
> +    end
```suggestion
    @type = params[:type] if params[:type]
```

2023-11-02 20:08 UTC, garyhtou commented on app/controllers/events_controller.rb
> +      @all_transactions = @all_transactions.select { |x| x.stripe_cardholder && x.stripe_cardholder.user.id == @user.id }
```suggestion
      @all_transactions = @all_transactions.select { |t| t.stripe_cardholder&.user == @user }
```

2023-11-02 20:08 UTC, garyhtou commented on app/controllers/events_controller.rb
> +    if @type
_not working code_
```suggestion
    if @type
      type_filters = {
        "ach_transfer" => {
          "settled" => ->(t) { t.local_hcb_code.ach_transfer? },
          "pending" => ->(t) { t.raw_pending_outgoing_ach_transaction_id }
        },
        #...
      }
      
      filter = type_filters[@type]
      if filter
        @all_transactions = @all_transactions.select filter["settled"]
        @pending_transactions = @pending_transactions.select filter["pending"]
      end
```

2023-11-02 20:08 UTC, garyhtou commented on app/services/transaction_grouping_engine/transaction/all.rb
> +      def initialize(event_id:, search: nil, tag_id: nil, user_id: nil)
is this being used?

```suggestion
      def initialize(event_id:, search: nil, tag_id: nil)
```

2023-11-02 20:08 UTC, garyhtou commented on app/views/events/show.html.erb
> +          data-menu-target="toggle" data-action="menu#toggle keydown@document->menu#keydown">
can we move the filter code into its own partial?

2023-11-02 20:08 UTC, garyhtou commented on app/views/events/show.html.erb
> +          <% elsif @user %>
Let's allow this to show even if transaction tags are not enabled

2023-11-02 21:37 UTC, sampoder commented on app/controllers/events_controller.rb
> +    if @type
added!

2023-11-08 21:51 UTC, garyhtou commented
(i'm updating this branch to debug heroku staging issues)

2023-11-09 19:40 UTC, garyhtou approved these changes

2023-11-09 19:40 UTC, garyhtou commented on app/controllers/events_controller.rb
> +    @type = params[:type] if params[:type]
```suggestion
    @type = params[:type]
```

2023-11-09 19:48 UTC, merged

2023-11-09 20:05 UTC, cjdenio commented on app/views/events/_filter.html.erb
> +      data-menu-target="toggle" data-action="menu#toggle keydown@document->menu#keydown">
`click@document->menu#close` is needed here so clicking outside the menu closes it

2023-11-09 20:07 UTC, cjdenio commented on app/controllers/events_controller.rb
> +      },
ACH payments are deprecated (there are only 2 total in production)