Add Countries To The Address In An Invoice
hackclub/hcb pull request #4201
Opened 2023-08-28 20:48 UTC by sampoder

I can't work out where we use this address but this should let you send invoices internationally!

2023-09-08 16:15 UTC, maxwofford commented
Has this been tested? What entries does Stripe support for this?

2023-09-08 21:45 UTC, sampoder commented
That's a good question... I tried to find where we pass this to Stripe but I don't think we even do...

2023-09-08 21:46 UTC, sampoder commented
(that said, I may be going insane)

2023-09-18 17:51 UTC, cjdenio commented
@sampoder it's passed to Stripe here:
https://github.com/hackclub/hcb/blob/b56bd0f1f0933eb0c98b0ae99f61da4cb139a68a/app/models/sponsor.rb#L130-L136

2023-09-18 17:55 UTC, sampoder commented
Oh perfect! Thank you Caleb!!

2023-09-25 04:42 UTC, cjdenio requested changes

2023-09-25 04:42 UTC, cjdenio commented on db/migrate/20230828203220_add_country_to_sponsor.rb
> +    add_column :sponsors, :address_country, :text, default: "United States of America"
```suggestion
    add_column :sponsors, :address_country, :text, default: "US"
```

2023-09-25 04:42 UTC, cjdenio commented on app/views/invoices/_form.html.erb
> +        <%= form.collection_select :address_country, Event.countries.map{ |c| [c.first, get_country_name_from_alpha2(c.first)] }, :first, :last, { include_blank: "Select a country", required: true, d
```suggestion
        <%= form.country_select :address_country, ["US"], priority_countries_divider: "", include_blank: "Select a country", required: true, disabled: @event.demo_mode? %>
```

2023-09-25 04:42 UTC, cjdenio commented on app/views/sponsors/_form.html.erb
> +
```suggestion
```

This form is deprecated and isn't shown in the UI

2023-09-25 04:42 UTC, cjdenio commented on db/migrate/20230828203220_add_country_to_sponsor.rb
> +    add_column :sponsors, :address_country, :text, default: "United States of America"
```suggestion
    add_column :sponsors, :address_country, :text, default: "US"
```

2023-09-25 04:42 UTC, cjdenio commented on spec/services/invoice_service/create_spec.rb
> +  let(:sponsor_address_country) { "United States of America" }
```suggestion
  let(:sponsor_address_country) { "US" }
```

2023-09-25 04:45 UTC, sampoder commented on app/views/sponsors/_form.html.erb
> +
coolio!

2023-09-25 04:47 UTC, sampoder commented
@cjdenio: I think Stripe wants us to pass them the two digit codes for countries. At least based on https://stripe.com/docs/api/customers/object#customer_object-shipping-address-country

2023-09-25 04:49 UTC, cjdenio commented
That's correct, I think this code already does that?

2023-09-25 04:50 UTC, sampoder commented
oh i really need to sleep, good catch!

2023-09-25 04:51 UTC, cjdenio commented
lol all good!

2023-09-25 04:51 UTC, sampoder commented
alrighty, merged in everything!

2023-09-25 04:55 UTC, cjdenio approved these changes
thanks!

2023-09-25 04:58 UTC, merged