Pretty donations in transaction view
hackclub/hcb pull request #421
Opened 2020-01-01 22:25 UTC by tmb

2020-01-01 22:34 UTC, tmb commented
Second commit is because `calculate_fee_amount` wasn't being run when fee reimbursements were manually matched, leading to some really weird math being done while trying to calculate the fee.

2020-01-01 23:27 UTC, thesephist requested changes
need a lil fix 📈

2020-01-01 23:27 UTC, thesephist commented on app/views/donations/_donation.html.erb
> +<% transaction = donation.payout.t_transaction %>
The indentation on this template is kind of fucked can we fix it

2020-01-01 23:27 UTC, thesephist commented on app/controllers/transactions_controller.rb
> +      end
It seems weird that this was missing before but it worked for invoices -- if it's being handled here now for all transactions, should we remove the code that was only handling it for invoices before, so we only have one place in the code that concerns this?

2020-01-02 23:21 UTC, tmb commented on app/controllers/transactions_controller.rb
> +      end
Invoices don't have the weird under $1 fee stuff—that's what thsi fixes

2020-01-03 00:03 UTC, merged