Restrict Login Codes To Their Origin Browser
hackclub/hcb pull request #4220
Opened 2023-09-02 09:40 UTC by sampoder

This will fix #3438. How it does it is that it generates a unique token when some signs in (this is the "browser token"), then it stores that token locally as a cookie in the browser as well as in the DB, then, when someone inputs a code it checks that the two match.

2023-09-02 14:41 UTC, northeastprince commented on app/models/login_code.rb
> +  blind_index :browser_token
Why does this need to be encrypted if it's already random?

2023-09-02 14:41 UTC, northeastprince commented on app/controllers/users_controller.rb
> +    cookies.encrypted[:browser_token] = { value: @browser_token, expires: Time.current + 15.minutes }
Can this just be `signed`?

2023-09-02 14:42 UTC, northeastprince commented
Before we implement this, I'm wondering if we should consider implementing and switching to login links instead. I think it's more secure anyway and easier to use.

2023-09-02 17:48 UTC, sampoder commented on app/models/login_code.rb
> +  blind_index :browser_token
Good point, I was just copying the session_token logic

2023-09-02 17:49 UTC, sampoder commented on app/controllers/users_controller.rb
> +    cookies.encrypted[:browser_token] = { value: @browser_token, expires: Time.current + 15.minutes }
Wdym?

2023-09-02 19:14 UTC, northeastprince commented on app/controllers/users_controller.rb
> +    cookies.encrypted[:browser_token] = { value: @browser_token, expires: Time.current + 15.minutes }
A signed cookie instead of an encrypted one.

2023-09-02 20:27 UTC, sampoder commented on app/controllers/users_controller.rb
> +    cookies.encrypted[:browser_token] = { value: @browser_token, expires: Time.current + 15.minutes }
we can do that!

2023-09-02 20:29 UTC, sampoder commented on app/controllers/users_controller.rb
> +    cookies.encrypted[:browser_token] = { value: @browser_token, expires: Time.current + 15.minutes }
```suggestion
    cookies.signed[:browser_token] = { value: @browser_token, expires: Time.current + 15.minutes }
```

2023-09-02 20:29 UTC, sampoder commented on app/controllers/users_controller.rb
> +      browser_token: cookies.encrypted[:browser_token]
```suggestion
      browser_token: cookies.signed[:browser_token]
```

2023-10-29 05:16 UTC, YodaLightsabr commented
@sampoder: what's the status of this PR? what do we have to do to move forward with it? It'd be great to get this out as one of our small wins in the next 5 weeks.

2023-10-29 05:23 UTC, sampoder commented
Other than the conflicts, this PR is good to review from my end

2023-10-29 12:58 UTC, sampoder commented
I now seem to be getting that error for all of those case, @YodaLightsabr if you're still not getting that error, what does your setup look like?

2023-11-02 20:07 UTC, garyhtou requested changes

2023-11-02 20:07 UTC, garyhtou commented on app/models/login_code.rb
> +  has_encrypted :browser_token
maybe we can use https://api.rubyonrails.org/classes/ActiveRecord/SecureToken/ClassMethods.html

or, moving the token generation logic into the model using a `before_validation`

2023-11-03 03:03 UTC, sampoder commented
check out #4405 which does this using the fancy rails method!

2023-11-03 03:03 UTC, closed without merging