Redesign Admin Dashboard
hackclub/hcb pull request #4234
Opened 2023-09-08 05:13 UTC by sampoder

My main goal here was to clean up clutter and make it easier to read things. The main thing is the addition of a nav bar:

<img width="1406" alt="Screenshot 2024-05-02 at 8 34 36 PM" src="https://github.com/hackclub/hcb/assets/39828164/5e6633d3-9123-4738-850c-f7bb9cecb42b">

The other updates were made to individual pages:

- Having the "displaying X" and pagination on one row using Flexbox
- Restructuring the forms like in #4160 
- Moving the title to the nav bar

2023-09-08 16:05 UTC, maxwofford commented
Ooooooh! This looks pretty! @hackclub/hcb-ops, based on the screenshot above are you cool with this change?

2023-09-08 16:23 UTC, maxwofford commented on app/controllers/admin_controller.rb
> +      "transaction_csvs"      => "Transaction CSVs",
This feels a little weird to do. Maybe something like a helper (ie. `<%= title "ACH" %>`) on each page that lets them self-identify?

2023-09-08 16:33 UTC, daisybanks commented
Hey @sampoder! This new nav bar looks great! Super easy to read and look for things!

2023-09-08 18:20 UTC, sampoder commented
yay!

On Fri, 8 Sep 2023 at 9:33 AM, Daisy ***@***.***> wrote:

> Hey @sampoder <https://github.com/sampoder>! This new nav bar looks
> great! Super easy to read and look for things!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/hcb/pull/4234#issuecomment-1711940644>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJP3VREWAF4PBZB47JUOBOLXZNCF7ANCNFSM6AAAAAA4P22B2A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-08 21:29 UTC, devramsean0 commented
Looks Great!

2023-09-08 22:50 UTC, sampoder commented on app/controllers/admin_controller.rb
> +      "transaction_csvs"      => "Transaction CSVs",
yeah this is jank. i think i misunderstood how the old system worked but i think i can actually get what i want using that so i'm gonna go back to that

2023-09-08 22:50 UTC, sampoder commented on app/views/admin/ach.html.erb
>  <% title "ACH" %>
```suggestion
<% title "ACHs" %>
```

2023-09-08 22:51 UTC, sampoder commented on app/views/admin/balances.html.erb
>  <%= form_with local: true, action: :balances, method: :get do |form| %>
```suggestion
<% title "Organization Balances" %>

<%= form_with local: true, action: :balances, method: :get do |form| %>
```

2023-09-08 22:51 UTC, sampoder commented on app/views/admin/bank_accounts.html.erb
> +<p class="mb2">
```suggestion
<% title "Bank Accounts" %>

<p class="mb2">
```

2023-09-08 22:53 UTC, sampoder commented on app/views/admin/bank_fees.html.erb
>  <%= form_with local: true, url: bank_fees_admin_index_path, method: :get do |form| %>
```suggestion
<% title "Bank Fees" %>

<%= form_with local: true, url: bank_fees_admin_index_path, method: :get do |form| %>
```

2023-09-08 23:25 UTC, sampoder commented on app/views/layouts/admin.html.erb
> +      <%= "#{@title} –" if !@title.nil? %>
```suggestion
      <%= yield(:title).concat(" –") if content_for?(:title) %>
```

2023-09-08 23:25 UTC, sampoder commented on app/views/layouts/admin.html.erb
> +          <%= @title if !@title.nil? %>
```suggestion
          <%= yield(:title) if content_for?(:title) %>
```

2023-09-08 23:25 UTC, sampoder commented on app/views/layouts/admin.html.erb
> +            <%= current_user.access_level %><%= ":" if !@title.nil? %>
```suggestion
            <%= current_user.access_level %><%= ":" if content_for?(:title) %>
```

2023-09-08 23:36 UTC, sampoder commented on app/controllers/admin_controller.rb
> +      "transaction_csvs"      => "Transaction CSVs",
i seem to have made a pig sty out of the git commit history, but jank no more

2023-09-21 11:20 UTC, malted commented
fancy!

2023-11-30 06:34 UTC, sampoder commented
@maxwofford @hackclub/hcb-ops would this be something worthwhile for you all? i could resolve the merge conflicts pretty easily and we could get this over the line

2023-11-30 14:35 UTC, hackliv commented
AMAZING. Is PayPal listed on there too?

2023-12-01 19:10 UTC, maxwofford commented
@sampoder there's your answer! yeah, please do when you have the time.

2023-12-02 21:12 UTC, sampoder commented
@hackliv yes it is! Under `Transfers`.

2023-12-02 21:15 UTC, sampoder commented
@maxwofford awesome! well that's been done :D

2024-01-10 01:09 UTC, sarthaktexas commented
I don't like this

2024-01-10 01:09 UTC, sarthaktexas commented
I will send you a figma tomorrow

2024-01-10 01:14 UTC, sampoder commented
lol Sarthak, any specifics?


On Tue, 9 Jan 2024 at 19:09, sarthak mohanty ☻ ***@***.***>
wrote:

> I will send you a figma tomorrow
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/hcb/pull/4234#issuecomment-1884034804>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJP3VRBC5E4BRWF7JBUVIGLYNXS6BAVCNFSM6AAAAAA4P22B2CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOBUGAZTIOBQGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-01-10 19:44 UTC, sampoder commented
@sarthaktexas Figma 👀

2024-05-03 03:33 UTC, YodaLightsabr requested changes

2024-05-03 03:33 UTC, YodaLightsabr commented on app/assets/stylesheets/admin.scss
> +  }
```suggestion
  summary:hover + detail, detail:hover, details:hover > .dropdown {
    display: block;
  }

  detail, .dropdown {
    display: none;
  }
```

2024-05-03 03:33 UTC, YodaLightsabr commented on app/assets/stylesheets/admin.scss
> +}
```suggestion
```

2024-05-03 03:33 UTC, YodaLightsabr commented on app/assets/stylesheets/admin.scss
> +}
```suggestion
.events-filter-select > label > select, .events-filter-select > label > input {
  flex-grow: 1
}
```

2024-05-03 03:35 UTC, YodaLightsabr approved these changes

2024-05-03 03:38 UTC, merged

2024-05-03 05:48 UTC, garyhtou commented
Did @hackliv or some one from operations get a chance to review this before merge?

2024-05-03 05:52 UTC, sampoder commented
We got feedback on the early version from a bunch of people and then worked with Sarthak on later versions