Validate Phone Number
hackclub/hcb pull request #4243
Opened 2023-09-13 20:21 UTC by sampoder

Fixes #3982

2023-09-15 16:58 UTC, cjdenio requested changes

2023-09-15 16:58 UTC, cjdenio commented on app/controllers/users_controller.rb
> +      if !((user_params[:phone_number] =~ /\A\+[1-9]\d{1,14}\z/)) && user_params[:phone_number]
Could you move this to a [model-level validation](https://guides.rubyonrails.org/active_record_validations.html)?

2023-09-16 18:32 UTC, sampoder commented
oh awesome @cjdenio, TIL! just updated, let me know if i did smth wrong :D

2023-09-16 22:13 UTC, sampoder commented
Seems like I've messed something up..

2023-09-16 22:40 UTC, cjdenio commented
@sampoder it looks like we're already using [this gem](https://github.com/daddyz/phonelib) for phone validation— I wonder if it's configured incorrectly

2023-09-17 21:35 UTC, northeastprince commented
Seems to be validating phone numbers correctly already on my end.

2023-09-18 02:18 UTC, cjdenio commented
Has that changed since [this comment](https://github.com/hackclub/hcb/issues/3982#issuecomment-1593549955)?

2023-09-18 15:53 UTC, northeastprince commented
Hmm, maybe the validations weren't done for some reason on that one or we need to format numbers in E164?

2023-09-18 17:58 UTC, sampoder commented
@northeastprince what was the phone number you used that broke it?

2023-09-20 16:33 UTC, sampoder commented
I guess I'll close this for now

2023-09-20 16:33 UTC, closed without merging