Add new form link for domains and re-enable
hackclub/hcb pull request #4257
Opened 2023-09-26 15:37 UTC by rluodev

2023-09-26 16:32 UTC, devramsean0 requested changes
You haven't re-enabled the perk card properly :)
Where you removed the `disabled` class. put this instead `#{"disabled" unless @perks_available}` This is important because the way you've got it currently will allow a user to apply for a domain even if their org isn't eligible. whereas by putting the "disabled" unless @perks_available it won't enable if the org isn't eligible

But otherwise LGTM

2023-09-26 21:03 UTC, hackliv commented
Can we add another engineer to review this too!

2023-09-27 02:13 UTC, rluodev commented
@cjdenio pls review thx!

2023-09-27 02:14 UTC, rluodev commented
> You haven't re-enabled the perk card properly :) Where you removed the `disabled` class. put this instead `#{"disabled" unless @perks_available}` This is important because the way you've got it currently will allow a user to apply for a domain even if their org isn't eligible. whereas by putting the "disabled" unless @perks_available it won't enable if the org isn't eligible
> 
> But otherwise LGTM

fixed!

2023-09-27 06:00 UTC, devramsean0 approved these changes
Fixed! LGTM

2023-09-27 15:23 UTC, cjdenio commented on app/views/events/promotions.html.erb
> +            @perks_available ? fillout_form("pUUaNHEiT1us", { "hcbprojname" => @event.name, "hcburl" => event_url(@event), "name" => current_user.name, "email" => current_user.email }) : root_path,
```suggestion
            @perks_available ? fillout_form("pUUaNHEiT1us", { hcbprojname: @event.name, hcburl: event_url(@event), name: current_user.name, email: current_user.email }) : root_path,
```

2023-09-27 15:25 UTC, cjdenio approved these changes

2023-09-27 15:27 UTC, merged