Fix #4264
hackclub/hcb pull request #4269
Opened 2023-09-29 04:04 UTC by sampoder

hopefully not too hacky! fixes #4264

2023-09-29 11:51 UTC, northeastprince commented on bin/dev
> +
```suggestion
```
Unrelated

2023-11-02 20:48 UTC, garyhtou requested changes

2023-11-02 20:48 UTC, garyhtou commented on app/assets/stylesheets/_utilities.scss
> +.mt6 {
can we move this class here?
https://github.com/hackclub/bank/blob/379cd0567728fbf61a6038613b99eb3e95d1ff69/app/assets/stylesheets/space.css#L36-L36

2023-11-02 20:51 UTC, YodaLightsabr commented on app/assets/stylesheets/_utilities.scss
> +.mt6 {
to add on to what gary said, could we use `96px` instead of `6rem` to stay consistent with the other units used in `space.css`?

2023-11-02 20:52 UTC, sampoder commented on app/views/donations/_donation_form.html.erb
> +    <ul class="tab-container max-width-1 mx-auto <%= "mt6" if @event.donation_header_image.attached? && !@event.donation_page_message.present? %>">
```suggestion
    <ul class="tab-container max-width-1 mx-auto <%= "mt7" if @event.donation_header_image.attached? && !@event.donation_page_message.present? %>">
```

we actually want to jump to 7! (and skip 6)

2023-11-02 20:52 UTC, sampoder commented on app/assets/stylesheets/_utilities.scss
> +.mt6 {
indeed we should

2023-11-02 20:53 UTC, sampoder commented
(i'm gonna keep mt6 is there coz its weird to have mt5 and mt7 but no mt6)

2023-11-02 20:54 UTC, YodaLightsabr commented on app/assets/stylesheets/_utilities.scss
> +.mt6 {
did you mean [indeed.com](https://indeed.com)?

2023-11-02 20:55 UTC, garyhtou approved these changes

2023-11-02 21:01 UTC, merged