Donation Spending Breakdowns
hackclub/hcb pull request #4319
Opened 2023-10-20 03:42 UTC by sampoder

Context: https://hackclub.slack.com/archives/CN523HLKW/p1697745184336139

Example: [breakdown.pdf](https://github.com/hackclub/hcb/files/13895171/breakdown.pdf)

For now, I've only made them accessible to admins but it'd be interesting to expand that.

2023-11-02 20:28 UTC, garyhtou requested changes

2023-11-02 20:28 UTC, garyhtou commented on app/controllers/hcb_codes_controller.rb
> +    end
```suggestion
    redirect_to @hcb_code and return if @hcb_code.amount_cents <= 0
```

2023-11-02 20:28 UTC, garyhtou commented on config/routes.rb
> +      get "breakdown", to: "hcb_codes#breakdown", as: :breakdown
i think we may be able to move this route in here
https://github.com/hackclub/bank/blob/604c5197cc8764f7b07af5aecb4d6435a528651e/config/routes.rb#L331-L331

2023-11-02 20:28 UTC, garyhtou commented on app/views/hcb_codes/show.html.erb
> +  <% if @hcb_code.amount_cents > 0 %>
```suggestion
  <% if @hcb_code.amount_cents.positive? %>
```

2023-11-02 20:28 UTC, garyhtou commented on app/controllers/hcb_codes_controller.rb
> +    @donations = {}
Can we move this logic into a service? this way we can break each section into it's own method to make it more readable

2023-11-03 00:19 UTC, sampoder commented
Alrightly, I cleaned up a couple of things and moved stuff into a service! I choose to use an EventService as it felt like that made more sense. @garyhtou thoughts?

2024-01-10 21:41 UTC, garyhtou commented on app/controllers/hcb_codes_controller.rb
> +    end
```suggestion
    return redirect_to @hcb_code unless @hcb_code.amount_cents.positive?
```

2024-01-10 21:41 UTC, garyhtou commented on app/controllers/hcb_codes_controller.rb
> +      end
```suggestion
    @event = @hcb_code.event
```

2024-01-10 21:41 UTC, garyhtou commented on app/views/hcb_codes/breakdown.pdf.erb
Add Sarthak's emoji stuff

2024-01-10 21:41 UTC, garyhtou commented on app/services/event_service/pair_income_with_spending.rb
> +        if available_on_current > (ct.amount_cents.abs - distributed)
Can we give `ct.amount_cents.abs - distributed` it's own variable?

2024-01-10 21:41 UTC, garyhtou commented on app/services/event_service/pair_income_with_spending.rb
> +      end
this should handle the case where the event was negative in the past

```suggestion
      negative = @event.canonical_transactions.order("date asc").filter_map do |ct|
        if ct.amount_cents > 0
          @income[ct.id.to_s] = {
            id: ct.id,
            memo: ct.local_hcb_code.memo,
            amount: ct.amount_cents,
            spent_on: [],
            available: ct.amount_cents
          }
          next
        end

        ct
      end

      negative.each do |ct|
        next unless @income.keys[@current_index]
        distribute_spending_to_income(ct:)
      end
```

2024-01-10 21:41 UTC, garyhtou commented on app/controllers/hcb_codes_controller.rb
> +    @hcb_code.canonical_transactions.each do |ct|
```suggestion
    # PairIncomeWithSpending is done on a per CanonicalTransaction basis
    # This compute it for this specific HcbCode
    @hcb_code.canonical_transactions.each do |ct|
```

2024-01-10 21:41 UTC, garyhtou commented on app/controllers/hcb_codes_controller.rb
> +      total_amount = group.reduce(0) { |sum, item| sum + item[:amount] }
```suggestion
      total_amount = group.sum(0) { |item| item[:amount] }
```

2024-01-10 21:41 UTC, garyhtou commented on app/views/hcb_codes/breakdown.pdf.erb
> +    <% if @spent_on.length > 0 %>
```suggestion
    <% if @spent_on.any? %>
```

2024-01-10 21:41 UTC, garyhtou commented on app/views/hcb_codes/breakdown.pdf.erb
> +          Thank you for your kind donation towards <%= @event.name %>, your support is truly appreciated. At the moment, all of your donation is yet to be spent.
```suggestion
          Thank you for your kind donation towards <%= @event.name %>, your support is truly appreciated. At the moment, your donation has yet to be spent.
```

2024-01-10 21:41 UTC, garyhtou commented on app/views/hcb_codes/breakdown.pdf.erb
> +                  <%= transaction[:memo].gsub(/[^[:alnum:][:blank:][:punct:]]/, '').squeeze(' ').strip %>
```suggestion
                  <%= link_to transaction[:memo].strip, transaction[:url] %>
```

2024-01-10 21:41 UTC, garyhtou commented on app/services/event_service/pair_income_with_spending.rb
> +              memo: ct.local_hcb_code.memo,
```suggestion
              memo: ct.local_hcb_code.memo,
              url: ct.local_hcb_code.url,
```

2024-01-10 21:41 UTC, garyhtou commented on app/controllers/hcb_codes_controller.rb
> +      { id: group.first[:id], memo:, amount: total_amount }
```suggestion
      significant_transaction = group.max_by { |t| t[:amount] }
      { id: significant_transaction[:id], memo:, amount: total_amount, url: significant_transaction[:url] }
```

2024-01-10 22:33 UTC, garyhtou approved these changes
Great!

In the future:
- Send via email for large events (e.g. HQ)
- Improve performance of `PairIncomeWithSpending` by using a running total

2024-01-10 22:36 UTC, merged