Limit Billing Addresses to US & Canada + include Canadian Provinces & American / Canadian Territories
hackclub/hcb pull request #4343
Opened 2023-10-24 20:10 UTC by sampoder

Context: https://hackclub.slack.com/archives/CN523HLKW/p1698168882359829.

It seems like Stripe only supports US & Canada:

<img width="348" alt="Screenshot 2023-10-24 at 1 10 23 PM" src="https://github.com/hackclub/hcb/assets/39828164/f1924274-280a-4fd5-a3a6-df92bf381125">

fixes #4351 as well

2023-10-25 18:03 UTC, sampoder commented on app/views/users/edit_address.html.erb
> +          <%= form.country_select :stripe_billing_address_country, nil, { selected: "US", only: ["US", "CA"] }, { required: true } %>
```suggestion
          <%= form.country_select :stripe_billing_address_country, nil, { only: ["US", "CA"] }, { required: true } %>
```

2023-10-25 18:04 UTC, sampoder commented on app/views/users/edit_address.html.erb
> +          <%= form.country_select :stripe_billing_address_country, nil, { selected: "US", only: ["US", "CA"] }, { required: true } %>
fixes #4351

2023-11-02 20:18 UTC, garyhtou requested changes

2023-11-02 20:18 UTC, garyhtou commented on app/views/users/edit_address.html.erb
> +            <%= form.label :address_state, "State / Province" %>
We have the `countries` gem installed, i'd suggest that we use that instead of hardcoding

here's a starter:
```ruby
ISO3166::Country.new("US").subdivisions.values.map {|s| [s.translations["en"], s.code] }
```

2023-11-02 20:32 UTC, garyhtou requested changes

2023-11-02 20:32 UTC, garyhtou commented on app/views/users/edit_address.html.erb
> +                  ISO3166::Country.new("CA").subdivisions.values.map { |s| [s.translations["en"], s.code] }
Move this to controller as `@states`

2023-11-02 20:39 UTC, garyhtou approved these changes
yay. we love canada

![image](https://github.com/hackclub/hcb/assets/20099646/f39618b0-cd9a-4b76-bc52-985365df41c2)

2023-11-02 20:42 UTC, merged