Admin Weekly Ledger Audits
hackclub/hcb pull request #4355
Opened 2023-10-26 07:17 UTC by sampoder

<img width="1552" alt="Screenshot 2024-01-10 at 5 39 21 PM" src="https://github.com/hackclub/hcb/assets/39828164/eb8cc4f3-63d8-4cc3-8b64-3386dfbc1f87">

<img width="1552" alt="Screenshot 2024-01-10 at 5 40 36 PM" src="https://github.com/hackclub/hcb/assets/39828164/6613e5f0-d7fe-4d4e-b371-4e014642b5c1">

2023-10-26 23:12 UTC, sampoder commented
@garyhtou any idea what's up with `ReceiptUploadsMailbox` and RSpec?

2023-10-27 00:27 UTC, cjdenio commented on app/models/hcb_code.rb
> +  belongs_to :compliance_check
```suggestion
  belongs_to :compliance_check, optional: true
```

@sampoder The test was failing because `belongs_to` associations are required by default

2023-10-27 00:28 UTC, sampoder commented on app/models/hcb_code.rb
> +  belongs_to :compliance_check
oh amazing, thank you so much Caleb!

2024-01-03 19:47 UTC, garyhtou commented
@sampoder can we revisit this one? now that we're in 2024, the finance team is working on closing the books for 2023. Features regarding auditing will help them with that process

2024-01-03 19:59 UTC, garyhtou requested changes

2024-01-03 19:59 UTC, garyhtou commented on app/controllers/admin_controller.rb
> +
Let's move this into an `Admin::ComplianceCheckController` that inherits from `AdminController` (located at `app/controllers/admin/complicance_check_controller.rb`. And update the routes file so that is located at `admin/complicate_check/*`. something like:

```ruby
namespace :admin do
  resources :compliance_check, only: [:index, :show] do
    get "flagged", on: :collection
    post "action", on: :member
  end
end
```

You'll also need to move the views

2024-01-03 19:59 UTC, garyhtou commented on app/models/hcb_code.rb
> +#  reviewer_id                  :bigint
I would prefer if we had an additional model that served as a join table to hold these columns. the HcbCode model preferably shouldn't be aware of compliance checks

https://guides.rubyonrails.org/association_basics.html#the-has-many-through-association

2024-01-03 19:59 UTC, garyhtou commented on app/jobs/generate_compliance_check_job.rb
> +  queue_as :default
```suggestion
  queue_as :low
```

2024-01-03 19:59 UTC, garyhtou commented on db/schema.rb
> +    t.string "card_grants_category_lock"
unrelated

2024-01-03 20:02 UTC, garyhtou commented on app/controllers/admin_controller.rb
> +
Conext as to why: We've been stuffing everything into the adminController for a long time now. It's not how Rails is designed to work, we should start avoiding this pattern

2024-01-04 02:31 UTC, sampoder commented on db/schema.rb
> +    t.string "card_grants_category_lock"
thanks good catch
```suggestion
    t.integer "stripe_card_shipping_type", default: 0, null: false
```

2024-01-04 02:35 UTC, sampoder commented on app/models/event.rb
> +#  pending_transaction_engine_at   :datetime         default(Sat, 13 Feb 2021 22:49:40.981965000 UTC +00:00)
```suggestion
#  pending_transaction_engine_at   :datetime         default(Sat, 13 Feb 2021 22:49:40.000000000 UTC +00:00)
```

2024-01-04 21:09 UTC, garyhtou commented
FYI, I haven't looked at the frontend of this yet. this request might already be in the PR.

After chatting with Hunter, I learned that it would be help to have information about the org readily available when reviewing transactions. While reviewing transactions, Ops needs context on the Org and its mission to determine whether that specific transaction is reasonable for the org.

2024-01-04 22:37 UTC, sampoder commented
Cool! I believe we have that data in there already, let me know if we should add more.

2024-01-06 11:30 UTC, garyhtou reviewed
great progress here!

2024-01-06 11:30 UTC, garyhtou commented on app/models/compliance_check.rb
> +class ComplianceCheck < ApplicationRecord
sorry, i know this is a tall ask:

`ComplianceCheck` -> `Admin::LedgerAudit`

Reasoning:
- I imagine "compliance" as preventative and "audit" as follow-up
- I want to save the term "compliance" for when we start implementing more accounting tools
- Namespacing this under `Admin` since it's an admin-only tool

2024-01-06 11:30 UTC, garyhtou commented on app/models/hcb_code_review.rb
> +class HcbCodeReview < ApplicationRecord
`HcbCodeReview` -> `Admin::LedgerAudit::Task`

2024-01-06 11:30 UTC, garyhtou commented on app/controllers/admin/compliance_checks_controller.rb
> +      @compliance_check = ComplianceCheck.find(params[:id] || id)
I'm not sure if `id` is a valid var/method
```suggestion
      @compliance_check = ComplianceCheck.find(params[:id])
```

2024-01-06 11:30 UTC, garyhtou commented on app/controllers/admin/compliance_checks_controller.rb
> +    end
I should have pointed this out earlier. This should be in a separate controller with separate actions so that the path is: `POST` `admin/ledger_audits/1/tasks/3/flagged` and `POST` `admin/ledger_audits/1/tasks/3/reviewed`


```ruby
module Admin
  class LedgerAduits
    class Tasks < AdminController
      def reviewed
        # stuff
      end

      def flagged
        # stuff
      end
    end
end
```


routes file might look like
```ruby
  namespace :admin do
    resources :ledger_audits, only: [:index, :show] do
      get "flagged", on: :collection
      resources :tasks do
        post :reviewed
        post :flagged
      end
    end
  end
```

With separate endpoints, you also don't run the risk of unintended states being saved from this line:
```ruby
@hcb_code_review.update(status: params[:status], reviewer: current_user)
```

2024-01-06 11:30 UTC, garyhtou commented on app/models/compliance_check.rb
> +#  start      :date
Is there a difference between `start` and `created_at`?

2024-01-06 11:30 UTC, garyhtou commented on app/models/hcb_code_review.rb
> +  belongs_to :reviewer, class_name: "User", optional: true
i love that we're tracking the reviewer!

2024-01-06 11:30 UTC, garyhtou commented on app/views/admin/compliance_checks/index.html.erb
> +<%= link_to "📅 This Week's Compliance Check", "/admin/compliance_checks/#{@compliance_checks.first.id}", class: "btn" %>
```suggestion
<%= link_to "📅 This Week's Compliance Check", admin_compliance_check_path(@compliance_checks.first), class: "btn" %>
```

2024-01-06 11:30 UTC, garyhtou commented on app/views/admin/compliance_checks/index.html.erb
> +<%= link_to "⚠️ Flagged Transactions", "/admin/compliance_checks/flagged", class: "btn bg-error ml2" %>
```suggestion
<%= link_to "⚠️ Flagged Transactions", flagged_admin_compliance_checks_path, class: "btn bg-error ml2" %>
```

2024-01-06 11:30 UTC, garyhtou commented on app/views/admin/compliance_checks/index.html.erb
> +          <a href="/admin/compliance_checks/<%= compliance_check.id %>">Review</a>
```suggestion
          <a href="<%= admin_compliance_check_path compliance_check %>">Review</a>
```

2024-01-06 11:30 UTC, garyhtou commented on app/views/admin/compliance_checks/index.html.erb
> +        <td><%= compliance_check.hcb_code_reviews.where({ status: "pending" }).count %></td>
Add a `pending` and `flagged` scope in the model

```suggestion
        <td><%= compliance_check.hcb_code_reviews.pending.count %></td>
```

2024-01-06 11:30 UTC, garyhtou commented on app/controllers/admin/compliance_checks_controller.rb
> +      @hcb_code_reviews = HcbCodeReview.where({ status: "flagged" })
Add a `flagged` scope to the model

2024-01-06 11:30 UTC, garyhtou commented on app/views/admin/compliance_checks/index.html.erb
> +<%= link_to "📅 This Week's Compliance Check", "/admin/compliance_checks/#{@compliance_checks.first.id}", class: "btn" %>
Nice!

2024-01-06 11:30 UTC, garyhtou commented on app/views/admin/compliance_checks/show.html.erb
> +    </div>
rendering comments may be nice too

2024-01-06 11:30 UTC, garyhtou commented on app/views/admin/compliance_checks/show.html.erb
Move the stuff inside the `.first(1).each` loop into `/app/views/admin/ledger_aduits/tasks/show.html.erb`

Then, in the `show` action of the `LedgerAuditsController`:
```ruby
module
  class LedgerAuditsController
    def show
      @ledger_aduit = Admin::LedgerAudit.find(params[:id])
      next_task = @ledger_audit.tasks.pending.first
      redirect_to @next_task and return if @next_task.present?
    end
  end
end
```

Then this file (`app/views/admin/compliance_checks/show.html.erb`) will just be a blank slate:

"Yay! You've reviewed everything, great job"

2024-01-06 11:30 UTC, garyhtou commented on app/views/compliance_checks/_compliance_check.html.erb
> +<div id="<%= dom_id compliance_check %>">
:eyes: good use of `dom_id`

2024-01-06 11:30 UTC, garyhtou commented on app/jobs/generate_compliance_check_job.rb
> +    CanonicalPendingTransaction
IIRC it should be transactions from the past week

See https://github.com/hackclub/hcb/issues/4344#issuecomment-1781712191

2024-01-06 11:30 UTC, garyhtou commented on app/views/admin/compliance_checks/show.html.erb
> +<h2>Fraud-O-Matic: Weekly Compliance Checker (<%= @compliance_check.hcb_code_reviews.where.not({ status: "pending" }).count + 1 %>/<%= @compliance_check.hcb_code_reviews.count %>)</h2>
i'm confused by the `+ 1` lol

![image](https://github.com/hackclub/hcb/assets/20099646/551a7b24-19af-41d6-a9e5-5b2068a050b0)

2024-01-06 11:30 UTC, garyhtou commented on app/views/admin/compliance_checks/flagged.html.erb
> +        <th>Actions</th>
Each row should link to `/admin/ledger_audits/:ledger_audit_id/tasks/:id` from there, admins can perform actions.

This flagged page can just be Audit Week, Flagged By, Transaction Date, Memo, Amount, and the link to the `LedgerAudit::Task` show page

2024-01-06 11:30 UTC, garyhtou commented on app/views/compliance_checks/_compliance_check.html.erb
> +<div id="<%= dom_id compliance_check %>">
i'm not sure if I see where we're using it

2024-01-06 11:30 UTC, garyhtou commented on app/views/admin/compliance_checks/show.html.erb
> +  <div class="action_row">
It would be cool if you could open the HcbCode show page in a new tab. Maybe a `Open transaction` button

use case: admins adding comments to the transaction

2024-01-06 11:32 UTC, garyhtou commented on app/models/hcb_code_review.rb
> +#  status              :string           default("pending")
I'd suggest using AASM, but it's not necessary here because the states are simple.

AASM will automatically give you scope tho  :eyes:. up to you!

2024-01-06 14:18 UTC, sampoder commented on app/jobs/generate_compliance_check_job.rb
> +    CanonicalPendingTransaction
Oops! I accidentally removed that when testing, going to add back.

2024-01-06 14:19 UTC, sampoder commented on app/jobs/generate_compliance_check_job.rb
> +      .where.not(hcb_codes: { hcb_code: nil })
```suggestion
      .where.not(hcb_codes: { hcb_code: nil })
      .where(created_at: 1.week.ago..)
```

2024-01-06 14:36 UTC, sampoder commented on app/models/hcb_code_review.rb
> +#  status              :string           default("pending")
for now, i think we can probably stick with no AASM, if things get complicated lets switch over

2024-01-06 14:43 UTC, sampoder commented on app/views/admin/compliance_checks/show.html.erb
> +<h2>Fraud-O-Matic: Weekly Compliance Checker (<%= @compliance_check.hcb_code_reviews.where.not({ status: "pending" }).count + 1 %>/<%= @compliance_check.hcb_code_reviews.count %>)</h2>
oh yeah umm
```suggestion
<h2>Fraud-O-Matic: Weekly Compliance Checker (<%= @compliance_check.hcb_code_reviews.where.not({ status: "pending" }).count %>/<%= @compliance_check.hcb_code_reviews.count %>)</h2>
```

2024-01-06 14:49 UTC, sampoder commented on app/models/compliance_check.rb
> +#  start      :date
Oh yes.. but it was missing. Start should be the day that the transactions start from.

2024-01-07 01:27 UTC, sampoder commented on app/views/admin/compliance_checks/show.html.erb
> +    </div>
we're starting to run out of space, instead i'm going to link to the hcb code

2024-01-10 22:45 UTC, garyhtou commented on app/controllers/admin/ledger_audits_controller.rb
> +      redirect_to admin_ledger_audits_task_url(next_task) and return if next_task.present?
```suggestion
      redirect_to next_task and return if next_task.present?
```

2024-01-10 22:45 UTC, garyhtou commented on app/controllers/admin/ledger_audits_controller.rb
> +      render layout: "admin" unless next_task.present?
```suggestion
      render layout: "admin"
```

2024-01-10 22:45 UTC, garyhtou commented on app/controllers/admin/ledger_audits_controller.rb
> +    end
Let's move this to `TasksController#index`

2024-01-10 22:45 UTC, garyhtou commented on app/jobs/generate_ledger_audit_job.rb
> +        task = Admin::LedgerAudit::Task.create(hcb_code_id: HcbCode.find_by(hcb_code: cpt.hcb_code).id, admin_ledger_audit_id: ledger_audit.id)
```suggestion
        task = Admin::LedgerAudit::Task.create(hcb_code: HcbCode.find_by(hcb_code: cpt.hcb_code), admin_ledger_audit: ledger_audit)
```

2024-01-10 22:45 UTC, garyhtou commented on app/models/admin/ledger_audit/task.rb
> +      scope :flagged, -> { where("status = ?", "flagged").distinct }
```suggestion
      scope :pending, -> { where("status = ?", "pending") }
      scope :flagged, -> { where("status = ?", "flagged") }
```

2024-01-10 22:45 UTC, garyhtou commented on app/views/admin/ledger_audits/index.html.erb
> +<% if @ledger_audits.first %>
```suggestion
<% if @ledger_audits.any? %>
```

2024-01-10 22:45 UTC, garyhtou commented on app/views/admin/ledger_audits/index.html.erb
> +    <% @ledger_audits.each do |ledger_audit| %>
```suggestion
    <% @ledger_audits.find_each do |ledger_audit| %>
```

2024-01-10 23:17 UTC, garyhtou commented on db/schema.rb
> -# frozen_string_literal: true
undo this

2024-01-10 23:20 UTC, garyhtou approved these changes
Yay!

2024-01-10 23:22 UTC, merged