Catch exceptions regarding Bank Syncs on the nightly job
hackclub/hcb pull request #4359
Opened 2023-10-27 08:12 UTC by devramsean0

This should catch exceptions on the nightly Bank Sync Job allowing other banks to continue syncing if one errors.

I suggest we rerun the sync job within the preview deployment to ensure I didn't break anything (I shouldn't have but you never know)

2023-10-27 16:00 UTC, sampoder requested changes
This is awesome! Quick thing: it looks like there are some changes from your pinned cards PR still on the branch, we probably want to remove them

2023-10-27 18:32 UTC, devramsean0 commented
Oh, weird. I switched branches and VScode didn't show any changes on the branch before I started

2023-10-29 09:04 UTC, sampoder approved these changes
lgtm!

2023-10-30 21:58 UTC, maxwofford commented
@devramsean0 while this functions, there's probably a simpler way to do this in ruby. I'd encourage you to look around a bit and see if there's something built in that can one-line this for us.

2023-10-30 22:22 UTC, devramsean0 commented
@maxwofford  don't think there is a built-in way to apply an error handler per line in a function (A google search didn't find anything for ruby and I couldn't find anything for rails either) additionally, ChatGPT when I asked just now came up with the same solution to what I've done.

I could however be looking in the wrong places.

2023-10-30 22:59 UTC, devramsean0 commented
Oh, Interesting! I had no idea you could call a method like that

2023-10-30 23:02 UTC, maxwofford commented
EDIT: Reposted because I had a typo from the ChatGPT response (that, ironically, ChatGPT has correct)

Nice job with searching, ChatGPT and Google will usually get results with such an old language. Good ruby code commonly reads like a regular English sentence. For example, I'd start with writing this to make it kinda like English:

```diff
- import_raw_plaid_transactions!
+ try_to import_raw_plaid_transactions!
```

The code will _try to import raw plaid transactions_, but it doesn't say it actually will succeed. Now to figure out how we can write that:

<img width="717" alt="Screenshot 2023-10-30 at 18 44 09" src="https://github.com/hackclub/hcb/assets/5891442/d4ec43e7-1b81-41df-a7c1-40e89d90e801">

I didn't include the code it spit out because it was kinda verbose, but after cleaning it up I got it down to this:

```rb
def try_to(&block)
  yield
rescue => e
  Airbrake.notify(e)
end
```

With the `&block` syntax, I need to update how I'm running the code:


```diff
- try_to import_raw_plaid_transactions!
+ try_to { import_raw_plaid_transactions! }
```

Now I can `try_to` run any sort of method in a single line! This won't solve all your problems; for example, you'll have to figure out some way of running `import_raw_plaid_transactions!`, but I'm sure you can figure it out from here!

2023-11-01 12:26 UTC, devramsean0 commented
@maxwofford I've made that change but now we have some failed CI (tests) which I'm not sure how to fix.

2023-11-01 16:13 UTC, maxwofford reviewed
Nice work! I added a couple other comments, but these are more suggestions; your code should run fine as is

2023-11-01 16:13 UTC, maxwofford commented on app/services/transaction_engine/nightly.rb
> +        try_to { fix_plaid_mistakes! }
Seems like we're already wrapping this in a rescue under here https://github.com/hackclub/hcb/pull/4359/files#diff-f9e99fb7aa8b1e445d8bf52e00c10cb35be31ab4d3077a242b8c25822e9799a4L112

Do we need to wrap it again?

2023-11-01 16:13 UTC, maxwofford commented on app/services/transaction_engine/nightly.rb
> +      rescue => e
Same as above, it seems like we don't need to wrap the `run` method if our individual methods are all being rescued individually.

2023-11-01 16:13 UTC, maxwofford commented on app/services/transaction_engine/nightly.rb
> +      begin
Small syntax thing, but [you can do this](https://stackoverflow.com/a/1542682)

2023-11-01 22:39 UTC, YodaLightsabr commented
Could we possibly use inline `rescue`? It seems to work similarly to our `try_to` method.

<img width="841" alt="image" src="https://github.com/hackclub/hcb/assets/76178582/1800a505-9919-445b-ae64-63ff5c3aa37e">

2023-11-02 17:45 UTC, devramsean0 commented
EDIT: Added some references and context behind my confusion
Probably! How does rescue work with passing error contents to variables though?

Additionally, I've found at least 1 article saying that using inline rescue is a bad idea [[1]](https://thoughtbot.com/blog/don-t-inline-rescue-in-ruby)
And a Ruby Issue page suggesting that inline rescue can't take arguments (and therefore surely not set a var like the `e` I'm currently using) [[2]](https://bugs.ruby-lang.org/issues/6739)

2023-11-02 20:48 UTC, YodaLightsabr commented
Interesting, I hadn't considered that. To address concern 1, I don't think that filtering the type of error would be especially useful here, since we would be sending it to Airbrake anyways. However, because you have to pass a value and not a block, I agree that we should move forward with our clever `try_to` method since inline `rescue` wouldn't work for our use case.

It's certainly interesting syntax that I hadn't seen before, though. TIL!

2023-11-03 07:00 UTC, devramsean0 commented on app/services/transaction_engine/nightly.rb
> +      rescue => e
Good Catch!
I might have gone a bit over the top with the error handling :)

2023-11-03 07:04 UTC, devramsean0 commented on app/services/transaction_engine/nightly.rb
> +        try_to { fix_plaid_mistakes! }
Probably not, tbh I forgot I added error handling there

2023-11-05 19:29 UTC, devramsean0 commented
I would love another review on this. But hopefully, this should be ready to merge!

2023-11-17 18:54 UTC, cjdenio commented on app/services/transaction_engine/nightly.rb
> +  block.call
```suggestion
def try_to
  yield
```

2023-11-17 19:28 UTC, devramsean0 commented on app/services/transaction_engine/nightly.rb
> +  block.call
What does `yeid` do?

2023-11-20 19:24 UTC, garyhtou approved these changes
great work here! i'm excited to get this in

2023-11-20 19:25 UTC, merged