Feature: SMS receipts to Receipt Bin
hackclub/hcb pull request #4363
Opened 2023-10-29 06:03 UTC by sampoder

inspired by #4105, adapted from #3360. very much a WIP.

2023-10-29 16:32 UTC, YodaLightsabr reviewed
Nice work!

2023-10-29 16:32 UTC, YodaLightsabr commented on app/controllers/twilio_controller.rb
> +      user_id = last_sent_message_hcb_code&.canonical_pending_transactions&.last&.stripe_card&.user&.id
Should we continue to support multiple accounts linked to the same phone number?

2023-10-29 16:32 UTC, YodaLightsabr commented on app/controllers/twilio_controller.rb
> +        return
```suggestion
      return if @attachments.none?
```

2023-10-29 16:32 UTC, YodaLightsabr commented on app/controllers/twilio_controller.rb
> +    if @user.present? && Flipper.enabled?(:receipt_bin_2023_04_07, @user)
Maybe we could try something like this?
```suggestion
    return unless @user.present? && Flipper.enabled?(:receipt_bin_2023_04_07, @user)
```
I noticed at the bottom we're responding with XML no matter what, and I'm wondering if we should only show that if the receipts were uploaded.

2023-10-29 16:32 UTC, YodaLightsabr commented on app/controllers/twilio_controller.rb
> +          )
I'm not sure if you have to wrap the attachment data with `ActiveStorage::Blob.create_and_upload!`. In the receipt upload mailbox I just passed the attachment data. 

https://github.com/hackclub/hcb/blob/3df4d72a850ba4d9bf80c151ae7122b8b0938e96/app/mailboxes/receipt_uploads_mailbox.rb#L89-L93

2023-10-29 20:25 UTC, sampoder commented on app/controllers/twilio_controller.rb
> +          )
Oh, sick!

2023-10-29 20:26 UTC, sampoder commented on app/controllers/twilio_controller.rb
> +          )
That makes this super simple now

2023-10-29 20:30 UTC, sampoder commented on app/controllers/twilio_controller.rb
> +      user_id = last_sent_message_hcb_code&.canonical_pending_transactions&.last&.stripe_card&.user&.id
Let me investigate. IMO no.

2023-11-02 21:06 UTC, garyhtou requested changes

2023-11-02 21:06 UTC, garyhtou commented on app/controllers/twilio_controller.rb
> +      potential_users = User.where(phone_number: params["From"])
should we also filter by `phone_number_verified`?

2023-11-02 21:06 UTC, garyhtou commented on app/controllers/twilio_controller.rb
> +      results
please test this first

```suggestion
      num_media = params["NumMedia"].to_i
      return [] if num_media.zero?

      (0..num_media - 1).map do |i|
        {
          media_url: params["MediaUrl#{i}"],
          filename: File.basename(URI.parse(attachment[:media_url]).path),
          content_type: params["MediaContentType#{i}"]
        }
      end
```

2023-11-02 21:06 UTC, garyhtou commented on app/controllers/twilio_controller.rb
> +      url = URI.parse(attachment[:media_url])
if wonder if we should filter by `http/https` only as a security measure

2023-11-02 21:06 UTC, garyhtou commented on app/controllers/twilio_controller.rb
> +  def grab_attachments!
should we combine this into the `attachments` method?

2023-11-02 21:06 UTC, garyhtou commented on app/controllers/twilio_controller.rb
> +    end
```suggestion
    receipts = ::ReceiptService::Create.new(
      receiptable: nil,
      uploader: @user,
      attachments: @attachments,
      upload_method: "sms"
    ).run!

    respond_to do |format|
      format.xml { render xml: "<Response><Message> Added #{pluralize receipts.count, 'receipt'} to your receipt bin! </Message></Response>" }
    end
```

2023-11-03 03:21 UTC, sampoder commented on app/controllers/twilio_controller.rb
> +      results
after combining the grab attachments method and attachments i think it's more readable to use the `.each`. it also lets me use `break` etc.

2023-11-30 20:10 UTC, garyhtou commented on app/controllers/twilio_controller.rb
> +  skip_before_action :signed_in_user # do not require logged in user
```suggestion
class TwilioController < ActionController::Base
  protect_from_forgery except: :webhook
  include ActionView::Helpers::TextHelper # for `pluralize`
```

2023-11-30 20:10 UTC, garyhtou commented on app/controllers/twilio_controller.rb
> +    @attachments ||= begin
```suggestion
  def set_attachments
    @attachments = begin
```

same for `set_user`. and don't forget to update the `before_action`

2023-11-30 20:41 UTC, garyhtou commented on app/controllers/twilio_controller.rb
> +      Hey! We couldn't find any attachments in your message. If you're looking
can we hint that this feature is for uploading receipts? i can see someone replying to a "your card was charged" SMS and then getting confused by "We couldn't find any attachments in your message"

2023-11-30 20:46 UTC, garyhtou approved these changes
great work on this!

2023-11-30 20:46 UTC, garyhtou approved these changes
great work on this!

2023-11-30 20:46 UTC, garyhtou approved these changes
great work on this!

2023-11-30 20:54 UTC, merged