Add public view of card grant spending
hackclub/hcb pull request #4384
Opened 2023-11-01 07:06 UTC by sampoder

This uses a model that pops up on transparent orgs with card grants:

<img width="1437" alt="Screenshot 2023-11-01 at 12 04 44 AM" src="https://github.com/hackclub/hcb/assets/39828164/e457c9f4-9c9b-406f-b341-966c3570a8ae">

All private info should be hidden, though I'd appreciate a sanity check on that.

I thought a model was the cleanest way to do this.

Closes #4380.

Happy halloween! 🎃

2023-11-01 07:45 UTC, maxwofford commented
Awesome work on this @sampoder! I'm half tempted to merge even with it needing tweaks because this by itself makes everything so much clearer.

2023-11-01 16:17 UTC, sampoder commented
@maxwofford awesome! i just changed it up a little so that this view shows up when you click "Details" while signed in as an organiser and added a little icon to keep it visually distinct

2023-11-01 22:27 UTC, YodaLightsabr reviewed
Nice work on this! I just wanted to add a few comments to make sure our popover implementation is consistent.

2023-11-01 22:27 UTC, YodaLightsabr commented on app/assets/javascripts/ui.js
> +      $.get(`${$(frame).data('src')}?async_frame=true`,  data => {
I think this might interfere with or break the HcbCode popover implementation
https://github.com/hackclub/hcb/blob/837ba812492346d041c5eddf50865b9941097c3d/app/models/hcb_code.rb#L53

2023-11-01 22:27 UTC, YodaLightsabr commented on app/controllers/card_grants_controller.rb
> +    @async_frame = params[:async_frame].present?
```suggestion
    @frame = params[:frame].present?
```

Thoughts on using `frame` instead of `async_frame`?

2023-11-01 22:27 UTC, YodaLightsabr commented on app/views/canonical_pending_transactions/_canonical_pending_transaction.html.erb
> +  <% if defined?(receipt_upload_button) && receipt_upload_button %>
```suggestion
  <% if local_assigns[:receipt_upload_button] %>
```
This might be a little bit cleaner (for cases like this where you want to be able to pass in `false`)

2023-11-01 22:27 UTC, YodaLightsabr commented on app/views/canonical_pending_transactions/_canonical_pending_transaction.html.erb
> +  <% if defined?(receipt_upload_button) && receipt_upload_button %>
```suggestion
  <% if local_assigns[:receipt_upload_button] %>
```

2023-11-01 22:27 UTC, YodaLightsabr commented on app/views/canonical_transactions/_canonical_transaction.html.erb
> +  <% if defined?(receipt_upload_button) && receipt_upload_button %>
```suggestion
  <% if local_assigns[:receipt_upload_button] %>
```

2023-11-01 22:27 UTC, YodaLightsabr commented on app/views/canonical_transactions/_canonical_transaction.html.erb
> +  <% if defined?(receipt_upload_button) && receipt_upload_button %>
```suggestion
  <% if local_assigns[:receipt_upload_button] %>
```

2023-11-01 22:45 UTC, sampoder commented on app/assets/javascripts/ui.js
> +      $.get(`${$(frame).data('src')}?async_frame=true`,  data => {
that explains a lot omg... lol yes, let's use frame

2023-11-01 22:45 UTC, sampoder commented on app/assets/javascripts/ui.js
> +      $.get(`${$(frame).data('src')}?async_frame=true`,  data => {
```suggestion
      $.get(`${$(frame).data('src')}?frame=true`,  data => {
```

2023-11-01 22:48 UTC, sampoder commented on app/assets/javascripts/ui.js
> +      $.get(`${$(frame).data('src')}?frame=true`,  data => {
```suggestion
      $.get($(frame).data('src')`,  data => {
```

2023-11-01 22:48 UTC, sampoder commented on app/assets/javascripts/ui.js
> +      $.get($(frame).data('src')`,  data => {
```suggestion
      $.get($(frame).data('src'),  data => {
```

2023-11-01 22:49 UTC, sampoder commented on app/views/canonical_transactions/_canonical_transaction.html.erb
> +    <%= async_frame_to public_card_grant_path(ct.local_hcb_code.disbursement.card_grant, params: { async_frame: true }), as: :div do %>
```suggestion
    <%= async_frame_to public_card_grant_path(ct.local_hcb_code.disbursement.card_grant, params: { frame: true }), as: :div do %>
```

2023-11-09 03:55 UTC, sampoder commented
@maxwofford @YodaLightsabr: whilst the HCPD may be fictitious, what do we need to do to push this PR over the line? Does it look good to the both of you?

2024-01-03 22:55 UTC, garyhtou requested changes
This is very cool! Two large feedbacks:
- We should find a new name for the controller action (we're currently overriding an existing`public` method)
- Give the popover (public) version its own view file. This means moving shared content into partials.

2024-01-03 22:55 UTC, garyhtou commented on app/controllers/card_grants_controller.rb
> +  def public
This action should be renamed. `public` is basically like a keyword in Ruby; we don't want to be overriding that

2024-01-03 22:55 UTC, garyhtou commented on app/views/canonical_transactions/_canonical_transaction.html.erb
> +        <%= inline_icon "like" %>
Do we wanna update the transfer page to have the same terminology/icon?

https://github.com/hackclub/bank/blob/c1807ec9e56164a6fca4a1c9b4dfe35aea440340/app/views/events/transfers.html.erb#L81-L83

2024-01-03 22:55 UTC, garyhtou commented on config/routes.rb
> +  resources :card_grants, only: [:show, :public], path: "grants" do
if we have `get "public"` at the bottom, I don't think we need `:public` here

2024-01-03 22:55 UTC, garyhtou commented on app/views/canonical_pending_transactions/_canonical_pending_transaction.html.erb
> +    <%= link_to "Details", pt.url, data: Flipper.enabled?(:hcb_code_popovers_2023_06_16, current_user) && (!defined?(@force_no_popover) || !@force_no_popover) ? { turbo_frame: "_top", behavior: "moda
There is no need to check if `@force_no_popover` is defined. Undefined instance variables return `nil`. So, `(!defined?(@force_no_popover) || !@force_no_popover)` I think can be rewritten as just `!@force_no_popover`

2024-01-03 22:55 UTC, garyhtou commented on app/views/canonical_transactions/_canonical_transaction.html.erb
> +    <% end %>
Is the only difference the link? If so, do

```ruby
<% details_link = ct.local_hcb_code.card_grant? ? public_card_grant_path(ct.local_hcb_code.disbursement.card_grant) : ct.local_hcb_code.url %>

<%= link_to "Details", details_link, blath blath blah other stuff %>
```

2024-01-03 22:55 UTC, garyhtou commented on app/views/card_grants/show.html.erb
Instead of using the `show` view for both the full-page and "public"/popover version. Let's create a separate page for the public version. It can sit at `card_grants/:id/popover`.

Over all shared content from this page into their own partials. I'm thinking we could have 3:
- `balance`
- `spending_instructions`
- `transactions`

This will also us to get rid of the `@public` instance variable

2024-01-04 06:22 UTC, maxwofford submitted a review, later dismissed
Hey @sampoder! You or @garyhtou should have a chat with @SerenityUX. HCPD might not be real, but the HCPD: Pizza Crimes Division is a real thing headed by them and they probably have some opinions about this!

As for https://github.com/hackclub/hcb/issues/4380, I think this is missing one big component: on a regular event, I can audit it by looking at the transaction history in linear order. If I check it each day, I can look at the most recent ~5 transactions and stop searching once I reach the previous day's transactions.

On card grant events, if I want to see if someone has done something invalid in the past day, **I have to go through every card's popover every single day**. I think that's too hard to audit / call transparent.

2024-01-04 08:31 UTC, sampoder commented
howdy! that makes sense to me. i guess that wasn't quite the problem i was trying to solve with the original PR which is why what we've got here isn't a perfect fit. instead of trying to shoehorn in a fix to what we already have, would it make sense to build out an admin tool like we have with https://github.com/hackclub/hcb/pull/4355? some other ideas I have are: including card grant transactions in exports or having a toggle to list them on the ledger directly.

2024-01-04 08:32 UTC, sampoder commented
Oh, and I'll also text Thomas!

2024-01-05 22:31 UTC, sarthaktexas commented
What you suggested (daily compliance checks) is what Thomas, Jasper, and I agreed on. I think this PR is fine to merge especially because they need this quickly. cc @maxwofford

2024-01-05 22:35 UTC, sarthaktexas commented
@maxwofford said his request to change was in fact not a request to not merge. We are just waiting for an approval from @garyhtou.

2024-01-06 02:24 UTC, garyhtou commented
> What you suggested (daily compliance checks) is what Thomas, Jasper, and I agreed on.

Is this their intention behind https://github.com/hackclub/hcb/issues/4932?

2024-01-06 03:59 UTC, sarthaktexas commented
Oh we have two options. Webhook works if you want to add that into the codebase -- or what Max suggested is a compliance check feature for organizations (not an internal admin tool) giving out card grants.

2024-01-06 04:11 UTC, garyhtou commented
> Oh we have two options. Webhook works if you want to add that into the codebase -- or what Max suggested is a compliance check feature for organizations (not an internal admin tool) giving out card grants.

I think webhooks will be a lighter lift for us. Let's go for that especially since it's a very niche use case (we have few card grant programs). https://github.com/hackclub/hcb/issues/4932 outlines the spec that Jasper and I agreed on

2024-01-06 06:36 UTC, garyhtou approved these changes
coolio!

2024-01-06 06:50 UTC, merged