Auto-rename STRIPE FEE REIMBURSEMENTs
hackclub/hcb pull request #4421
Opened 2023-11-04 14:03 UTC by sarthaktexas

fixes #4354

2023-11-04 14:05 UTC, sampoder commented
to help with Rubocop, you can run `bin/lint`. it'll fix most things for you!

2023-11-04 14:28 UTC, sarthaktexas commented
> to help with Rubocop, you can run `bin/lint`. it'll fix most things for you!

thank you love you @sampoder

2023-11-04 14:32 UTC, sampoder approved these changes
looks good to me!

2023-11-04 22:30 UTC, garyhtou requested changes
you're on the right track!

2023-11-04 22:30 UTC, garyhtou commented on app/models/canonical_transaction.rb
> +  scope :likely_hack_club_bank_stripe_fee_reimbursement, -> { where("memo ilike 'STRIPE FEE REIMBURSEMENT%'") }
```suggestion
  scope :likely_fee_reimbursement, -> { where(memo: "Stripe fee reimbursement") }
```

Two edits here:
- `likely_hack_club_bank_stripe_fee_reimbursement` -> `likely_fee_reimbursement`. This better reflects the `FeeReimbursement` model.
- We can make the `where` query more strict, the transaction memos are "Stripe fee reimbursement"
	<img width="889" alt="image" src="https://github.com/hackclub/hcb/assets/20099646/2b55ef48-d73c-4e33-88f3-08d43433441a">
	
	Side note: Technically, we have [control over this memo](https://github.com/hackclub/bank/blob/a0da88f1b4c335e4f7923dd4fad3a20905556897/app/services/fee_reimbursement_service/nightly.rb#L20-L20) and could change that line so that it is prettier. However, I like the approach you took here for one key reason: The new pretty memo contains an emoji, which may not be supported by all banks (such as Increase) and could be lost when it goes through their systems.

2023-11-04 22:30 UTC, garyhtou commented on app/services/stripe_card_service/nightly.rb
The new code here looks great, however, let's move it into the FeeReimbursement's nightly job. That is located here:
https://github.com/hackclub/bank/blob/a0da88f1b4c335e4f7923dd4fad3a20905556897/app/services/fee_reimbursement_service/nightly.rb

2023-11-04 22:50 UTC, sarthaktexas commented on app/models/canonical_transaction.rb
> +  scope :likely_hack_club_bank_stripe_fee_reimbursement, -> { where("memo ilike 'STRIPE FEE REIMBURSEMENT%'") }
Why does it capitalize the memo i didn't realize it was lowercase cause of that

2023-11-04 22:52 UTC, sarthaktexas commented on app/services/stripe_card_service/nightly.rb
that job only runs for unprocessed fee reimbursements, should I move it outside that fragment?

2023-11-05 00:20 UTC, garyhtou commented
<table>
<tr>
 <th>Before
 <th>After
<tr>
 <td>
<img width="1372" alt="image" src="https://github.com/hackclub/hcb/assets/20099646/a671788d-3bb1-4a73-b658-5f5cd7c3d10d">

 <td>
<img width="1381" alt="image" src="https://github.com/hackclub/hcb/assets/20099646/70d684e6-2e24-445c-ac47-69fa06c60acb">

</table>

2023-11-05 00:20 UTC, garyhtou approved these changes
Yayyy! amazing job 🎉

2023-11-05 05:13 UTC, merged