Add Comment Notifications
hackclub/hcb pull request #4423
Opened 2023-11-05 05:25 UTC by sampoder

Now folks will get an email if one of their teammates comments on a transaction! And if it's an admin-only comment, it'll go to the POC.

2023-12-27 16:41 UTC, sampoder commented
@polypixeldev we currently have this for comment notifications; thoughts?

2023-12-27 16:50 UTC, northeastprince commented on app/mailers/comment_mailer.rb
> +  end
These should all be private.

2023-12-27 16:50 UTC, northeastprince commented on app/mailers/comment_mailer.rb
> +class CommentMailer < ApplicationMailer
I don't think we should have this as a root class since it's only applicable to comments on a transaction.

2023-12-28 00:37 UTC, polypixeldev commented on app/views/comment_mailer/notification.html.erb
> +<%= @comment.user.full_name %> has left a comment on <i><%= @hcb_code.memo %> </i>:
I think the email content should mention the project that the transaction is in and provide a link to the comment, like

\<user> has left a comment on \<memo> in \<project>:
\<comment>
Click here to view and reply on HCB.

2023-12-28 03:33 UTC, sampoder commented on app/views/comment_mailer/notification.html.erb
> +<%= @comment.user.full_name %> has left a comment on <i><%= @hcb_code.memo %> </i>:
that'd be awesome! do you want to try making a PR into the PR to add that? I could also but I know you were interested in tackling this

2023-12-28 05:25 UTC, polypixeldev commented on app/views/comment_mailer/notification.html.erb
> +<%= @comment.user.full_name %> has left a comment on <i><%= @hcb_code.memo %> </i>:
sure, i'll work on it tomorrow evening or the friday hack morning!

2023-12-28 06:25 UTC, cjdenio commented on app/services/hcb_code_service/comment/create.rb
> +        emails = @admin_only ? [hcb_code.event.point_of_contact.email] : hcb_code.event.organizer_positions.map { |organizer| organizer.user.email }.reject { |email| email == @current_user.email }
```suggestion
        emails = @admin_only ? [hcb_code.event.point_of_contact.email] : hcb_code.event.users.pluck(:email).excluding(@current_user.email)
```

2023-12-28 07:14 UTC, sampoder commented
awesome!

From Sam


On Wed, 27 Dec 2023 at 9:25 PM, Samuel Fernandez ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In app/views/comment_mailer/notification.html.erb
> <https://github.com/hackclub/hcb/pull/4423#discussion_r1437396058>:
>
> > @@ -0,0 +1,3 @@
> +<%= @comment.user.full_name %> has left a comment on <i><%= @hcb_code.memo %> </i>:
>
> sure, i'll work on it tomorrow evening or the friday hack morning!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/hcb/pull/4423#discussion_r1437396058>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJP3VRGV5LU72UWNXOBA3MDYLT7FXAVCNFSM6AAAAAA66CU5UWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOJXGY4TCNZXGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-18 21:43 UTC, garyhtou requested changes

2024-01-18 21:43 UTC, garyhtou commented on app/services/hcb_code_service/comment/create.rb
> +        CommentMailer.with(hcb_code:, comment:, emails:).notification.deliver_later
`after_create_commit` in the model

2024-01-18 21:43 UTC, garyhtou commented on app/mailers/comment_mailer.rb
Comments will be used for the reimbursement system. So, this shouldn't be specific to HcbCode. Instead, we'll base it around `Commentable`. Each commentable (e.g. HcbCode, ExpenseReport) should define a method that returns a list of users. `CommetMailer` will then notify those users

2024-01-18 21:43 UTC, garyhtou commented on app/mailers/comment_mailer.rb
> +  def message_id(hcb_code)
takes in a `comment`

2024-01-18 21:43 UTC, garyhtou commented on app/mailers/comment_mailer.rb
> +    mail(mail_settings)
`render "comment_mailer/#{@commentable.class.underscore}/notification"`

2024-01-18 21:43 UTC, garyhtou commented on app/views/comment_mailer/notification.html.erb
> +<%= @comment.user.full_name %> has left a comment on <i><%= @hcb_code.memo %> </i> in <i><%= @hcb_code.event.name %> </i>:
```suggestion
<%= @comment.user.name %> has left a comment on <i><%= @hcb_code.memo %></i> in <i><%= @hcb_code.event.name %> </i>:
```

2024-01-22 20:15 UTC, sampoder commented on app/mailers/comment_mailer.rb
> +class CommentMailer < ApplicationMailer
Fixed, now this works for all comments!

2024-01-22 20:26 UTC, sampoder commented on app/services/hcb_code_service/comment/create.rb
> +        comment = hcb_code.comments.create!(attrs)
```suggestion
        hcb_code.comments.create!(attrs)
```

2024-01-22 20:29 UTC, northeastprince commented on app/models/hcb_code.rb
> +  end
Why should these go in the model (or the concern)?

2024-01-22 20:29 UTC, northeastprince commented on app/mailers/comment_mailer.rb
> +  end
These should go below `#headers`.

2024-01-22 20:29 UTC, northeastprince commented on app/views/comment_mailer/hcb_code/notification.html.erb
> +<%= link_to "Click here to view and reply on HCB.", "#{hcb_code_url(@commentable)}#comment-#{@comment.hashid}" %>
I would recommend putting the link on the word "comment" or integrating it somewhere else.

2024-01-22 20:29 UTC, northeastprince commented on app/models/comment.rb
> +    CommentMailer.with(commentable:, comment: self).notification.deliver_later
The two parameters are redundant since the commentable can be accessed from the comment.

2024-01-22 21:23 UTC, sampoder commented on app/models/hcb_code.rb
> +  end
https://github.com/hackclub/hcb/pull/4423#discussion_r1458003033

What they should be depends on what commentable is.

2024-01-22 21:23 UTC, sampoder commented on app/views/comment_mailer/hcb_code/notification.html.erb
> +<%= link_to "Click here to view and reply on HCB.", "#{hcb_code_url(@commentable)}#comment-#{@comment.hashid}" %>
```suggestion
<%= link_to "Click here to view and reply to the comment on HCB.", "#{hcb_code_url(@commentable)}#comment-#{@comment.hashid}" %>
```

2024-01-22 21:24 UTC, sampoder commented on app/models/comment.rb
> +    CommentMailer.with(commentable:, comment: self).notification.deliver_later
agreed

2024-01-22 21:25 UTC, sampoder commented on app/mailers/comment_mailer.rb
> +    @comment = params[:comment]
```suggestion
    @comment = params[:comment]
```
```suggestion
    @comment = params[:comment]
    @commentable = @comment.commentable
```

2024-01-22 21:25 UTC, sampoder commented on app/models/comment.rb
> +    CommentMailer.with(commentable:, comment: self).notification.deliver_later
```suggestion
    CommentMailer.with(comment: self).notification.deliver_later
```

2024-01-22 22:03 UTC, northeastprince commented on app/models/hcb_code.rb
> +  end
I would call it `#notification_subject` then.

2024-01-25 22:01 UTC, sampoder commented on app/models/hcb_code.rb
> +  end
I'd like to keep prepending `comment_mailer` to give folks a bit more context

2024-02-16 21:18 UTC, sampoder commented on app/models/hcb_code.rb
> +    return comment.admin_only ? [self.event.point_of_contact.email] : self.event.users.pluck(:email).excluding(comment.user.email)
```suggestion
    return (comment.admin_only ? User.admin : self.event.users).pluck(:email).excluding(comment.user.email)
```

@maxwofford I'm going to make this switch which I think will be more helpful

2024-02-27 21:22 UTC, garyhtou commented on app/models/concerns/commentable.rb
> +  end
```suggestion
  def comment_mailer_to(comment)
    []
  end

  def comment_mailer_subject
    "New comment from HCB"
  end
```

2024-02-27 21:22 UTC, garyhtou commented on app/models/concerns/commentable.rb
> +  def comment_mailer_to(comment)
```suggestion
  def comment_recipients_for(comment)
```

2024-02-27 21:22 UTC, garyhtou commented on app/mailers/comment_mailer.rb
> +      template_path: "comment_mailer/#{@commentable.class.to_s.underscore}"
```suggestion
      template_path: "comment_mailer/#{@commentable.class.name.underscore}"
```

2024-02-27 21:22 UTC, garyhtou commented on app/mailers/comment_mailer.rb
> +    }.reject { |_, x| x.blank? }
```suggestion
    }.compact_blank
```

2024-02-27 21:22 UTC, garyhtou commented on app/mailers/comment_mailer.rb
> +    "<comment-#{comment.id}-#{comment.created_at.to_i}@hackclub.com>"
```suggestion
    "<comment-#{comment.id}-#{comment.created_at.to_i}@hcb.hackclub.com>"
```

2024-02-27 21:22 UTC, garyhtou commented on app/mailers/comment_mailer.rb
> +    message_id(first_comment)
Let's use the commentable to generate a thread id. this will fix the bug where we generate a different thread id if the first comment is deleted

2024-02-27 21:22 UTC, garyhtou commented on app/mailers/comment_mailer.rb
> +      references: thread_id(@commentable)
```suggestion
  def headers
    {
      in_reply_to: thread_id(@commentable),
      message_id: message_id(@comment),
      references: # TODO, this need to be a list of message ids
```
https://www.hostknox.com/tutorials/email/headers#:~:text=References%3A%20%2D%20as%20the%20In%2D,the%20replies%20in%20the%20thread.
https://cr.yp.to/immhf/thread.html

2024-02-27 21:22 UTC, garyhtou commented on app/mailers/comment_mailer.rb
> +    }.merge(headers(@commentable))
```suggestion
    }.merge(headers)
```

2024-02-27 21:22 UTC, garyhtou commented on app/models/hcb_code.rb
> +    return (comment.admin_only ? User.admin : self.event.users).pluck(:email).excluding(comment.user.email)
```suggestion
    if comment.admin_only?
      return User.admin.pluck(:email).excluding(comment.user.email)
    end

    self.events.map { |e| e.pluck(:email) }.flatten.excluding(comment.user.email)
```

2024-02-27 21:22 UTC, garyhtou commented on app/mailers/comment_mailer.rb
> +      to: @commentable.comment_mailer_to(@comment),
```suggestion
      to: @commentable.comment_mailer_to(@comment),
      reply_to: (@commentable.comment_mailer_to(@comment) + @comment.user.email).uniq
```

2024-02-27 21:22 UTC, garyhtou commented on app/views/comment_mailer/hcb_code/notification.html.erb
> +<%= @comment.user.name %> has left a comment on <i><%= @commentable.memo %></i> in <i><%= @commentable.event.name %></i>:
```suggestion
<% hcb_code = @commentable %>

<%= @comment.user.name %> has left a comment on <i><%= @commentable.memo %></i> in <i><%= @commentable.event.name %></i>:
```
then update rest of the code to use `hcb_code`

2024-02-28 00:16 UTC, sampoder commented on app/mailers/comment_mailer.rb
> +      references: thread_id(@commentable)
Added!

2024-02-28 00:17 UTC, sampoder commented on app/mailers/comment_mailer.rb
> +    message_id(first_comment)
Because thread ID is essentially a reference to the first message's ID, we need to use a comment. In the case where the first comment is deleted, that's alright though because it would reference the second comment which would already be in the thread

2024-02-29 22:02 UTC, garyhtou commented on app/mailers/comment_mailer.rb
> +    "<comment-#{comment.id}-#{comment.created_at.to_i}@hcb.hackclub.com>"
```suggestion
    # "<comment-cmt_Sl3ns3@hcb.hackclub.com>"
    "<comment-#{comment.public_id}@hcb.hackclub.com>"
```

2024-02-29 22:02 UTC, garyhtou commented on app/models/hcb_code.rb
> +    self.events.map { |e| e.users.pluck(:email) }.flatten.excluding(comment.user.email)
```suggestion
    self.events.flat_map { |e| e.users.pluck(:email) }.excluding(comment.user.email)
```

2024-02-29 22:05 UTC, garyhtou commented on app/mailers/comment_mailer.rb
> +      reply_to: (@commentable.comment_recipients_for(@comment) + [@comment.user.email]).uniq,
Small edit so that the sender's email shows up first
```suggestion
      reply_to: ([@comment.user.email] + @commentable.comment_recipients_for(@comment)).uniq,
```

2024-02-29 22:06 UTC, garyhtou approved these changes
we're one step closer to bringing chat to HCB (~~and eventually taking over new expensify~~)

2024-02-29 22:07 UTC, merged