Email when Stripe card is lost
hackclub/hcb pull request #4444
Opened 2023-11-08 22:37 UTC by sampoder

sad moment :(

2023-12-11 22:21 UTC, northeastprince commented on app/mailers/stripe_card_mailer.rb
> +  def physical_card_lost
```suggestion
  def lost_in_shipping
```

2023-12-11 22:21 UTC, northeastprince commented on app/mailers/stripe_card_mailer.rb
> +    @card = StripeCard.find params[:card_id]
Don't repeat the logic, just extract it to a `before_action` callback. And I think we can just pass the model in, we don't need the ID.

2023-12-11 22:21 UTC, northeastprince commented on db/migrate/20231108222523_add_lost_to_stripe_cards.rb
> +    add_column :stripe_cards, :lost, :boolean, default: false
Maybe call the column `lost_in_shipping` instead? Without context, it sounds like someone lost their own card and reported it.

2023-12-11 22:21 UTC, northeastprince commented on app/models/stripe_card.rb
> +      end
```suggestion
      if stripe_obj[:shipping][:status] == "returned" || stripe_obj[:shipping][:status] == "failure"
        unless lost?
          self.lost = true
          StripeCardMailer.with(card_id: self.id).lost_in_shipping.deliver_later
        end
      end

```

2023-12-11 22:21 UTC, northeastprince commented on app/mailers/stripe_card_mailer.rb
> +         subject: "Your HCB card (ending in #{@card.last4}) for #{@event.name} was lost in shipping."
```suggestion
         subject: "Your HCB card (ending in #{@card.last4}) for #{@event.name} was lost in shipping"
```

2023-12-13 20:58 UTC, garyhtou requested changes
Let's add some UI on the StripeCard show page that mentioned that this card was lost in shipping

2023-12-13 20:58 UTC, garyhtou commented on app/models/stripe_card.rb
> +#  lost                                :boolean          default(FALSE)
Validates that only physical cards can be lost

2023-12-13 20:58 UTC, garyhtou commented on db/migrate/20231108222523_add_lost_to_stripe_cards.rb
> +    add_column :stripe_cards, :lost, :boolean, default: false
this is a good idea

2023-12-13 20:58 UTC, garyhtou commented on app/models/stripe_card.rb
> +        self.lost = true
What happens to the [stripe_status](https://stripe.com/docs/api/issuing/cards/object#issuing_card_object-status) of a Stripe card when it's lost in shipping? Some Stripe automatically set its state to `cancelled`? Or should we do this ourselves?

2023-12-13 21:04 UTC, cjdenio commented on app/views/stripe_card_mailer/physical_card_lost.html.erb
> +<p>Unfortunately, your HCB card (ending in <%= @card.last4 %>) for <%= @event.name %> was lost in shipping. Please order a new one <%= link_to "here", event_cards_overview_path(event_id: @event.slug)
This copy feels a little negative? Like "oops, WE messed up and lost your card" when that's rarely what happens (it's usually returned by the postal service because of an incorrect address or something)

2023-12-14 01:21 UTC, garyhtou commented on app/views/stripe_card_mailer/physical_card_lost.html.erb
> +<p>Unfortunately, your HCB card (ending in <%= @card.last4 %>) for <%= @event.name %> was lost in shipping. Please order a new one <%= link_to "here", event_cards_overview_path(event_id: @event.slug)
maybe we can change it to something along the lines of "Unfortunately, the postal service was unable to deliver your HCB card (ending in 1234) to your provided address. Please order a new one here"

2024-01-03 03:07 UTC, garyhtou commented
Should we good to merge after addressing feedback

2024-01-03 03:28 UTC, sampoder commented on app/models/stripe_card.rb
> +        self.lost = true
They seem to do nothing, we should probably do this ourselves

2024-01-03 03:35 UTC, sampoder commented on app/models/stripe_card.rb
> +      if (stripe_obj[:shipping][:status] == "returned" || stripe_obj[:shipping][:status] == "failure") && !lost_in_shipping?
this is the format Rubocop wants it in

2024-01-03 03:39 UTC, sampoder commented
Awesome, I think I got everyone's feedback in!

2024-01-03 04:14 UTC, garyhtou requested changes
one last big item. i just noticed a possible bug with `cancel!`

2024-01-03 04:14 UTC, garyhtou commented on app/models/stripe_card.rb
> +  validate :validate_lost_in_shipping_for_physical_cards_only
```suggestion
  validate :only_physical_cards_can_be_lost_in_shipping
```

2024-01-03 04:14 UTC, garyhtou commented on app/models/stripe_card.rb
> +    if card_type == "virtual" && lost_in_shipping == true
this just makes it a bit more clear
```suggestion
    if !physical? && lost_in_shipping?
```

2024-01-03 04:14 UTC, garyhtou commented on app/models/stripe_card.rb
> +        self.cancel!
since `cancel!` calls this method (`sync_from_stripe!`) there might be some weird recursion stuff going on. 

Maybe the best way to approach this is with a `before_save` callback:
`if lost_in_shipping_changed? && lost_in_shipping?` then `self.cancel!`

let's make sure we test this thoroughly

2024-01-03 04:51 UTC, sampoder commented on app/models/stripe_card.rb
> +  before_save { self.cancel! if lost_in_shipping_changed? && lost_in_shipping? }
@garyhtou would this be what we'd want to do?

2024-01-03 04:51 UTC, sampoder commented on app/models/stripe_card.rb
> +  before_save { self.cancel! if lost_in_shipping_changed? && lost_in_shipping? }
how would this differ from running it directly afterwards? in both cases, i'd assume `lost_in_shipping?` would be true

2024-01-03 05:35 UTC, garyhtou commented on app/models/stripe_card.rb
> +        self.cancel!
fyi, this may cause an unexpected early save. usually `sync_from_stripe!` doesn't call `save!`, but `cancel!` does :|

2024-01-03 06:12 UTC, sampoder commented
Just tested this locally by making a new card, modifying this line to force it to be true:

```
if (true || stripe_obj[:shipping][:status] == "returned" || stripe_obj[:shipping][:status] == "failure") && !lost_in_shipping?
```

And running `StripeCard.last.sync_from_stripe!` in my console.

Worked like a charm.

2024-01-03 06:14 UTC, garyhtou approved these changes
let's hope the postal services stop losing cards :)

2024-01-03 06:19 UTC, sampoder commented
we can only pray

2024-01-03 06:19 UTC, merged