Remove MFA Codes / Requests
hackclub/hcb pull request #4575
Opened 2023-11-30 21:13 UTC by sampoder

RIP

2023-12-14 02:45 UTC, garyhtou commented on db/schema.rb
Can you remove the unrelated changes?

2023-12-14 02:52 UTC, garyhtou requested changes
this looks good. it's just the unrelated changes

2024-01-04 08:57 UTC, sampoder commented
sorry i missed your comment earlier @garyhtou, should be done now!

2024-01-04 19:21 UTC, maxwofford commented on app/controllers/admin_controller.rb
> -  before_action :signed_in_admin, except: [:twilio_messaging]
I might be misreading this. Do we want to do this?

2024-01-04 19:33 UTC, sampoder commented on app/controllers/admin_controller.rb
> -  before_action :signed_in_admin, except: [:twilio_messaging]
Mb! We don't want to remove:

```
before_action :signed_in_admin, except: [:twilio_messaging]
```

2024-01-04 19:34 UTC, sampoder commented on app/controllers/admin_controller.rb
> -  before_action :signed_in_admin, except: [:twilio_messaging]
The other two we want to remove though to as they were only for `:twilio_messaging`.

This should be fixed now!

2024-01-20 21:06 UTC, cjdenio approved these changes
This looks ready to merge!

2024-01-21 02:01 UTC, merged