Add messages to recurring donations
hackclub/hcb pull request #4590
Opened 2023-12-01 21:40 UTC by sampoder

## Summary of the problem

We had this field but it did nothing!

## Describe your changes

Now values inputted will be saved in the recurring donation record and they should be emailed out. Do we only want to email messages once? I feel like we should and can edit this PR to do that.

2023-12-01 21:46 UTC, sampoder commented
(ignore those schema changes I'll fix them quickly when my laptop gets some juice in it)

2023-12-02 01:43 UTC, cjdenio requested changes
Great start! I agree that messages should only be sent for the first donation— you can use `Donation#initial_recurring_donation?` to check

2023-12-02 05:41 UTC, sampoder commented on app/models/donation.rb
> +    elsif includes_message? && (initial_recurring_donation? || !recurring?)
@cjdenio that should do this! is there a cleaner way you can think of?

2023-12-21 21:05 UTC, garyhtou commented on app/models/donation.rb
Let's remove the changes from this file and include the message here:

https://github.com/hackclub/bank/blob/6ea51d0675f51ed73409a7e185afc5f6f284a816/app/services/recurring_donation_service/handle_invoice_paid.rb#L10-L19

Only include the message if it's the first donation

2023-12-21 21:07 UTC, garyhtou commented on app/models/donation.rb
This is because ideally, `Donation` shouldn't know much about `RecurringDonation`.

2024-01-10 03:42 UTC, garyhtou commented on app/models/donation.rb
addressed

2024-01-10 03:44 UTC, garyhtou approved these changes
I think this should be good to go now! please sanity check it first (I haven't tested it)

2024-01-10 03:52 UTC, merged