Small Bugs
hackclub/hcb pull request #462
Opened 2020-01-19 00:13 UTC by tmb

Closes #457, #451, #454

2020-01-19 04:37 UTC, thesephist requested changes
Couple minor requests, but otherwise lit.

2020-01-19 04:37 UTC, thesephist commented on app/models/transaction.rb
> +    self.includes(:fee_relationship).where.not(fee_relationships: { event_id: 183 }).sum('@amount').to_i
Let's add a comment here to explain why we're using this number 183. Otherwise it's just a magic number that someone else reading the code in the future will get super confused by.

ORRrrrr

Another way to write code here that documents itself / the intent here correctly would be to do something like this:

```ruby
hq_event_id = 183
transactions_not_for_hq = self.includes(:fee_relationship).where.not(fee_relationships: { event_id: hq_event_id })
transactions_not_for_hq.sum('@amount').to_i
```

This way, we express exactly what we intend to do here without any comments, and there's no risk of future readers getting confused.

2020-01-19 04:37 UTC, thesephist commented on app/models/transaction.rb
> +      .where(["transactions.created_at > ? and transactions.created_at < ?", start_time, end_time])
Same point applies as above. I think we can just define a variable here or a global constant that's `HQ_EVENT_ID` and reference that instead of a hard-coded in number that can be cryptic later.

2020-01-19 04:37 UTC, thesephist commented on app/views/card_requests/_form.html.erb
> +        { required: true }
Can you shed some light on why this works this way? I'm a little confused by why this now works but didn't before.

2020-01-19 18:17 UTC, lachlanjc commented on app/views/card_requests/_form.html.erb
> +        { required: true }
Check the HTML, but I don’t think this will actually solve the issue. You need “Select state” to have `disabled`, or it’s a valid option to submit the form with, so even if `required` is rendered it is circumvented by the default option.

2020-01-20 04:27 UTC, tmb commented on app/views/card_requests/_form.html.erb
> +        { required: true }
It seems to work fine as is.. prompts the user to select a state if "Select state" is selected.

2020-01-20 04:28 UTC, merged