Waive all fees collected on refunded donations
hackclub/hcb pull request #4666
Opened 2023-12-09 20:58 UTC by sampoder

WIP because I want to test, what'd be a good way of testing?

2023-12-10 05:52 UTC, cjdenio commented
Do we want to do this from an operational standpoint? Stripe doesn't waive fees when we refund a payment

2023-12-10 07:04 UTC, sampoder commented
Not sure, there was an open issue, I was playing around

2023-12-13 17:13 UTC, rluodev commented
@hackliv Would this be something that we'd want to do?

2023-12-13 18:37 UTC, sampoder commented
For reference, here's the issue #2093

2023-12-14 15:17 UTC, hackliv commented
If there is a way to do this automatically, then yes, would be great for Ops to not have to worry about!

2023-12-14 15:18 UTC, hackliv commented
I will share though that I'd prefer prioritizing instant fee waive/un-waive on pending disbursements over this though if you all are starting a dive into bug fixes for fees!

2024-01-03 20:16 UTC, garyhtou commented on app/services/donation_service/refund.rb
> +          fee = ct.canonical_event_mapping.fees.first
this line may need to be updated due to https://github.com/hackclub/hcb/pull/4773

2024-01-03 20:16 UTC, garyhtou commented on app/services/donation_service/refund.rb
> +
```suggestion
```

2024-01-03 20:27 UTC, sampoder commented on app/services/donation_service/refund.rb
> +          fee = ct.fee
@garyhtou does that work?

2024-01-03 20:46 UTC, cjdenio requested changes
https://github.com/hackclub/hcb/blob/13576eb84d5ff7bf7436bec1600c95869c8df91b/app/services/fee_engine/create.rb also needs to be updated for when a CanonicalTransaction comes in _after_ the donation is refunded

2024-01-03 23:00 UTC, garyhtou commented on app/services/donation_service/refund.rb
> +          fee = ct.fee
i believe so

2024-01-04 08:48 UTC, sampoder commented on app/services/fee_engine/create.rb
> +      reason = "REFUNDED" if canonical_transaction.donation&.refunded?
@cjdenio would this do the trick?

2024-01-04 20:32 UTC, cjdenio commented on app/services/fee_engine/create.rb
> +      reason = "REFUNDED" if canonical_transaction.donation&.refunded?
`CanonicalTransaction#donation`, unintuitively, doesn't work for modern donations

```suggestion
      reason = "DONATION REFUNDED" if canonical_transaction.local_hcb_code.donation&.refunded?
```

2024-01-04 20:35 UTC, sampoder commented on app/services/fee_engine/create.rb
> +      reason = "REFUNDED" if canonical_transaction.donation&.refunded?
Oh neat good catch

2024-01-04 22:00 UTC, cjdenio approved these changes

2024-01-04 22:22 UTC, merged