Add signee status toggle in users list
hackclub/hcb pull request #4704
Opened 2023-12-12 06:48 UTC by rluodev

Also added link to org documents in deletion request card.

This closes issues #4699 and #4694.

<img width="525" alt="Screenshot 2023-12-11 at 10 48 27 PM" src="https://github.com/hackclub/hcb/assets/34289582/2018ede0-9e1f-4161-af57-e230d0728ed4">

![image](https://github.com/hackclub/hcb/assets/34289582/4f614030-a024-4993-b0de-b0dd92218668)

2023-12-12 08:03 UTC, sampoder requested changes
tested locally, works like a charm! a couple of quick comments from me

2023-12-12 08:03 UTC, sampoder commented on app/views/events/_organization_position_invite.html.erb
>            <span>No contract signature</span>
```suggestion
          <span>No contract signature</span>
          <%= link_to "(toggle)", toggle_signee_status_organizer_path(position.id), data: { turbo_method: "post", turbo_frame: "_top" } %>
```
thoughts on moving the toggle up here? feels weird to have two separate items in the list related to contract signature.

2023-12-12 08:03 UTC, sampoder commented on app/views/events/_organization_position_invite.html.erb
> +        <%= link_to "Toggle contract signature status", toggle_signee_status_organizer_path(position.id), data: { turbo_method: "post", turbo_frame: "_top" } %>
```suggestion
      <div>
        <% if position.signee? %>
          <%= inline_icon "checkmark", size: 20, style: "vertical-align: middle; margin: -0.2rem 0.5rem 0 0;" %>
        <% else %>
          <%= inline_icon "checkbox", size: 20, style: "vertical-align: middle; margin: -0.2rem 0.5rem 0 0;" %>
        <% end %>
        <%= link_to "Toggle contract signature status", toggle_signee_status_organizer_path(position.id), data: { turbo_method: "post", turbo_frame: "_top" } %>
      </div>
```
closing tag :D

2023-12-12 12:16 UTC, sarthaktexas commented
Two things since you're already working on the card:
1. Could we fix the UI of the organizer being deleted? Just make it more clear who's being deleted.

2. Could we add a direct download link to the Fiscal Sponsorship Agreement?

2023-12-12 12:19 UTC, sarthaktexas requested changes
Above comments.

2023-12-12 14:35 UTC, hackliv commented
I assume this would be a feature going forward since it might take too much time to edit that for every existing user currently. Can we create another issue where when someone requests a user deletion they have to check a box indicating whether the user is a contract signee?

2023-12-12 14:35 UTC, hackliv approved these changes

2023-12-12 16:48 UTC, rluodev commented
> Two things since you're already working on the card:
> 
> 1. Could we fix the UI of the organizer being deleted? Just make it more clear who's being deleted.
> 2. Could we add a direct download link to the Fiscal Sponsorship Agreement?

1 is done, not sure how to do 2 tbh

2023-12-12 16:49 UTC, rluodev commented
also I think one of you needs to review as hcb-engineers

2023-12-12 16:56 UTC, cjdenio commented on app/controllers/organizer_positions_controller.rb
> +    end
```suggestion
    organizer_position.toggle!(:is_signee)
```

2023-12-12 16:56 UTC, cjdenio commented on config/routes.rb
> +  resources :organizer_positions, only: [:destroy, :toggle_signee_status], as: "organizers" do
```suggestion
  resources :organizer_positions, only: [:destroy], as: "organizers" do
```

2023-12-12 18:31 UTC, sarthaktexas commented
@Soar1826 In the future, always keep the top-most comment updated.
This is what the admin side looks like now:
<img width="537" alt="image" src="https://github.com/hackclub/hcb/assets/28282096/2257fb1c-6f86-41cf-9e60-ac71a16bdfc1">

I also get this error on testing, presumably from Caleb's change in `routes.rb`:
![image](https://github.com/hackclub/hcb/assets/28282096/b7572454-586c-4655-a08c-b997b3c71306)

2023-12-12 18:41 UTC, sarthaktexas requested changes
Above.

2023-12-12 19:34 UTC, rluodev commented
My laptop is dead and I’m editing code on my phone on GitHub. @sarthaktexas can you check if that new commit fixed it?

2023-12-12 20:06 UTC, cjdenio commented
@sarthaktexas you'll need to have Turbo enabled in your dev environment for the link to work (since it relies on `data-turbo-method`). (http://localhost:3000/my/settings/previews)

2023-12-13 02:08 UTC, rluodev commented
@sarthaktexas @cjdenio @sampoder This should be good to go.

2023-12-13 04:53 UTC, sarthaktexas commented
Hey! I can't approve this without trying it first so give me tomorrow to figure out how to enable Turbo. Great work!

2023-12-13 06:40 UTC, sampoder approved these changes
Code looks good to me - thanks for the great work on this Ruien!

2023-12-13 17:45 UTC, sarthaktexas approved these changes
Just like Sam said, works like a charm once Turbo is on! Great work :)

2023-12-13 17:45 UTC, sarthaktexas commented on app/views/events/_organization_position_invite.html.erb
> +        <%= link_to "(toggle)", toggle_signee_status_organizer_path(position.id), data: { turbo_method: "post", turbo_frame: "_top" } %>
Will this create a problem if an admin is not on Turbo? Or are all admins on Turbo?

2023-12-13 17:45 UTC, sarthaktexas commented on app/views/events/_organization_position_invite.html.erb
> +        <%= link_to "(toggle)", toggle_signee_status_organizer_path(position.id), data: { turbo_method: "post", turbo_frame: "_top" } %>
This might be a question for @cjdenio

2023-12-13 17:46 UTC, rluodev commented on app/views/events/_organization_position_invite.html.erb
> +        <%= link_to "(toggle)", toggle_signee_status_organizer_path(position.id), data: { turbo_method: "post", turbo_frame: "_top" } %>
Turbo is a feature enabled for everyone on prod now.

2024-01-01 02:43 UTC, garyhtou commented on app/views/events/_organization_position_invite.html.erb
> +        <%= link_to "(toggle)", toggle_signee_status_organizer_path(position.id), data: { turbo_method: "post", turbo_frame: "_top" } %>
Let's make it a bit harder to accidentally toggle this

```suggestion
        <%= link_to "(toggle)", toggle_signee_status_organizer_path(position.id), data: { turbo_method: "post", turbo_frame: "_top", turbo_confirm: "Are you sure you want to toggle #{position.user.name}'s contract signee status?" } %>
```

2024-01-01 02:43 UTC, garyhtou approved these changes

2024-01-01 02:46 UTC, merged