Ignore Chrome Extension Errors in Airbrake
hackclub/hcb pull request #4705
Opened 2023-12-12 07:06 UTC by rluodev

I think this fixes #4667, but I have no way of testing it. Added a filter in `/config/initializers/airbrake.rb` to filter out anything that starts with `chrome-extension://`, but since I don't think I have access to airbrake I can't test this.

2023-12-12 08:05 UTC, sampoder commented on config/initializers/airbrake.rb
> +  end
```suggestion
  notice.ignore! if notice[:errors].any? { |error| error[:file].start_with?("chrome-extension://") }
```

I believe in Ruby we can just write this which is shorter (and cooler?)

2023-12-12 15:14 UTC, cjdenio requested changes
Great start! Since these errors are reported by the JavaScript frontend, a filter has to be added in `app/javascript/airbrake.js`:
https://github.com/hackclub/hcb/blob/8c9d91d290d60d9ff56924a9ed09abeb38e0248b/app/javascript/airbrake.js#L14-L17

2023-12-12 19:23 UTC, sampoder commented on config/initializers/airbrake.rb
```suggestion


```

add back that line

2023-12-13 02:02 UTC, rluodev commented
@cjdenio @garyhtou I think this is good to go

2023-12-13 06:40 UTC, sampoder approved these changes
LGTM

2023-12-13 22:57 UTC, garyhtou commented
@cjdenio did you want to review this one? no worries if you're short on capacity

2023-12-14 17:08 UTC, cjdenio commented on app/javascript/airbrake.js
> +  if (notice.errors.some((error) => error.file.startsWith('chrome-extension://'))) return null;
```suggestion
  if (
    notice.errors
      .flatMap(e => e.backtrace)
      .some(e => e.file?.startsWith('chrome-extension://'))
  )
    return null
```

`Error` objects don't have a `file`, but they have `Backtraces` that do

2023-12-14 17:09 UTC, cjdenio approved these changes

2023-12-14 17:11 UTC, merged