Make it possible to void invoices
hackclub/hcb pull request #4720
Opened 2023-12-13 01:27 UTC by rluodev

This adds the ability to void an invoice and adds sorting options on both admin- and user-side to sort and view these voided invoices.

Once merged, this will close #4711.

Voided invoice

<img width="925" alt="Screenshot 2023-12-13 at 9 01 18 AM" src="https://github.com/hackclub/hcb/assets/34289582/85f2bfa8-1e8f-44d2-b2f3-551fc165fb4e">
paid invoice with void button disabled

<img width="1082" alt="Screenshot 2023-12-12 at 5 25 35 PM" src="https://github.com/hackclub/hcb/assets/34289582/b0d84521-c2e3-4f0e-8c5f-54a404cb4698">
sent invoice with void button

<img width="1082" alt="Screenshot 2023-12-12 at 5 25 54 PM" src="https://github.com/hackclub/hcb/assets/34289582/de336da6-7fe4-4771-a3da-792945c15f1f">

<img width="1501" alt="Screenshot 2023-12-12 at 5 23 52 PM" src="https://github.com/hackclub/hcb/assets/34289582/cc41488e-6200-4d2e-8b00-ea55f313d211">

<img width="1082" alt="Screenshot 2023-12-12 at 5 26 56 PM" src="https://github.com/hackclub/hcb/assets/34289582/51c68b32-737b-4f6b-9472-a796fd8462b3">

2023-12-13 01:30 UTC, sarthaktexas commented
by rawr???

2023-12-13 01:37 UTC, rluodev commented
> by rawr???

that's just what I could think of

2023-12-13 04:48 UTC, sarthaktexas requested changes
Could I get captions on the images in the PR description? Specifically, the first few because I cannot tell the difference.

2023-12-13 04:52 UTC, sarthaktexas commented
Also, I cannot approve this until I test it locally, so you'll have to wait until tomorrow for an approval review. I've reviewed your code and have some comments. I will submit a review tomorrow when I have a pair of fresh morning eyes. I love the feature!

2023-12-13 07:57 UTC, sampoder reviewed
Couple of comments from me. Main thing is that I think we should be using `.void_v2` instead of creating a separate `.voided`.

2023-12-13 07:57 UTC, sampoder commented on app/views/hcb_codes/_invoice.html.erb
> +      class: "btn bg-error mr1 right" %>
```suggestion
    <%= link_to "Void this invoice",
      invoice_void_path(@invoice.id),
      disabled: !organizer_signed_in? || @invoice.voided? || @invoice.paid_v2?,
      method: :post,
      data: { confirm: "Are you sure you want to void this invoice? This action cannot be undone." },
      class: "btn bg-error mr1 right" unless @invoice.paid_v2? || @invoice.voided?  %>
```

Let's hide this button if the invoice is paid or already voided, reduces clutter imo.

2023-12-13 07:57 UTC, sampoder commented on app/views/hcb_codes/_invoice.html.erb
> +      data: { confirm: "Are you sure you want to void this invoice? This action cannot be undone." },
```suggestion
      data: { confirm: "Are you sure you want to void this invoice? Voided invoices can not be paid and this action cannot be undone." },
```

Let's be super clear with folks about what this button does.

2023-12-13 07:57 UTC, sampoder commented on app/views/hcb_codes/_invoice.html.erb
> +<% elsif @invoice.archived? %>
Can an invoice be both voided and archived? It seems like I can still archive voided invoices. Do we want to support this?

2023-12-13 07:57 UTC, sampoder commented on app/models/invoice.rb
> +
Let's continue using `void_v2?`. Afaik `mark_void!` should lead to `void_v2?` returning true.

2023-12-13 07:57 UTC, sampoder commented on app/controllers/admin_controller.rb
> +    relation = relation.open_v2.excluding(relation.voided) if @open
```suggestion
    relation = relation.open_v2 if @open
```
When we void a invoice they should transition to the `void_v2` state and therefore not be open. Were you observing that when testing this?

2023-12-13 07:57 UTC, sampoder commented on app/controllers/admin_controller.rb
> +    relation = relation.voided if @voided
```suggestion
    relation = relation.void_v2 if @voided
```

2023-12-13 07:57 UTC, sampoder commented on app/controllers/invoices_controller.rb
> +      relation = relation.voided
```suggestion
      relation = relation.void_v2
```

2023-12-13 16:46 UTC, rluodev commented on app/controllers/admin_controller.rb
> +    relation = relation.open_v2.excluding(relation.voided) if @open
Yeah, while testing, I had to use .excluding in order to get it to actually exclude voided ones. not sure why.

2023-12-13 16:47 UTC, rluodev commented on app/views/hcb_codes/_invoice.html.erb
> +<% elsif @invoice.archived? %>
I mean it doesn't change anything visually aside from the invoice archive button changing between archive and unarchive, so I think we can just hide the archive button once voided? Will push a change for this.

2023-12-13 16:53 UTC, rluodev commented on app/models/invoice.rb
> +
Done!

2023-12-13 17:00 UTC, rluodev commented
@sampoder re: the void_v2 thing - it only works for *some* invoices, apparently, and the voided? call is a much more reliable way to keep track of voided status since we keep a record on our end of when the invoice was voided ~~instead of asking stripe, "hey is this void" and maybe not receiving back a correct response.~~

wait no i totally assumed that void_v2 was a call to stripe but anyway it still doesn't always work.

2023-12-13 18:33 UTC, sampoder commented on app/controllers/admin_controller.rb
> +    relation = relation.open_v2.excluding(relation.voided) if @open
Were you running `.mark_void!`?

2023-12-13 18:34 UTC, sampoder commented
@Soar1826 how are you testing this locally? I'd like to pull it up on my computer and investigate.

2023-12-13 19:09 UTC, rluodev commented on app/controllers/admin_controller.rb
> +    relation = relation.open_v2.excluding(relation.voided) if @open
yep, 
<img width="485" alt="Screenshot 2023-12-13 at 11 08 10 AM" src="https://github.com/hackclub/hcb/assets/34289582/111d019d-08b7-4df1-95c6-8b678cf94e72">

2023-12-13 19:16 UTC, rluodev commented
wait no nvm it was a weird thing that happened to one invoice on my end

2023-12-13 19:16 UTC, rluodev commented
void_v2 works fine

2023-12-15 00:12 UTC, sampoder commented
Oh hell yeah!

2023-12-15 00:14 UTC, sampoder commented on app/controllers/admin_controller.rb
> +    relation = relation.open_v2.excluding(relation.void_v2) if @open
```suggestion
    relation = relation.open_v2 if @open
```
I believe it's implied that `open_v2` invoices are not `void_v2`

2023-12-15 00:22 UTC, sampoder requested changes
Couple from me! Looking really good.

2023-12-15 00:22 UTC, sampoder commented on app/services/invoice_service/void.rb
In the same way we have `MarkPaid`, let's have `MarkVoid` instead of just `Void`.

2023-12-15 00:22 UTC, sampoder commented on app/controllers/invoices_controller.rb
> +    @invoice.voided_by = current_user
Would it make sense to move this into the service? Feels more in line with what we do on `MarkPaid`

2023-12-15 00:22 UTC, sampoder commented on app/views/hcb_codes/_invoice.html.erb
> +<% elsif @invoice.archived? %>
I could archive an invoice and then void it, should we display that in any way?

2023-12-15 00:22 UTC, sampoder commented on app/views/hcb_codes/_invoice.html.erb
> +    <% end %>
```suggestion
    <%= link_to "Void this invoice",
      invoice_void_path(@invoice.id),
      disabled: !organizer_signed_in? || @invoice.void_v2? || @invoice.paid_v2?,
      method: :post,
      data: { confirm: "Are you sure you want to void this invoice? Voided invoices can not be paid and this action cannot be undone." },
      class: "btn bg-error mr1 right"unless @invoice.void_v2? || @invoice.paid? %>
  <%= link_to (@invoice.archived? ? "Un-archive" : "Archive"),
    (@invoice.archived? ? invoice_unarchive_path(@invoice) : invoice_archive_path(@invoice)),
    disabled: !organizer_signed_in?,
    method: :post,
    class: "btn bg-muted" unless @invoice.void_v2? %>
```

Test this rq but I think this is valid and imo cleaner

2023-12-15 00:24 UTC, rluodev commented on app/views/hcb_codes/_invoice.html.erb
> +<% elsif @invoice.archived? %>
The general idea is that voiding takes precedence - you can't archive after voiding, so it makes no sense to show something as archived when the void tab does the same thing and only shows voided like how archived only shows archived.

2023-12-15 00:25 UTC, rluodev commented on app/views/hcb_codes/_invoice.html.erb
> +    <% end %>
I feel like we do want to hide the button to archive as well when voided, doesn't really make sense to void and then archive.

2023-12-15 00:26 UTC, sampoder commented on app/views/hcb_codes/_invoice.html.erb
> +<% elsif @invoice.archived? %>
That makes sense to me; thanks for clarifying! Just to sanity check, after we "void" an archived invoice does it show up as "archived" anywhere?

2023-12-15 00:27 UTC, rluodev commented on app/services/invoice_service/void.rb
done!

2023-12-15 00:27 UTC, sampoder commented on app/views/hcb_codes/_invoice.html.erb
> +    <% end %>
Oh yes, that's my bad! I intended for that to be the case. Let me quickly fix my suggestion.

2023-12-15 00:27 UTC, sampoder commented on app/views/hcb_codes/_invoice.html.erb
> +    <% end %>
Fixed, sorry

2023-12-15 00:27 UTC, rluodev commented on app/controllers/invoices_controller.rb
> +    @invoice.voided_by = current_user
I was doing it in-line with the other actions in invoice controller, like archive, etc.

2023-12-15 00:28 UTC, rluodev commented on app/views/hcb_codes/_invoice.html.erb
> +    <% end %>
thanks! also, one more thing: shouldn't `unless @invoice.void_v2? && @invoice.paid?` be `unless @invoice.void_v2? or @invoice.paid?`?

2023-12-15 00:29 UTC, rluodev commented on app/views/hcb_codes/_invoice.html.erb
> +<% elsif @invoice.archived? %>
No, the status are all listed as void I believe, will test tho.

2023-12-15 00:31 UTC, rluodev commented on app/views/hcb_codes/_invoice.html.erb
> +<% elsif @invoice.archived? %>
yep, they all show as void.

2023-12-15 00:39 UTC, sampoder commented on app/views/hcb_codes/_invoice.html.erb
> +<% elsif @invoice.archived? %>
Perfect!

2023-12-15 18:14 UTC, rluodev commented on app/views/hcb_codes/_invoice.html.erb
> +    <% end %>
@sampoder

2023-12-18 19:26 UTC, sampoder commented on app/views/hcb_codes/_invoice.html.erb
> +    <% end %>
Yes, though use `||`

2023-12-18 19:27 UTC, sampoder commented on app/controllers/invoices_controller.rb
> +    @invoice.voided_by = current_user
Let's move it into the service, that way we can reuse the service and it'll be consistent

2023-12-22 04:14 UTC, sampoder approved these changes
Awesome, LGTM!

2024-01-10 05:22 UTC, garyhtou requested changes

2024-01-10 05:22 UTC, garyhtou commented on app/models/invoice.rb
> +  scope :voided, -> { where.not(voided_at: nil) }
Technically using `voided_at` works! However, when using AASM, this code pattern of using `*_at` to determine state can be buggy. Here's why!

Let's say an Invoice goes from `open` -> `paid`. Each state transition usually involves setting a timestamp (e.g. `opened_at`, and `paid_at`). We'd expect `where.not(opened_at: nil)` to give us a list of `open` invoices, however, this actually gives us a list of invoices that were _open at some point_. This is because state transitions do not clear the timestamps of other states.

In this specific case, it works fine because `void` is a terminal state. Once it's voided, there is no other state it could transition to.

To prevent possible bugs like these in the future, let's switch it to using the `aasm_state` column for determining state.

```suggestion
  scope :voided, -> { where(aasm_state: "void_v2") }
```

---

Also, I just wanted to mention that AASM automatically provides scopes. In this case, our `voided` scope is the exact same as AASM's provided `void_v2` scope.

2024-01-10 05:22 UTC, garyhtou commented on app/views/hcb_codes/_invoice.html.erb
> +      disabled: !organizer_signed_in? || @invoice.void_v2? || @invoice.paid_v2?,
Since we have `unless @invoice.void_v2? || @invoice.paid?` on line 153, I think it might not be needed

```suggestion
      disabled: !organizer_signed_in?,
```

2024-01-10 05:22 UTC, garyhtou commented on app/views/hcb_codes/_invoice.html.erb
> +      class: "btn bg-error mr1 right" unless @invoice.void_v2? || @invoice.paid? %>
I see that we're also checking for `deposited?` on line 51. I'm actually not sure if this is necessary; but imma assume it is 🤷‍♂️ (it's tough to say because the state management in this model needs some work)

```suggestion
      class: "btn bg-error mr1 right" unless @invoice.void_v2? || @invoice.deposited? || @invoice.paid? %>
```

2024-01-10 05:22 UTC, garyhtou commented on app/views/hcb_codes/_invoice.html.erb
> +    class: "btn bg-muted" unless @invoice.void_v2? %>
It seems like the intention is to not allow `void` -> `archive`. However, at the moment, it's possible to `void` a previously archived invoice (and it'd be in both states!). Is that intentional?

The void button is visible for archived invoices.

2024-01-10 05:22 UTC, garyhtou commented on app/services/invoice_service/mark_void.rb
> +      invoice.save
Three edits:
1. Wrap in a database transaction. If anything fails, it will rollback changes; this way invoices aren't partially voided.
2. use `close_stripe_invoice` which is already defined. You'll need to make `close_stripe_invoice` a public method. If you'd like, feel free to give it a better name (e.g.`void_stripe_invoice`)
3. Use `save!`. If there is a validation error, I'll rollback the changes and show an error to the User

```suggestion
      Invoice.transaction do
        invoice.voided_at = DateTime.now
        invoice.voided_by = @user

        invoice.close_stripe_invoice
        invoice.mark_void!

        invoice.save!
      end
```

2024-01-10 05:22 UTC, garyhtou commented on app/controllers/invoices_controller.rb
> +      relation = relation.unpaid.excluding(relation.void_v2)
We should update the `unpaid` and `archived` scope rather than excluding voided invoices here

2024-01-10 16:57 UTC, rluodev commented on app/views/hcb_codes/_invoice.html.erb
> +    class: "btn bg-muted" unless @invoice.void_v2? %>
Yep, this is intentional, as the invoice can be possibly archived and then voided, at which point it will just show up solely in the voided tab

2024-01-18 05:38 UTC, rluodev commented on app/controllers/invoices_controller.rb
> +      relation = relation.unpaid.excluding(relation.void_v2)
fixed!

2024-01-20 00:34 UTC, sarthaktexas approved these changes
lgtm great job

2024-02-02 06:29 UTC, garyhtou commented on app/services/invoice_service/mark_void.rb
> +        invoice.mark_void!
Let's do `mark_void!` before `close_stripe_invoice`. This is because we can rollback `mark_void!`. But we can't rollback `close_stripe_invoice` since it's an API call to Stripe

```suggestion
        invoice.mark_void!
        invoice.close_stripe_invoice
```

2024-02-02 06:32 UTC, garyhtou commented on app/services/invoice_service/mark_void.rb
> +        invoice.voided_by = @user
Add `timestamp: true` to the `aasm do` block in the model. AASM will then automatically set the timestamp.

https://github.com/aasm/aasm#timestamps




You can also add a parameter to the AASM transition to take in a user.
See this as an example: https://github.com/hackclub/bank/blob/945eadcce352b789331b3058a8fe1de55e8c727a/app/models/disbursement.rb#L117-L123

2024-02-14 17:35 UTC, sarthaktexas approved these changes

2024-02-29 00:19 UTC, garyhtou reviewed
looks good, just a couple small things then good to merge

2024-02-29 00:19 UTC, garyhtou commented on app/controllers/invoices_controller.rb
> +    ::InvoiceService::MarkVoid.new(invoice_id: params[:invoice_id], user: current_user).run
```suggestion
    ::InvoiceService::MarkVoid.new(invoice_id: @invoice.id, user: current_user).run
```

2024-02-29 00:19 UTC, garyhtou commented on app/views/hcb_codes/_invoice.html.erb
> +    <% unless @invoice.paid_v2? or @invoice.deposited? or @invoice.void_v2? %>
i _think_ this does the same? i'm not confident about this change
```suggestion
    <% if @invoice.open_v2? %>
```

2024-02-29 00:19 UTC, garyhtou commented on app/views/hcb_codes/_invoice.html.erb
> +      class: "btn bg-error mr1 right" unless @invoice.void_v2? || @invoice.deposited? || @invoice.paid? %>
maybe this works
```suggestion
      class: "btn bg-error mr1 right" if @invoice.open_v2? %>
```

2024-03-01 04:02 UTC, merged