Admin: User information page
hackclub/hcb pull request #4798
Opened 2023-12-19 07:25 UTC by devramsean0

## Summary of the problem

This completes Gary's request in #4651 by adding a more complete page to see any relevant information about a user

## Describe your changes

I decided to use the admin controller for this page as I concluded it's an admin page, so it's protected by that authentication level, It also appears to take an id parameter for all its routes too.
I then searched each model using the user ID. and put that information in a table so that it only shows if the user has 1 of those transactions/cards

![image](https://github.com/hackclub/hcb/assets/81807361/617c1879-8841-4301-a28a-6b4adc2d19b8)

2023-12-19 23:36 UTC, sampoder commented on app/controllers/admin_controller.rb
> +    @donations = Donation.where(email: @user.email) # Probably not the best way to fetch this but I don't have any other ideas
Does it make sense for these to be displayed? These aren't ever really actions taken by the user on HCB.

2023-12-20 17:56 UTC, devramsean0 commented on app/controllers/admin_controller.rb
> +    @donations = Donation.where(email: @user.email) # Probably not the best way to fetch this but I don't have any other ideas
I think it makes sense to show the Invoices that a user has created, not sure if donations make sense though.

2023-12-20 18:38 UTC, sampoder commented on app/controllers/admin_controller.rb
> +    @donations = Donation.where(email: @user.email) # Probably not the best way to fetch this but I don't have any other ideas
Agree with displaying invoices, but I think we can scrap donations.

2023-12-21 17:44 UTC, devramsean0 commented on app/controllers/admin_controller.rb
> +    @donations = Donation.where(email: @user.email) # Probably not the best way to fetch this but I don't have any other ideas
Yeah, I agree. I've now removed it

2024-01-17 20:06 UTC, sarthaktexas approved these changes
Approved! Tried it on my side and worked like a charm. I did not try LOB Checks.

2024-01-17 20:22 UTC, sampoder commented on app/views/admin/user_information.html.erb
> +<h1>Information for <%= @user.full_name %></h1>
Do we still want this page? Sorry I'm not caught up on this PR. Are we adding the information to both places?

2024-01-18 06:57 UTC, devramsean0 commented on app/views/admin/user_information.html.erb
> +<h1>Information for <%= @user.full_name %></h1>
Adding it to both places seems excessive (and hardish to maintain)
I'll remove the new page

2024-01-31 06:43 UTC, garyhtou requested changes

2024-01-31 06:43 UTC, garyhtou commented on config/routes.rb
> +      get "user", to: "admin#user_information"
I think this is no longer being used

2024-01-31 06:43 UTC, garyhtou commented on app/views/users/edit_admin.html.erb
> +        <% end %>
Currently, it is not possible for this data to be shown because the instance variables are never defined.

For example, `@invoice` is never defined

2024-01-31 07:20 UTC, devramsean0 commented on app/views/users/edit_admin.html.erb
> +        <% end %>
Ack, I must have forgotten to add those in when we changed the page it's on

2024-02-03 04:13 UTC, garyhtou commented on app/controllers/users_controller.rb
> +    @lob_checks = Check.where(creator_id: @user.id)
One cool thing about Rails is that you don't need to explicitly pass the id!

```suggestion
    @invoices = Invoice.where(creator: @user)
    @check_deposits = CheckDeposit.where(created_by: @user)
    @increase_checks = IncreaseCheck.where(user: @user)
    @lob_checks = Check.where(creator: @user)
```

2024-02-03 04:13 UTC, garyhtou commented on app/views/users/edit_admin.html.erb
> +        <% end %>
all good!

2024-02-03 04:13 UTC, garyhtou commented on app/views/users/edit_admin.html.erb
> +        <% end %>
It looks like we're still missing `@ach_transfer` and `@disbursement`

2024-02-15 22:51 UTC, devramsean0 commented
closes #4651

2024-02-26 19:05 UTC, garyhtou commented on app/views/users/edit_admin.html.erb
> +        <% if @checks_deposited.present? %>
```suggestion
        <% if @checks_deposits.present? %>
```

2024-02-26 19:05 UTC, garyhtou commented on app/views/users/edit_admin.html.erb
> +            <% @checks_deposited.each do |check| %>
```suggestion
            <% @checks_deposits.each do |check| %>
```

2024-02-26 19:17 UTC, garyhtou approved these changes
@sarthaktexas Please test by impersonating in prod after merging

2024-02-27 19:52 UTC, sarthaktexas requested changes

2024-02-27 19:52 UTC, sarthaktexas commented on app/views/users/edit_admin.html.erb
> +    <% if current_user.admin? %>
```suggestion
    <% if admin_signed_in? %>
```

2024-02-27 19:52 UTC, sarthaktexas approved these changes

2024-02-27 19:57 UTC, merged