Rebranding error pages
hackclub/hcb pull request #4814
Opened 2023-12-20 18:31 UTC by devramsean0

## Summary of the problem

This brings the error pages that are served on GitHub pages that are designed for when Heroku is having issues closer to the other error pages. (see #4563)

## Describe your changes

I went about recreating the [500 error page](https://hcb.hackclub.com/500.html) as closely as made sense (notice the lack of the second row in the footer, and the changelog icon among other small things)

![image](https://github.com/hackclub/hcb/assets/81807361/12f88d2a-de9d-4587-90e4-799b5b9c9347)
![image](https://github.com/hackclub/hcb/assets/81807361/4d65fb33-0c1a-4177-baf5-f7cf6cea944e)

2023-12-21 01:39 UTC, sampoder commented on app/controllers/admin_controller.rb
> +
@devramsean0 looks like a couple of changes form your other PR are in here, cool if they get removed?

2023-12-21 01:43 UTC, sampoder approved these changes
Looks wise, this looks good to me! It might be fun to hide some easter eggs in both of these pages but these do the job perfectly.

2023-12-21 06:03 UTC, aramshiva commented
no rickrolls :/ 
~~2/10 stars~~

2023-12-21 07:12 UTC, devramsean0 commented on app/controllers/admin_controller.rb
> +
Yeah...
Why does this always happen to me :(

2023-12-21 07:26 UTC, devramsean0 commented
I can't think of any interesting Easter eggs :/
Any ideas? bc that sounds fun

2024-01-09 03:59 UTC, garyhtou requested changes
Looks great! couple small changes

2024-01-09 03:59 UTC, garyhtou commented on docs/application-error.html
> +  '             Fira Sans', Oxygen, Ubuntu, 'Helvetica Neue', sans-serif;
Should this `'` be moved so there isn't leading whitespace in the string?

2024-01-09 03:59 UTC, garyhtou commented on docs/application-error.html
> +</html>
we always keep a newline at the end of files
```suggestion
</html>

```

2024-01-09 03:59 UTC, garyhtou commented on docs/maintenance-mode.html
> +</html>
```suggestion
</html>

```

2024-01-09 21:00 UTC, garyhtou approved these changes
Great!

2024-01-09 21:03 UTC, merged