Admin cards: Rename "FIRST Grants" to "Hackathon Grants"
hackclub/hcb pull request #4837
Opened 2023-12-22 18:46 UTC by aramshiva

Solves #4783. Renames all Hackathon Grants to remove FIRST's affilation on admin menu.

2023-12-22 18:57 UTC, sampoder commented on app/javascript/components/command_bar/CommandBar.js
>          (window.location.href = adminUrls["FIRST Grants"]),
Let's also update the admin URLs hash to use Hackathon Grants

2023-12-22 19:00 UTC, sampoder requested changes
Awesome! Could we also update the card on the homepage?

<img width="420" alt="Screenshot 2023-12-22 at 10 59 42 AM" src="https://github.com/hackclub/hcb/assets/39828164/175d9e19-e48a-498a-af0c-434bffcafb97">

2023-12-22 19:02 UTC, aramshiva commented on app/javascript/components/command_bar/CommandBar.js
>          (window.location.href = adminUrls["FIRST Grants"]),
oops my bad!

2023-12-22 19:07 UTC, sampoder approved these changes
LGTM!

2024-01-03 23:45 UTC, aramshiva commented
just fixed conflicts!

2024-01-04 00:51 UTC, garyhtou approved these changes
coolio! 1️⃣🤖

2024-01-04 00:54 UTC, merged