Don't report user-induced errors to AppSignal
hackclub/hcb pull request #4910
Opened 2024-01-04 22:36 UTC by northeastprince

## The Problem
Errors are getting reported that aren't actual issues on our end, like `RecordNotFound` or `InvalidCrossOriginRequest` errors.
## The Solution
Just don't report them in the first place!

2024-01-04 23:20 UTC, garyhtou approved these changes

2024-01-04 23:22 UTC, garyhtou requested changes

2024-01-04 23:22 UTC, garyhtou commented on config/appsignal.yml
> +    - ActiveRecord::RecordNotFound
We may want to report `RecordNotFound` in certain cases. Such as `RecordNotFound` in jobs. What are your thoughts?

2024-01-05 01:05 UTC, northeastprince commented on config/appsignal.yml
> +    - ActiveRecord::RecordNotFound
It's pretty standard to not report `RecordNotFound` errors, so if it means something went wrong if it occurs in a job, I think a different/more-specific exception should be raised.

2024-01-09 00:26 UTC, garyhtou commented on config/appsignal.yml
> +    - ActiveRecord::RecordNotFound
Let's report `ActiveRecord::RecordNotFound`. It can be indicative of a bug on our end

2024-01-09 00:26 UTC, garyhtou requested changes

2024-01-09 00:26 UTC, garyhtou commented on config/appsignal.yml
> +    - ActiveRecord::RecordNotFound
```suggestion
```

2024-01-11 16:58 UTC, northeastprince commented on config/appsignal.yml
> +    - ActiveRecord::RecordNotFound
Ok,  but then we'll have to change the notification settings as they pop up for controllers so we don't get notified for them after every deployment.

2024-01-11 18:29 UTC, garyhtou approved these changes

2024-01-11 18:29 UTC, garyhtou commented
>Ok, but then we'll have to change the notification settings as they pop up for controllers so we don't get notified for them after every deployment.

Yes! Let's do that! Can you see if you're able to configure that in AppSignal?

2024-01-11 18:31 UTC, merged