Keep track of personal transactions in the database
hackclub/hcb pull request #4913
Opened 2024-01-05 00:47 UTC by sampoder

## Summary of the problem

The whole system of commenting was janky. If we want to make this public we would want to do it better.

## Describe your changes

I made a join table in the database and starting using that to track things.

![image](https://github.com/hackclub/hcb/assets/20099646/03b40d9f-c685-47ad-8ee2-fbeaf5206909)

![image](https://github.com/hackclub/hcb/assets/20099646/5b4a184a-dc79-4ff1-9767-2cddb353b2fe)

2024-01-05 00:49 UTC, sampoder commented
This again is working towards https://github.com/hackclub/hcb/issues/4904

2024-01-05 00:50 UTC, sarthaktexas commented
me likey

2024-01-05 00:52 UTC, sarthaktexas commented on db/schema.rb
this is my favorite file in your pr

2024-01-05 00:52 UTC, sampoder commented
i'm glad you likey

> On 4 Jan 2024, at 5:50 PM, sarthak mohanty ☻ ***@***.***> wrote:
> 
> 
> me likey
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/hackclub/hcb/pull/4913#issuecomment-1877963778>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AJP3VRABKL45ZBAC7V7T2ETYM5E7BAVCNFSM6AAAAABBNW56Y6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNZXHE3DGNZXHA>.
> You are receiving this because you authored the thread.
>

2024-01-05 00:53 UTC, sampoder commented on db/schema.rb
this is by far my least favourite file.... it's a nightmare

2024-01-05 00:58 UTC, garyhtou reviewed
what are your thoughts on rephrasing it as `Repayment` rather than `Reimbursement`. I don't want people to get it confused with the usual reimbursement.

2024-01-05 00:58 UTC, garyhtou commented on app/controllers/hcb_codes_controller.rb
> +    invoice = ::InvoiceService::Create.new(
Move this into a `before_create` callback in `HcbCode::PersonalTransaction`

2024-01-05 01:27 UTC, sampoder commented
Repayment is a good word for it!

2024-01-05 02:34 UTC, northeastprince commented on app/models/hcb_code.rb
> +  has_one :personal_transaction, class_name: "HcbCode::PersonalTransaction", required: false
```suggestion
  has_one :personal_transaction, required: false
```

2024-01-05 02:34 UTC, northeastprince commented on app/models/hcb_code/personal_transaction.rb
> +    self.table_name = "hcb_code_personal_transactions"
```suggestion
    belongs_to :reviewer
```

2024-01-10 00:23 UTC, garyhtou requested changes
Great work! couple minor things

2024-01-10 00:23 UTC, garyhtou commented on app/controllers/hcb_codes_controller.rb
> +    result = HcbCode::PersonalTransaction.create(hcb_code_id: hcb_code.id, reporter_id: current_user.id)
No need to pass in the ID, Rails will automatically grab that from the object

```suggestion
    result = HcbCode::PersonalTransaction.create(hcb_code:, reporter: current_user)
```

2024-01-10 00:23 UTC, garyhtou commented on app/controllers/hcb_codes_controller.rb
> +    return render plain: "404 Not found", status: :not_found if !event&.hack_club_hq?
Let's move this logic into pundit.

```ruby
class HcbCodePolicy < ApplicationPolicy
  def invoice_as_personal_transaction?
    (user&.admin? || present_in_events?) && record.event&.hack_club_hq?
  end
end
```

2024-01-10 00:23 UTC, garyhtou commented on app/controllers/hcb_codes_controller.rb
> +    result = HcbCode::PersonalTransaction.create(hcb_code_id: hcb_code.id, reporter_id: current_user.id)
can we give `result` another name? maybe `personal_transaction` or `personal_tx`

2024-01-10 00:23 UTC, garyhtou commented on app/models/hcb_code/personal_transaction.rb
> +    before_validation :send_invoice, if: -> { invoice.nil? }
```suggestion
    after_create :send_invoice, if: -> { invoice.nil? }
```

2024-01-10 00:23 UTC, garyhtou commented on app/models/hcb_code/personal_transaction.rb
> +      self.invoice_id = invoice.id
Directly pass the service's output to `self.invoice=`

```suggestion
      self.invoice = ::InvoiceService::Create.new(
        event_id: event.id,
        due_date: 1.month.from_now,
        item_description: "Reimbursing personal transaction: #{hcb_code.memo}",
        item_amount: hcb_code.amount.abs,
        current_user: reporter,
        sponsor_id: nil,
        sponsor_name: spender.name,
        sponsor_email: spender.email,
        sponsor_address_line1: spender.stripe_cardholder.stripe_billing_address_line1,
        sponsor_address_line2: spender.stripe_cardholder.stripe_billing_address_line2,
        sponsor_address_city: spender.stripe_cardholder.stripe_billing_address_city,
        sponsor_address_state: spender.stripe_cardholder.stripe_billing_address_state,
        sponsor_address_postal_code: spender.stripe_cardholder.stripe_billing_address_postal_code,
        sponsor_address_country: spender.stripe_cardholder.stripe_billing_address_country
      ).run
```

2024-01-10 00:23 UTC, garyhtou commented on app/models/hcb_code/personal_transaction.rb
> +    belongs_to :hcb_code
Validate `hcb_code` is unique. We only want one `PersonalTransaction` per `HcbCode`

2024-01-10 00:23 UTC, garyhtou commented on app/views/hcb_codes/_accidental_misuse.html.erb
> +<% if local_assigns[:hcb_code].event&.hack_club_hq? && !local_assigns[:hcb_code].personal_transaction.present? %>
After moving the `hack_club_hq?` into pundit, we can use that here to conditionally render the partial.

```suggestion
<% if policy(local_asigns[:hcb_code]).invoice_as_personal_transaction? && local_assigns[:hcb_code].personal_transaction.nil? %>
```

https://github.com/varvet/pundit#:~:text=You%20can%20easily%20get%20a%20hold%20of%20an%20instance%20of%20the%20policy%20through%20the%20policy%20method%20in%20both%20the%20view%20and%20controller.%20This%20is%20especially%20useful%20for%20conditionally%20showing%20links%20or%20buttons%20in%20the%20view%3A

2024-01-10 20:18 UTC, sampoder commented on app/models/hcb_code/personal_transaction.rb
> +    before_validation :send_invoice, if: -> { invoice.nil? }
Making this change breaks things unfortunately: 

<img width="962" alt="Screenshot 2024-01-10 at 2 17 19 PM" src="https://github.com/hackclub/hcb/assets/39828164/a6568791-d0b6-49ff-b2e7-53d08fdeface">

2024-01-10 21:43 UTC, garyhtou commented on app/models/hcb_code/personal_transaction.rb
> +    before_validation :send_invoice, if: -> { invoice.nil? }
let's try
```suggestion
    before_validation :send_invoice, on: :create, if: -> { invoice.nil? }
```

2024-01-10 21:55 UTC, garyhtou approved these changes

2024-01-10 21:59 UTC, merged