Speed up general receipt upload box using Turbo Streams & Direct Uploads
hackclub/hcb pull request #4916
Opened 2024-01-05 09:41 UTC by sampoder

## Summary of the problem

This page was slow. For every single receipt you uploaded using the big general receipt upload box, it would have to reload the page.

## Describe your changes

Ian & I switched the process over to Turbo Streams, check it out:

https://github.com/hackclub/hcb/assets/39828164/ae6fde03-d5ab-4f41-b95f-657c23624c71

Here's what we've made async:

1. Deleting receipts from the receipt bin
2. Uploading receipts to receipt bin
3. Uploading receipts to specific transactions
4. Add a receipt to a transaction from the bin

2024-01-05 15:27 UTC, sarthaktexas submitted a review, later dismissed
works for me tank u sam and ian

2024-01-13 18:18 UTC, sampoder commented
Want to flag something that I just remembered: we haven't added Turbo Streams for receipt linking from the suggested pairing window. Fun.

2024-01-13 18:33 UTC, sampoder commented
Another edge case I want to flag with suggested pairings:

```
<% if pairing.hcb_code.canonical_transactions.any? %>
                      <% pairing.hcb_code.canonical_transactions.each do |ct| %>
                        <%= render partial: "canonical_transactions/canonical_transaction", locals: { ct:, force_display_details: true, hide_tags: true, show_event_name: true } %>
                      <% end %>
                    <% else %>
                      <% pairing.hcb_code.canonical_pending_transactions.each do |pt| %>
                        <%= render partial: "canonical_pending_transactions/canonical_pending_transaction", locals: { pt:, force_display_details: true, hide_tags: true, show_event_name: true } %>
                      <% end %>
                    <% end %>
```
We need to check the case where a transaction HAS a suggested pairing but a person uploads / links a receipt from the `Transactions` list, we need to make sure that this code (in `generate_streams`):

```
    if @receiptable
      if @receiptable.canonical_transactions&.any?
        @receiptable.canonical_transactions.each do |ct|
          streams.append(turbo_stream.replace(
                           ct.local_hcb_code.hashid,
                           partial: "canonical_transactions/canonical_transaction",
                           locals: { ct:, force_display_details: true, receipt_upload_button: true, show_event_name: true, updated_via_turbo_stream: true }
                         ))
        end
      else
        @receiptable.canonical_pending_transactions&.each do |pt|
          streams.append(turbo_stream.replace(
                           pt.local_hcb_code.hashid,
                           partial: "canonical_pending_transactions/canonical_pending_transactio",
                           locals: { pt:, force_display_details: true, receipt_upload_button: true, show_event_name: true, updated_via_turbo_stream: true }
                         ))
        end
      end
    end
```
Is replacing the transactions in the Transactions list and not in the suggested pairing window. At the moment, it replaces the transaction in the suggested pairing window.

2024-01-13 18:37 UTC, sampoder commented
To fix both of these issues, we need to write some Turbo stream code that once a receipt is linked / uploaded through whatever method (incl. the suggested pairing window) we remove any suggested pairs from the carousel. 

A couple things to think about: how do we keep the users current position in the carousel? Say they've clicked through 3 pairings and then accept the 4th, we don't want to then show them the first 3 again.

Lot's of interesting things to consider... _sigh_.

2024-01-13 23:45 UTC, sampoder commented on app/models/user.rb
> +                 .select { |pairing| pairing.hcb_code.needs_receipt? }
added this; do we want to be showing suggested pairings for transactions that already have a receipt? i thought we wouldn't. this will be a lot faster after #4888.

2024-02-02 02:46 UTC, garyhtou commented on app/models/user.rb
> +  def suggested_receipt_pairings
here's a refactor:

```ruby
# app/models/receipt_bin.rb
class ReceiptBin
  def initialize(user)
    @user = user
  end

  def suggested_receipt_pairings
    # blah blah blah code here
  end
end
```

```ruby
# app/models/user.rb
def receipt_bin
  ReceiptBin.new(self)
end
```

**Usage example:**
```ruby
User.first.receipt_bin.suggested_receipt_pairings
```

---

This concepts somewhat falls under the idea of using POROs (Plain Old Ruby Object)

2024-02-02 02:46 UTC, garyhtou commented on config/routes.rb
> +    get "suggested_pairings", to: "static_pages#suggested_pairings", as: :suggested_pairings
let's make the path: `/receipt_bin/suggested_pairings`

You can do this using a route `scope`

2024-02-02 02:46 UTC, garyhtou commented on db/schema.rb
unrelated

2024-02-02 02:46 UTC, garyhtou commented on app/models/user.rb
> +                 .select { |pairing| pairing.hcb_code.needs_receipt? }
ty

2024-02-02 03:38 UTC, sampoder commented on db/schema.rb
oops!

2024-02-29 22:42 UTC, garyhtou commented on app/models/receipt.rb
> +    ReceiptJob::SuggestPairings.perform_later(self)
pseudo code:
```suggestion
    if async_upload
      ReceiptJob::SuggestPairings.perform_later(self)
    else
      ReceiptJob::SuggestPairings.perform_now(self)
    end
```

2024-02-29 22:42 UTC, garyhtou commented on app/views/receipts/_form_v3.html.erb
> +            <img style="display: none;" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=" onload="let e = this.parentElement; $.
this is creative lol

2024-03-01 00:44 UTC, sarthaktexas commented on app/views/receipts/_form_v3.html.erb
> +            <img style="display: none;" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=" onload="let e = this.parentElement; $.
this is so funny

2024-03-19 19:36 UTC, cjdenio requested changes
https://github.com/hackclub/hcb/assets/34525547/8bafd4c5-934c-4acf-b80d-047678331d06

I can't get this to work at all

2024-03-19 19:36 UTC, cjdenio commented on app/models/user/receipt_bin.rb
> +    def suggested_receipt_pairings
Can this be a concern on `User`? I think `user.suggested_receipt_pairings` is simpler than `User::ReceiptBin.new(user).suggested_receipt_pairings`

2024-03-19 19:38 UTC, garyhtou commented on app/models/user/receipt_bin.rb
> +    def suggested_receipt_pairings
I believe user has a `receipt_bin` method. So usage looks like:

```ruby
user = User.find(1)
user.receipt_bin.suggested_receipt_pairings
```

It helps decouple receipt bin from user

2024-03-21 17:08 UTC, garyhtou commented
🪄 I just chatted with Caleb. Go ahead and test this really thoroughly and then merge it!

2024-03-21 20:47 UTC, merged