Donations summary page for events, add donation message, first donation mailer
hackclub/hcb pull request #492
Opened 2020-02-02 05:25 UTC by tmb

![image](https://user-images.githubusercontent.com/17188543/73603576-77eee080-4552-11ea-9458-b304af7a7c08.png)

Same as before, not totally sure where you want the `donation.message` field to go so I left it out

2020-02-02 15:28 UTC, lachlanjc commented
If you’re expecting them to be somewhat long sometimes you could put them in a little popover or modal

2020-02-05 20:26 UTC, thesephist requested changes
TLDR almost ready to merge, we can polish UI stuff once it's in master.

2020-02-05 20:26 UTC, thesephist commented on app/controllers/events_controller.rb
> +    @donations = @event.donations.where(status: 'succeeded').sort_by {|d| d.created_at }
I think it makes more sense for this list to be reverse-chronological, so it matches the transactions list.

2020-02-05 20:26 UTC, thesephist commented on app/mailers/donation_mailer.rb
> +    mail to: @emails, subject: "Congrats! 🎉 You've received a donation from #{@donation.name}"
This seems a bit long and might not show on phone screens in one line.. how about

>Congrats on receiving your first donation! 🎉

2020-02-05 20:26 UTC, thesephist commented on app/mailers/donation_mailer.rb
> +    mail to: @emails, subject: "Congrats! 🎉 You've received a donation from #{@donation.name}"
Specifying "first" may also clear up confusion, so people are less likely to get the impression that they'll get notified for every donation.

2020-02-05 20:26 UTC, thesephist commented on app/models/donation.rb
> +    'Unknown'
Might we want to raise an exception here so we (devs) are notified? This should never happen in practice, right? So it's better to fail loudly here since it probably means we messed up some code logic somewhere and need to fix it.

2020-02-05 20:26 UTC, thesephist commented on app/views/donation_mailer/first_donation_notification.html.erb
> +  You can <%= link_to 'click here', event_donation_overview_path(@donation.event.slug) %> to see the full details, including when you'll receive the payment to be able to spend it.
Might be nice to include the first donation's donor and amount, so it's not super generic. Maybe like:

>Congrats! We're emailing to let you know that you've received your first-ever donation of $XX from $XX.

2020-02-05 20:26 UTC, thesephist commented on app/views/events/donation_overview.html.erb
> +	<% @donations.each do |d| %>
I think this UI needs work but we can handle that once we merge to master.

2020-02-05 20:26 UTC, thesephist commented on app/views/events/_nav.html.erb
> +      <%= link_to 'Donations', event_donation_overview_path(event_id: @event.slug) %>
Can we put this behind the `donations_page_enabled` flag?

2020-02-05 20:26 UTC, thesephist commented on db/schema.rb
> +    t.text "donation_page_message"
Is it just me or does this PR not include a migration to add these two columns?

2020-02-07 22:15 UTC, tmb commented on app/models/donation.rb
> +    'Unknown'
If we raise an exception the whole view will break (bad)—I'm leaving Unknown there with the hope that people will hit us up.

2020-02-07 22:18 UTC, tmb commented on db/schema.rb
> +    t.text "donation_page_message"
Another one of the donations one does that we already merged.

2020-02-08 03:43 UTC, merged