Automatically Freeze cards on deletion requests
hackclub/hcb pull request #4995
Opened 2024-01-10 07:30 UTC by devramsean0

## Summary of the problem

Previously, whenever you removed a team member from an org. The cards remain active, meaning that someone could spend org funds nefariously (or without being able to upload receipts)
#4929 

## Describe your changes

This runs a loop after any invites are cancelled in the deletion_requests controller that runs cancel! on any cards that the deleted user owns that are not already cancelled.

![image](https://github.com/hackclub/hcb/assets/81807361/1dc324e8-2cc8-4574-8348-c381d1d6b947)

2024-01-10 08:16 UTC, sampoder commented on app/controllers/organizer_positions_controller.rb
> +      card.cancel!() unless card.stripe_status = "cancelled"
```suggestion
      card.cancel! unless card.stripe_status = "cancelled"
```

small thing

2024-01-10 08:16 UTC, sampoder commented on db/schema.rb
Could you remove the changes in this file?

2024-01-10 17:54 UTC, cjdenio commented on app/views/organizer_position_deletion_requests/_form.html.erb
> +    Removing this user will also cancel all of their cards, meaning any payments will not go through!
```suggestion
    Removing this user will also permanently cancel all of their cards, meaning any payments will not go through!
```

It would also be great if this copy showed the number of cards the user has

2024-01-11 20:13 UTC, sarthaktexas commented on app/views/organizer_position_deletion_requests/_form.html.erb
> +    Removing this user will also permanently cancel their <%= @card_number %> card, meaning any payments will not go through!
~~What if they have multiple cards?~~ Let's rename this variable to card_count or something similar

2024-01-25 15:31 UTC, sarthaktexas approved these changes
approved!

2024-01-25 15:33 UTC, sarthaktexas requested changes

2024-01-25 15:33 UTC, sarthaktexas commented on app/views/organizer_position_deletion_requests/_form.html.erb
> +    Removing this user will also permanently cancel their <%= @card_count %> card(s), meaning any payments will not go through!
wait... actually very small thing -- can we use[ .pluralize](https://apidock.com/rails/String/pluralize) to change card(s) into the plural form when necessary.

2024-01-26 03:24 UTC, sarthaktexas submitted a review, later dismissed
YESSIRRRRRR

2024-02-02 00:57 UTC, garyhtou reviewed
Great! just some small edits


Just as an FYI, [this PR](https://github.com/hackclub/hcb/pull/5069/files) was recently merged. We might want to update the copy on the review app to day "X cards will be cancelled"

2024-02-02 00:57 UTC, garyhtou commented on app/views/organizer_position_deletion_requests/_form.html.erb
> +  <p class="warning">
Let's hide this message if the user doesn't have cards

2024-02-02 00:57 UTC, garyhtou commented on app/views/organizer_position_deletion_requests/_form.html.erb
> +    Removing this user will also permanently cancel their <%= pluralize(@card_count, "card") %>, meaning any payments will not go through!
```suggestion
    Removing this user will also permanently cancel their <%= pluralize(@card_count, "card") %>. Recurring charges like subscriptions will be declined after cards are canceled.
```

2024-03-02 03:40 UTC, garyhtou submitted a review, later dismissed
@sarthaktexas please test & merge after handling suggestions!

2024-03-02 03:40 UTC, garyhtou commented on app/controllers/organizer_positions_controller.rb
> +    cards = @organizer_position.user.stripe_cards.where(event_id: @organizer_position.event.id)
```suggestion
    cards = @organizer_position.user.stripe_cards.where(event: @organizer_position.event)
```

2024-03-02 03:40 UTC, garyhtou commented on app/views/organizer_position_deletion_requests/_form.html.erb
> +  <% if @opdr.organizer_active_cards.count != 0 %>
```suggestion
  <% if @opdr.organizer_active_cards.count.any? %>
```

2024-03-02 03:40 UTC, garyhtou commented on app/views/organizer_position_deletion_requests/_form.html.erb
> +      Removing this user will also permanently cancel their <%= pluralize(@opdr.organizer_active_cards.count("card")) %>, Recurring charges like subscriptions will be declined after cards are cancele
```suggestion
      Removing this user will also permanently cancel their <%= pluralize(@opdr.organizer_active_cards.count, "card") %>. Recurring charges like subscriptions will be declined after cards are canceled.
```

2024-03-11 10:00 UTC, merged