Collect emails of ACH & check recipients + (optionally) send them emails
hackclub/hcb pull request #5051
Opened 2024-01-17 02:48 UTC by zoya-hussain

## Summary of the problem

This PR addresses issue #5003, which is to collect recipient's email address for transfers (ACHs & Checks).

## Describe your changes

I followed Sam's helpful instruction to help create a space where people can check off whether they would like to notify the recipient about their ACH transfer or check. Then, the recipient's email shows up on the transaction information, and the recipient can receive an email about the sender, amount sent, and reason for transaction.

<img width="788" alt="Screenshot 2024-01-16 at 8 39 53 PM" src="https://github.com/hackclub/hcb/assets/118136785/5fbae1a7-fbff-40c4-9e37-6fd190345f8f">
<img width="1065" alt="Screenshot 2024-01-16 at 8 38 06 PM" src="https://github.com/hackclub/hcb/assets/118136785/3a67c1f2-4618-4467-8af6-c24107c81926">
<img width="501" alt="Screenshot 2024-01-16 at 8 39 29 PM" src="https://github.com/hackclub/hcb/assets/118136785/8a21e456-ef5e-45f0-8695-6d2f009c0aa0">
<img width="822" alt="Screenshot 2024-01-16 at 8 36 42 PM" src="https://github.com/hackclub/hcb/assets/118136785/1088b86b-ebdf-4bc9-82bd-a6125a878341">

2024-01-17 02:48 UTC, sampoder approved these changes

2024-01-17 03:57 UTC, garyhtou requested changes
Yay! We're on the right path! I've got a couple of suggestions and bugs

2024-01-17 03:57 UTC, garyhtou commented on app/models/ach_transfer.rb
> +      before do
Let's send the mail after the state change
```suggestion
      after do 
```

2024-01-17 03:57 UTC, garyhtou commented on app/models/increase_check.rb
>        after do
Couple things here!
1. Let's send the mail after the state change.
2. It looks like the mailer constant name is `IncreaseCheckMailer` (let's update it from `IncreaseChecksMailer`
3. The parameter that `IncreaseCheckMailer` takes is `check`, not `increase_checks`


```suggestion
      after do
        IncreaseCheckMailer.with(check: self).notify_recipient.deliver_later if self.send_email_notification
```

2024-01-17 03:57 UTC, garyhtou commented on app/mailers/ach_transfer_mailer.rb
> +    mail to: @ach_transfer.email, subject: "Your ACH from #{@ach_transfer.event.name} is in transit 🚂"
```suggestion
    mail to: @ach_transfer.email, subject: "Your ACH transfer from #{@ach_transfer.event.name} is in transit"
```

2024-01-17 03:57 UTC, garyhtou commented on app/mailers/increase_check_mailer.rb
> +    mail to: @check.email, subject: "Your check from #{@check.event.name} is in transit 🚂"
```suggestion
    mail to: @check.email, subject: "Your check from #{@check.event.name} is in transit"
```

2024-01-17 03:57 UTC, garyhtou commented on app/views/ach_transfer_mailer/notify_recipient.html.erb
Since these emails are likely to be going to businesses and adults, we want to use a more professional copy!

Can we update both copies to be something along the lines of:

>Hi \<NAME\>,
>
>\<EVENT NAME\> has sent you a \<AMOUNT\> ACH transfer for _"\<PURPOSE\>"_.
>
>If you have any questions about this transfer, please contact \<EVENT NAME\>.
>
>Sincerely,
>[HCB](https://hackclub.com/hcb)
>
>_\<EVENT NAME\> is fiscally sponsored by The Hack Foundation (d.b.a. HCB), a 501(c)(3) nonprofit (EIN: 81-2908499)._

2024-01-17 03:57 UTC, garyhtou commented on app/views/hcb_codes/_increase_check.html.erb
> +    </p>
```suggestion
    <p>
      <strong>Recipient email</strong>
      <%= @hcb_code.increase_check.email || "<i>(no email provided)</i>".html_safe %>
    </p>
```

2024-01-17 03:57 UTC, garyhtou commented on app/views/hcb_codes/_ach_transfer.html.erb
> +        <%= @hcb_code.ach_transfer.email %>
We should handle the case where old ACH transfers do not have an email.

```suggestion
        <%= @hcb_code.ach_transfer.email || "<i>(no email provided)</i>".html_safe %>
```

2024-01-17 03:57 UTC, garyhtou commented on spec/mailers/previews/ach_transfer_mailer_preview.rb
Great job adding these previews! they're pretty handy

2024-01-17 03:57 UTC, garyhtou commented on app/models/ach_transfer.rb
In both models, let's validate that the email is... well, valid

Example: https://github.com/hackclub/bank/blob/63e66321d3d07094499f5e3fcf3ca5a49dfe236b/app/models/mailbox_address.rb#L33. It should also `allow_nil: true`

Also, let's `validate_presence_of :email, on: :create` to make sure that the email exists when creating new records

2024-01-17 03:57 UTC, garyhtou commented on app/controllers/ach_transfers_controller.rb
> +    params.require(:ach_transfer).permit(:routing_number, :account_number, :email, :bank_name, :recipient_name, :amount_money, :payment_for, :scheduled_on, file: [])
Do we need to also permit `send_email_notification`?

This is currently preventing the value from making it into the database. If the user selects the `send_email_notification` checkbox it will still appear as `FALSE` in the database because it gets filtered out here.

After making the change, you can check that it works by:
1. Submitting the form with `send_email_notification` checked
2. Typing `AchTransfer.last` in the Rails console. You should see `send_email_notification: true` somewhere in there

2024-01-17 03:57 UTC, garyhtou commented on app/controllers/increase_checks_controller.rb
> +      :email,
Do we need to also permit `send_email_notification`?

2024-01-17 03:57 UTC, garyhtou commented on app/views/ach_transfers/_form.html.erb
> +    </div>
We can remove the dollar sign prefix

![image](https://github.com/hackclub/hcb/assets/20099646/c06eda62-d044-4278-b1b0-e815121cf177)

2024-01-17 04:20 UTC, sampoder commented on app/views/ach_transfers/_form.html.erb
> +    </div>
that ones my bad! sorry.

2024-01-17 14:59 UTC, cjdenio commented on app/mailers/ach_transfer_mailer.rb
> +    mail to: @ach_transfer.email, subject: "Your ACH from #{@ach_transfer.event.name} is in transit 🚂"
I think it would be great if the `from` address was set to `<org name> via HCB`— people receiving this email might not be familiar with HCB and think it's spam.

2024-01-21 17:57 UTC, sampoder commented on app/controllers/ach_transfers_controller.rb
> +    params.require(:ach_transfer).permit(:routing_number, :account_number, :email, :bank_name, :recipient_name, :amount_money, :payment_for, :scheduled_on, file: [])
```suggestion
    params.require(:ach_transfer).permit(:routing_number, :account_number, :email, :bank_name, :recipient_name, :amount_money, :payment_for, :scheduled_on, :send_email_notification, file: [])
```

2024-01-21 18:11 UTC, cjdenio requested changes

2024-01-21 18:11 UTC, cjdenio commented on app/models/increase_check.rb
> +  validate_presence_of :email, on: :create
```suggestion
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address" }, allow_nil: true
  validates_presence_of :email, on: :create
```

2024-01-21 18:11 UTC, cjdenio commented on app/models/ach_transfer.rb
> +  validate_presence_of :email, on: :create
```suggestion
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address" }, allow_nil: true
  validates_presence_of :email, on: :create
```

2024-01-21 18:14 UTC, sampoder commented on app/mailers/ach_transfer_mailer.rb
> +    mail to: @ach_transfer.email, subject: "Your ACH from #{@ach_transfer.event.name} is in transit 🚂"
@zoya-hussain check out https://github.com/hackclub/hcb/blob/9adbcba6822898567bab9b12911835cbfea4ec9b/app/mailers/grant_mailer.rb#L7 for an example of this

2024-01-21 18:16 UTC, cjdenio commented on app/models/ach_transfer.rb
> +  validate_presence_of :email, on: :create
the `presence: true` change is still relevant

2024-01-21 18:23 UTC, sampoder commented on app/models/ach_transfer.rb
> +  validate_presence_of :email, on: :create
oh sorry, didn't catch that

2024-01-28 16:27 UTC, sampoder approved these changes

2024-02-03 04:19 UTC, garyhtou reviewed
so so so close! just one last large change, then we'll be at the finish line. thank you

2024-02-03 04:19 UTC, garyhtou commented on app/models/ach_transfer.rb
> +#  email                     :string
sorry, i know this is a big change. can we rename this to `recipient_email`? This way, it matches `recipient_name` and `recipient_tel`; and prevents ambiguity on who's email it is

2024-02-15 21:55 UTC, garyhtou approved these changes
yay! let's put this in prod

2024-02-15 22:19 UTC, merged