Org ledger: Add pinned transactions
hackclub/hcb pull request #5126
Opened 2024-01-27 19:01 UTC by manuthecoder

## Summary 
Add pinned transactions feature! (#5041)

## Video
https://github.com/hackclub/hcb/assets/77016441/7c0ce766-20c6-4426-bb07-941ff36ddc47

2024-01-29 04:16 UTC, sampoder requested changes
Things are looking awesome here!

Before we merge this, here are the main things I think we're going to need to do:

* Let's move the toggle from the `/hcb_code/{id}` route and let's put it on the ledger. Similar to how if you hover over a transaction, there's the toggle tag option. Let's have a `Pin` / `Unpin` option. We can keep the same controller method etc.

* Let's clean up the styles into a dedicated `.scss` file and try to use the classes we already have as much as possible. I can take point on that.

* Let's remove the formatting changes to `app/models/login_code.rb`

* There are a couple of unrelated changes in the `schema.rb` file, let's remove those.

🚀 nice cooking! :D

2024-01-29 05:25 UTC, sampoder commented
Awesome, I pushed the styling changes and some linting fixes

2024-01-29 22:00 UTC, garyhtou reviewed
I love this!

when hoving to remove a pin, can we have a slash through the pin icon?

2024-01-29 22:00 UTC, garyhtou commented on app/models/event.rb
> +  has_many :pins, class_name: "HcbCode::Pin"
thoughts on this?

```suggestion
  has_many :hcb_code_pins, class_name: "HcbCode::Pin"
```

2024-01-29 22:00 UTC, garyhtou commented on app/models/hcb_code/pin.rb
> +        errors.add(:base, "You can only pin up four transactions to an event.")
```suggestion
        errors.add(:base, "You can only pin up four transactions.")
```

2024-01-31 05:48 UTC, sampoder reviewed
Quick updates after Gary's review

2024-01-31 05:48 UTC, sampoder commented on app/views/events/_pinned_transactions.html.erb
> +  <% @event.pins.each do |pin| %>
```suggestion
  <% @event.hcb_code_pins.each do |pin| %>
```

2024-01-31 05:48 UTC, sampoder commented on app/models/hcb_code/pin.rb
> +      if event.pins.count > 4
```suggestion
      if event.hcb_code_pins.count > 4
```

2024-02-03 04:08 UTC, garyhtou reviewed
Great work!

---

It might be nice to be able to pin all types of transactions, including Check transfers. That doesn't seem to currently be possible

2024-02-03 04:08 UTC, garyhtou commented on app/controllers/hcb_codes_controller.rb
> +    HcbCode::Pin.find_by(event: @event, hcb_code: @hcb_code)&.destroy || HcbCode::Pin.create(event: @event, hcb_code: @hcb_code)
smart!

2024-02-03 04:08 UTC, garyhtou commented on app/models/hcb_code/pin.rb
> +        errors.add(:base, "You can only pin up four transactions.")
```suggestion
        errors.add(:base, "You can only pin up to four transactions.")
```

2024-02-03 04:08 UTC, garyhtou commented on app/policies/hcb_code_policy.rb
> +    user&.admin?
It appears the UI is visible to everyone, but only admins can use the route

2024-02-03 04:08 UTC, garyhtou commented on app/views/canonical_transactions/_canonical_transaction.html.erb
> +   <%= render "canonical_transactions/icon", ct: %>
THANK YOU FOR THIS 🙏

2024-02-03 04:08 UTC, garyhtou commented on app/views/hcb_codes/_pin.html.erb
> +<% type = local_assigns[:type].nil? ? "" : local_assigns[:type] + " " %>
Is this being used?

2024-02-03 04:08 UTC, garyhtou commented on db/schema.rb
There are some unrelated schema changes here!

2024-02-03 04:08 UTC, garyhtou commented on app/views/hcb_codes/_pin.html.erb
> +  <button type="submit" class="inline-flex muted items-end btn btn-small bg-info" style="margin-left: auto">
This button doesn't seem to visually fit in here. Maybe switch it out for a link like the other two?
![image](https://github.com/hackclub/hcb/assets/20099646/6a6180ae-40fc-4eac-9d9c-9b58f65737b4)

2024-02-03 04:08 UTC, garyhtou commented on app/views/events/_pinned_transactions.html.erb
> +        <% end %>
Should this be in a `if organizer_signed_in?` Otherwise it'd show in transparency mode

2024-02-03 04:08 UTC, garyhtou commented on app/views/events/_pinned_transactions.html.erb
> +            <%= inline_icon "pin", size: 20 %>
Let's add a tooltip here

2024-02-03 04:08 UTC, garyhtou commented on app/views/events/_pinned_transactions.html.erb
This is what it looks like on mobile

![image](https://github.com/hackclub/hcb/assets/20099646/cc95ce5f-8466-4204-9252-8adc84359c5b)

2024-02-03 04:08 UTC, garyhtou commented on app/views/events/_pinned_transactions.html.erb
> +          <%= pin.hcb_code.ct.date.strftime("%Y-%m-%d") %> &bull; <%= render_money pin.hcb_code.amount %>
Thought on rendering the date in a more human-readable format such as `Jan 3rd, 2024`

2024-02-03 04:09 UTC, garyhtou commented on app/views/events/_pinned_transactions.html.erb
> +            <%= inline_icon "pin", size: 20 %>
Helps make it more clear that clicking will unpin

2024-02-03 18:36 UTC, sampoder approved these changes
Looks good to me! Very exciting

2024-02-15 21:46 UTC, garyhtou approved these changes
Great!
![image](https://github.com/hackclub/hcb/assets/20099646/8091132c-b575-4b05-a949-90921ad3493a)

2024-02-15 21:46 UTC, merged