Admin: Move Event balances page's Export button for lower visual importance
hackclub/hcb pull request #5188
Opened 2024-02-03 01:44 UTC by aramshiva

Fixes #5016
New:
![CleanShot 2024-02-06 at 17 40 40@2x](https://github.com/hackclub/hcb/assets/79479940/51f04317-6385-4ac3-aa39-e615cd91195c)
Old:
![CleanShot 2024-02-02 at 17 43 10@2x](https://github.com/hackclub/hcb/assets/79479940/4e1ab90c-180f-40a2-a213-f18cb1538b36)

> The Export button on the admin's organization search page looks like the search button.
> Maybe people unintentionally click it when trying to search.
> 
> Solution
> Move it next to search and make the button's color muted.
https://github.com/hackclub/hcb/issues/5016#issue-2077547502

2024-02-03 02:50 UTC, garyhtou commented
Can we move it to the right of the search button instead of the search bar?

![image](https://github.com/hackclub/hcb/assets/20099646/be2c0448-6e4b-4195-8e32-650bf3ddc55e)

2024-02-03 03:01 UTC, garyhtou commented
Please re-request for my review after the edit and after Ian has approved it! thanks 😄

2024-02-07 01:42 UTC, YodaLightsabr commented on app/views/admin/events.html.erb
> +  <%= form.text_field :q, value: params[:q], style: "vertical-align: top;" %>
```suggestion
  <%= form.text_field :q, value: params[:q], style: "vertical-align: top;", placeholder: "Search" %>
```

2024-02-07 01:42 UTC, YodaLightsabr approved these changes

2024-02-07 06:23 UTC, garyhtou reviewed
Is the event_filter partial being used elsewhere? if it is, we likely don't wanna show the button elsewhere!

I'm not able to double check right now because i'm on my phone

2024-02-08 10:01 UTC, garyhtou requested changes
the partial is being used [here](https://github.com/hackclub/bank/blob/e2d49a66f9544d0be87b49dd8b609efa17971a0a/app/views/admin/balances.html.erb#L8)

we likely don't want to render two types of "export" buttons on the admin event balances page

2024-02-13 03:49 UTC, garyhtou approved these changes

2024-02-13 03:53 UTC, merged