Cards info panel now aligns card number and hidden dots
hackclub/hcb pull request #5192
Opened 2024-02-03 23:39 UTC by rluodev

now fixed like sarthak showed

See https://github.com/hackclub/hcb/issues/5143 for screenshots

2024-02-05 22:46 UTC, garyhtou approved these changes
yay! so satisfying now.

good to merge after approval from @sarthaktexas

2024-02-05 22:54 UTC, cjdenio requested changes
<img width="340" alt="Screenshot 2024-02-05 at 5 47 45 PM" src="https://github.com/hackclub/hcb/assets/34525547/4943bdbd-f164-4ddf-9e32-a390411ddc65">

It's still not quite aligned— `items-end` pushes the dots towards the bottom of the container. `items-center` should do the trick!

2024-02-06 13:01 UTC, sarthaktexas commented
NO @cjdenio do items-center and then reveal the number… the icon causes it to not be centered even when you do that

2024-02-06 14:43 UTC, cjdenio commented
I did, and it was... can you share a screenshot of the text being misaligned with `items-center`, then correctly aligned with `items-end`?

2024-02-06 14:55 UTC, sarthaktexas commented
ykkk i can't actually recreate it anymore

2024-02-06 14:55 UTC, sarthaktexas requested changes

2024-02-06 14:55 UTC, sarthaktexas commented on app/views/stripe_cards/_details.html.erb
> +            <div class="flex justify-between mono items-end">
```suggestion
            <div class="flex justify-between mono items-center">
```

2024-02-06 14:56 UTC, cjdenio approved these changes

2024-02-06 14:56 UTC, sarthaktexas approved these changes

2024-02-06 14:59 UTC, merged