Admin users list now shows card grants
hackclub/hcb pull request #5194
Opened 2024-02-04 01:08 UTC by rluodev

title

(will add pics in like a day)

2024-02-04 10:26 UTC, garyhtou requested changes

2024-02-04 10:26 UTC, garyhtou commented on app/views/admin/users.html.erb
> +          <% if user.card_grants.size > 0 %>
add `includes(:card_grants)` to `@users` to prevent N+1s

2024-02-14 17:22 UTC, rluodev commented on app/views/admin/users.html.erb
> +          <% if user.card_grants.size > 0 %>
wait what does this mean

2024-02-14 22:28 UTC, garyhtou commented on app/views/admin/users.html.erb
> +          <% if user.card_grants.size > 0 %>
here's a bit of info! https://medium.com/doctolib/how-to-find-fix-and-prevent-n-1-queries-on-rails-6b30d9cfbbaf

Inside the controller, wherever we define the @users variable, we want to add `includes(:card_grants)` to the chain.

For example:
```ruby
@users = User.all.includes(:card_grants)
```

2024-02-29 00:41 UTC, garyhtou commented on app/controllers/admin_controller.rb
>      end
I'd suggest writing it as like because both branches of the condition needs the includes for events and card grants
```ruby
      relation = @event.users
    else
      relation = User.all
    end
    relation = relation.includes(:events).includes(:card_grants)
```

2024-02-29 00:43 UTC, garyhtou commented on app/controllers/admin_controller.rb
>      end
[`89e8a80` (#5194)](https://github.com/hackclub/hcb/pull/5194/commits/89e8a80cc523cb98f40f2f74a823e088a83592d7)

2024-02-29 00:44 UTC, garyhtou approved these changes
great!

2024-03-01 03:09 UTC, sarthaktexas approved these changes

2024-03-01 03:10 UTC, merged