Fixes #32
hackclub/hcb pull request #52
Opened 2018-12-30 22:31 UTC by tmb

Fix issue #32

2018-12-31 01:15 UTC, lachlanjc reviewed
- I don’t think return belongs here
- Should this be a form validation error instead? Not sure

2018-12-31 02:26 UTC, tmb commented
@lachlanjc return is needed because it'll double render otherwise, not too sure about the second one.

is it cool to merge this? it's a pretty small change and is functional

2018-12-31 03:44 UTC, maxwofford requested changes

2018-12-31 03:44 UTC, maxwofford commented on app/controllers/organizer_position_invites_controller.rb
> +    if event.users.pluck(:email).include? @invite.email
@tmb this should be done with model validations

2018-12-31 04:06 UTC, zachlatta commented on app/controllers/organizer_position_invites_controller.rb
> +    if event.users.pluck(:email).include? @invite.email
So, just to clarify, you can add something like the following to the invite model:

```ruby
validates :not_already_invited

private

def not_already_invited
  # add logic + errors.add(...) here
end

2018-12-31 20:28 UTC, tmb commented
moved! sorry this took so long, ended up getting distracted implementing another feature which I eventually realized should be on the `one` branch (where I am now putting it!)

2018-12-31 22:57 UTC, maxwofford commented on app/models/organizer_position_invite.rb
> +      return false
Does this need a `return` here?

2019-01-01 09:47 UTC, tmb commented on app/models/organizer_position_invite.rb
> +      return false
I think so, doesn't it signify to `:validate` that the check failed?

2019-01-02 00:08 UTC, maxwofford commented on app/models/organizer_position_invite.rb
> +      return false
Looking at the examples in the docs, doesn't seem like they use them (https://guides.rubyonrails.org/active_record_validations.html#custom-methods)

2019-01-02 03:34 UTC, tmb commented on app/models/organizer_position_invite.rb
> +      return false
👍hmmm ok will change!

2019-01-02 03:35 UTC, tmb commented
merging 😄

2019-01-02 03:38 UTC, merged

2019-01-02 14:18 UTC, zachlatta commented on app/models/organizer_position_invite.rb
> +      return false
> The valid? method will verify that the errors collection is empty, so your custom validation methods should add errors to it when you wish validation to fail: