Re-styling the download button for emphasis
hackclub/hcb pull request #5232
Opened 2024-02-07 00:23 UTC by zoya-hussain

## Summary of the problem

Addressing issue #5223 and making the button for downloading documents larger! Did this by changing basic UI components, plus fixing a small bug with the alignment of the Edit and Delete buttons. 

## Describe your changes

<img width="612" alt="Screenshot 2024-02-06 at 6 18 36 PM" src="https://github.com/hackclub/hcb/assets/118136785/b00e24d4-06e9-43eb-8c82-c9aace2034ea">

![0img_1726](https://github.com/hackclub/hcb/assets/118136785/33bf71a3-8a16-45c4-845a-6ff384ddd75f)

(Plus, a picture of Sarthak at Lonestar with his pink cowboy hat, which I used to test this!)

2024-02-07 01:51 UTC, sampoder requested changes
Only a small thing! I think we can get rid of the wrapped div

2024-02-07 01:51 UTC, sampoder commented on app/views/documents/show.html.erb
> +  </div>
```suggestion
  <div class="flex items-center mt2" style="gap: 6px">
    <%= link_to document_download_path(@document), target: :_blank, class: "btn" do %>
      <%= inline_icon "download" %>
      Download
      <% end %>
    <%= link_to "Edit", edit_document_path(@document), class: "btn bg-info" %>
    <%= link_to "Destroy", @document, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn--destroy" %>
  </div>
```

2024-02-13 22:56 UTC, sampoder approved these changes
LGTM!

2024-02-15 23:54 UTC, garyhtou approved these changes

2024-02-15 23:58 UTC, merged