Deleting Expensify from Member Deletion Form
hackclub/hcb pull request #5258
Opened 2024-02-13 23:10 UTC by zoya-hussain

## Summary of the problem

Addressing issue #5211, deleting Expensify question and params from Organizer Position Deletion Request and removing Expensify params from `filtered_params`.

<img width="978" alt="Screenshot 2024-02-13 at 5 06 57 PM" src="https://github.com/hackclub/hcb/assets/118136785/5c4ebd31-f317-4660-87e2-3b3edef77352">

2024-02-13 23:13 UTC, sampoder approved these changes
LGTM!

2024-02-13 23:20 UTC, garyhtou requested changes
Can we also remove it from here?

https://github.com/hackclub/bank/blob/88c1b23381a4988bfc6cfc621efadd87cc43b6c9/app/views/organizer_position_deletion_requests/show.html.erb#L51-L55

2024-02-14 06:12 UTC, sampoder approved these changes

2024-02-27 02:09 UTC, garyhtou approved these changes
great!

2024-02-27 21:26 UTC, merged