Subtle Admin Comments Redesign
hackclub/hcb pull request #5293
Opened 2024-02-18 22:26 UTC by sampoder

## Summary of the problem

Closes https://github.com/hackclub/hcb/issues/5272.

## Describe your changes

Thought this looked nice, happy to make it more prominent. 

<img width="972" alt="Screenshot 2024-02-18 at 2 25 33 PM" src="https://github.com/hackclub/hcb/assets/39828164/e29e3ca5-f786-4c89-9481-4c191cef6c1c">

<img width="939" alt="Screenshot 2024-02-18 at 2 26 13 PM" src="https://github.com/hackclub/hcb/assets/39828164/a2e2ba10-cf50-46d5-856a-65bca9d1810a">

2024-02-19 02:55 UTC, cjdenio requested changes
This causes admin comments to be shown to normal users!

2024-02-19 05:54 UTC, sampoder commented
LOL! My bad...

2024-02-19 06:04 UTC, sampoder commented
Fixed!

2024-02-19 08:28 UTC, garyhtou reviewed
oops, i left comments, but never published those comments

2024-02-19 08:28 UTC, garyhtou commented on app/assets/stylesheets/_dark.scss
> +  .comments .card.comment__admin {
I wonder if `admin` should be a modifier instead of an element?

https://getbem.com/naming/

`comment--admin`

2024-02-19 08:28 UTC, garyhtou commented on app/views/comments/_item_v2.html.erb
>  <div class="mt2 mb2">
I _think_ this might fix the problem. please test it!

```suggestion
<% return if comment.admin_only? && !admin_signed_in? %>

<div class="mt2 mb2">
```

2024-02-19 08:28 UTC, garyhtou commented on app/views/comments/_list_v2.html.erb
>    <% @hcb_code.comments.order(created_at: :asc).each do |comment| %>
rendering as a collection is more performant

```ruby
<%= render "comments/item_v2", collection: @hcb_code.comments.order(created_at: :asc), as: :comment %>
```

2024-02-19 08:31 UTC, garyhtou commented on app/views/comments/_item_v2.html.erb
>  <div class="mt2 mb2">
Instead of handling the authorization in the list partial, we should do it in the item partial for 3 reasons:

1. ~~i think the ternary will mess up preloading~~ (jk i lied)
2. adding the condition in the item partial will also "protect" other usages of the item partial
3. having this condition in the item partial makes it easy to do `policy(comment).show?` if we wanted to use Pundit

2024-02-19 16:50 UTC, cjdenio commented on app/views/comments/_item_v2.html.erb
>  <div class="mt2 mb2">
This might also be a good use-case for [Pundit scopes](https://github.com/varvet/pundit?tab=readme-ov-file#scopes)

2024-02-19 17:56 UTC, sampoder commented on app/views/comments/_item_v2.html.erb
>  <div class="mt2 mb2">
Ended up going with Pundit, but yep!

2024-02-19 17:57 UTC, sampoder commented
@cjdenio & @garyhtou pushed some code that uses Pundit, thoughts? Also added in Pundit scopes.

2024-02-19 18:01 UTC, cjdenio commented on app/policies/comment_policy.rb
> +    user.admin? || (record.commentable.event.users.include?(user) && !record.admin_only)
`commentable.event` will have weird behavior on disbursements (which have more than one Event)

2024-02-19 18:01 UTC, cjdenio commented on app/views/comments/_list_v2.html.erb
> +  <% if policy_scope(@hcb_code.comments) && local_assigns[:blankslate?] %>
```suggestion
  <% if policy_scope(@hcb_code.comments).empty? && local_assigns[:blankslate?] %>
```

2024-02-19 18:01 UTC, cjdenio commented on app/views/comments/_item_v2.html.erb
> +<% return if !CommentPolicy.new(current_user, comment).show? %>
```suggestion
<% return if !policy(comment).show? %>
```

2024-02-19 20:49 UTC, sampoder commented on app/policies/comment_policy.rb
> +    user.admin? || (record.commentable.event.users.include?(user) && !record.admin_only)
Should be fixed now!

2024-02-20 06:21 UTC, garyhtou commented
I think this is good to go, but I'll leave the final review to @cjdenio!

2024-02-20 06:25 UTC, sampoder commented
Coolio

2024-02-20 15:37 UTC, cjdenio approved these changes

2024-02-20 15:37 UTC, cjdenio commented
This is great, thanks!

2024-02-20 17:03 UTC, merged