Documents: Add Archive feature
hackclub/hcb pull request #5344
Opened 2024-02-26 22:14 UTC by rluodev

you can now archive and unarchive documents at will

<img width="933" alt="Screenshot 2024-02-29 at 8 57 16 AM" src="https://github.com/hackclub/hcb/assets/34289582/44df67e7-6d02-4e1f-b897-89b4968bea78">

<img width="933" alt="Screenshot 2024-02-29 at 8 57 21 AM" src="https://github.com/hackclub/hcb/assets/34289582/2e381ceb-941d-42f9-b0e7-4e140ccdf12f">

<img width="933" alt="Screenshot 2024-02-29 at 8 57 28 AM" src="https://github.com/hackclub/hcb/assets/34289582/3aaca060-5800-48fb-99f2-12433a2f21b3">

<img width="933" alt="Screenshot 2024-02-29 at 8 57 40 AM" src="https://github.com/hackclub/hcb/assets/34289582/61df461d-3055-413f-9989-9c588c737fcd">

if no documents are archived "archived documents" tab does not show

2024-02-27 22:31 UTC, garyhtou commented on app/models/document.rb
> +  scope :common_archived, -> { where(event_id: nil).where(aasm_state: :archived) }
instead of creating a new scope, we can chain scopes together!

```ruby
Document.common.archived
```

The `archived` scope is defined by AASM

2024-02-27 22:46 UTC, rluodev commented on app/models/document.rb
> +  scope :common_archived, -> { where(event_id: nil).where(aasm_state: :archived) }
oh so I just don't need to define new scopes at all then?

2024-02-27 22:51 UTC, rluodev commented on app/models/document.rb
> +  scope :common_archived, -> { where(event_id: nil).where(aasm_state: :archived) }
fixed!

2024-02-29 16:46 UTC, rluodev commented
how tf did merge from main fail the lint

2024-03-01 01:25 UTC, sarthaktexas submitted a review, later dismissed
lgtm!

2024-03-01 07:06 UTC, garyhtou reviewed
great work on this! i love how clean it is

2024-03-01 07:06 UTC, garyhtou commented on app/controllers/documents_controller.rb
> +  def toggle_archive
great work here! very clean!

2024-03-01 07:06 UTC, garyhtou commented on app/services/document_service/archive.rb
I do appreciate that you created a service for these, but I think this code is small enough where it might not be necessary.

Imma suggest removing these those services, and I'll help provide the code that will replace it

2024-03-01 07:06 UTC, garyhtou commented on app/models/document.rb
> +    event :unarchive do
we prefix all our events with `mark_`
```suggestion
    event :mark_archive do
      transitions from: :active, to: :archived
    end

    event :mark_unarchive do
```

2024-03-01 07:06 UTC, garyhtou commented on app/services/document_service/archive.rb
> +        @document.save!
calling an AASM event bang method will automatically save the record. So, the `save!` isn't necessary. This also means that the transaction isn't necessary since we're only saving once.

2024-03-01 07:06 UTC, garyhtou commented on app/models/document.rb
> +    state :archived
```suggestion
    state :archived, before_exit: -> do
      self.archived_by = nil
      self.archived_at = nil
    end
```

2024-03-01 07:06 UTC, garyhtou commented on app/controllers/documents_controller.rb
> +    end
```suggestion
    if @document.archived?
      @document.mark_archived!(current_user)
      flash[:success] = "Document successfully unarchived."
    else
      @document.mark_active!
      flash[:success] = "Document successfully archived."
    end
```

2024-03-01 07:06 UTC, garyhtou commented on app/models/document.rb
> +      transitions from: :active, to: :archived
```suggestion
      transitions from: :active, to: :archived
      after do |archived_by = nil|
        update!(archived_by:) if archived_by.present?
      end

```

2024-03-01 07:06 UTC, garyhtou commented on app/views/documents/common_index.html.erb
> +<% if @documents.archived.length > 0 %>
```suggestion
<% if @documents.archived.any? %>
```

2024-03-01 07:06 UTC, garyhtou commented on app/views/documents/common_index.html.erb
> +<% if @documents.archived.length > 0 %>
We should define variables in the controller such as `@active_documents` and `@archived_documents`.

2024-03-01 07:06 UTC, garyhtou commented on app/views/documents/index.html.erb
> +  <%= render @documents.active %>
Let's define the variables:
- `@active_documents`
- `@active_common_documents`
- and `@archived_documents`

2024-03-01 07:06 UTC, garyhtou commented on db/schema.rb
> +  create_table "metrics", force: :cascade do |t|
unrelated

2024-03-08 04:25 UTC, rluodev commented on app/services/document_service/archive.rb
sounds good

2024-03-10 06:00 UTC, rluodev commented on app/views/documents/index.html.erb
> +  <%= render @documents.active %>
done!

2024-03-10 06:00 UTC, rluodev commented on app/views/documents/common_index.html.erb
> +<% if @documents.archived.length > 0 %>
done!

2024-03-14 02:05 UTC, garyhtou requested changes

2024-03-14 02:05 UTC, garyhtou commented on app/controllers/documents_controller.rb
> +    authorize @archived_documents
```suggestion
    authorize @active_documents = Document.common.active
    authorize @archived_documents = Document.common.archived
```

2024-03-14 02:05 UTC, garyhtou commented on app/controllers/documents_controller.rb
> +    authorize @archived_documents
I think we want to authorize all of them

```suggestion
    authorize @active_documents = @event.documents.includes(:user).active
    authorize @active_common_documents = Document.common.active
    authorize @archived_documents = @event.documents.includes(:user).archived
    authorize @archived_common_documents = Document.common.archived
```

2024-03-14 02:05 UTC, garyhtou commented on app/views/documents/_document.html.erb
> +    <strong class="brand-sans h3 block mt1 line-height-2"><%= document.name %> <span class="brand-sans h4 mt1 line-height-1" style="color: gray"><%= "(Archived)" if document.archived? %></span></stro
Can we wrap the `if` outside of the `span`? This way we don't end up with an empty `span`

2024-03-14 02:05 UTC, garyhtou commented on app/views/documents/index.html.erb
> +<% if @documents.archived.length > 0 %>
```suggestion
<% if @documents.archived.any? %>
```

2024-03-14 02:05 UTC, garyhtou commented on app/views/documents/index.html.erb
> +<% if @documents.archived.length > 0 %>
It appears that `@documents` is no longer defined

2024-03-14 02:05 UTC, garyhtou commented on app/controllers/documents_controller.rb
> +    redirect_to @document.event || documents_path
I think it probably makes more sense to redirect to the document, rather than the event or document index page.

```suggestion
    redirect_to @document
```

2024-03-18 20:42 UTC, rluodev commented on app/controllers/documents_controller.rb
> +    authorize @archived_documents
oops I forgot to include the others

2024-03-18 20:43 UTC, rluodev commented on app/views/documents/index.html.erb
> +<% if @documents.archived.length > 0 %>
whoops will fix

2024-03-21 15:42 UTC, rluodev commented on app/views/documents/index.html.erb
> +<% if @documents.archived.length > 0 %>
fixed!

2024-03-21 15:43 UTC, rluodev commented on app/views/documents/_document.html.erb
> +    <strong class="brand-sans h3 block mt1 line-height-2"><%= document.name %> <span class="brand-sans h4 mt1 line-height-1" style="color: gray"><%= "(Archived)" if document.archived? %></span></stro
fixed!

2024-03-27 18:45 UTC, garyhtou commented on app/views/documents/_document.html.erb
> +    <strong class="brand-sans h3 block mt1 line-height-2"><%= document.name %><% if document.archived? %> <span class="brand-sans h4 mt1 line-height-1" style="color: gray">(Archived)</span><% end %><
```suggestion
    <strong class="brand-sans h3 block mt1 line-height-2"><%= document.name %>
      <% if document.archived? %>
        <span class="brand-sans h4 mt1 line-height-1" style="color: gray">(Archived)</span>
      <% end %>
    </strong>
```

2024-03-27 18:45 UTC, garyhtou commented on app/views/documents/show.html.erb
> +    <span class="bold block mb1">This document was archived by <%= user_mention User.find(@document.archived_by_id) %> on <%= format_date @document.archived_at %>.</span>
```suggestion
    <span class="bold block mb1">This document was archived by <%= user_mention @document.archived_by %> on <%= format_date @document.archived_at %>.</span>
```

2024-03-27 18:51 UTC, garyhtou submitted a review, later dismissed
i got this error while testing. can you please fix?

![image](https://github.com/hackclub/hcb/assets/20099646/34dda61a-914f-439e-ad3a-8737c53f0be9)

2024-04-29 16:03 UTC, rluodev commented
oop will take a look, did not see this email in my inbox

2024-04-29 16:05 UTC, cjdenio commented
@garyhtou I can't reproduce, and this doesn't seem to be an issue caused by this PR

2024-05-13 18:51 UTC, sampoder submitted a review, later dismissed
LGTM! Only thing is that it might be nice to add `text-wrap: balance` to the information cards.

Before:

<img width="528" alt="Screenshot 2024-05-13 at 1 50 58 PM" src="https://github.com/hackclub/hcb/assets/39828164/fa219061-2b90-4567-95a7-a93465a6349d">

After:

<img width="456" alt="Screenshot 2024-05-13 at 1 51 15 PM" src="https://github.com/hackclub/hcb/assets/39828164/a4fbedec-a754-43a8-b61b-52e3e89d4db8">

2024-05-20 15:47 UTC, rluodev commented
> LGTM! Only thing is that it might be nice to add `text-wrap: balance` to the information cards.
> 
> Before:
> 
> <img alt="Screenshot 2024-05-13 at 1 50 58 PM" width="528" src="https://private-user-images.githubusercontent.com/39828164/330171678-fa219061-2b90-4567-95a7-a93465a6349d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjAyNzEsIm5iZiI6MTcxNjIxOTk3MSwicGF0aCI6Ii8zOTgyODE2NC8zMzAxNzE2NzgtZmEyMTkwNjEtMmI5MC00NTY3LTk1YTctYTkzNDY1YTYzNDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE1NDYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2Y2FjZWJjZGMxOGQxZDIyNzIyNTU3Mjk3MjJlNzdmNTEwMDJhOTRiNTQ2MGM3ZDQ4ZWNkMDAxZmQxYmQ3MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qFNMxMtPlvPCb7x7G5Ykw2cinc-EJEe62GW4li4E6Uk">
> After:
> 
> <img alt="Screenshot 2024-05-13 at 1 51 15 PM" width="456" src="https://private-user-images.githubusercontent.com/39828164/330171715-a4fbedec-a754-43a8-b61b-52e3e89d4db8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjAyNzEsIm5iZiI6MTcxNjIxOTk3MSwicGF0aCI6Ii8zOTgyODE2NC8zMzAxNzE3MTUtYTRmYmVkZWMtYTc1NC00M2E4LWI2MWItNTJlM2U4OWQ0ZGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE1NDYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1OGFlZDIzMGQ0ODY0YzUyYjg1Y2VjMDY4OTBmYWE4NGVjNmJlZWQ1NGYyNzQyNGQ2MzdlZmY0OGQ1ODYwNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BSHt1-VegtJlH6ktt-E4VBr8meSS2zR_YosnErL14xY">

I think this leaves a bit too much empty space on the sides - also, it'd be inconsistent with the styling of other pages where this same card is used (like invoices).

2024-05-31 00:24 UTC, garyhtou commented
@sampoder if you get a chance, can you double check and merge? 🪄

2024-05-31 14:49 UTC, sampoder approved these changes

2024-05-31 14:49 UTC, sampoder commented
LGTM

2024-05-31 15:05 UTC, merged