Bug: Fix un-human-readable data values on user information page
hackclub/hcb pull request #5355
Opened 2024-02-28 15:14 UTC by devramsean0

## Summary of the problem

Just fixes a few small things we noticed after the deployment to prod
See #5350 

## Describe your changes

I fixed a table heading, added some icons to rows, Makes money look like money on the page

![image](https://github.com/hackclub/hcb/assets/81807361/d64ac238-4746-4e72-8ded-9f61cace7841)

closes #5350

2024-02-28 15:27 UTC, sarthaktexas commented
Whoops! So sorry, I should have clarified. I had originally only wanted frozen and cancelled cards to have a emoji.

2024-02-28 15:30 UTC, sarthaktexas requested changes

2024-02-28 15:30 UTC, sarthaktexas commented on app/views/users/edit_admin.html.erb
> +                  <td>$<%= render_money_amount invoice.total %></td>
Instead of doing some string interpolation fuckery, use the `render_money` method like you do in line 60 as opposed to the `render_money_amount` method.

2024-02-28 15:30 UTC, sarthaktexas commented on app/views/users/edit_admin.html.erb
> +                    <%= inline_icon "emoji", size: 20 %> Active
If active, let's not show an emoji.

2024-02-28 15:30 UTC, sarthaktexas commented on app/views/users/edit_admin.html.erb
> +                  <td>$<%= render_money_amount check.amount_cents %></td>
Same as above.

2024-02-28 15:30 UTC, sarthaktexas commented on app/views/users/edit_admin.html.erb
> +                  <td>$<%= render_money_amount check.amount %></td>
Same as above.

2024-02-28 15:30 UTC, sarthaktexas commented on app/views/users/edit_admin.html.erb
> +                  <td>$<%= render_money_amount check.amount %></td>
Same as above.

2024-02-28 15:30 UTC, sarthaktexas commented on app/views/users/edit_admin.html.erb
> +                  <td>$<%= render_money_amount ach.amount %></td>
Same as above.

2024-02-28 15:30 UTC, sarthaktexas commented on app/views/users/edit_admin.html.erb
> +                  <td>$<%= render_money_amount disbursement.amount %></td>
Same as above.

2024-02-28 15:30 UTC, sarthaktexas commented on db/schema.rb
Let's uncommit this.

2024-02-28 17:23 UTC, devramsean0 commented on app/views/users/edit_admin.html.erb
> +                  <td>$<%= render_money_amount invoice.total %></td>
I didn't even realise I switched methods partway through lol

2024-02-28 17:24 UTC, devramsean0 commented on db/schema.rb
Its always the dang schema :/

2024-03-09 03:12 UTC, sarthaktexas submitted a review, later dismissed

2024-03-09 08:19 UTC, sarthaktexas commented
updated ss:
<img width="950" alt="Screenshot 2024-03-09 at 12 19 10 AM" src="https://github.com/hackclub/hcb/assets/28282096/a9e1a657-4a82-4b21-8bbd-be3b171d21d0">

2024-03-14 01:52 UTC, garyhtou commented on app/assets/stylesheets/application.scss
I'm not sure if it makes sense to add this CSS here for this very specific use case. Can we go without the strikeout CSS?

2024-03-14 01:52 UTC, garyhtou commented on app/views/users/edit_admin.html.erb
> +                <td class="inline-flex items-center w-100">
We also have an inactive state where the card has not been initially activated

2024-03-14 01:52 UTC, garyhtou commented on app/views/users/edit_admin.html.erb
> +                  <td><%= disbursement.aasm_state.humanize %></td>
```suggestion
                  <td><%= disbursement.state_text %></td>
```

2024-03-14 01:52 UTC, garyhtou commented on app/views/users/edit_admin.html.erb
> +                  <td><%= invoice.status.humanize %></td>
```suggestion
                  <td><%= invoice.state_text %></td>
```

2024-03-14 01:52 UTC, garyhtou commented on app/views/users/edit_admin.html.erb
> +                <td class="<%= "primary bold" if Date.parse("#{card.stripe_exp_month}/#{card.stripe_exp_year}") < Date.today %>"><%= Date.parse("#{card.stripe_exp_month}/#{card.stripe_exp_year}").str
Please move this logic into the model. Maybe create an `expired?` method

2024-03-24 01:05 UTC, sarthaktexas approved these changes

2024-03-24 01:06 UTC, sarthaktexas commented
closes #5537 as well

2024-03-25 18:24 UTC, garyhtou reviewed
🪄 looks good. @sarthaktexas will test and merge

2024-03-25 18:24 UTC, merged