Update the documentation name, icon and tooltip
hackclub/hcb pull request #5387
Opened 2024-03-04 16:02 UTC by devramsean0

## Summary of the problem

See #5342 

## Describe your changes

I updated the icon, name and tooltip in the nav bar. I also changed the title of the Documentation page to match

![image](https://github.com/hackclub/hcb/assets/81807361/7a7bbd4c-0497-4ab6-8414-f8bcca26c44f)

2024-03-04 17:42 UTC, garyhtou commented on app/views/events/_nav.html.erb
> +      <%= dock_item "Documents",
This looks like invalid ERB

2024-03-05 07:03 UTC, dwahbe commented on app/views/events/_nav.html.erb
> +        tooltip: "See legal documents, helpful tips, account statements, and FAQ",
I know I suggested this but I would update this to 
```suggestion
        tooltip: "View legal documents, account statements, and FAQ",
```

2024-03-05 08:02 UTC, sarthaktexas commented on app/views/events/_nav.html.erb
> +        tooltip: "See legal documents, helpful tips, account statements, and FAQ",
I concur with Dylan

2024-03-05 20:34 UTC, devramsean0 commented on app/views/events/_nav.html.erb
> +      <%= dock_item "Documents",
It appears to be valid to me,
Where do you think the error is?

2024-03-05 20:34 UTC, devramsean0 commented on app/views/events/_nav.html.erb
> +        tooltip: "See legal documents, helpful tips, account statements, and FAQ",
I also concur

2024-03-05 21:31 UTC, sarthaktexas requested changes

2024-03-05 21:31 UTC, sarthaktexas commented on app/views/events/_nav.html.erb
> +      <%= dock_item "Documents",
<img width="840" alt="Screenshot 2024-03-05 at 3 30 53 PM" src="https://github.com/hackclub/hcb/assets/28282096/0483cc47-2f7e-408b-af64-8c6605cfe3ee">
be so fr

2024-03-05 21:36 UTC, sarthaktexas commented
I sent you a corrected nav bar file Sean!

2024-03-11 09:35 UTC, sarthaktexas approved these changes

2024-03-11 09:37 UTC, merged