Add `LetterOpener` quicklink to HCB logo menu
hackclub/hcb pull request #5400
Opened 2024-03-06 16:33 UTC by malted

Also adds menu divider titles

![image](https://github.com/hackclub/hcb/assets/59726149/85610b93-71ba-4326-b9d2-cde42cbe9341)

2024-03-06 17:04 UTC, sampoder approved these changes
Thank you! This is really helpful

2024-03-08 06:04 UTC, sarthaktexas requested changes

2024-03-08 06:04 UTC, sarthaktexas commented on app/views/application/_header.html.erb
> +        <div class="menu__divider" data-label="Admin"></div>
what does the value of `data-label` do here?

2024-03-10 01:11 UTC, malted commented on app/views/application/_header.html.erb
> +        <div class="menu__divider" data-label="Admin"></div>
tl;dr

`&::after { content: attr(data-label) }`

2024-03-10 01:13 UTC, sarthaktexas approved these changes

2024-03-19 21:14 UTC, merged