Make card details copy-on-click-able
hackclub/hcb pull request #5408
Opened 2024-03-08 03:37 UTC by malted

does what it says on the tin

oh also refactoring

2024-03-08 05:54 UTC, sarthaktexas commented
# go to bed.

2024-03-08 05:58 UTC, sarthaktexas requested changes
it appears there is inconsistent logic across blocks of code.

2024-03-08 05:58 UTC, sarthaktexas commented on app/views/stripe_cards/_details.html.erb
> +    <% if stripe_card.virtual? %>
you check if it's virtual here, but not if the stripe_card is theirs.

2024-03-08 05:58 UTC, sarthaktexas commented on app/views/stripe_cards/_details.html.erb
> +          <% if stripe_card.user == current_user %>
here you check if the stripe_card is theirs.

2024-03-08 05:58 UTC, sarthaktexas commented on app/views/stripe_cards/_details.html.erb
> +    <% if stripe_card.user == current_user && stripe_card.virtual? %>
here you check both. why the inconsistency?

2024-03-08 05:58 UTC, sarthaktexas commented on app/views/stripe_cards/_details.html.erb
> +    <div>
can we fs-mask this too? or are we limiting the information that we mask to only sensitive content?

2024-03-19 21:30 UTC, sarthaktexas commented on app/views/stripe_cards/_details.html.erb
> +    <div>
WRONG try again 🤡🤡🤡

2024-03-19 21:36 UTC, malted commented on app/views/stripe_cards/_details.html.erb
> +    <div>
stop being a meanie

2024-03-23 07:51 UTC, sarthaktexas approved these changes
code looks good. i see two tooltips on the card number with diff directions, i can't test if that causes a problem or not but i trust.

2024-03-23 20:25 UTC, malted commented
The different directions are intended!

2024-03-23 20:25 UTC, merged

2024-03-23 21:28 UTC, garyhtou commented on app/views/stripe_cards/_details.html.erb
> +          <%= copy_to_clipboard(stripe_card.full_card_number, class: "w-fit", tooltip_direction: "e") do %>
@malted important feedback:

We should not expose the full card number to the front end unless it was explicitly asked for.

This is because we're tracking when card numbers are accessed
https://github.com/hackclub/bank/blob/34aecab447b76773f0e91fc128350c8530cb55af/app/controllers/stripe_cards_controller.rb#L54-L56

Please make it so that this tooltip does not appear until `@show_card_details` is true

cc @sarthaktexas

2024-03-23 21:29 UTC, garyhtou commented on app/views/stripe_cards/_details.html.erb
> +          <%= copy_to_clipboard(stripe_card.cvc, class: "w-fit", tooltip_direction: "e") do %>
Same thing applies here

2024-03-23 21:31 UTC, garyhtou commented on app/views/stripe_cards/_details.html.erb
> +          <%= copy_to_clipboard(stripe_card.full_card_number, class: "w-fit", tooltip_direction: "e") do %>
A more UX-friendly solution could be to keep this functionality by making it fetch the card number via a request then copy it to the clipboard