Fix `organizer_signed_in?`
hackclub/hcb pull request #5419
Opened 2024-03-09 22:00 UTC by malted

2024-03-09 23:20 UTC, garyhtou reviewed
I think removing the memorization may slow down all page loads

2024-03-14 20:31 UTC, malted commented
@garyhtou memoised. Does this look better?

2024-03-18 18:56 UTC, garyhtou requested changes

2024-03-18 18:56 UTC, garyhtou commented on app/helpers/sessions_helper.rb
> +      return false unless signed_in?
Returning inside a block will return from the entire method, not just the block. We likely want to use `next` here.

2024-03-18 18:56 UTC, garyhtou commented on app/helpers/sessions_helper.rb
> +      return false unless signed_in?
I'm not sure if it will store it inside the cache hash

2024-03-18 18:56 UTC, garyhtou commented on app/helpers/sessions_helper.rb
> +    @organizer_signed_in[memoization_key] ||= begin
When the block returns a falsey value (such as `false`), it will likely ignore the memorization in future calls.

[HCB TRIVIA - Ruby, Memoization using Or-Equals Operator.pdf](https://github.com/hackclub/hcb/files/14641141/HCB.TRIVIA.-.Ruby.Memoization.using.Or-Equals.Operator.pdf)

2024-03-18 18:56 UTC, garyhtou commented on app/helpers/sessions_helper.rb
> +    memoization_key = [event, current_user, as]
I believe we don't need `current_user` in the memoization key, because `organizer_signed_in?` is always called with the perspective of the current user

2024-07-29 19:16 UTC, closed without merging