Improve role explanation on invite modal
hackclub/hcb pull request #5428
Opened 2024-03-10 09:21 UTC by malted

![image](https://github.com/hackclub/hcb/assets/59726149/51ee53e0-1f6e-4b2c-a8b3-ae6f57693f28)

2024-03-12 17:48 UTC, sarthaktexas submitted a review, later dismissed

2024-03-12 17:48 UTC, sarthaktexas commented on app/views/events/_form_invite.erb
> +  <% admin_tools("mb2 flex g1 w-fit") do %>
we're using the renamed `admin_tool` method now
```suggestion
  <% admin_tool("mb2 flex g1 w-fit") do %>
```

2024-03-12 17:48 UTC, sarthaktexas commented on app/views/events/_organization_position_invite_pending.html.erb
> +              <%= role %><%= " ✔" if invite.role == role %>
Visually it shows selected, but I don't think this is accessible. Can you add an `aria-current` for screenreaders?

2024-03-12 17:48 UTC, sarthaktexas commented on app/views/events/_form_invite.erb
> +    </div>
This copy is a good start. I think making them a consistent format would be better. I specifically mean choosing between "Someone invited..." vs "Inviting someone..." What if we changed which one was displayed based on what was selected? (Alpine.js can do this easily)

2024-03-12 22:43 UTC, malted commented on app/views/events/_organization_position_invite_pending.html.erb
> +              <%= role %><%= " ✔" if invite.role == role %>
Done on both invites and pending invites.

2024-03-12 22:45 UTC, malted commented on app/views/events/_form_invite.erb
> +    </div>
It did change in response to selection before! @maxwofford suggested to keep it static - I agree with him.

2024-03-12 22:57 UTC, malted commented on app/views/events/_form_invite.erb
> +    </div>
Changed the copy!

2024-03-12 23:02 UTC, sarthaktexas commented on app/views/events/_form_invite.erb
> +    </div>
Ah, sorry then!

2024-03-12 23:13 UTC, sarthaktexas commented
How is your ERB Lint failing? It passes for me

2024-03-14 01:32 UTC, garyhtou commented
> How is your ERB Lint failing? It passes for me

Maybe there's a closing tag missing somewhere. it currently looks like this
![image](https://github.com/hackclub/hcb/assets/20099646/204ae130-f1cc-4989-b01b-9fb891008d96)

2024-03-14 01:34 UTC, garyhtou requested changes

2024-03-14 01:34 UTC, garyhtou commented on app/views/events/_organization_position_invite.html.erb
>          <p class="h2 bold m0"><%= position.user.name %></p>
It looks like some User Permission UI is leaking outside of the feature flag

2024-03-14 19:21 UTC, malted commented on app/views/events/_organization_position_invite.html.erb
>          <p class="h2 bold m0"><%= position.user.name %></p>
This was fixed in https://github.com/hackclub/hcb/pull/5483

2024-03-14 19:22 UTC, malted commented
@garyhtou Ok now I'm really confused. It looks normal for me.

2024-03-15 04:18 UTC, garyhtou approved these changes
thanks!

2024-03-15 04:18 UTC, garyhtou commented on app/views/events/_organization_position_invite.html.erb
>          <p class="h2 bold m0"><%= position.user.name %></p>
It _was_ un-fixed by this PR!!
![image](https://github.com/hackclub/hcb/assets/20099646/c8fc3cfb-c463-4762-844c-7b60b1d39b4d)

I've added a new commit to re-fix it

2024-03-15 04:18 UTC, garyhtou commented on app/views/events/_form_invite.erb
> +      </div>
After merging this PR, let's work on the copy for this

2024-03-15 04:18 UTC, garyhtou commented on app/views/events/_organization_position_invite_pending.html.erb
> +    Invited <%= relative_timestamp(invite.created_at) %> as a
After merging, let's come back to this card to do a copy edit/visual design. Here's what it currently looks like

![image](https://github.com/hackclub/hcb/assets/20099646/af6bba65-78bc-4f2b-83c4-6de5cb60c850)

2024-03-15 04:54 UTC, merged