Add settings feature toggle in org settings
hackclub/hcb pull request #5430
Opened 2024-03-10 09:51 UTC by malted

![image](https://github.com/hackclub/hcb/assets/59726149/03e92ae2-9a87-4b74-9c00-ed364d5c9acc)

2024-03-11 04:51 UTC, sarthaktexas requested changes
Add a background

2024-03-11 04:56 UTC, maxwofford commented
I'm fine with this merging without a background just for now because it's a feature flag! We should clarify though, can anyone toggle the feature flag currently?

2024-03-11 05:41 UTC, maxwofford commented
2 drafts you can use:

<img width="343" alt="amaziograph_DBC9F70E-9C41-45A4-A444-0EB6BE1EE33B amaziograph" src="https://github.com/hackclub/hcb/assets/5891442/c94cf6e0-25c8-46d0-a2ce-4e46540c760b">


![amaziograph_DBC9F70E-9C41-45A4-A444-0EB6BE1EE33B amaziograph](https://github.com/hackclub/hcb/assets/5891442/b5fed338-b525-4b5b-bc55-df7878b7d854)

2024-03-11 05:44 UTC, maxwofford commented
These aren't relevant to the feature, but still fun patterns:

![amaziograph_5FB89CDD-0783-4282-9984-CBF06D26DEBD amaziograph](https://github.com/hackclub/hcb/assets/5891442/2fe3235e-c42d-4352-87fb-de0f611b511e)
<img width="520" alt="amaziograph_45819717-5BC1-4088-B6F9-54AD1466CDC7 amaziograph" src="https://github.com/hackclub/hcb/assets/5891442/ebf9c074-044f-4cdc-8d6b-db5373efe7b6">

2024-03-15 20:03 UTC, malted commented
![image](https://github.com/hackclub/hcb/assets/59726149/bfdfe499-5776-4479-8d76-fb4c73a8750e)
![image](https://github.com/hackclub/hcb/assets/59726149/f11878b0-325d-4b42-b832-9bf20973158c)

2024-03-15 20:16 UTC, garyhtou reviewed
What happens to member roles when the feature gets disabled? Should they become managers? or silently stay as members? (mentioned in https://github.com/hackclub/hcb/issues/5533)

2024-03-15 20:16 UTC, garyhtou commented on app/views/events/edit.html.erb
> +    Disallow certain users from performing critical finanical actions.
Can we have a more descriptive copy here? Maybe even link to the `/roles` page

```erb
<%= link_to "learn more about the roles", roles_path %>
```

2024-03-15 20:57 UTC, malted commented
![image](https://github.com/hackclub/hcb/assets/59726149/eb7726f6-05a0-4e9c-890b-98e519b1a187)

![image](https://github.com/hackclub/hcb/assets/59726149/a7546283-a07b-4b57-98e2-09edde57bc3a)


All users and pending invites automatically become managers after the user accepts this dialogue

2024-03-18 19:00 UTC, garyhtou commented
@sarthaktexas can you do another review on this.

good to merge after @sarthaktexas's approval

2024-03-18 19:14 UTC, sarthaktexas requested changes

2024-03-18 19:14 UTC, sarthaktexas commented on app/views/events/edit.html.erb
> +    Disallow certain users from performing critical finanical actions.
```suggestion
    Disallow certain users from performing critical financial actions!
```

2024-03-18 19:14 UTC, sarthaktexas commented on app/assets/stylesheets/components/_features.scss
> +      opacity: 0.8;
```suggestion
      opacity: 0.3;
```

2024-03-18 19:15 UTC, sarthaktexas commented on app/assets/stylesheets/components/_features.scss
> +      opacity: 0.8;
Your choice if you want to keep this or not:
<img width="574" alt="Screenshot 2024-03-18 at 2 15 16 PM" src="https://github.com/hackclub/hcb/assets/28282096/e5e9ee81-21b6-4a7c-bc74-96a46b9081ac">

2024-03-18 19:16 UTC, malted commented on app/assets/stylesheets/components/_features.scss
> +      opacity: 0.8;
Looks good; cheers!

2024-03-18 19:17 UTC, malted commented
I work at a bank and spelled financial wrong 🎀

2024-03-18 19:19 UTC, sarthaktexas approved these changes

2024-03-18 19:20 UTC, merged