Reimbursements: Improved feature flags
hackclub/hcb pull request #5590
Opened 2024-03-16 18:03 UTC by YodaLightsabr

## Summary of the problem
Feature flags are user level

## Describe your changes
Feature flags are now org level and can only be enabled by users with the feature flag enabled

Also added a card to the org settings page only visible to users with the feature flag enabled

2024-03-16 18:05 UTC, sampoder commented on app/views/events/edit.html.erb
> +      Reimburse team members and let volunteer submit epenses directly in HCB!
```suggestion
      Reimburse team members and let volunteer submit expenses directly in HCB!
```

2024-03-16 18:07 UTC, sampoder commented on app/views/events/edit.html.erb
> +      Reimburse team members and let volunteer submit expenses directly in HCB!
```suggestion
      Reimburse team members and volunteers directly through HCB! It's our very own version of Expensify.
```

Thoughts on this copy?

2024-03-16 18:08 UTC, sarthaktexas requested changes

2024-03-16 18:08 UTC, sarthaktexas commented on app/views/events/edit.html.erb
> +        <%# link_to "Shipped!", enable_feature_path(feature: :transfers_2022_04_21), method: :post, class: 'btn bg-accent' %>
Why is this a comment?

2024-03-16 18:08 UTC, sarthaktexas commented on app/views/events/edit.html.erb
> +      Reimburse team members and let volunteer submit epenses directly in HCB!
```suggestion
      Reimburse team members and let volunteer submit expenses directly in HCB!
```

2024-03-16 18:14 UTC, YodaLightsabr commented on app/views/users/_nav.html.erb
> +      selected: local_assigns[:selected] == :reimbursements if current_user.events.flag_enabled(:reimbursements_2024_03_10).exists? %>
```suggestion
      selected: local_assigns[:selected] == :reimbursements if current_user.events.flag_enabled(:reimbursements_2024_03_10).exists? || Flipper.enabled?(:reimbursements_2024_03_10) %>
```

Check for any of users orgs having it _or_ for general availability

2024-03-16 18:22 UTC, sarthaktexas submitted a review, later dismissed

2024-03-16 18:23 UTC, sampoder submitted a review, later dismissed

2024-03-17 07:56 UTC, sampoder approved these changes
Code LGTM!

2024-03-17 07:58 UTC, merged