Add breakdown feature
hackclub/hcb pull request #5665
Opened 2024-03-21 00:10 UTC by manuthecoder

## **Description:**
This pull request includes the addition of a "Breakdown" button in the sidebar, providing users with comprehensive insights into project expenses. When clicked, this button opens a new page dedicated to showcasing various expense breakdown metrics, aiding users in better understanding their financial data.

## **New Features:**
- **Breakdown Button:** Added a new button in the sidebar for accessing expense breakdown details.
- **Breakdown Page:** Created a new page layout to display detailed expense breakdown information. Hover over a chart to export it as a PNG image. 

## **Expense Breakdown Metrics:**
- **Overall Balance by Date:** Displays the overall balance of expenses over different time periods.
- **Overall Change by Date:** Presents the overall change in expenses over different time periods.
- **Max Positive Change:** Highlights the maximum positive change in expenses.
- **Max Negative Change:** Highlights the maximum negative change in expenses.
- **Expenses by Tag:** Categorizes expenses based on predefined tags for easier tracking.
- **Expenses by User:** Segregates expenses based on the user who incurred them.
- **Expenses by Merchant:** Organizes expenses based on the merchant where the transaction occurred.
- **Expenses by Category:** Groups expenses based on predefined categories for better understanding and analysis.

## **Screenshots**
![127 0 0 1_3000_hack_the_seas_breakdown](https://github.com/hackclub/hcb/assets/77016441/88e70584-e9dd-4da0-b494-1fdbe97c9832)

## **Important note!**
I've added fake data which appears _only on development_. Remove this before deploying to production

2024-03-21 00:29 UTC, sampoder commented
WOW! Awesome. I'll check this out later this week! (Midterm season sorry)

2024-03-21 00:30 UTC, garyhtou commented
Sooo cool!

2024-03-26 04:23 UTC, sampoder requested changes
This is looking really good! Just dropped some comments about what we need to do before this gets merged, feel free to DM me any questions you've got about the code :D

2024-03-26 04:23 UTC, sampoder commented on app/assets/stylesheets/_dark.scss
> +  }
Could you instead use these classes: `border b--muted` on the card?

2024-03-26 04:23 UTC, sampoder commented on app/assets/stylesheets/components/_cards.scss
> +}
Let's use the standard card design with the same border-radius

2024-03-26 04:23 UTC, sampoder commented on app/controllers/events_controller.rb
> +      }
Can you work through making the changes in this file to make them more readable? This code I originally wrote was janky and was more of a proof of concept.

2024-03-26 04:23 UTC, sampoder commented on app/models/organizer_position.rb
> +
Same comment as above, let's make this more readable!

2024-03-26 04:23 UTC, sampoder commented on app/views/events/breakdown.html.erb
> +</style>
Let's put this in a dedicated file

2024-04-21 07:20 UTC, manu-gurudath commented
idk what the last commit did i just clicked on a button 😭

2024-04-21 07:21 UTC, manu-gurudath commented
I just made changes based on the code you reviewed. Let me know if anything else needs to be changed! 🚀

2024-05-08 06:59 UTC, sampoder submitted a review, later dismissed
I'm really liking the look of this & would be happy to merge as-is. I've added this cool GitHub heatmap. This is the current state:

![image](https://github.com/hackclub/hcb/assets/39828164/fe964b02-aa4f-44fd-b8a8-3c4f11efce27)

My only ask is that we feature flag this and collect some user feedback before showing this to everyone. We'll probably want to make some changes.

Let's also get some other engineers' eyes on this.

2024-05-08 07:01 UTC, manu-gurudath commented
hi! I think It would look way more aesthetically pleasing if you added the cards back instead of leaving the charts without a background color/outline

2024-05-08 07:03 UTC, manu-gurudath commented
also if you could add a heading/label to the heatmap which said "expenses in the past year" it would look more intuitive

2024-05-08 07:04 UTC, manu-gurudath commented
also I noticed the chart labels getting cut off
![image](https://github.com/hackclub/hcb/assets/77016441/967bc7ef-e040-4d63-a422-134a8876cc57)

2024-05-30 11:26 UTC, jaspermayone commented
So cool, happy to test this!

2024-06-11 05:03 UTC, manu-gurudath commented
not sure what happened here...
![image](https://github.com/hackclub/hcb/assets/77016441/3112d00f-a9d7-405e-b71b-fe5d299ac725)

2024-06-18 17:38 UTC, sampoder commented on app/models/tag.rb
> +
```suggestion
```

2024-06-18 17:38 UTC, sampoder commented on app/views/events/_nav.html.erb
> +    <%= dock_item "Breakdown",
Fill Flipper flag

2024-06-18 19:11 UTC, garyhtou commented on app/assets/stylesheets/_utilities.scss
Move into breakdown component css file

2024-06-18 19:11 UTC, garyhtou commented on app/assets/stylesheets/components/_breakdown.scss
> +}
```suggestion
}

```

2024-06-18 19:11 UTC, garyhtou commented on app/assets/stylesheets/components/_cards.scss
> +.card-breakdown {
maybe move into breakdown component?

```suggestion
.card--breakdown {
```

2024-06-18 19:11 UTC, garyhtou commented on app/controllers/events_controller.rb
> +    end
```suggestion
    authorize @event
```

2024-06-18 19:39 UTC, garyhtou reviewed
let's feature flag & merge!

2024-06-18 19:39 UTC, garyhtou commented on app/controllers/events_controller.rb
> +    @maximum_negative_change = @heatmap.values.map { |change| change[:negative] }.min || 0
```suggestion
    @maximum_positive_change = @heatmap.values.max { |change| change[:positive] } || 0
    @maximum_negative_change = @heatmap.values.min { |change| change[:negative] } || 0
```

2024-06-18 19:39 UTC, garyhtou commented on app/policies/event_policy.rb
> +    is_public || admin_or_user?
For the time being, let's not making it transparent yet

```suggestion
    admin_or_user?
```

2024-06-18 19:39 UTC, garyhtou commented on app/services/breakdown_engine/categories.rb
> +                          .joins("LEFT JOIN canonical_transactions ct ON raw_stripe_transactions.id = ct.transaction_source_id")
```suggestion
                          .joins("LEFT JOIN canonical_transactions ct ON raw_stripe_transactions.id = ct.transaction_source_id and ct.transaction_source_type = ${RawStripeTransaction.class}")
```

2024-06-18 19:39 UTC, garyhtou commented on app/services/breakdown_engine/heatmap.rb
> +      end
```suggestion
      last_date = heatmap.keys.max.to_date

      ((last_date + 1.day).to_date..6.days.from_now.to_date).each do |date|
        heatmap[date.to_s] = {
          negative: 0,
          positive: 0
        }
      end
```

2024-06-18 19:39 UTC, garyhtou commented on app/services/breakdown_engine/heatmap.rb
> +      range = start.to_date...0.days.ago.to_date
```suggestion
      range = start.to_date...6.days.from_now.to_date
```

2024-06-18 19:39 UTC, garyhtou commented on app/services/breakdown_engine/merchants.rb
> +           ELSE TRIM(UPPER(SPLIT_PART(raw_stripe_transactions.stripe_transaction->'merchant_data'->>'name', '*', 1)))
do the `THEN` and `ELSE` need to be switched?

2024-06-18 19:39 UTC, garyhtou commented on app/services/breakdown_engine/merchants.rb
> +                          .joins("LEFT JOIN canonical_transactions ct ON raw_stripe_transactions.id = ct.transaction_source_id")
`transaction_source_type` problem from above

2024-06-18 19:39 UTC, garyhtou commented on app/services/breakdown_engine/tags.rb
> +      tags = @event.tags.each_with_object({}) do |tag, hash|
```suggestion
      tags = @event.tags.includes(hcb_codes: [:canonical_transactions, :canonical_pending_transactions]).each_with_object({}) do |tag, hash|
```

2024-06-18 19:39 UTC, garyhtou commented on app/services/breakdown_engine/tags.rb
> +      tags.select { |key, value| value > 0 }
```suggestion
      tags = @event.tags.includes(hcb_codes: [:canonical_transactions, :canonical_pending_transactions]).each_with_object({}) do |tag, hash|
        amount_cents_sum = tag.hcb_codes.sum do |hcb_code|
          [hcb_code.amount_cents, 0].min
        end
        hash[tag.label] = (amount_cents_sum * -1).to_f / 100 if amount_cents_sum > 0
      end
```

2024-06-18 19:39 UTC, garyhtou commented on app/services/breakdown_engine/users.rb
> +                                         .sum(:amount_cents).abs.to_f / 100
```suggestion
                                         .sum(:amount_cents).to_f / 100 * -1
```

2024-06-18 19:39 UTC, garyhtou reviewed
let's feature flag & merge!

2024-06-18 20:20 UTC, merged