Create `callout` partial and use for unauthorized transfers
hackclub/hcb pull request #5673
Opened 2024-03-21 07:02 UTC by malted

From:
![image](https://github.com/hackclub/hcb/assets/59726149/c110c13e-8bb8-4989-b948-611530e4daa2)

To:
![image](https://github.com/hackclub/hcb/assets/59726149/173e78a1-71b3-4f23-b5f9-9fd44d589bee)

This brings them in line with the rest of HCB's design system.

This PR also adds the following callout for members on transfer forms:
![image](https://github.com/hackclub/hcb/assets/59726149/4fb4417e-860a-493b-8900-b1fccaf2cb73)

2024-03-21 07:51 UTC, malted commented
this was tedious ugh

2024-03-21 18:35 UTC, garyhtou requested changes

2024-03-21 18:35 UTC, garyhtou commented on app/views/application/_callout.html.erb
> +  <% unless local_assigns[:body].nil? %>
This should be a block rather than a parameter.

```erb
<%= render "callout" do %>
  <p>body</p>
<% end %>
```

2024-03-21 18:35 UTC, garyhtou commented on app/views/application/_callout.html.erb
> +<% questions = local_assigns[:questions].nil? ? false : questions %> <!-- defaults to false -->
rename this to `questions_footer` for more clarify!

2024-03-21 18:35 UTC, garyhtou commented on app/views/application/_callout.html.erb
> +  <% unless local_assigns[:body].nil? %>
This should remove the need for `raw_html`

2024-03-21 18:36 UTC, garyhtou commented
Let me know if you need any help with these changes. Please also fix ERB lint!

2024-03-21 18:45 UTC, malted commented on app/views/application/_callout.html.erb
> +  <% unless local_assigns[:body].nil? %>
But what about `title`? Some usages have html in the title too.

2024-03-21 19:11 UTC, garyhtou commented on app/views/application/_callout.html.erb
> +  <% unless local_assigns[:body].nil? %>
i think we can do

```ruby
<% title =  capture do %>
  <b>HTML</b> is cool
<% end %>

<% render "callout" title:, do %>
  <p>body</p>
<% end %>
```

2024-03-22 00:12 UTC, malted commented on app/views/application/_callout.html.erb
> +<% questions = local_assigns[:questions].nil? ? false : questions %> <!-- defaults to false -->
Done!

2024-03-25 22:04 UTC, garyhtou reviewed
you'll need to update the rest of the usage after the refactor

2024-03-29 20:40 UTC, garyhtou commented on app/views/ach_transfers/new.html.erb
> +<% if @event.present? && !policy(@event).new_transfer? %>
```suggestion
<% unless policy(@event).new_transfer? %>
```

2024-03-29 20:40 UTC, garyhtou commented on app/views/check_deposits/index.html.erb
> +    <%= render "callout2", type: "warning", title: "Important info about depositing checks", questions_footer: true do %>
```suggestion
    <%= render "callout", type: "warning", title: "Important info about depositing checks", questions_footer: true do %>
```

2024-03-29 20:40 UTC, garyhtou commented on app/views/disbursements/new.html.erb
> +<% end %>
Because this page has a dynamic `@source_event`, let's not add this until we can dynamically render these messages based on the currently selected source event

```suggestion
```

2024-03-29 20:40 UTC, garyhtou commented on app/views/events/_no_transfer_permission_callout.html.erb
> +<%= render "callout", type: "info", title: "You can't transfer money." do %>
```suggestion
<%= render "callout", type: "info", title: "You can't transfer money" do %>
```

2024-03-29 20:40 UTC, garyhtou commented on app/views/events/_no_transfer_permission_callout.html.erb
> +    <li>To learn more, visit the <%= link_to "user roles explainer page", roles_path %>.</li>
Handle explanation for demo mode

2024-03-29 20:40 UTC, garyhtou commented on app/views/events/_no_transfer_permission_callout.html.erb
> +<%= render "callout", type: "info", title: "You can't transfer money." do %>
Move the `if !policy(@event).new_transfer?` into this partial.

this means the partial need to take in an event param

2024-03-29 20:40 UTC, garyhtou commented on app/views/invoices/index.html.erb
> +            w_fit: false,
this `w_fit` param no longer exists. i think you need to pass it in as a `class` param

2024-03-29 20:40 UTC, garyhtou commented on app/views/application/_callout.html.erb
> +  <% end %>
we take in a `footer` param. if `footer == :questions` then we render the questions footer. otherwise, if `footer.present?`, then we render whatever is in `footer`.

this allow us to do stuff like this:
```erb
<%= render "callout" footer: "contact us for help" %>
```

2024-04-02 21:58 UTC, garyhtou approved these changes

2024-04-02 22:02 UTC, merged