[User Roles] Let non-managers see org setting (but disable form)
hackclub/hcb pull request #5742
Opened 2024-03-25 20:18 UTC by malted

Disables all form fields for members

![image](https://github.com/hackclub/hcb/assets/20099646/aa81a575-f98c-4077-8cad-90efa4fa7728)

2024-03-25 23:14 UTC, garyhtou requested changes

2024-03-25 23:14 UTC, garyhtou commented on app/policies/event_policy.rb
>    def admin_or_user?
https://github.com/hackclub/bank/blob/34aecab447b76773f0e91fc128350c8530cb55af/app/controllers/stripe_cards_controller.rb#L69 and https://github.com/hackclub/bank/blob/34aecab447b76773f0e91fc128350c8530cb55af/app/controllers/stripe_cards_controller.rb#L74 will break if this is private!!

2024-03-25 23:14 UTC, garyhtou commented on app/policies/event_policy.rb
> +    admin_or_user?
This policy is good. However, on the page, a member can still type into some fields. Please double check that everything's disabled, including form fields

2024-03-25 23:25 UTC, garyhtou commented on app/policies/event_policy.rb
>    def admin_or_user?
Fixed by https://github.com/hackclub/hcb/pull/5670

2024-03-26 19:53 UTC, malted commented on app/policies/event_policy.rb
> +    admin_or_user?
Everything is disabled!

2024-03-26 20:48 UTC, garyhtou commented on app/views/events/_form.html.erb
> +      <% if policy(@event).remove_logo? %>
```suggestion
      <% if policy(@event).update? %>
```

2024-03-26 20:48 UTC, garyhtou commented on app/views/events/_form.html.erb
> +      <% if policy(@event).remove_background_image? %>
```suggestion
      <% if policy(@event).update? %>
```

2024-03-26 20:57 UTC, garyhtou approved these changes

2024-03-26 21:00 UTC, merged