Allow users to modify their own events (date & address)
hackclub/hcb pull request #58
Opened 2019-01-12 18:33 UTC by tmb

2019-01-12 18:41 UTC, lachlanjc requested changes
Nice work here, let’s clean this up before merging though

2019-01-12 18:41 UTC, lachlanjc commented on app/controllers/events_controller.rb
> +      params.require(:event).permit(
Should be all on one line

2019-01-12 18:41 UTC, lachlanjc commented on app/controllers/events_controller.rb
> +
Extra line here

2019-01-12 18:41 UTC, lachlanjc commented on app/views/events/show.html.erb
> +
Fix indentation here

2019-01-12 18:41 UTC, lachlanjc commented on app/controllers/events_controller.rb
> +      if @event.update(event_params)
This is rather inelegant. Could avoid the repeating through `@event.update(current_user.admin? ? event_params : user_event_params)`

2019-01-12 20:19 UTC, tmb commented on app/controllers/events_controller.rb
> +      if @event.update(event_params)
ah, thanks for this. I figured there was some less ugly way to do it 👍

2019-01-12 20:23 UTC, tmb commented on app/controllers/events_controller.rb
> +      if @event.update(event_params)
ok also that's so cool you can do ternary as method params omg

2019-01-12 20:41 UTC, maxwofford commented on app/controllers/events_controller.rb
> +    end
Trailing whitespace – your editor might have a way to automatically remove these

2019-01-13 05:07 UTC, tmb commented
merging in!

2019-01-13 05:07 UTC, merged