Refactor `InvoicePolicy`
hackclub/hcb pull request #5804
Opened 2024-03-27 21:37 UTC by malted

2024-03-27 21:42 UTC, cjdenio requested changes

2024-03-27 21:42 UTC, cjdenio commented on app/policies/invoice_policy.rb
> +    admin_or_user? && !record.unapproved?
This will error since `admin_or_user?` expects `record` to be an `Invoice`.

one solution: add a common method to `ApplicationPolicy` like
```ruby
class ApplicationPolicy
  # ...

  def admin_or_user?
    event = record.is_a?(Event) ? event : record.try(:event)
    user&.admin? || (user && event && event&.users&.include?(user))
  end
end

2024-03-27 21:44 UTC, cjdenio commented on app/policies/invoice_policy.rb
> +    (is_public? || admin_or_user?) && !unapproved?
`is_public?` isn't defined

2024-03-27 22:24 UTC, garyhtou commented on app/policies/invoice_policy.rb
> +    admin_or_user? && !record.unapproved?
`event = record.is_a?(Event) ? event : record.try(:event)` is slow. let's just define a method in InvoicePolicy — we'll make a better shared solution later

2024-03-28 22:08 UTC, malted commented on app/policies/invoice_policy.rb
> +    (is_public? || admin_or_user?) && !unapproved?
Fixed!

2024-03-29 20:16 UTC, closed without merging

2024-03-29 20:16 UTC, garyhtou commented
after a review of this pr on call with @malted, we decided this is no longer needed