Remove Unused files and helpers referencing SVB
hackclub/hcb pull request #5816
Opened 2024-03-28 05:09 UTC by aramshiva

Fixes #4984.
Removes unused SVB files/helpers

2024-03-28 05:18 UTC, aramshiva commented
I'll do some extra checks once preview is deployed as don't want to make sure I broke something.

2024-03-28 05:25 UTC, aramshiva commented
![ScreenShot 2024-03-27 at 22 25 09@2x](https://github.com/hackclub/hcb/assets/79479940/5639a041-4d01-4360-97d4-d573daf5bd87)
@garyhtou can you provide logs?

2024-03-28 21:35 UTC, garyhtou commented
@cjdenio when you get a chance, could you review this?

2024-03-29 14:20 UTC, cjdenio requested changes
I see the test for `Parsers::SiliconValleyBank` was removed, but the service itself was not— we should be removing both at the same time

2024-03-29 14:20 UTC, cjdenio commented on app/services/transaction_engine/transaction_csv_service/upload.rb
> -        transaction_csv.file.open do |f|
This service should be completely removed— deleting these three lines just makes it do nothing

2024-04-26 19:48 UTC, cjdenio approved these changes

2024-04-26 19:50 UTC, merged