💳 Add personalization design functionality to Stripe cards
hackclub/hcb pull request #5817
Opened 2024-03-28 05:40 UTC by YodaLightsabr

## Summary of the problem
All of HCB's Stripe cards are black with the HCB logo on it. That's cool and all, but it would be nice if organizations could have personalized card designs so that they wouldn't confuse their cards.

## Describe your changes
This PR creates the `StripeCard::PersonalizationDesign` model and syncs it with Stripe. It automatically creates personalization designs for events whenever their name changes, and there's a one time job allowing us to backfill designs. Admins also have the ability to create and manage designs.

This has been tested with Test Data in Stripe.

Some screenshots of the UI:

| <img width="625" alt="image" src="https://github.com/hackclub/hcb/assets/76178582/f423724b-7428-46a7-a6f7-9f743ecb9e2e"> | <img width="1171" alt="image" src="https://github.com/hackclub/hcb/assets/76178582/66ba1c61-5641-4e70-9b19-53a7f652c16c"> |
|:--------:|:--------:|
| Design Selection Page | Admin Designs Page |

2024-04-01 21:43 UTC, garyhtou approved these changes
Let's create a `StripeCard::PersonalizationDesign`
- It should sync to Stripe
- Have a `stripe_id`
- has_many :stripe_cards
- has_one_attached :logo

Hard code Physical Bundles (white vs black plastic cards), and store their stripe IDs in the Rails credentials. Also create them in stripe test mode and add the IDs.

```ruby
class StripeCard
  belongs_to :personalization_design, optional: true
end
```

2024-04-01 21:43 UTC, garyhtou requested changes
whoops, didn't mean to approve

2024-04-01 21:45 UTC, garyhtou commented
Handle webhook approvals

2024-04-30 00:39 UTC, garyhtou submitted a review, later dismissed
**Re: Stripe gem version**
Get a list of breaking changes from Stripe gem versions 9 and 10. Then, for each breaking change, comment on whether this affects us


Overall, let's pare this down to the smallest MVP. where orgs by default have a personalization design of their logo in text on a black card.

2024-04-30 00:39 UTC, garyhtou commented on app/models/stripe_card/personalization_design.rb
> +#  stripe_physical_bundle :string
this should be suffixed with `id`

2024-04-30 00:39 UTC, garyhtou commented on app/services/stripe_service.rb
> +  def self.physical_bundles
```suggestion
  def self.physical_bundle_ids
```

2024-04-30 00:39 UTC, garyhtou commented on app/services/stripe_card_service/personalization_design/create.rb
> +        pd
wrap in transaction

2024-04-30 00:39 UTC, garyhtou commented on app/models/event.rb
> +    file = URI.open("https://hcb-cc.hackclub.dev/api/embeds/bank?name=#{URI.encode_uri_component(name)}")
does this file need to be closed?

2024-05-02 01:57 UTC, sampoder commented
Re Stripe library:

* https://github.com/stripe/stripe-ruby/releases/tag/v9.0.0
* https://github.com/stripe/stripe-ruby/releases/tag/v10.0.0

Are the two releases with breaking changes that we need to review

2024-07-10 17:00 UTC, garyhtou reviewed
After merge:
- Add a mailer: "Your chosen design is unavailable"

2024-07-10 17:00 UTC, garyhtou commented on app/assets/stylesheets/components/_physical_cards.scss
> +}
```suggestion
}

```

2024-07-10 17:00 UTC, garyhtou commented on app/controllers/admin_controller.rb
> +    @q = params[:q].present? ? params[:q] : nil
```suggestion
    @q = params[:q].presence
```

2024-07-10 17:00 UTC, garyhtou commented on app/controllers/admin_controller.rb
> +    @pending = params[:pending] == "1" ? true : nil
```suggestion
    @pending = params[:pending] == "1"
```

2024-07-10 17:00 UTC, garyhtou commented on app/controllers/admin_controller.rb
> +    @event_id = params[:event_id].present? ? params[:event_id] : nil
```suggestion
    @event_id = params[:event_id].presence
```

2024-07-10 17:00 UTC, garyhtou commented on app/controllers/admin_controller.rb
> +    relation = relation.search(@q) if @q
does this `search` method exist?

2024-07-10 17:00 UTC, garyhtou commented on app/controllers/stripe_cards/personalization_designs_controller.rb
> +      @design.update!(common: true)
```suggestion
      @design.update!(common: true, event: nil)
```

2024-07-10 17:00 UTC, garyhtou commented on app/controllers/stripe_cards_controller.rb
> +      stripe_card_personalization_design_id: sc[:stripe_card_personalization_design_id] || event.stripe_card_personalization_designs.select { |d| d.stripe_name.starts_with?("#{event.name} Black Card"
```suggestion
      stripe_card_personalization_design_id: sc[:stripe_card_personalization_design_id] || event.default_stripe_card_personalization_design&.id
```

```ruby
# event.rb
def default_stripe_card_personalization_design
  stripe_card_personalization_designs.where("stripe_name like '#{event.name} Black Card%'").first
end
```

2024-07-10 17:00 UTC, garyhtou commented on app/models/event.rb
> +  before_update :generate_stripe_card_designs, if: -> { name_changed? }
Does this work when creating a new event?

2024-07-10 17:00 UTC, garyhtou commented on app/models/event.rb
> +  before_update :generate_stripe_card_designs, if: -> { name_changed? }
move this to after_commit

2024-07-10 17:00 UTC, garyhtou commented on app/models/event.rb
> +      URI.open("https://hcb-cc.hackclub.dev/api/embeds/bank?name=#{URI.encode_uri_component(name)}") do |file|
What happens if the name contains unicode? (emojis)

2024-07-10 17:00 UTC, garyhtou commented on app/models/stripe_card.rb
> +  belongs_to :personalization_design, foreign_key: "stripe_card_personalization_design_id", class_name: "StripeCard::PersonalizationDesign", optional: true
After merge, backfill the default black card into production (`ipcd_1OyaidFSaumjmb9rxEmwLrcI`).

then, make this association required.

2024-07-10 17:00 UTC, garyhtou commented on app/models/stripe_card/personalization_design.rb
> +    scope :white, -> { where(stripe_physical_bundle: StripeService.physical_bundle_ids[:white]) }
```suggestion
    scope :black, -> { where(stripe_physical_bundle_id: StripeService.physical_bundle_ids[:black]) }
    scope :white, -> { where(stripe_physical_bundle_id: StripeService.physical_bundle_ids[:white]) }
```

2024-07-10 17:00 UTC, garyhtou commented on app/models/stripe_card/personalization_design.rb
> +    scope :white, -> { where(stripe_physical_bundle: StripeService.physical_bundle_ids[:white]) }
Double check these work

2024-07-10 17:00 UTC, garyhtou commented on app/models/stripe_card/personalization_design.rb
> +
```suggestion
```

2024-07-10 17:00 UTC, garyhtou commented on app/models/stripe_card/personalization_design.rb
> +    end
recommendation: create a `name` method

2024-07-11 19:54 UTC, garyhtou commented on app/services/stripe_card_service/create.rb
> +      @stripe_personalization_design_id = @stripe_card_personalization_design_id ? StripeCard::PersonalizationDesign.find(@stripe_card_personalization_design_id)&.stripe_id : nil
```suggestion
      @stripe_personalization_design_id = @stripe_card_personalization_design_id ? StripeCard::PersonalizationDesign.find(@stripe_card_personalization_design_id).stripe_id : nil
```

2024-07-11 19:54 UTC, garyhtou commented on app/services/stripe_card_service/personalization_design/create.rb
> +
```suggestion
      def carrier_text
        header_body = "Visit hack.af/activate to activate your new card#{" for #{@event.name}" if @event.present?} from any device"

        {
          header_title: carrier_text_header_title,
          header_body:,
          footer_title: "https://hack.af/activate",
          footer_body: "Visit hack.af/activate to activate from any device"
        }
      end

      def carrier_text_header_title
        text = "HCB card for #{@event.name}"

        return text if @event.present? && text.length <= 30

        "Your new HCB card is here"
      end

```

2024-07-11 19:54 UTC, garyhtou commented on app/services/stripe_card_service/personalization_design/create.rb
> +        pd = StripeCard::PersonalizationDesign.create(event: @event, common: @event.nil? && @common)
```suggestion
        pd = StripeCard::PersonalizationDesign.create!(event: @event, common: @common)
```

2024-07-11 19:54 UTC, garyhtou commented on app/services/stripe_card_service/personalization_design/create.rb
> +                                                                       physical_bundle: StripeService.physical_bundle_ids[@color],
Before calling Stripe, check that the physical bundle id exists

2024-07-11 19:54 UTC, garyhtou commented on app/services/stripe_card_service/personalization_design/create.rb
> +                                                                     }).id
wrap in transaction

2024-07-11 19:54 UTC, garyhtou commented on app/views/admin/stripe_card_personalization_designs.html.erb
> +  <% @common_designs.compact.each do |design| %>
```suggestion
  <% @common_designs.each do |design| %>
```

2024-07-11 19:54 UTC, garyhtou commented on app/views/admin/stripe_card_personalization_designs.html.erb
> +          <%= design.stripe_name&.sub(" (#{design.id})", "*") %>
Use the new `name` method

2024-07-11 19:54 UTC, garyhtou commented on app/views/admin/stripe_card_personalization_designs.html.erb
> +<h2>Organization & Private Designs</h2>
```suggestion
<h2>All Designs</h2>
```

2024-07-11 19:54 UTC, garyhtou commented on app/controllers/admin_controller.rb
> +    @event_designs = relation.not_common
```suggestion
    @event_designs = relation
```

2024-07-11 19:54 UTC, garyhtou commented on app/models/stripe_card.rb
> +  belongs_to :personalization_design, foreign_key: "stripe_card_personalization_design_id", class_name: "StripeCard::PersonalizationDesign", optional: true
validate design belongs to same event as this card's event

2024-07-11 19:54 UTC, garyhtou commented on app/views/stripe_cards/_form.html.erb
> +    <% end %>
restructure the nesting to be
```
if
  admin tool
    designs = 
```

2024-07-11 19:54 UTC, garyhtou commented on app/views/stripe_cards/_form.html.erb
> +  <%# form.hidden_field :stripe_card_personalization_design_id, value: "1" %>
can this be removed?

2024-07-11 19:54 UTC, garyhtou commented on app/services/stripe_card_service/create.rb
> +      @stripe_personalization_design_id = @stripe_card_personalization_design_id ? StripeCard::PersonalizationDesign.find(@stripe_card_personalization_design_id)&.stripe_id : nil
after merge and backfilling prod default stripe card design, you'll want to set the default here, rather than passing `nil` to stripe.

2024-07-11 19:54 UTC, garyhtou commented on app/models/stripe_card.rb
> +  belongs_to :personalization_design, foreign_key: "stripe_card_personalization_design_id", class_name: "StripeCard::PersonalizationDesign", optional: true
validate personalization_design.nil? when virtual

2024-07-11 19:54 UTC, garyhtou commented on app/models/stripe_card/personalization_design.rb
> +    end
https://github.com/hackclub/bank/blob/d5d2b851d37efc80413b34c82b498053814bae6a/app/models/concerns/has_stripe_dashboard_url.rb#L3

2024-07-11 19:54 UTC, garyhtou commented on app/views/stripe_cards/_stripe_card.html.erb
> +    <div class="stripe-card__overlay"></div>
is this needed?

2024-07-11 19:54 UTC, garyhtou commented
🪄

2024-07-12 19:23 UTC, sampoder commented on app/models/event.rb
> +      URI.open("https://hcb-cc.hackclub.dev/api/embeds/bank?name=#{URI.encode_uri_component(name)}") do |file|
They'll be rendered and rejected

2024-07-12 21:01 UTC, merged