[User Roles] Show a transfer permission warning on `/disbursements/new` when the user has insufficient perm in the selected `from` org
hackclub/hcb pull request #5885
Opened 2024-04-02 19:34 UTC by malted

![image](https://github.com/hackclub/hcb/assets/59726149/6dddd261-9923-4d62-9ab0-82feed3a2b2e)

In this scenario, I am a member (and not a manager) of the Expensicon 2023 event.

2024-04-02 20:19 UTC, malted commented
~~Note to self: use `x-cloak`~~

2024-04-02 23:31 UTC, malted commented
@cjdenio would like your input here

What magical concoction of `x-effect` and co. would be needed to avoid `"x-bind:disabled": "disabled && !JSON.parse(JSON.stringify(managerEvents)).includes(parseInt(sourceEventInput))"` on every single form element?

2024-04-02 23:41 UTC, malted commented
Nvm! Solved it.

2024-04-02 23:56 UTC, malted commented on app/views/disbursements/_form.html.erb
> +  <div x-show="!JSON.parse(JSON.stringify(managerEvents)).includes(parseInt(sourceEventInput))" x-transition x-cloak>
```suggestion
  <div x-show="!disabled" x-transition x-cloak>
```

2024-04-03 20:11 UTC, cjdenio requested changes
- The "you can't transfer money" callout should not render if you don't have a source event selected
- HCB admins should be able to transfer from any organization

2024-04-03 20:11 UTC, cjdenio commented on app/views/disbursements/_form.html.erb
> +                disabled = !JSON.parse(JSON.stringify(managerEvents)).includes(parseInt(sourceEventInput)) || playgroundSourceEvent;
These could be replaced with [getters](https://alpinejs.dev/directives/data#getters)

2024-04-03 20:11 UTC, cjdenio commented on app/views/disbursements/_form.html.erb
> +              }",
Writing the JSON in Ruby is better practice since it prevents malicious code injection (though there are no such vulnerabilities here) 

```suggestion
              html: {"x-data" => {
                fee: nil,
                sourceEventInput: @source_event&.id,
                managerEvents: current_user.organizer_positions.where(role: :manager).pluck(:event_id),
                playgroundEvents: current_user.events.where(demo_mode: true).pluck(:event_id),
                disabled: nil,
                playgroundSourceEvent: nil,
              }.to_json,
```

2024-04-03 20:11 UTC, cjdenio commented on app/views/disbursements/_form.html.erb
> +                sourceEventInput: #{@source_event&.id || "null"},
Change this to `sourceEventInput: null,` and add `.fill` to the `x-model`: https://alpinejs.dev/directives/model#fill

2024-04-04 15:00 UTC, malted commented on app/views/disbursements/_form.html.erb
> +                sourceEventInput: #{@source_event&.id || "null"},
Done! Cheers

2024-04-04 19:07 UTC, malted commented on app/views/disbursements/_form.html.erb
> +                disabled = !JSON.parse(JSON.stringify(managerEvents)).includes(parseInt(sourceEventInput)) || playgroundSourceEvent;
Done!

2026-03-02 02:06 UTC, closed without merging