[Reimbursements] Contact operations to migrate from Expensify
hackclub/hcb pull request #5886
Opened 2024-04-02 20:40 UTC by sampoder

![image](https://github.com/hackclub/hcb/assets/20099646/053a803c-b458-4ff2-a460-3e6471832a1a)

2024-04-02 20:57 UTC, malted commented
```erb
<%= render "callout", title: "Looking for Expensify?", footer: :questions do %>
	<p class="m0">We have our own reimbursement tool now, which we recommend using instead! #{link_to "Learn more here" foo_path}</p>
<% end %>
```

Depends on https://github.com/hackclub/hcb/pull/5673

2024-04-03 00:09 UTC, garyhtou approved these changes

2024-04-03 00:09 UTC, garyhtou requested changes
oo one sec

2024-04-03 00:14 UTC, garyhtou approved these changes

2024-04-03 00:17 UTC, merged