[Appsignal] Configure Frontend Error Reporting
hackclub/hcb pull request #6012
Opened 2024-04-13 20:22 UTC by sampoder

Pretty simple, based on https://docs.appsignal.com/guides/configuration.html#front-end-javascript.

Closes https://github.com/hackclub/hcb/issues/4892.

2024-04-13 20:23 UTC, sampoder commented on app/javascript/appsignal.js
> +        key: '<YOUR FRONTEND API KEY>',
@garyhtou I can't access the page to get the API keys for Appsignal, can you get me one and help me put it in here?

2024-04-26 17:04 UTC, cjdenio requested changes

2024-04-26 17:04 UTC, cjdenio commented on app/javascript/controllers/index.js
> +  installErrorHandler(appsignal, application)
This gets overwritten by Airbrake since a Stimulus app can only have 1 error handler. See [the source for @appsignal/stimulus](https://unpkg.com/browse/@appsignal/stimulus@1.0.18/dist/esm/index.js)

2024-04-26 20:42 UTC, sampoder commented on app/javascript/controllers/index.js
> +  installErrorHandler(appsignal, application)
Oh interesting, do you know if there's an alternative way of doing this?

2024-04-26 20:43 UTC, sampoder commented on app/javascript/controllers/index.js
> +  installErrorHandler(appsignal, application)
Or would we have to write a custom handler that does both.

2024-04-26 20:47 UTC, northeastprince commented on app/javascript/controllers/index.js
> +  installErrorHandler(appsignal, application)
Do we still need Airbrake, at least for this?

2024-09-07 02:15 UTC, closed without merging