Reduce visual loudness of typography
hackclub/hcb pull request #6290
Opened 2024-05-14 20:52 UTC by lachlanjc

## Summary of the problem

We've long been using SF Rounded in Safari, but it never became available in other browsers. I don't want core typography to look so different across browsers, so dropping back to the system font stack. Additionally, there's a lot of unneeded shouting across typography:

- Our 700/800-weight bold looked fun with SF Rounded, but unnecessarily loud with standard SF. Dropping weight down to 600 to streamline
- Dropping down the size of our massive modal dialog titles
- No need for table headings to be in all caps

## Describe your changes

Smaller modal titles:
![CleanShot 2024-05-14 at 16 23 48@2x](https://github.com/hackclub/hcb/assets/5074763/e172425b-aa40-4476-a989-8a6ed42d562c)

Table headings, before:
![CleanShot 2024-05-14 at 16 28 54@2x](https://github.com/hackclub/hcb/assets/5074763/6c5f7b5d-aa30-479c-99cd-bba058517356)

Table headings, after:
![CleanShot 2024-05-14 at 16 29 06@2x](https://github.com/hackclub/hcb/assets/5074763/070c4cdd-3aac-476f-8def-dc099bcbf0cb)

On the homepage, metadata doesn't need to be bold:
<img width="921" alt="image" src="https://github.com/hackclub/hcb/assets/5074763/8ebfd296-ba97-4d55-bda8-15eda9979b17">

In the sidebar, the item font size is slightly smaller & lighterweight:
<img width="900" alt="image" src="https://github.com/hackclub/hcb/assets/5074763/0d96a8d4-9494-4f2f-b185-95f69392ee08">

2024-05-14 20:59 UTC, sampoder commented
Most of these changes look pretty good (especially the table headings!). Personally, though, I preferred the bolder event / organization name in the left navbar.

2024-05-14 21:05 UTC, lachlanjc commented
@sampoder That's valid! I'm about to redesign the whole sidebar, so the org name styling is temporary, but I think once you live with this change for a little while it'll grow on you.

2024-05-14 21:07 UTC, sarthaktexas requested changes
yes!! I've been wanting to make these changes for a while but did not want to mess with your design. thanks! **can we have a longer discussion on the organization name?**

2024-05-14 21:07 UTC, sarthaktexas commented on app/views/events/donation_overview.html.erb
> +        <th style="text-align: right;">Amount</th>
```suggestion
        <th class="text-right">Amount</th>
```

2024-05-14 21:07 UTC, sarthaktexas commented on app/views/events/partner_donation_overview.html.erb
> +        <th style="text-align: right;">Amount</th>
```suggestion
        <th class="text-right">Amount</th>
```

2024-05-14 21:07 UTC, sarthaktexas commented on app/views/events/transfers.html.erb
> +        <th style="text-align: right;">Amount</th>
```suggestion
        <th class="text-right">Amount</th>
```

2024-05-14 21:07 UTC, sarthaktexas commented on app/views/invoices/index.html.erb
> +      <th style="text-align: right;">Amount</th>
```suggestion
      <th class="text-right">Amount</th>
```

2024-05-14 21:07 UTC, sarthaktexas commented on app/assets/stylesheets/components/_transactions.scss
> +  padding-left: 1rem;
```suggestion
  @apply pl-4;
```

2024-05-14 21:07 UTC, sarthaktexas commented on app/assets/stylesheets/components/_transactions.scss
> +  padding-left: 1rem;
We're trying to move over to Tailwind, so most of my review is converting things that can be included with this PR.

2024-05-14 21:07 UTC, sarthaktexas commented on app/assets/stylesheets/components/_transactions.scss
> +  font-weight: 600;
for example, not converting this because it involves converting more than just this.

2024-05-14 21:07 UTC, sarthaktexas commented on app/assets/stylesheets/components/_dock.scss
>    cursor: pointer;
```suggestion
  @apply absolute right-[5px] top-[5px] cursor-pointer;
```

2024-05-14 21:07 UTC, sarthaktexas commented
Oh! Nevermind, looks like Sam commented the same thing!

2024-05-14 21:46 UTC, cjdenio commented on app/views/reimbursement/reports/_create_form.html.erb
> +      <%= form.submit "Start report", class: "bg-info mt2", disabled: @event && (!organizer_signed_in? || @event&.demo_mode?) %>
Does this have any effect? `bg-info` should be the default

2024-05-14 21:47 UTC, cjdenio commented on app/assets/stylesheets/basscss.css
> +.bold,
Ideally I'd rather not change this, since this file is meant to be static utility classes

2024-05-14 21:55 UTC, cjdenio commented on app/assets/stylesheets/components/_dock.scss
>    cursor: pointer;
could probably be `right-1` (4px) or `right-1.5` (6px) to avoid the arbitrary value

2024-05-14 22:03 UTC, lachlanjc commented on app/assets/stylesheets/components/_dock.scss
>    cursor: pointer;
I didn't edit this code, just running Prettier here. None of this is relevant to this PR so resolving this.

2024-05-14 22:07 UTC, lachlanjc commented on app/views/reimbursement/reports/_create_form.html.erb
> +      <%= form.submit "Start report", class: "bg-info mt2", disabled: @event && (!organizer_signed_in? || @event&.demo_mode?) %>
Not right now! I'm working on a buttons redesign on another branch & it was useful there, dropping it here.
```suggestion
      <%= form.submit "Start report", class: "mt2", disabled: @event && (!organizer_signed_in? || @event&.demo_mode?) %>
```

2024-05-14 22:15 UTC, lachlanjc commented on app/assets/stylesheets/basscss.css
> +.bold,
I'm dropping all usages of 700 weight across the UI, this doesn't seem worth re-architecting before switching to the Tailwind class. I've resolved this by updating the font weight Tailwind uses for bold classes as well. Thanks!

2024-05-14 22:53 UTC, lachlanjc commented on app/assets/stylesheets/components/_transactions.scss
> +  padding-left: 1rem;
This isn't relevant to this PR since we're not updating non-typography code regardless, but `@apply` is an anti-pattern for Tailwind, in my experience. It's best to write a strong configuration theme with all the CSS variables stored in one place, let Tailwind use those tokens only (Tailwind in an app should not have its default color palette, for instance), then consume the tokens through 1) Tailwind classes in HTML/JSX, and 2) the same token variables in the component-based CSS.

Tailwind's strength is in keeping styling colocated with view code, such that classes like this aren't left behind in CSS files while unused, and maintaining a strong design system of tokens. Using `@apply` inside component-based CSS, especially with arbitrary values, has all the problems of component-based CSS having classes not tied to their real usage, doesn't enforce the design system. It uses Tailwind more as a DSL/shorthand for CSS, which adds unnecessary complexity over plain CSS.

2024-05-15 04:00 UTC, sarthaktexas commented on app/assets/stylesheets/basscss.css
> +.bold,
oh shoot i didn't notice this at all @cjdenio thanks for noticing

2024-05-15 18:57 UTC, sarthaktexas submitted a review, later dismissed

2024-05-15 18:57 UTC, sarthaktexas commented on app/views/events/_filter.html.erb
> +        class="btn btn-small bg-info menu__toggle menu__toggle--arrowless overflow-visible z1"
```suggestion
        class="btn btn-small bg-info menu__toggle menu__toggle--arrowless overflow-visible z-10"
```

2024-05-15 18:57 UTC, sarthaktexas commented on app/views/events/_filter.html.erb
> +      class="btn btn-small bg-info menu__toggle menu__toggle--arrowless overflow-visible z1"
```suggestion
      class="btn btn-small bg-info menu__toggle menu__toggle--arrowless overflow-visible z-10"
```

2024-05-15 18:58 UTC, sarthaktexas reviewed
changing z values to use increments of 10 not 1.

2024-05-15 19:01 UTC, cjdenio commented on tailwind.config.js
> +    fontWeight: {
This should be nested under `extend`, otherwise it overwrites Tailwind's existing font-weight utilities (`font-normal`, etc)

2024-05-15 19:17 UTC, lachlanjc commented
@sarthaktexas I genuinely appreciate your desire to clean up CSS across the board here—there's a ton of work left to do in that area. That said, this PR is about typographic hierarchy, not switching other parts of the app to Tailwind or changing our approach to z-indexes. If you'd like my eyes on a PR with the changes you'd like to make, or if you want to discuss CSS architecture, I'm super happy to contribute in those ways. But it's crucial that on a PR, the creator is responsible for the changes shipped, and that there's a clear scope so we can get it out the door.

2024-05-16 01:42 UTC, lachlanjc commented on tailwind.config.js
> +    fontWeight: {
Oh great catch! I've allowlisted only the font weights we want to use.

2024-05-16 22:40 UTC, garyhtou submitted a review, later dismissed
Overall, I like what's happening here! I do think that the organization name should be bolder, however, I'll leave the final decision up to you.

2024-05-17 19:09 UTC, garyhtou approved these changes

2024-05-17 19:09 UTC, garyhtou approved these changes

2024-05-17 21:22 UTC, merged