Remove check auto-voiding & language around it
hackclub/hcb pull request #632
Opened 2020-05-20 15:34 UTC by tmb

Changes:
- Removed the job that autovoids checks
- Removed the call to schedule the autovoiding job from the Check model
- Removed the language telling the user about autovoiding from the send page.

2020-05-20 16:17 UTC, maxwofford commented
@tmb wish we had talked about the specific implementation for this in a proposal first. The flow that this PR allows that I'd like to prevent is:

- user issues a check
- months pass & user forgets to void
- bad actor deposits the check

- user issues a check
- months pass & user forgets
- check money is left floating in our positive pay account, making auditing/transitioning to a new positive pay account more complex

I'd like to have a solution that covers those.

2020-05-20 16:32 UTC, tmb commented
@maxwofford what if we proceeded forward with what I currently have & we send an email to the user giving them a heads up after 3 months "hey! your check to x for $y hasn't been deposited yet—please make sure to void it or ask the recipient to cash it"

2020-05-20 16:37 UTC, maxwofford commented
Can we send the email + auto-void after 6 months or something?

2020-05-20 16:49 UTC, tmb commented
@maxwofford how about we do one at 3, auto-void plus another at 6?

2020-05-20 16:50 UTC, maxwofford commented
@tmb love it. let's do that

2020-05-21 20:15 UTC, maxwofford requested changes

2020-05-21 20:15 UTC, maxwofford commented on app/jobs/refund_sent_check_job.rb
> +    check.void!
whitespace

2020-05-22 19:00 UTC, maxwofford submitted a review, later dismissed

2020-10-11 01:51 UTC, maxwofford commented on app/models/check.rb
> +      RemindSentCheckJob.set(wait_until: send_date + 3.month).perform_later(self)
Do we want to kill this line if we're preventing auto-voids? Assume that would also kill the `undeposited_reminder.html.erb` file.

2020-10-11 12:57 UTC, lachlanjc commented on app/models/check.rb
> +      RemindSentCheckJob.set(wait_until: send_date + 3.month).perform_later(self)
I think it's still useful functionality to know a check hasn't been deposited after months—it feels like Bank is looking out for you more

2021-03-06 22:45 UTC, closed without merging