Install console1984 and audit1984
hackclub/hcb pull request #6443
Opened 2024-05-29 04:19 UTC by manuthecoder

See #6352

2024-05-29 04:22 UTC, sampoder submitted a review, later dismissed
PR seems perfect to me; thanks for taking this on!

2024-05-29 14:35 UTC, northeastprince requested changes

2024-05-29 14:35 UTC, northeastprince commented on config/routes.rb
> +  mount Audits1984::Engine => "/console"
A base controller needs to be specified or this route needs to be constrained unless we want anyone to be able to access this.

2024-05-30 00:07 UTC, garyhtou commented on config/routes.rb
> +  mount Audits1984::Engine => "/console"
Thanks for pointing that out! Let's go with adding a constraint on this mount

2024-05-30 00:15 UTC, garyhtou commented on Gemfile
> +gem "audits1984"
```suggestion
gem "audits1984"

```

2024-05-30 00:15 UTC, garyhtou commented on db/schema.rb
> -
Let's keep this at the top of the file

2024-05-30 01:58 UTC, manu-gurudath commented
the last commit is broken!

2024-05-30 03:30 UTC, manu-gurudath commented
finished adding admin constraints

2024-05-30 19:02 UTC, garyhtou commented
@sampoder if you get a chance, would you mind running migrations and testing locally? 🪄

2024-05-30 19:05 UTC, garyhtou commented on db/migrate/20240529041318_create_console1984_tables.console1984.rb
> +      t.string :username, null: false
IIRC, it will ask for your name when you enter the rails console. console1984 does provide a way to programically set that value (we use it for https://github.com/hackclub/hackathons-backend).

Is there a way to get the name/email of the person who ran `heroku run bin/rails c`? This way we can autofill that

2024-05-30 19:22 UTC, sampoder commented on db/migrate/20240529041318_create_console1984_tables.console1984.rb
> +      t.string :username, null: false
I'm going to merge this with the manual name ask for now; @manuthecoder feel free to look into a programatic way if you're interested

2024-05-30 19:25 UTC, merged