Add skeleton screen
hackclub/hcb pull request #6592
Opened 2024-06-07 07:55 UTC by manuthecoder

See #6555

2024-06-09 00:56 UTC, malted commented on config/environments/development.rb
> +  # config.file_watcher = ActiveSupport::EventedFileUpdateChecker
Did you mean to commit this?

2024-06-09 01:04 UTC, malted commented
Hey! Would you mind adding screenshots & describing what the PR does?

2024-06-09 01:10 UTC, manu-gurudath commented on config/environments/development.rb
> +  # config.file_watcher = ActiveSupport::EventedFileUpdateChecker
oops - I was having some issues when updating my files locally. I'll uncomment this line - thank you for letting me know!

2024-06-09 01:12 UTC, manu-gurudath commented
> Hey! Would you mind adding screenshots & describing what the PR does?

Here's a brief video of what the PR does:

https://github.com/hackclub/hcb/assets/77016441/01fb8bd9-23bc-4a8e-bd80-34f6ec31f5e4


Essentially, this PR is a rewrite of the old loading animation for transaction popovers

2024-06-09 04:27 UTC, malted commented on app/assets/stylesheets/components/_shimmer.scss
> +      rgba(200, 200, 200, 0.1),
Is it possible to use a palette colour here & in other places or does it mess up the gradient?

2024-06-12 20:14 UTC, garyhtou commented on app/views/canonical_transactions/_canonical_transaction.html.erb
> +      <%= render "canonical_pending_transactions/skeleton" %>
```suggestion
      <%= render "hcb_codes/skeleton" %>
```

2024-06-12 20:15 UTC, garyhtou commented
This is largely to good 🪄. @sampoder can you review (test to make sure it works) and merge?

2024-06-13 12:34 UTC, sampoder commented
Yes, will do today.

2024-06-13 13:52 UTC, sampoder requested changes
Hey Manu! Thanks for making this PR. At the moment, I think that this PR needs a little tweaking before we can merge this.

My main point of feedback is that it was helpful to have the transaction card in the previous version,  would it be possible to integrate a skeleton into this card:

<img width="814" alt="Screenshot 2024-06-13 at 9 49 31 AM" src="https://github.com/hackclub/hcb/assets/39828164/d5b082a7-7d3e-4208-a7b6-85df922eeb62">

See in the screenshot where there are dashes, those could be skeleton-ized. My second piece of feedback is that we should handle receipts. We have a rough count of the amount of receipts. Could we add a skeleton for those?

Thanks so much!

2024-06-13 18:18 UTC, manu-gurudath commented
Hi! I've gone ahead and increased the detail within the skeleton card as seen here:

![image](https://github.com/hackclub/hcb/assets/77016441/12171187-d3ea-47d6-82cc-6ce6a3d5c142)

Up to 4 reciept skeleton loaders are now visible, as seen here:  
![image](https://github.com/hackclub/hcb/assets/77016441/ecaefd81-9eb2-422b-95fa-2ebe462c781f)

2024-06-14 21:41 UTC, sampoder commented
I think that that card still doesn't look like the card we end up rendering? It has four columns whilst ours only has one.

2024-07-01 14:55 UTC, sampoder commented
At the moment, I still think the current skeleton is closer to what we want and that it's styles look more like HCB's. Could you work on using the original styles and using that to build skeletons for comments and receipts?

2024-07-03 05:46 UTC, manu-gurudath commented
@sampoder What are your thoughts on having a basic spinner instead, using pure CSS? This would simplify the codebase, and would look nice in my opinion. 

See a demo: https://jsfiddle.net/tg218uwc/5/

2024-07-05 17:30 UTC, sampoder commented
I feel like I'd still prefer what we already have? I'm not exactly sure what's wrong with it

2024-07-07 02:08 UTC, manu-gurudath commented
I was suggesting this because we have more than just _transaction_ popovers - there's popovers for cards and transfers as well. Using a spinner could make it easier, but I could build a skeleton UI for those in the future if you'd like

2024-07-10 14:22 UTC, sampoder commented
Yeah I agree with some sort of general purpose loading screen. Maybe not a spinner but some sort of full screen shimmer?

2024-10-31 23:48 UTC, garyhtou commented
Closing (on call with @manuthecoder)

2024-10-31 23:48 UTC, closed without merging