Add tag colors
hackclub/hcb pull request #6690
Opened 2024-06-12 21:25 UTC by manuthecoder

See #6638 

> [!IMPORTANT]  
> Run `yarn install` to re-install the packages as it includes on new dependenceis

Now, you can add tags & colors to emojis through a new modal.
![image](https://github.com/hackclub/hcb/assets/77016441/ecc1aeb1-498a-480d-9f2d-faef32ef219f)
![image](https://github.com/hackclub/hcb/assets/77016441/9a8c3683-58e4-4827-93b6-e428a00c97f3)
![image](https://github.com/hackclub/hcb/assets/77016441/50d3c522-68be-4004-ba83-851f06e873dd)
![image](https://github.com/hackclub/hcb/assets/77016441/c992885b-5f2b-401e-9493-e4bd1bbcbf58)

2024-06-14 21:48 UTC, sampoder requested changes
A couple of points of feedback. I think we should drop the emojis, people can already add them in text (see hcb.hackclub.com/hq) and it will reduce the complexity. Plus if they're in plain text, it reduces the amount of images we need to load. Secondly, I think the colours are too sharp at the moment and they don't fit in well with the rest of the colours on the ledger. I'm not sure what to do about that at the moment, let me think about it over the weekend. Lastly we should probably use a blue button on the modal and allow for no colour or some sort of option that is no colour.

2024-06-22 01:05 UTC, manu-gurudath commented
I've removed the emojis feature and reduced the intensity of the colors. Let me know what you think!

2024-06-22 15:40 UTC, cjdenio commented on app/views/canonical_pending_transactions/_canonical_pending_transaction.html.erb
> +              <%= render "hcb_codes/create_tag", code: pt.local_hcb_code, instance: instance %>
i'd like to avoid rendering this modal once for every transaction on the page

2024-06-24 20:07 UTC, sampoder commented on .ruby-version
Can we discard these changes?

2024-06-24 20:07 UTC, sampoder commented on app/assets/stylesheets/application.scss
> +}
```suggestion
}

```

2024-06-24 20:08 UTC, sampoder commented on app/views/canonical_pending_transactions/_canonical_pending_transaction.html.erb
> +<% end %>
Can we keep the new lines at the bottom of these files?

2024-06-24 20:10 UTC, sampoder commented on app/controllers/tags_controller.rb
> +    tag = @event.tags.find_or_create_by(label: params[:label].strip, color: params[:color])
Look into using `create_with`: https://apidock.com/rails/v5.2.3/ActiveRecord/QueryMethods/create_with

2024-06-24 20:10 UTC, sampoder commented on app/views/canonical_pending_transactions/_canonical_pending_transaction.html.erb
> +          <% if !defined?(receipt_upload_button) && !defined?(hide_tags) && organizer_signed_in? && !pt.instance_of?(OpenStruct) && Flipper.enabled?(:transaction_tags_2022_07_29, @event || pt.local_h
Any reason these were moved?

2024-06-24 20:22 UTC, sampoder submitted a review, later dismissed
Here's some more general design feedback:

It's hard to see what I've selected:

<img width="617" alt="Screenshot 2024-06-24 at 1 12 45 PM" src="https://github.com/hackclub/hcb/assets/39828164/2b4bec15-5911-4b15-b5d6-95272dda6d33">

Let's make the text black here:

<img width="144" alt="Screenshot 2024-06-24 at 1 17 03 PM" src="https://github.com/hackclub/hcb/assets/39828164/7c7f1e5f-4f20-4ced-adba-61a9829f03de">

Is there a way to design this so that we only render the circle for tags with colours without making the alignment look weird? Maybe we could put them on the right?

<img width="424" alt="Screenshot 2024-06-24 at 1 20 07 PM" src="https://github.com/hackclub/hcb/assets/39828164/f6b2ae39-fae9-44a7-9952-82a99c657961">

2024-06-24 21:39 UTC, manu-gurudath commented
Thanks for the feedback! Please let me know if you have any more suggestions

2024-06-25 00:26 UTC, garyhtou commented
I'm cool with just doing colors for now. I will say that having icons as a first-class config is nice because it would allow us to collapse tags down to just their emoji and color. On hover, the badge could expand to show the label.

2024-07-01 20:51 UTC, sampoder commented
Just took another look, I appreciate the clearer toggles. How hard would it be to make the circle a checkmark? When clicking "Create" on the modal, it reloads the whole page. Would it be possible to change that? I think enabling Turbo on the form should make that possible.

2024-07-03 01:58 UTC, manu-gurudath commented
fixed!

2024-07-16 20:05 UTC, garyhtou reviewed
i love the new modal for creating a tag!

2024-07-16 20:05 UTC, garyhtou commented on app/views/hcb_codes/_create_tag.html.erb
> +    <%= form.submit "Create", class: "btn bg-primary mt-2 float-right" %>
we tend to use blue for these types of buttons

```suggestion
    <%= form.submit "Create", class: "btn bg-info mt-2 float-right" %>
```

2024-07-16 20:05 UTC, garyhtou commented on app/views/hcb_codes/_create_tag.html.erb
> +          colors = ["muted", "red", "orange", "yellow", "green", "cyan", "blue", "purple"]
Please store this as constant in the model.

Then, add a validation in the model so that the `color` column can only contain these values

2024-07-16 20:05 UTC, garyhtou commented on app/views/hcb_codes/_create_tag.html.erb
> +          <%= form.radio_button :color, color, checked: color === "muted" %>
I'm a bit confused by the `checked: color === "muted"`.

I'm not sure what the intention is, and it's uncommon to use `===` in ruby

2024-07-16 20:05 UTC, garyhtou commented on app/assets/stylesheets/components/_tags.scss
> +}
new line at EOF please

2024-07-23 05:23 UTC, manu-gurudath commented on app/views/hcb_codes/_create_tag.html.erb
> +          <%= form.radio_button :color, color, checked: color === "muted" %>
This sets the default color to `muted`

2024-07-24 21:45 UTC, garyhtou submitted a review, later dismissed

2024-07-24 21:45 UTC, garyhtou commented on app/assets/stylesheets/components/_transactions.scss
> +}
```suggestion
}

```

2024-07-24 21:45 UTC, garyhtou commented on app/views/canonical_pending_transactions/_canonical_pending_transaction.html.erb
Instead of doing a `|| "muted"` fallback in ERB. Let's set the default value for the `color` column to be "muted".

If we're setting a default value, let's also make it `null: false`

2024-07-24 21:45 UTC, garyhtou submitted a review, later dismissed

2024-07-24 21:48 UTC, garyhtou commented on app/views/hcb_codes/_create_tag.html.erb
> +    <% end %>
```suggestion
  <%= link_to "#", class: "menu__input", data: { behavior: "modal_trigger", modal: "create_tag" }, onclick: "document.getElementById('create_tag_hcb_code_id').value = '#{button}'" do %>
    <%= inline_icon "plus", size: 15 %>
      Create tag
  <% end %>
```

2024-07-24 21:49 UTC, garyhtou submitted a review, later dismissed

2024-07-24 21:58 UTC, garyhtou approved these changes

2024-07-24 22:02 UTC, merged