Add rich session data
hackclub/hcb pull request #6714
Opened 2024-06-13 23:49 UTC by manuthecoder

See #6712

2024-06-14 16:24 UTC, sampoder requested changes
Can we use `maps.hackclub.com`? Search the codebase for examples of where we've used it.

2024-06-14 21:40 UTC, sampoder requested changes
Thanks for that! A couple of things, geolocating for city is going to burn through all of our Geolocated API credits. Every time we create a user session, we save its longitude and latitude, so you can do `session.longitude` and `session.latitude`.

Secondly, for sessions that don't have an IP it makes the page look very imbalanced as there is a massive map on some sessions and nothing on others. Any thoughts on how we could fix that? Maybe there's a way we can design it in a way that the height doesn't change whether or not you have a map? Or we can render the entire world if we don't know? I'm not sure.

2024-06-15 06:47 UTC, manu-gurudath commented
>...geolocating for city is going to burn through all of our Geolocated API credits...

What if HCB used [findip.net's](findip.net) API? It's free and unlimited. 

>  ... for sessions that don't have an IP it makes the page look very imbalanced ... Any thoughts on how we could fix that?

What if we showed an empty square with "No preview available," like how my app currently does:
![image](https://github.com/hackclub/hcb/assets/77016441/0d36d8ff-7204-45d6-8591-2e91aed6ff3f)

I'm also formatting the map & placeholder with`aspect-ratio: 1 / 1` to ensure it remains the correct dimensions.

2024-06-16 05:25 UTC, sampoder commented on app/views/users/_user_session.html.erb
> +    <img class="w-full rounded mb-3 aspect-square" src="https://maps.hackclub.com/api/shipping?latitude=<%= session.latitude %>&longitude=<%= session.latitude %>" />
```suggestion
    <img class="w-full rounded mb-3 aspect-square" src="https://maps.hackclub.com/api/shipping?latitude=<%= session.latitude %>&longitude=<%= session.longitude %>" />
```

2024-06-16 05:35 UTC, sampoder approved these changes
LGTM!

2024-06-16 05:38 UTC, merged