Create comment reactions
hackclub/hcb pull request #7004
Opened 2024-07-02 07:55 UTC by manuthecoder

This PR addresses #6865, adding the functionality for users to react to comments. Below is a screen recording on how to do so: 

https://github.com/hackclub/hcb/assets/77016441/47bb7f36-b58d-4bef-908b-4b77dc4a93c5

2024-07-02 08:00 UTC, sampoder commented
Incredible, looking forward to reviewing this tomorrow!

2024-07-02 14:10 UTC, cjdenio commented on app/views/comments/_reaction_bar.html.erb
> +      <button class="reactions-btn tooltipped tooltipped--n <%= has_reacted ? "reactions-btn--reacted" : "" %>" value="<%= emoji %>" name="emoji" aria-label="Reacted by <%= user.count <= 10 ? user.ma
```suggestion
      <button class="reactions-btn tooltipped tooltipped--n <%= has_reacted ? "reactions-btn--reacted" : "" %>" value="<%= emoji %>" name="emoji" aria-label="Reacted by <%= user.count <= 10 ? user.map(&:name).join(", ") : user.take(10).map(&:name).join(", ") + " + #{user.count - 10} #{pluralize(user.count - 10, "other")}" %>">
```

This should just be `name`— `preferred_name` can be nil

2024-07-02 14:47 UTC, sampoder requested changes
Looks pretty good to me! I didn't get a chance to review the Turbo Streams stuff but hope these comments are helpful.

2024-07-02 14:47 UTC, sampoder commented on app/assets/images/icons/emoji-add.svg
this is really nice!

2024-07-02 14:47 UTC, sampoder commented on app/controllers/reactions_controller.rb
> +  def update
Maybe let's call this method `toggle`

2024-07-02 14:47 UTC, sampoder commented on app/controllers/reactions_controller.rb
> +    existing_reaction = CommentReaction.find_by(user_id: user_id, comment_id: params[:comment_id], emoji: params[:comment][:emoji] || params[:emoji])
```suggestion
    existing_reaction = CommentReaction.find_by(user: current_user, comment_id: params[:comment_id], emoji: params[:comment][:emoji] || params[:emoji])
```

does this work? I'm not sure but if it does it would cleaner

2024-07-02 14:47 UTC, sampoder commented on app/controllers/reactions_controller.rb
> +    puts params
```suggestion
```

2024-07-02 14:47 UTC, sampoder commented on app/controllers/reactions_controller.rb
> +class ReactionsController < CommentsController
any reason this is inheriting from `CommentsController`? just curious.

2024-07-02 14:47 UTC, sampoder commented on app/views/comments/_reaction_bar.html.erb
> +      <button class="reactions-btn tooltipped tooltipped--n <%= has_reacted ? "reactions-btn--reacted" : "" %>" value="<%= emoji %>" name="emoji" aria-label="Reacted by <%= user.count <= 10 ? user.ma
Let's also put this in a method on the class, something like "label"

2024-07-02 14:47 UTC, sampoder commented on app/models/comment_reaction.rb
> +class CommentReaction < ApplicationRecord
we probably want this to be Comment::Reaction

so something like:

```ruby
class Comment
  class Reaction < ApplicationRecord
  end
end
```

in `/comment/reaction.rb`

2024-07-02 14:47 UTC, sampoder commented on app/controllers/reactions_controller.rb
> +class ReactionsController < CommentsController
we might want this to be `Comment::ReactionsController`, something like:

```
module Comment
  class ReactionsController < ApplicationController
  end
end
```

2024-07-02 14:47 UTC, sampoder commented on db/migrate/20240625221911_create_comment_reactions.rb
> +      t.bigint :user_id, null: false
```suggestion
       t.references :user, null: false, foreign_key: true
```

I think you want to do this

2024-07-02 16:40 UTC, cjdenio commented on app/views/comments/_reaction_bar.html.erb
> +          onclick="this.form.requestSubmit()">
```suggestion
          onclick="this.form.requestSubmit()">
```

Can this just be `type="submit"`?

2024-07-02 17:12 UTC, manu-gurudath commented on app/views/comments/_reaction_bar.html.erb
> +          onclick="this.form.requestSubmit()">
Tried this earlier but the stimulus controller would prevent the form from submitting...

2024-07-02 20:43 UTC, manu-gurudath commented on app/controllers/reactions_controller.rb
> +class ReactionsController < CommentsController
It threw an error saying Comment was already defined, but it works when I remove the line

2024-07-02 20:45 UTC, manu-gurudath commented on app/controllers/reactions_controller.rb
> +class ReactionsController < CommentsController
I have no idea why I wrote that (ruby was throwing weird errors). I've fixed it by using ApplicationController now.

2024-07-02 20:49 UTC, manu-gurudath commented on app/controllers/reactions_controller.rb
> +  def update
Thoughts on setting it to `react`? It would have more clarity in the file `comment_policy.rb`

2024-07-02 21:25 UTC, northeastprince commented on app/models/comment/reaction.rb
> +    belongs_to :user
```suggestion
    belongs_to :author, class_name: "User"
```
or creator

2024-07-02 21:25 UTC, northeastprince commented on app/models/comment.rb
> +  has_many :comment_reactions, dependent: :destroy, class_name: "Comment::Reaction"
```suggestion
  has_many :reactions, dependent: :destroy
```

2024-07-02 21:25 UTC, northeastprince commented on app/models/comment.rb
> +
The first method shouldn't be coupled with the second. Just have the association named reactions and preload users for the second one if needed.

2024-07-03 14:12 UTC, cjdenio commented on app/controllers/reactions_controller.rb
> +    authorize Comment.find(params[:comment_id])
```suggestion
  before_action :set_comment

  def react
    authorize @comment
```

I see there's a `set_comment` filter below but it's unused

2024-07-03 14:17 UTC, cjdenio commented on config/routes.rb
> +    resources :reactions, only: [:update], to: "reactions#react"
This should either be
```ruby
resources :reactions, only: [:create, :destroy]
```
or 
```ruby
resources :reactions, only: [] do
  get :react, on: :collection
end
```

— `resources` doesn't take a `to` param

2024-07-05 05:31 UTC, sampoder commented on app/models/comment/reaction.rb
> +    belongs_to :user
Please use creator, reactor or user. Let's not use author we haven't used that word in this codebase and I'd prefer to keep it like somewhat consistent?

2024-07-09 01:00 UTC, manu-gurudath commented on app/models/comment.rb
> +
not sure what I have to fix, `reactions` and `reacted_by` are separate functions

2024-07-16 19:55 UTC, garyhtou reviewed
Great work! I love this. Just some things to clean up

2024-07-16 19:55 UTC, garyhtou commented on app/controllers/reactions_controller.rb
> +    puts "does this work"
can we drop this comment?

2024-07-16 19:55 UTC, garyhtou commented on app/assets/stylesheets/components/_reactions.scss
> +}
new line at end of files, please!
```suggestion
}

```

2024-07-16 19:55 UTC, garyhtou commented on app/assets/stylesheets/components/_reactions.scss
> +        background-color: lighten($muted, 30%);
the light gray background feels slightly off. i doesn't fit the hcb vibe I think. I'm not sure if I'm alone here

2024-07-16 19:55 UTC, garyhtou commented on app/controllers/reactions_controller.rb
> +    existing_reaction = Comment::Reaction.find_by(author_id: current_user.id, comment_id: params[:comment_id], emoji: params[:comment][:emoji] || params[:emoji])
We should be able to directly pass objects/records instead of IDs
```suggestion
    existing_reaction = Comment::Reaction.find_by(author: current_user, comment: @comment, emoji: params[:comment][:emoji] || params[:emoji])
```

2024-07-16 19:55 UTC, garyhtou commented on app/controllers/reactions_controller.rb
> +      Comment::Reaction.create(emoji: params[:comment][:emoji], author_id: user_id, comment_id: params[:comment_id])
Let's bang these methods because we want it to fail loudly (raise an error instead of just returning true/false)

```suggestion
      existing_reaction.destroy!
    else
      Comment::Reaction.create!(emoji: params[:comment][:emoji], author: current_user, comment: @comment)
```

2024-07-16 19:55 UTC, garyhtou commented on app/controllers/reactions_controller.rb
> +      Comment::Reaction.create(emoji: params[:comment][:emoji], author_id: user_id, comment_id: params[:comment_id])
We're doing `params[:comment][:emoji] || params[:emoji]` above, should we add the ` || params[:emoji]` to this too?

2024-07-16 19:55 UTC, garyhtou commented on app/models/comment.rb
> +  end
We're overriding the `reactions` method defined by the association. Maybe we should rename this method to `reactions_by_emoji` or `reaction_emojis`

2024-07-16 19:55 UTC, garyhtou commented on app/models/comment.rb
> +  def reacted_by(t)
what's `t`? can we have a more descriptive name here?

2024-07-16 19:55 UTC, garyhtou commented on app/models/comment/reaction.rb
> +#  emoji      :string           not null
Can we add a validation for emojis?

`validate_presence_of :emoji` and also validate that it contains exactly one emoji

2024-07-16 19:55 UTC, garyhtou commented on app/policies/comment_policy.rb
> +    user.admin? || users.include?(user)
Let's change it to this. It basically says you can react if you can see it!

```suggestion
    show?
```

2024-07-16 19:55 UTC, garyhtou commented on app/views/comments/_item.html.erb
> +        <%= render partial: "comments/reactions", locals: { comment: } %>
very clean! I love this

2024-07-16 19:55 UTC, garyhtou commented on app/views/comments/_reaction_bar.html.erb
> +        emojis = ["👍", "👎", "😄", "🎉", "😔", "❤️", "🚀", "👀"]
Can we store this as constant inside the Reaction mode?

```ruby
class Comment
  class Reaction
    EMOJIS = %w[🪄 😊]
  end
end

# to get the list, use...
Comment::Reaction::EMOJIS
```

2024-07-16 19:55 UTC, garyhtou commented on app/views/comments/_reaction_bar.html.erb
> +    has_reacted = user.find { |u| u.author_id == current_user.id }
```suggestion
    has_reacted = user.any? { |u| u.author == current_user }
```

2024-07-16 19:55 UTC, garyhtou commented on app/views/comments/_reaction_bar.html.erb
> +    comment.reactions.each do |emoji, user|
should `user` be called `users`? it appears to be a list of users

2024-07-16 19:55 UTC, garyhtou commented on db/migrate/20240625221911_create_comment_reactions.rb
> +      t.references :comment, null: false, foreign_key: { to_table: :comments, column: :comment_id }
is the `column: :comment_id` needed?

2024-07-16 19:55 UTC, garyhtou commented on db/schema.rb
Please undo the unrelated changes here!

2024-07-16 19:55 UTC, garyhtou commented on app/models/comment/reaction.rb
> +    belongs_to :author, class_name: "User"
Validate that [author, comment, emoji] just be unique. In other words, a user can not react with the same emoji multiple times on a single comment

2024-07-16 19:55 UTC, garyhtou commented on app/views/comments/_reaction_bar.html.erb
> +<div class="flex gap-1" id="reactions_<%= comment.id %>">
i love how this looks!

2024-07-16 19:57 UTC, garyhtou commented on config/routes.rb
> +  resources :comments, only: [:edit, :update] do
I think comments already have a resource. I'm not sure if adding this will create unnecessary routes.

Comment routes are defined here: https://github.com/hackclub/bank/blob/6b4b7955f3adf3699aff0bfecf5b08303a0cfabc/config/routes.rb#L19-L21

2024-07-18 06:22 UTC, manu-gurudath commented on app/controllers/reactions_controller.rb
> +    puts "does this work"
haha I'll do that

2024-07-23 04:43 UTC, manu-gurudath commented on app/assets/stylesheets/components/_reactions.scss
> +        background-color: lighten($muted, 30%);
I made the buttons blue - let me know what you think!

2024-07-24 21:29 UTC, garyhtou commented on app/controllers/reactions_controller.rb
> +class ReactionsController < ApplicationController
this controller should also be named under comments. 

```suggestion
class Comment
  class ReactionsController < ApplicationController
```

2024-07-24 21:29 UTC, garyhtou commented on app/controllers/reactions_controller.rb
> +      Comment::Reaction.create!(emoji: params[:comment][:emoji] || params[:emoji], author: current_user, comment: @comment)
See if we actually need both params

2024-07-24 21:29 UTC, garyhtou commented on app/models/comment.rb
> +                     .order(created_at: :asc)
I don't know if order is preserved when we do `group_by`

2024-07-24 21:29 UTC, garyhtou commented on app/models/comment.rb
> +                     .group_by(&:emoji)
```suggestion
    reactions.joins(:author)
                    .select("comment_reactions.comment_id, comment_reactions.author_id, comment_reactions.emoji, users.*")
                    .order(created_at: :asc)
                    .group_by(&:emoji)
```

2024-07-24 21:29 UTC, garyhtou commented on app/models/comment.rb
> +    user_names = reactions_by_emoji.flat_map { |_, reactions| reactions.filter { |reaction| reaction.emoji == emoji }.map(&:author).map(&:name) }.uniq
```suggestion
    user_names = reactions_by_emoji[emoji]&.map(&:author)&.map(&:name) || []
```

2024-07-24 21:29 UTC, garyhtou commented on app/models/comment.rb
> +    user_names.count > max_users ? "#{user_names.first(max_users).join(", ")} +#{user_names.count - max_users} more" : user_names.join(", ")
```suggestion
    user_names.count > max_users ? "#{user_names.first(max_users).join(", ")} +#{user_names.count - max_users} more" : user_names.to_sentence
```

2024-07-24 21:29 UTC, garyhtou commented on app/models/comment/reaction.rb
> +#  index_comment_reactions_on_comment_id  (comment_id)
Let's add an index on emoji

2024-07-24 21:29 UTC, garyhtou commented on app/models/comment/reaction.rb
> +    belongs_to :author, class_name: "User"
```suggestion
    belongs_to :reactor, class_name: "User"
```

2024-07-24 21:29 UTC, garyhtou commented on app/models/comment/reaction.rb
> +
```suggestion
    validates_inclusion_of :emoji, in: EMOJIS, on: :create

```

2024-07-24 21:29 UTC, garyhtou commented on app/views/comments/_reaction_bar.html.erb
> +    has_reacted = users.any? { |u| u.author == current_user }
```suggestion
    comment.reactions_by_emoji.each do |emoji, reactions| 
    has_reacted = reactions.any? { |u| u.author == current_user }
```

2024-07-24 21:29 UTC, garyhtou commented on app/views/comments/_reaction_bar.html.erb
> +    <button class="reactions-btn tooltipped tooltipped--n <%= has_reacted ? "reactions-btn--reacted" : "" %>"  aria-label="Reacted by <%= comment.reacted_by(emoji) %>">
```suggestion
    <button class="reactions-btn tooltipped tooltipped--n <%= "reactions-btn--reacted" if has_reacted %>"  aria-label="Reacted by <%= comment.reacted_by(emoji) %>">
```

2024-07-24 21:34 UTC, garyhtou commented on app/views/comments/reactions/react.turbo_stream.erb
Let's not directly access params in the view if possible.

instead we should use `comment` or `@comment`

2024-07-24 21:34 UTC, garyhtou commented on config/routes.rb
> +      resources :reactions, only: [:update], as: 'comment_reaction', to: "reactions#react"
I wonder if the `as` is necessary

2024-07-25 20:31 UTC, manu-gurudath commented
wait it's not ready

2024-07-25 21:08 UTC, manu-gurudath commented
ready!

2024-07-31 21:04 UTC, garyhtou submitted a review, later dismissed

2024-08-02 14:05 UTC, sampoder approved these changes

2024-08-02 14:06 UTC, sampoder commented
Nice work on this!

2024-08-02 14:10 UTC, merged