Redesign home page
hackclub/hcb pull request #7105
Opened 2024-07-13 17:37 UTC by manuthecoder

# See #7092 
> ### Describe your goals
> 
> # Motivation
> Upon reorganizing the current events homepage in #7090, I identified an opportunity for HCB Events to benefit from a dedicated events homepage.
> 
> # What's this about!?
> The redesigned homepage will feature an "**at a glance**" view of events, replacing the current list of recent transactions. This new page will include information about team members, cards, and a predefined number of recent transactions. Widgets will offer links to transactions, cards, or entire pages. 
> 
> Future enhancements could allow users to reorder widgets or create custom "filter" widgets.
> 
> # Key Changes:
> - The transparency banner will be moved from the transactions page to the homepage.
> - The transaction history chart from the transactions page will become a separate widget on the homepage.
> 
> # Proposed Widgets:
> - Balance over time chart
> - Recent transactions table
> - Team members
> - Recent event activity (based on @sampoder's activity feature flag)
> - Cards (sorted by most recent transaction)
> - Recent donations
> - Overview of recent reimbursements
> 
> > [!IMPORTANT]  
> > **It is crucial to distinguish this from the breakdown page, which provides a detailed event report. The homepage will be minimalist, offering a concise "at a glance" overview.**
> 
> # Preview
> ![Frame 1](https://github.com/user-attachments/assets/36d7ff0c-fd06-4abe-ae6e-3f093c1a1b67)
> 
> 
> **See it on Figma! https://www.figma.com/design/YTFyYUMwu3MbTZtVwxZp2y/Untitled?node-id=0-1&t=48xUtMQAaXL30ubf-1**
>

2024-07-15 01:05 UTC, sampoder commented on app/views/events/transactions.erb
Can this be renamed to `transactions.html.erb`?

2024-07-15 21:43 UTC, garyhtou commented
Can you look myself and @dwahbe in for review when ready?

2024-07-15 21:58 UTC, garyhtou commented
For context on this PR: https://hackclub.slack.com/archives/C07387PENKH/p1721080636872069

2024-08-20 17:52 UTC, garyhtou commented
FYI, @dwahbe and I just updated the Google doc with a list of feedback based on the current version. lmk if you've got any questions

2024-08-21 14:46 UTC, manu-gurudath commented
just saw the comment thank you for letting me know!

2024-09-05 03:33 UTC, sampoder requested changes
Couple of code comments! Going to load this up locally and test.

2024-09-05 03:33 UTC, sampoder commented on app/assets/stylesheets/components/_badges.scss
> +    }
Are there any side effects of making this change to other parts of the app? If possible, it'd be nice to not change pre-existing classes.

2024-09-05 03:33 UTC, sampoder commented on app/assets/stylesheets/components/_badges.scss
> +    }
Any reason for the `!important`s? Same question as above

2024-09-05 03:33 UTC, sampoder commented on app/assets/stylesheets/components/_pinned_transactions.scss
> -      opacity: 0;
What was the thinking behind removing the on hover?

2024-09-05 03:33 UTC, sampoder commented on app/javascript/controllers/balance_graph_controller.js
> +      window.location.pathname.replace('/transactions', '') + '/balance_by_date'
```suggestion
      window.location.pathname.replace('/transactions', 'balance_by_date')
```

2024-09-05 03:33 UTC, sampoder commented on app/policies/event_policy.rb
> +  end
Let's have these all be the same method, ideally the same as `show?` and then you can alias them

2024-09-05 03:33 UTC, sampoder commented on app/views/events/home/_tags_users.html.erb
> +    @empty_users = users.empty?
You can avoid instance variables in views

2024-09-05 03:33 UTC, sampoder commented on app/views/events/home/_team.html.erb
> +      <% end %>
If there's 9 organisers it doesn't make sense to render a +1

2024-09-05 03:33 UTC, sampoder commented on app/views/events/show.html.erb
> -<% end %>
It'd be nice to keep live updates, if possible

2024-09-05 03:33 UTC, sampoder commented on app/views/events/transactions.html.erb
I'm assuming this is the same?

2024-09-05 03:33 UTC, sampoder commented on config/routes.rb
> +    # Home page
```suggestion
    # Loaded as Turbo frames on the home page
```

2024-09-05 03:37 UTC, sampoder commented on app/assets/stylesheets/_dark.scss
> +    --card-bg: #252429;
What are you trying to do with these?

2024-09-05 03:48 UTC, sampoder submitted a review, later dismissed
Taking a look at the design now; looking really good in general!

Can we drop the "Money movement" heading?

<img width="795" alt="Screenshot 2024-09-04 at 8 42 42 PM" src="https://github.com/user-attachments/assets/eabc9252-e725-4476-aa4f-c4c2170d7d2c">

The blue feels out of place; can we use our theme colours or a variant of red? The JS you have generating an array looks pretty sweet!

<img width="837" alt="Screenshot 2024-09-04 at 8 43 29 PM" src="https://github.com/user-attachments/assets/48dde83a-a583-47f6-8755-4c6fcba99fd7">

Let's hide the heatmap if there are 0 transactions in the past year.

<img width="391" alt="Screenshot 2024-09-04 at 8 45 15 PM" src="https://github.com/user-attachments/assets/7524e63f-2646-4f9b-bd8f-d2a61fa73158">

Let's make the team members smaller and show more of them, I think it's alright if they wrap onto a new line. Though not sure how that'd change your alignment. Also, let's remove the "+X" and include it in the "See more (+X)".

Lastly (I'm going to try and figure this one out for you), disbursements seem to show as four duplicated transactions on the "Recent transactions..." widget:

<img width="504" alt="Screenshot 2024-09-04 at 8 46 39 PM" src="https://github.com/user-attachments/assets/0476f1fe-694b-4034-9f62-3429b25162e7">

2024-09-05 03:48 UTC, sampoder commented
Great work all round btw!

2024-09-05 03:55 UTC, sampoder commented on app/views/events/home/_transactions.html.erb
> +      <% cache transaction do %>
This is the line causing the duplicated transactions

2024-09-08 06:39 UTC, manu-gurudath commented on app/assets/stylesheets/components/_badges.scss
> +    }
Currently, the `.bg-success` and `.bg-error` badge background colors are too intense and would disrupt the UI. I've added these lines to make a less intense version of the badge. 

However, the !important was unnecessary and I've fixed that!

2024-09-08 06:49 UTC, manu-gurudath commented on app/assets/stylesheets/components/_badges.scss
> +    }
fixed!

2024-09-08 06:49 UTC, manu-gurudath commented on app/assets/stylesheets/_dark.scss
> +    --card-bg: #252429;
This is used for the `linear-gradient` to fade out the recent activity. See `app/views/events/home/_recent_activity.html.erb:3:129`

2024-09-08 06:49 UTC, manu-gurudath commented on app/views/events/transactions.html.erb
Just merged it with the code from the `main` branch!

2024-09-08 06:50 UTC, manu-gurudath commented on app/assets/stylesheets/components/_pinned_transactions.scss
> -      opacity: 0;
fixed!

2024-09-08 07:14 UTC, manu-gurudath commented
Hi @sampoder - thank you so much for the code review! 🚀✨

I've fixed the issues you've mentioned and feel free to test it out again whenever you're free. 

For the team members, I've reduced the size of the avatars so it shows ten, but I personally feel like the "+X" placeholder would look nicer since it is similar to the organization card on the home page and feels more cohesive with the other avatar row component. Let me know what you think!

2024-09-16 05:01 UTC, sampoder commented
Thanks Manu! Sorry I missed your earlier message, let me take a look rn

2024-09-16 05:03 UTC, sampoder commented on app/assets/stylesheets/_dark.scss
> +    --card-bg: #252429;
I gotcha, would it make sense to use the darkless variable as well?

2024-09-16 05:06 UTC, sampoder commented on app/views/events/home/_recent_activity.html.erb
> +    <div style="position:absolute;bottom:0;left:0;height:100px;width:100%;background:linear-gradient(transparent,var(--card-bg));pointer-events:none;z-index:1"></div>
Sorry to nit-pick, but we should format these like we format our CSS.

```suggestion
    <div style="position: absolute; bottom: 0; left: 0; height: 100px; width: 100%; background: linear-gradient(transparent, var(--card-bg)); pointer-events: none; z-index: 1"></div>
```

2024-09-16 05:07 UTC, sampoder commented on app/views/events/home/_tags_users.html.erb
> +              <%# _blank cuz of werird turbo frame bugs %>
Could you expand on this? Sorry, I'm not understanding what you mean.

2024-09-16 05:07 UTC, sampoder commented on app/views/events/home/_tags_users.html.erb
> +              <%= !Flipper.enabled?(:transaction_tags_2022_07_29, event) ? "With tags, you can neatly categorize your transactions." : "Either you don't have any tags, or you haven't categorized any
Let's reverse this and the others ones so we don't need the `!`

2024-09-16 05:07 UTC, sampoder commented on app/views/events/home/_tags_users.html.erb
> +            <% if !Flipper.enabled?(:transaction_tags_2022_07_29, event) %>
```suggestion
            <% unless Flipper.enabled?(:transaction_tags_2022_07_29, event) %>
```
please use `unless`!

2024-09-16 05:09 UTC, sampoder commented on app/policies/event_policy.rb
> +  alias_method :show?, :can_access_data?
```suggestion
  def show?
    is_public || admin_or_user?
  end

  alias_method :top_merchants?, :show?
  alias_method :top_categories?, :show?
  alias_method :tags_users?, :show?
  alias_method :transaction_heatmap?, :show?
```

This is just closer to Rails conventions and a little clearer imo

2024-09-16 05:11 UTC, sampoder commented on app/javascript/components/home/Users.js
> +const colors = Array.from({ length: 11 }, (_, i) => `hsl(352, 83%, ${70 - i * 5}%)`);
Could we have these all import from one shared place? Same thing with shuffle?

2024-09-16 05:33 UTC, sampoder commented
I hear the argument for consistency. I guess I personally think it's more worthwhile having more faces and the number in the link would be consistent with other cards on the page, which is probably more important. I haven't gotten a chance to pull the changes locally (I'm on a flight rn and the WiFi isn't the greatest!) but I do think one of the reasons the grey circles work is because they are very small in the event card.

2024-09-16 05:35 UTC, sampoder commented
I do want to get this merged in this week, here's what I was thinking we do:

1) Ensure that the transactions page is the exact same as before, at least for now. We can the changes we have right now into a new PR to merge later.

2) Create a Flipper flag

3) Render the new homepage if that Flipper flag is enabled, otherwise redirect or rewrite to transactions.

4) Getting this being used at HQ and by a couple of hackathons, start collecting feedback, improve on the homepage and then do a big ship once it's perfect.

I'm happy to take that on if that sounds good to you @manuthecoder :D

2024-09-16 05:49 UTC, sampoder commented
Sorry I was wrong! I just pulled and I saw we aren't do a (+X) on the other see alls. Thoughts on doing that?

2024-09-16 05:54 UTC, sampoder commented
Honestly looking at the +X thing again, I think it's good to go. Ignore my previous two comments, thanks for making that change.

2024-09-21 18:28 UTC, manu-gurudath commented on app/views/events/home/_tags_users.html.erb
> +              <%# _blank cuz of werird turbo frame bugs %>
Update: I edited the code so it no longer needs this `_blank` target

2024-09-24 16:27 UTC, manu-gurudath commented
changes made! again, thanks so much for the review and let me know if there's anything else which needs to be fixed

2024-10-04 00:04 UTC, garyhtou submitted a review, later dismissed
This LGTM to merge under the feature flag.

Go ahead and fix these following feedback after merge:


On medium screen sizes, there's no margin on the right of the page.
![image](https://github.com/user-attachments/assets/8b697868-dddb-4ecd-9996-e4a764630f09)

---

![image](https://github.com/user-attachments/assets/ef61a2db-8c6d-4360-bfc8-1ecf032933d5)

For $0 transactions, we usually use a grey color (see a screenshot from the ledger below). Let's replicate that for our badge here

![image](https://github.com/user-attachments/assets/dc6d3b3a-05d7-44d8-b855-3205c938493d)

2024-10-04 00:04 UTC, garyhtou commented on app/views/reimbursement/reports/_create_form.html.erb
Instead of doing `modal_id`, we should make the default ID more descriptive for prevent conflicts.

At the moment, I can see that the default ID is `create`. It should maybe be `create_reimbursement_report`.

Make sure you handle this for all the modals that you added `modal_id` for

2024-10-04 00:04 UTC, garyhtou commented on app/views/events/home/_money_movement.html.erb
> +            <%= modal_header(transaction.local_hcb_code.pretty_title(show_event_name: defined?(show_event_name), show_amount: defined?(show_amount), event_name: @event&.name, amount_cents: transactio
```suggestion
            <%= modal_header(transaction.local_hcb_code.pretty_title(show_event_name: defined?(show_event_name), show_amount: defined?(show_amount), event_name: @event.name, amount_cents: transaction.amount), external_link: transaction.local_hcb_code.url) %>
```

2024-10-04 00:04 UTC, garyhtou commented on app/views/events/home/_transactions.html.erb
> +            <%= modal_header(transaction.local_hcb_code.pretty_title(show_event_name: defined?(show_event_name), show_amount: defined?(show_amount), event_name: @event&.name, amount_cents: transactio
```suggestion
            <%= modal_header(transaction.local_hcb_code.pretty_title(show_event_name: defined?(show_event_name), show_amount: defined?(show_amount), event_name: @event.name, amount_cents: transaction.amount), external_link: transaction.local_hcb_code.url) %>
```

2024-10-04 00:04 UTC, garyhtou commented on app/views/events/home/_money_movement.html.erb
> +            <%= modal_header(transaction.local_hcb_code.pretty_title(show_event_name: defined?(show_event_name), show_amount: defined?(show_amount), event_name: @event&.name, amount_cents: transactio
```suggestion
            <%= modal_header(transaction.local_hcb_code.pretty_title(show_event_name: defined?(show_event_name), show_amount: defined?(show_amount), event_name: @event.name, amount_cents: transaction.amount), external_link: transaction.local_hcb_code.url) %>
```

2024-10-04 00:05 UTC, garyhtou commented
@sampoder if you wanna provide feedback go ahead. Otherwise, I'd like this merged by this week

2024-10-08 16:23 UTC, manu-gurudath commented on app/views/reimbursement/reports/_create_form.html.erb
done!

2024-10-10 23:38 UTC, garyhtou approved these changes
merging under a flipper flag

2024-10-10 23:50 UTC, merged