Improve reimbursement keybinds
hackclub/hcb pull request #7169
Opened 2024-07-18 04:46 UTC by manuthecoder

This PR adds `ctrl+enter` and `escape` keybinds to close the lightbox when editing fields in reimbursement expense inputs.

2024-07-18 13:29 UTC, sampoder approved these changes
Two things:

1) We currently have ctrl-enter for each of the fields except the description field. Could you add `data-behavior="ctrl_enter_submit"` to that field?

2) I like having the escape key, however, I think that it should not save the form and instead cancel any edits made. Thoughts?

2024-07-18 13:29 UTC, sampoder requested changes
Sorry, meant to request changes.

2024-07-24 20:25 UTC, garyhtou commented on app/javascript/controllers/expense_form_controller.js
> +          this.formTarget.requestSubmit()
Let's see if we can close the lightbox without submitting the POST request. however, this fine as is for now

2024-07-24 20:25 UTC, garyhtou commented on app/views/reimbursement/expenses/_form.html.erb
Should we change memo to also use ctrl+enter? At the moment it's just enter to submit the form

2024-07-27 20:29 UTC, sampoder commented on app/javascript/controllers/expense_form_controller.js
> +        this.close()
What's the thinking behind this change?

2024-07-29 17:26 UTC, garyhtou commented on app/javascript/controllers/expense_form_controller.js
> +        this.close()
Please double-check this, but here's my understanding.

Previously, we were using `requestSubmit` to close the lightbox. Now, we have the `close` method.

2024-07-30 05:36 UTC, manu-gurudath commented on app/javascript/controllers/expense_form_controller.js
> +        this.close()
Update: This function is called when the user clicks on the overlay. In my updated code, I've used a combination of requestSubmit() and close(). The reason for this is to make the UI feel more responsive when the user clicks outside the reimbursement input.

2024-07-31 20:45 UTC, garyhtou reviewed
LGTM to me. @sampoder, would you like to do another review pass on this?

2024-08-01 14:55 UTC, sampoder commented on app/javascript/controllers/expense_form_controller.js
> +        this.close()
I'm going to remove this because I want there to be feedback for when something is "saved"

```suggestion
```

2024-08-01 14:57 UTC, sampoder commented on app/javascript/controllers/expense_form_controller.js
> +      })
```suggestion
      document.addEventListener('keydown', e => {
        if (e.key === 'Escape' && this.enabledValue) {
          this.formTarget.reset()
          this.close()
        }
      })
```

2024-08-01 15:15 UTC, sampoder approved these changes

2024-08-01 15:15 UTC, merged