[Documents] Tabulate pages
hackclub/hcb pull request #7477
Opened 2024-08-13 16:53 UTC by malted

Closes https://github.com/hackclub/hcb/issues/7475

![image](https://github.com/user-attachments/assets/8da1cc95-7294-444b-8c3a-2c72822dc7c7)

![image](https://github.com/user-attachments/assets/7eac09e7-2c34-45c4-a021-a8a05da1634f)

cc @dwahbe

2024-08-16 18:48 UTC, dwahbe commented
Amazing!!

2024-08-16 19:47 UTC, garyhtou requested changes
Can you add the other tabs, as described here?
https://github.com/hackclub/hcb/issues/7475#issuecomment-2286859363

2024-08-21 19:37 UTC, garyhtou submitted a review, later dismissed
I'm going to merge this as is. Next steps:
1. PR to add an enum to Document for its category. Also add an admin view to categorize all existing documents. Require category for newly uploaded documents (add validation present on create)
2. Once all documents have been categorized, add the additional tabs

2024-08-21 19:42 UTC, garyhtou approved these changes

2024-08-21 19:45 UTC, merged