Improve dark mode
hackclub/hcb pull request #7512
Opened 2024-08-14 18:08 UTC by manuthecoder

# Summary

## Dark mode improvements
-   Relocates the dark mode toggle to user settings (refer to the screenshot below).
-   Storing the dark mode preference as a cookie instead of using `localStorage`. Previously, the user's theme preference was stored via `localStorage`, which, despite preloading the script, couldn't entirely prevent a Flash of Unstyled Content (FOUC). The new approach uses cookies, allowing Ruby to automatically set `data-dark="true"` on the HTML element when the user loads the page, effectively avoiding a FOUC.
-   Introducing a `system` theme option. **Important:** The new implementation uses a `system_preference` cookie in `dark.js` to further prevent a FOUC on subsequent reloads.

## Login page
- Removes unnecessary buttons next to logo

![image](https://github.com/user-attachments/assets/b7f918fb-d1dd-4752-ad67-b65deecd26ce)

2024-08-14 21:43 UTC, sampoder commented
This is really nice, thank you for putting this together! Personally, I think we can do without the back button at the moment. Most users know that they can click the logo to go home, plus I think we're generally trying to reduce clutter.

I'm on the fence about the new settings button; what does it look like if the box is above the "Jump to..."? 

For the "Toggle Theme" button could we make it dynamic, so "Dark mode" when light and "Light mode" when dark?

Last thing, thoughts on putting organizations first than user settings?

2024-08-14 22:06 UTC, dwahbe commented
This is an awesome start! I totally agree with @sampoder. I think instead of back button, adding a link to the Dashboard as the top item on the org switcher. I think this has less clutter and also makes the HCB logo and org name the same button, which will be easier to navigate. 

Also +1 on 
- dynamic light / dark mode switcher would be great
- putting organizations above light / dark mode switcher and sign out (I would put dashboard on top, then organizations)

2024-08-26 07:49 UTC, manu-gurudath commented
cc @garyhtou @sampoder @dwahbe 

I updated this issue's objective - let me know what you think! ✨

2024-08-26 16:22 UTC, sampoder requested changes
Interesting work with the dark mode changes! Is it possible to pull that out of this PR? That'll make the two things easier to review.

2024-08-26 16:28 UTC, sampoder commented on app/views/users/edit.html.erb
> +
This shouldn't be in the account settings page. It's a per-device setting not a per-account setting. Can we go back to use a toggle like we had before?

2024-08-26 16:29 UTC, sampoder commented on app/views/events/landing/_header.html.erb
> +  aria-label="toggle dark modeToggle dark mode" tabindex="0">
This is shown as a tooltip
```suggestion
  aria-label="Toggle dark mode" tabindex="0">
```

2024-08-26 16:29 UTC, sampoder commented on app/views/layouts/admin.html.erb
> -          </button>
Please don't remove this, it's helpful for admins

2024-08-26 16:31 UTC, sampoder commented on app/views/users/_nav.html.erb
These changes feel unrelated; can we pull them into a separate PR?

2024-08-26 16:33 UTC, sampoder commented on app/views/application/_header.html.erb
> -    </button>
See comment on https://github.com/hackclub/hcb/pull/7512/files?w=1#r1731495560

2024-08-26 16:33 UTC, sampoder commented on app/views/application/_header.html.erb
> +      <%  end unless request.path.include?("auth") %>
What's the thinking behind this line?

2024-08-26 16:35 UTC, manu-gurudath commented on app/views/application/_header.html.erb
> +      <%  end unless request.path.include?("auth") %>
It removes the "sign in" button on the auth page

2024-08-26 16:41 UTC, sampoder commented on app/views/application/_header.html.erb
> +      <%  end unless request.path.include?("auth") %>
Gotcha, let's pull that into a separate PR

2024-08-26 16:44 UTC, sampoder commented on app/views/application/_header.html.erb
> +        <% end %>
This is sweet! Again though, just to make this easier to review and so we can get the organization switcher changes merged in, can this be in a separate PR?

I do also think we can drop the `signed_in?` check but I'd have to take a close look once it's in a separate PR

2024-08-26 16:46 UTC, sampoder commented on app/views/events/_nav.html.erb
> +                  event_documentation_path(event_id: @event.slug),
Was this switch intentional?

2024-08-26 16:51 UTC, sampoder commented on app/views/users/edit_featurepreviews.html.erb
> +          description: "This feature flag adds an organization switcher to the top of the page, allowing you to quickly switch between your organizations."
```suggestion
          description: "This feature flag allowing you to quickly switch between your organizations from a dropdown next to the organization's name."
```
How's that sound? I want to be a bit more specific about where the switcher is

2024-08-26 17:12 UTC, sampoder requested changes
Finally got around to reviewing the org switcher stuff! It's looking pretty good and honestly I think this is ready to merge. My only ask is that we increase the size of the organization's name:

<img width="388" alt="Screenshot 2024-08-26 at 10 10 38 AM" src="https://github.com/user-attachments/assets/759f417c-9127-4ae7-b3af-4ba319307b7a">

Going to about 2em feels right:

<img width="638" alt="Screenshot 2024-08-26 at 10 12 08 AM" src="https://github.com/user-attachments/assets/634c3c98-1695-4862-aad4-7338a29664c1">

2024-08-28 07:18 UTC, manu-gurudath commented
Thanks so much for the code review!

edit: on a second thought this actually wasn't that hard to split the PRs 😅

2024-08-28 07:19 UTC, manu-gurudath commented
also all the dark mode buttons have been consolidated to a single file - here's what the new picker looks like... ✨ 


![image](https://github.com/user-attachments/assets/4d44ccbc-66be-48d0-b5f8-259a37352dfd)

2024-08-28 07:35 UTC, sampoder commented
Sweet thanks for that! Could we just pull the `events/_nav.html.erb` and the `events/_title.html.erb` changes into a separate PR? That's what I want to get merged in as soon as possible

2024-09-10 19:45 UTC, sampoder commented
@manuthecoder what's the current state of this PR, sorry I'm a little out of the loop. could you share a video of the current changes?

2024-09-12 15:43 UTC, manu-gurudath commented
Sure, no worries!

Essentially this PR improves the dark mode button by making it a dropdown menu and adding the "system" theme as an option. Behind the scenes, it saves the user's preference as a cookie so that the dark mode is server-rendered, thus preventing a FOUC. 

Since it's impossible to tell the client's dark mode setting when the cookie is set to system, **another** cookie called `system_preference` is set to "cache" the user's preference. This cookie is updated whenever the user changes their theme.


https://github.com/user-attachments/assets/ef563b88-0a8d-4985-bebc-3b408348ffe7


This PR also formats the sidebar code so it's easier to read

2024-09-17 21:21 UTC, sampoder approved these changes
Hell yeah, that video looks super clean! My only ask design-wise is that we still update the icon like we do in production.

And when we move this toggle has you do in your sidebar PR, let's have it so you click between System theme, Dark mode, Light mode. 

But yeah, once that icon is updated. Ping me and I'll do a code review and then get this merged

2024-09-17 21:22 UTC, sampoder commented on app/assets/javascripts/global.js
> +window.setCookie = (name,value,days) => {
```suggestion
window.setCookie = (name, value, days) => {
```
This is handy thanks!

2024-09-17 21:22 UTC, sampoder commented on app/assets/javascripts/global.js
> +})
Sounds good; thanks for the comment!

2024-09-17 21:23 UTC, sampoder commented on app/assets/javascripts/global.js
> +    const isExplicitlyDark = getCookie("theme") === 'dark' || (getCookie("theme") === 'system' && window.matchMedia?.('(prefers-color-scheme: dark)')?.matches) ;
Just as a naming thing, why is this called, `isExplicitlyDark`?

2024-09-17 21:24 UTC, sampoder commented on app/assets/javascripts/global.js
> -  BK.s('toggle_theme').find('svg').toggle()
Let's still keep this! Just have the icon be what ever the system theme is when system is the setting

2024-09-17 21:25 UTC, sampoder commented on app/assets/javascripts/global.js
>      })
Could you help me understand this? Sorry this is my first time reading this part of the codebase

2024-09-17 21:25 UTC, sampoder commented on app/assets/javascripts/ui.js
> +})
What's this? looks great! just missing context

2024-09-17 21:26 UTC, sampoder commented on app/assets/javascripts/ui.js
> -$(document).on('click', '[data-behavior~=toggle_theme]', () => BK.toggleDark())
Did we move this somewhere?

2024-09-17 21:26 UTC, sampoder commented on app/views/application/_header.html.erb
> +    <% if !@event %>
```suggestion
    <% unless @event %>
```

unless pls!

2024-09-17 21:27 UTC, sampoder commented on app/views/layouts/admin.html.erb
> +          <%= render partial: "application/dark_mode_toggle", locals: { top: true } %>
```suggestion
          <%= render partial: "application/theme_toggle", locals: { top: true } %>
```

2024-09-17 21:27 UTC, sampoder submitted a review, later dismissed
see above :D

2024-09-21 18:54 UTC, manu-gurudath commented on app/views/users/edit_featurepreviews.html.erb
> +          description: "This feature flag adds an organization switcher to the top of the page, allowing you to quickly switch between your organizations."
Sounds great!

2024-09-21 18:54 UTC, manu-gurudath commented on app/views/events/_nav.html.erb
> +                  event_documentation_path(event_id: @event.slug),
whoops! thanks for catching this

2024-09-21 18:54 UTC, manu-gurudath commented on app/assets/javascripts/global.js
> +    const isExplicitlyDark = getCookie("theme") === 'dark' || (getCookie("theme") === 'system' && window.matchMedia?.('(prefers-color-scheme: dark)')?.matches) ;
Originally this was used to identify whether the user had explicitly set their preference to dark mode, but since this also returns true when the system theme is dark, I'll rename it.

2024-09-21 18:54 UTC, manu-gurudath commented on app/assets/javascripts/ui.js
> -$(document).on('click', '[data-behavior~=toggle_theme]', () => BK.toggleDark())
See `dark_mode_toggle_controller.js`

2024-09-21 18:58 UTC, manu-gurudath commented on app/assets/javascripts/ui.js
> +})
This changes the new search button's tooltip depending on your device.

2024-09-21 19:00 UTC, manu-gurudath commented on app/assets/javascripts/global.js
>      })
This is part of a larger function which listens for the browser's dark mode preference changes, and then updates the app accordingly

2024-10-04 00:12 UTC, garyhtou commented on app/views/application/_header.html.erb
> +      class="muted pointer no-select tooltipped tooltipped--s <%= "hidden" if @event %>"
Instead of using CSS to hide, let's use a conditional in ERB

2024-10-04 00:12 UTC, garyhtou commented on app/views/application/_header.html.erb
> +</header>
```suggestion
</header>

```

2024-10-17 23:36 UTC, garyhtou reviewed
Feedback from call: Go ahead and remove the theme switcher button from the login page. it's not needed there and it currently makes the page unbalanced.

2024-10-21 05:51 UTC, manu-gurudath commented
This issue should close #7399

2024-11-08 01:13 UTC, garyhtou commented on app/assets/javascripts/dark.js
>        return
Since the theme color is now set by the backend, we no longer need `data-ignore-theme` to override the frontend. This can be removed

2024-11-08 01:13 UTC, garyhtou commented on app/assets/javascripts/global.js
> +}
Let's explore whether there's a native brower API for cookies. would something like this work?
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/get

2024-11-08 01:13 UTC, garyhtou commented on app/assets/javascripts/ui.js
> +})
See if we can move this into a stimulus controller

2024-11-08 01:13 UTC, garyhtou commented on app/views/application/_theme_toggle.html.erb
> +    <%= inline_icon "sun", size: home_action_size, class: "theme-icon-sun" %>
Look into if we have css to hide the sun icon

2024-11-08 01:13 UTC, garyhtou commented on app/views/layouts/application.html.erb
> +<html lang="en" data-dark="<%= @is_dark %>" <%= "data-ignore-theme" unless @dark.nil? %>>
`data-ignore-theme` can likely be dropped

2024-11-24 06:40 UTC, manu-gurudath commented on app/assets/javascripts/global.js
> +}
Unfortunately, this API is only available for browser extensions/add-ons 😔 
![image](https://github.com/user-attachments/assets/a3c0b3a5-e32d-4e89-823f-c5d2a5c9a322)

2024-12-12 04:09 UTC, merged