Document account number verification letter
hackclub/hcb pull request #7558
Opened 2024-08-16 18:26 UTC by manuthecoder

This PR addresses #7488 and provides on-demand verification letter generation through the documents page. 

[Verification Letter for Hack Club HQ.pdf](https://github.com/user-attachments/files/16808396/Verification.Letter.for.Hack.Club.HQ.pdf.pdf)

2024-08-16 20:24 UTC, garyhtou requested changes
our terminology will need to be slightly different since they don't hold official bank accounts. all bank accounts are owned by Hack Club.

I'll come back later to update the copy

2024-08-16 20:24 UTC, garyhtou commented on app/controllers/documents_controller.rb
> +    authorize @event, policy_class: DocumentPolicy
We need to handle the case where the Event doesn't have an account number

2024-08-16 20:24 UTC, garyhtou commented on app/views/documents/index.html.erb
> +    <% end %>
don't render if they don't have an account number

2024-08-16 20:24 UTC, garyhtou commented on app/views/documents/verification_letter.pdf.erb
> +      Fiscal Sponsorship Operations Lead<br />
```suggestion
      HCB Director of Operations<br />
```

2024-08-19 17:11 UTC, manu-gurudath commented on app/controllers/documents_controller.rb
> +    authorize @event, policy_class: DocumentPolicy
See updated `document_policy.rb`

2024-08-23 00:30 UTC, garyhtou commented on app/controllers/documents_controller.rb
> +        send_data ::DocumentService::VerificationLetter.new(event: @event).run, filename: "verification_letter.png"
```suggestion
        send_data ::DocumentService::PreviewVerificationLetter.new(event: @event).run, filename: "verification_letter.png"
```

preview PDF is not loading

2024-08-23 00:55 UTC, garyhtou commented on app/controllers/documents_controller.rb
> +        send_data ::DocumentService::PreviewVerificationLetter.new(event: @event).run, filename: "verification_letter.png"
Please include org name in file name

2024-08-29 23:48 UTC, garyhtou approved these changes

2024-08-29 23:50 UTC, merged