[UI] Visual refresh across core components
hackclub/hcb pull request #7741
Opened 2024-08-27 21:58 UTC by lachlanjc

## Summary of the problem

We've had the same plastic-y looking buttons that grab focus with slightly garish colors & shadows for 4 years. They've been fun, but now that we have more pages & more features, elements are competing for attention, and it makes the app mentally more burdensome to use than necessary. We can tone down some of these colors & font sizes & shadows and improve peace & clarity across the site. It's a new era for HCB!

## Describe your changes

I've refreshed styling across:

- Card shadows
- Buttons
- Menus (dropping the loud hover state)
- Inputs (including now having two sizes, one smaller one for search bars so they fit perfectly)
- Dock
- Filterbars

![CleanShot 2024-08-27 at 17 51 10@2x](https://github.com/user-attachments/assets/07ece186-c8ba-4bb0-a1da-066fa63582a1)
![CleanShot 2024-08-27 at 17 51 31@2x](https://github.com/user-attachments/assets/b1b81d5c-f46a-40d7-93ef-7f8b6be5e82d)
![CleanShot 2024-08-27 at 17 51 00@2x](https://github.com/user-attachments/assets/ea07956c-aa24-4be4-a01c-423bc3d05711)

The transaction filter menu shows the input/menu changes the best. I've removed the visual jiggling on hover, and fixed the different input heights across the tabs, the tabs adjusting width as they're selected, the size of the tabs, the width of the dividers:

https://github.com/user-attachments/assets/cc8b6e04-f90f-4a43-99e7-6e20966bb5fa

2024-08-27 22:41 UTC, sampoder commented
Moving the Export button up to the top is a sweet move; it's been awkwardly hovering there for a while :D

2024-08-31 02:37 UTC, garyhtou reviewed
Observation: I noticed that this PR adds a subset of the icon changes from https://github.com/hackclub/hcb/pull/7773; I wonder if that was intentional.

Since I didn't get the chance to look through the majority for this PR and I'm OOO after today, I'm asking @sampoder to take point on reviewing this PR.

2024-08-31 19:18 UTC, sampoder commented on app/assets/images/icons/full-screen.svg
Is there a reason for deleting this icon?

2024-08-31 19:32 UTC, sampoder commented on app/views/users/_nav.html.erb
>      <%= dock_item "Home",
<img width="385" alt="Screenshot 2024-08-31 at 12 23 19 PM" src="https://github.com/user-attachments/assets/ea15f4cc-b279-4d1b-afc7-c9053bca81b8">

To me the alignment here looks off, with the box around "Home" sticking out.

2024-08-31 19:32 UTC, sampoder commented on app/assets/stylesheets/components/_buttons.scss
Cmd+clicking on dock items seems to cause this:

<img width="430" alt="Screenshot 2024-08-31 at 12 31 59 PM" src="https://github.com/user-attachments/assets/e832760f-600b-47ec-9ca0-87662531812b">

2024-08-31 19:35 UTC, sampoder commented on app/assets/stylesheets/components/_forms.scss
<img width="934" alt="Screenshot 2024-08-31 at 12 34 22 PM" src="https://github.com/user-attachments/assets/173458fa-3683-40da-9b11-0cc50c71d5e4">

On `/my/inbox` the buttons inside the inputs feel like they need padding around them

2024-08-31 19:36 UTC, sampoder commented on app/assets/stylesheets/components/_forms.scss
FYI:

<img width="513" alt="Screenshot 2024-08-31 at 12 36 13 PM" src="https://github.com/user-attachments/assets/ae4e7a04-aeb9-4267-9718-d8f21f83acb4">

2024-08-31 19:38 UTC, sampoder commented on app/assets/stylesheets/components/_forms.scss
Similar to an above comment, but pinned transactions used to rely on some sort of margin from the form below:

<img width="1107" alt="Screenshot 2024-08-31 at 12 37 23 PM" src="https://github.com/user-attachments/assets/3e6ae70a-60b0-419e-a4d6-4c5705883eb6">

2024-08-31 19:40 UTC, sampoder commented on app/assets/stylesheets/components/_buttons.scss
<img width="239" alt="Screenshot 2024-08-31 at 12 38 49 PM" src="https://github.com/user-attachments/assets/a6b3313e-f9fc-4a04-8c53-63589d037262">

These two don't seem lined up (bottom of `/hq`)

2024-08-31 20:19 UTC, lachlanjc commented on app/assets/images/icons/full-screen.svg
It doesn't match the visual style of the rest of the set. I replaced it with a new version in the icon PR!

2024-08-31 20:21 UTC, sampoder requested changes
I've left a couple more comments about things I found clicking around the interface. I haven't been able to click through everything so I might come back with a bit more in a bit!

These PRs are always hard to review because at the end of the day it comes down to personal preference. There are parts of this PR I love and parts of our current design system I love.

I guess I can run through different parts of the PR.

I'm a fan of the less-rounded buttons, they'll be a lot easier to use late down the line! I also really like the edited filter dropdown without the gradient on hover and the reduced border radius. 

One little thing on colours, I think that I prefer the brighter colours on the radio buttons in dark mode (in light mode, what this PR brings in looks good)

The monospaced tooltips aren't really working in my opinion; I think it's because we don't use a monospace font off so it doesn't fit in with the others.

There also seems to be a top border on tables, what was thinking behind that?

I think the last comment I'll make is that I think the new selected indicator on dock items is a bit distracting and doesn't line up well.

2024-08-31 20:21 UTC, sampoder commented on app/assets/stylesheets/components/_filters.scss
> +.filterbar {
I love the new filter bar on `/invoices`!

2024-08-31 20:21 UTC, sampoder commented on app/assets/stylesheets/components/_forms.scss
> -  min-height: 2.5rem;
Personally I preferred the subtler border we had, especially in dark mode, this one really stands out

2024-08-31 20:21 UTC, sampoder commented on app/assets/stylesheets/components/_forms.scss
> -  min-height: 2.5rem;
This largely applies to dark mode.

2024-08-31 20:21 UTC, sampoder commented on app/assets/stylesheets/components/_forms.scss
<img width="860" alt="Screenshot 2024-08-31 at 1 15 16 PM" src="https://github.com/user-attachments/assets/9a5cd6dd-a661-44f1-bcf7-ce7cd6a89011">

The input on the command bar is a little off

2024-08-31 20:24 UTC, sampoder commented
cc: @malted & @YodaLightsabr what do you all think? want to make sure everyone gets a chance to join in

2024-09-01 01:57 UTC, sampoder commented on app/assets/images/icons/full-screen.svg
Sounds good!

2024-09-04 22:00 UTC, lachlanjc commented
Thank you for all your QA, @sampoder! Ready for another round whenever you have a moment. I don't have almost any sample data locally to test against, so I can't see all the potential states.

2024-09-16 15:25 UTC, lachlanjc commented
I would love to get this merged ASAP to reduce merge conflicts & unblock some other PRs! Do you want to do more QA @sampoder? Anything I can help with?

2024-09-23 20:37 UTC, sampoder commented
Sorry I missed this comment, please feel free to contact me via Slack (I get a lot of GitHub notifs!). I'm waiting to hear about others thoughts about this at the moment

2024-10-09 02:08 UTC, garyhtou requested changes
Hi Lachlan, I love the direction that we're headed here. The small typography and card shadows feel very refined. I also love the new filterbar; I know @sampoder has also mentioned that too!

There's _a lot_ of good stuff here. I appreciated your patience as I worked through all of them and collected feedback from the team.

In my review, you'll find feedback from myself and the team. I've tried my best to colocate them with their respective lines of code and provide in-depth descriptions, screenshots, and possible solutions/alternatives. As always, I'd love to hear your thoughts.

Below are two general items that aren't tied to a specific line of code.

## Dark Mode borders

The team (@sampoder & @YodaLightsabr) has brought up that borders in dark mode can be a bit harsh. I also noticed this too especially on the My Reimbursements page.

| Before | <img width="1299" alt="image" src="https://github.com/user-attachments/assets/e2f5a4bd-0b00-4765-b234-34a889f89275">|
|-|-|
|After|<img width="1291" alt="image" src="https://github.com/user-attachments/assets/a317d458-9c5f-41dd-ae88-d77bfc8041e9">|

As for a solution, the first thing that comes to mind is darkening the borders for lower contrast. Another solution could be redesigning the layout of this page to use fewer bordered elements. However, pages with multiple inputs and tables are not uncommon. I'd love to hear any ideas you have here.

## Hack Club's roots
Sam has voiced that he misses the "fun" of the old interface. To summarize feedback from the entire team, this PR brings a professional, corporate-esque look to HCB; similar to [Column](https://column.com/)'s dashboard. The previous button styling tied HCB to Hack Club. The button gradients reflects the gradients we often use on sites like [hackclub.com](https://hackclub.com/). It's a core part of our and Hack Club's brand identity.

I personally see the benefits of the "professional" looking UI that this PR brings. On the flip side, I also understand the viewpoint of keeping our Hack Club roots. I was torn and met with Mel for her thoughts and a decision. She said:

>love the new button size and shape but prefer the old gradient style coloring - i think the new style is too harsh and i like that the colors we currently have are in line with the rest of hack club

I think Mel ultimately made this decision because over the past half year, we've emphasized focusing on our roots. Our priority is serving Hack Club and teenagers.

With Mel's decision in mind, the actionable steps here are:
1. Keep the new button size and shape
2. Bring back the button background gradients

---

I know this may be a lot of feedback. I can tell you had put a lot of thought into this PR! As always, I'd love to hear any input you have.

2024-10-09 02:08 UTC, garyhtou commented on app/views/events/donation_overview.html.erb
> +        </button>
This "Copy link" button is missing a hover effect.


https://github.com/user-attachments/assets/352b4c0b-28c2-4d89-93ed-711f0a947102


It would also be beneficial to have a confirmation/indication that the link was copied.

2024-10-09 02:08 UTC, garyhtou commented on app/assets/stylesheets/components/_buttons.scss
>    }
I agree that our previous hover effect was too prominent. However, this new hover effect is not visible on my displays. I've heard similar feedback from the team (e.g. @YodaLightsabr).

https://github.com/user-attachments/assets/8ad22419-2870-449c-b0ea-faef28aca5e1

A visible hover state (alongside a `pointer` cursor) is important for indicating that a button/element is clickable. Our buttons have lost that visual cue.

As a solution, my first intuition may be to use a larger/darker `box-shadow` and slightly darken the background color. However, I'm sure you already have a couple of ideas here. I'm happy to do some brainstorming/research with you, if you'd like!

2024-10-09 02:08 UTC, garyhtou commented on app/assets/stylesheets/components/_forms.scss
> +  }
In dark mode, this placeholder color appears as if it is text. I think this may confuse some users.

|Before (contrast ratio 3.87:1)|After (10.95:1)|
|-|-|
| ![image](https://github.com/user-attachments/assets/cb6767d5-3f32-4f2a-b783-94dd34e2166f) | ![image](https://github.com/user-attachments/assets/8a8959b0-1d30-4bc3-b0ca-e5c2e8dec088) |

In light mode, this placeholder color is too light. For example, here's what the ACH Transfer form looks like:

|Before (4.41:1)|After (1.55:1)|
|-|-|
| ![image](https://github.com/user-attachments/assets/df68c09e-1bac-4354-9812-85d7020151a2) | ![image](https://github.com/user-attachments/assets/e4d42b6d-f303-4258-b8ba-869f250f7ced) |

Seeing that the new placeholder color is too dark in dark mode and too light in light mode, I'd recommend making it darker.

In dark mode, the contrast ratio is up at 10.95:1. Given that the [recommended minimum is 4.5:1](https://accessibleweb.com/question-answer/does-placeholder-text-need-to-meet-color-contrast-requirements/), I think we have some room to make the placeholder color darker when in dark mode; which will also help solve light mode.

2024-10-09 02:08 UTC, garyhtou commented on app/views/events/settings/_details.html.erb
> +    <ul class="mt0 pl4 mb2 slate">
Adding `slate` results in low contrast in dark mode (ratio of 1.65:1).

![image](https://github.com/user-attachments/assets/a106cf6e-a8da-4125-a3d4-9bbdc150a542)

I would recommend `muted` instead since that seems to play better when considering both light and dark mode. Here's a preview:

|Dark mode (4.87:1)|Light mode (3.16:1)|
|-|-|
| ![image](https://github.com/user-attachments/assets/620860f7-e779-4aa7-bcdc-10f59e3f2b7d) | ![image](https://github.com/user-attachments/assets/8af0a1b2-43e6-41bf-bebb-2f4fb12ec68b) |

In addition, `muted` will also match the other body-like copy that we have on the page.
![image](https://github.com/user-attachments/assets/5c240921-1145-4858-8b59-e92c257e8d7d)

However, this is still not perfect since the light mode contrast is a tad low (3.16:1).

2024-10-09 02:08 UTC, garyhtou commented on app/views/events/_title.html.erb
> +      <% end %>
This is much cleaner! Thank you

![image](https://github.com/user-attachments/assets/091fc523-1ddd-47e6-b31d-9c3d4a768ec9)

2024-10-09 02:08 UTC, garyhtou commented on app/views/events/g_suite_overview.html.erb
![image](https://github.com/user-attachments/assets/103622f1-d5bb-4278-b2c7-f2e916f72f2b)

I see that the `.info` class was renamed to `.bg-info` (in  `_badges.scss:41`). I believe line 26 should have its usage updated to `bg-info`.

https://github.com/hackclub/bank/blob/6cf7be91d513bed30a107ae6477ec5eaadba4dac/app/views/events/g_suite_overview.html.erb#L26

2024-10-09 02:08 UTC, garyhtou commented on app/views/application/_logo.html.erb
>        <%= button_to "#{"✔ " if current_user.pretend_is_not_admin}Pretend not to be an admin", user_path(current_user), method: :patch, params: { pretend_is_not_admin: !current_user.pretend_is_not_adm
Similar to my comment in `app/views/events/donation_overview.html.erb`, this button is also missing a hover effect
|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/0add054b-a090-4fcf-9504-0f20be73f5b0"/>|<video src="https://github.com/user-attachments/assets/8e7e65b0-1e45-4f7c-822c-f70761b961a4"/>|

2024-10-09 02:08 UTC, garyhtou commented on app/views/organizer_position/spending/controls/index.html.erb
> +  <div class="m-auto text-center mb-5 filterbar">
I like the addition of the new filterbar UI. This particular usage of the filterbar is a bit tricky because it fills the full width.

![image](https://github.com/user-attachments/assets/c77b5cd1-3c6d-4f7e-9f0c-34c9843e5dcd)

Other usages of filterbar typically have a search bar to fill the remaining width.

![image](https://github.com/user-attachments/assets/51fb323b-0f88-4f0f-ac6f-03756a3fcefa)

If we take a close look at that first screenshot, we can see that the border from filterbar spans across the entire width. I would recommend using `width: fit-content` to have it wrap tightly around the filter buttons. Here's a preview:

![image](https://github.com/user-attachments/assets/07cab8be-7b10-4e01-ac18-43d42363f27b)

2024-10-09 02:08 UTC, garyhtou commented on app/views/application/_logo.html.erb
>        <%= button_to "#{"✔ " if current_user.pretend_is_not_admin}Pretend not to be an admin", user_path(current_user), method: :patch, params: { pretend_is_not_admin: !current_user.pretend_is_not_adm
It appears all javascript-based menu items are missing their hover effect.

|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/348aa4eb-3218-4fef-b334-ed4ad3f3ad1e"/>|<video src="https://github.com/user-attachments/assets/34608d5f-c067-4789-a245-98952c9503f3"/>|

This specific recording was taken on an HcbCode Show page. Make sure you have transaction tags enabled for the organization.

A similar menu can be accessed on an Organization's admin settings page (http://localhost:3000/devhacks/settings/admin). This menu is also lacking its hover effect.

![image](https://github.com/user-attachments/assets/e4ef5783-35de-44c3-b96b-39089ed2c702)

2024-10-09 02:08 UTC, garyhtou commented on app/assets/stylesheets/components/_buttons.scss
> -    transform: scale(1.0625);
I see that we've removed the `transform: scale` on hover for buttons. I'd recommend also removing the effect from file upload buttons for consistency.

https://github.com/hackclub/bank/blob/57c5478221c1f726778090d8299996e3a6c1eebe/app/assets/stylesheets/components/_forms.scss#L110-L112

|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/6ddd3617-9c36-40e7-90b5-5933e0083be8"/>|<video src="https://github.com/user-attachments/assets/6766e7f5-9935-4b0d-bb7a-527153989647"/>|

2024-10-09 02:08 UTC, garyhtou commented on app/assets/stylesheets/components/_cards.scss
Here are a few things I've noticed about cards.

![image](https://github.com/user-attachments/assets/e08ba87f-0970-4e38-87a5-9ab62cc0a25a)

- The card's header and footer both have box shadows. But the body seems to be missing it.
- In the second card, the bottom horizontal line feels a bit loud when serving as a divider for the footer

<br/>

Here is another example of inconsistent box shadows. This specific screenshot is from the [Reimbursement Report show page](https://github.com/hackclub/bank/blob/b6eedc2fdfefaa01625955182d98d221c49b1ea0/app/views/reimbursement/reports/show.html.erb#L124-L129).
![image](https://github.com/user-attachments/assets/52699835-bf0b-4022-897b-e0092b46782d)

2024-10-09 02:08 UTC, garyhtou commented on app/assets/stylesheets/components/_buttons.scss
>    }
`bg-purple` and `bg-muted` in dark mode are broken. They appear to be the same as a normal button without any `bg-*` class set.

<img width="550" alt="image" src="https://github.com/user-attachments/assets/08389785-74e3-4a9e-9c14-160175d773e0">

As a reference, here's what they previously looked like:
![image](https://github.com/user-attachments/assets/909eeb1e-0373-4c93-9023-5139bec1bb04)

2024-10-09 02:08 UTC, garyhtou commented on app/assets/stylesheets/components/_buttons.scss
>    }
Looking at the set of button background colors, `success` and `accent` visually appear to be outliners.

<img width="580" alt="image" src="https://github.com/user-attachments/assets/53745ae4-5551-448b-a562-01cd2f31c630">
<img width="550" alt="image" src="https://github.com/user-attachments/assets/7dc82468-8dfa-478b-95c9-f41460dcd500">

_If you're noticing that purple isn't purple, see the comment above about broken color buttons in dark mode!_

The `bg-accent` also almost looks like it's disabled, especially in dark mode. I think it needs a stronger contrast against it's background.

<br/>

As a solution, I'd suggest making the `bg-success` and `bg-accent` button text match the others (`$white` in light mode, and `$smoke` in dark mode).

<img width="539" alt="image" src="https://github.com/user-attachments/assets/0946d152-dc06-4032-9a9d-dfc8d3960e8d">

This change does not address the contrast issue that a couple of the button colors have. We might need to play around with the palette itself to address this. Let me know if you have any thoughts.

2024-10-09 02:08 UTC, garyhtou commented on app/assets/stylesheets/components/_buttons.scss
>    }
The new `primary` button looks amazing! It draws attention, as a primary button should, and looks very "crisp".
![image](https://github.com/user-attachments/assets/401ffff4-b52b-4398-9a14-6c922455f9b7)

2024-10-09 02:08 UTC, garyhtou commented on app/helpers/donations_helper.rb
> +    html_escape "<iframe src='#{start_donation_donations_url event}' style='border:none;' name='donateFrame' scrolling='yes' frameborder='0' marginheight='0px' marginwidth='0px' height='512px' width=
I'd recommend using a heredoc instead of gsub'ing.

https://www.rubyguides.com/2018/11/ruby-heredoc/

2024-10-09 02:08 UTC, garyhtou commented on app/views/application/_logo.html.erb
> +    <a href="/" target="_blank">Open home in new tab</a>
Good edits!

2024-10-09 02:08 UTC, garyhtou commented on app/views/events/_title.html.erb
> +            <%# Show no placeholder %>
Amazing!

2024-10-09 02:08 UTC, garyhtou commented on app/views/events/account_number.html.erb
> +      <%= modal_header "Bank account details" %>
We avoid the word "bank" to prevent confusion around the legal standing of HCB.

```suggestion
      <%= modal_header "Account details" %>
```

2024-10-09 02:08 UTC, garyhtou commented on app/views/events/donation_overview.html.erb
> +      </button>
This new button dropdown is amazing! I love it

2024-10-09 02:08 UTC, garyhtou commented on app/helpers/donations_helper.rb
> +    html_escape "<iframe src='#{start_donation_donations_url event}' style='border:none;' name='donateFrame' scrolling='yes' frameborder='0' marginheight='0px' marginwidth='0px' height='512px' width=
I'm now seeing that this is existing code and you had only moved it. Feel free to ignore this feedback if you'd like.

2024-10-09 02:08 UTC, garyhtou commented on app/views/events/donation_overview.html.erb
>      <pre><%= html_escape "<iframe src='#{start_donation_donations_url @event}' style='border:none;' name='donateFrame' scrolling='yes' frameborder='0' marginheight='0px' marginwidth='0px' height='512
Please use the `donations_embed_html_code` helper you created to prevent the duplication of code. Thanks!

2024-10-09 02:08 UTC, garyhtou commented on app/views/events/settings/_details.html.erb
> +    <ul class="mt1 mb2 slate">
See the comment above about `slate` (low contrast in dark mode).

2024-10-09 02:08 UTC, garyhtou commented on app/views/events/show.html.erb
> +  <% end %>
Great placement! White buttons can be very handy for drawing less attention!

Mel has voiced concerns about having white buttons on a white background. She's said that users already have a hard time finding buttons. Having buttons that fade into the background would make them more difficult for users to locate.

It would be best to limit the use of white buttons on white backgrounds.

This screenshot below is an example of an excellent use of a white button!
<img width="368" alt="image" src="https://github.com/user-attachments/assets/e1e57577-647b-4417-a27d-29b483f63e49">

2024-10-09 02:08 UTC, garyhtou commented on app/views/organizer_position_invites/_form.html.erb
> +  <%= form.submit invite.persisted? ? "Invite" : "Save" %>
```suggestion
  <%= form.submit "Invite" %>
```
From my understanding, `invite.persisted?` will always be false here.

Also, I believe the two values are flipped because if `invite.persisted? == true`, this would indicate that it's already in the database and we're updating the record. Thus, we'd want it to say "Save". If `invite.persisted? == false`, then we'd be creating a new record and "Invite" makes sense.

2024-10-09 02:08 UTC, garyhtou commented on app/assets/stylesheets/components/_dock.scss
I love this hover effect for the badge

![image](https://github.com/user-attachments/assets/90eb5c5a-05f2-4967-bab8-9764a45a4f84)

2024-10-16 04:01 UTC, lachlanjc commented on app/views/events/donation_overview.html.erb
> +        </button>
It would indeed! I'll let that be a follow-up polish item

2024-10-16 04:02 UTC, lachlanjc commented on app/views/events/g_suite_overview.html.erb
I'm not able to run this page in local dev, but definitely a bug

2024-10-16 04:04 UTC, lachlanjc commented on app/views/organizer_position/spending/controls/index.html.erb
> +  <div class="m-auto text-center mb-5 filterbar">
Definitely unintentional, that's a perfect fix

2024-10-16 04:07 UTC, lachlanjc commented on app/assets/stylesheets/components/_buttons.scss
>    }
Eek, we should delete those `bg-smoke` buttons; the darker text lowering contrast looks like a visual bug, and it's not communicating something distinct from our normal/muted buttons but looks disabled. I don't see `bg-purple` buttons used anywhere, let's go ahead & drop that variant entirely

2024-10-16 04:07 UTC, lachlanjc commented on app/assets/stylesheets/components/_dock.scss
Oops yeah, that's a bug. Shouldn't have a ring on hover.

2024-10-16 04:09 UTC, lachlanjc commented on app/assets/stylesheets/components/_forms.scss
> +  }
Placeholder text doesn't need to meet contrast requirements, for exactly the reason you mentioned, it looks too prominent. Agreed on the dark mode though, let's reduce its visibility. Setting the color manually was to fix the visual bug of our greyscale using blue-tinted greys, and the browser using neutral greys, which looks bad visually side by side.

2024-10-16 04:11 UTC, lachlanjc commented on app/views/events/account_number.html.erb
> +      <%= modal_header "Bank account details" %>
Checked with Dylan & we are in the clear legally on this—we do provide a bank account, even if we're not a bank.

2024-10-16 04:12 UTC, lachlanjc commented on app/views/events/donation_overview.html.erb
>      <pre><%= html_escape "<iframe src='#{start_donation_donations_url @event}' style='border:none;' name='donateFrame' scrolling='yes' frameborder='0' marginheight='0px' marginwidth='0px' height='512
```suggestion
    <pre><%= donations_embed_html_code %></pre>
```

2024-10-16 04:14 UTC, lachlanjc commented on app/assets/stylesheets/components/_buttons.scss
>    }
Oof that is visually loud! Ideally we'd drop those red buttons, the red communicates something being wrong or needing attention & this is a super neutral/chill action.

2024-10-16 04:16 UTC, lachlanjc commented on app/assets/stylesheets/components/_buttons.scss
> -    transform: scale(1.0625);
Great catch! Done

2024-10-16 20:20 UTC, garyhtou commented on app/assets/stylesheets/components/_buttons.scss
>    }
+1 on deleting `bg-smoke` buttons!

I prefer to keep `bg-purple` around. We currently use purple to communicate AI-based features.

![image](https://github.com/user-attachments/assets/43c765fb-ab54-44c4-a399-ed4a19099963)
![image](https://github.com/user-attachments/assets/2603b848-2edf-450e-bd10-0b9f918c30f6)

I can see a world where we use that purple button!

2024-10-16 20:26 UTC, garyhtou commented on app/views/events/donation_overview.html.erb
> +        </button>
re: copy indication as a follow-up item

Sounds good to me!

2024-10-16 21:17 UTC, garyhtou commented on app/views/events/account_number.html.erb
> +      <%= modal_header "Bank account details" %>
Thanks for double-checking with Dylan. However, I just had a chat with Dylan yesterday to clear up confusion around this topic. I want to make sure we're on the same page.

I'm sure you're already aware of a good portion of this. Here's a quick rundown on the legal standing of HCB:

- HCB is legally not a bank; we don’t meet the regulatory or legal requirements. As a result, we legally can not call ourselves a bank. It's a fairly restricted word! This is the same with many fintech products including Chime, Cash App, and Betterment. It's the reason why both Betterment and Wealthfront call their products a "Cash Account".
- HCB partners with Member FDIC banks that provide banking services. We use Column, Increase, SVB, etc.
- The Hack Foundation/Zach is the legal owner of all the bank accounts with these banks. Fiscally sponsored organizations' money flows through Hack Club's bank accounts, but the bank accounts are fully owned by Hack Club. The Fiscal Sponsorship contract says we'll set aside a "fund" for each organization.
- We generate one bank **_account number_** designated for each organization. Under the hood, everyone’s money is sitting in the same bank accounts (owned by Hack Club). At the bank level, there is no separation of funds. That separation happens at the software level.
- From a legal perspective, we can likely say that "we provide banking-like services through our partner banks" (e.g. Column). However, here is what Zach has said on this topic:
	- “It’s important that users understand that they are fiscally sponsored by us, not that they have a bank account by us.”
	- "If an external party ever comes to us and says: 'Hey! You tricked your users into thinking they had bank accounts with you!', I want us to be able to respond with 'No, we make it extremely clear, in every part of our onboarding and in the app itself, that this is a fiscally sponsored fund - not a bank account'."

Because Zach is adamant about this, I need us to keep the modal header as "Account details" rather than "Bank account details".

Thanks for your understanding!

2024-10-21 20:28 UTC, garyhtou commented
Thanks for the reply and fixes, @lachlanjc. Feel free to ping me when this is ready for another review!

I know you're busy, so if you'd like us to handle the fixes, I'm also happy to do that. If you are interested, please give me a thumbs-up so that we're on the same page for the feedback above. We'll then edit this branch to address the feedback and get it ready to merge. Same thing for https://github.com/hackclub/hcb/pull/7773!

2025-01-08 07:26 UTC, lachlanjc commented
I've merged the branches & implemented some changes based on feedback! https://www.loom.com/share/c3bcc398ce40471f80047f7702b528f1

Please run with this from here—I'm sure there's some assorted bugs to catch etc. I haven't worked on the new mobile nav yet at all, only the desktop one.

2025-01-17 17:47 UTC, dwahbe commented
@lachlanjc so happy with this, thank you!! For some context, I met with @garyhtou and Mel and I'm going to start adding items here to finish this PR. @lachlanjc the team will finish this :)

- [ ] On mobile, quick actions should wrap and horizontally scroll, right now vertical
- [ ] When using a “card with a footer” the borders are not consistent, don’t show up on the bottom
- [ ] Break points are likely inconsistent, which causes Command K bar to show in mobile view. Happens when screen is 960px wide
<img width="375" alt="Screenshot 2025-01-17 at 11 45 19 AM" src="https://github.com/user-attachments/assets/ed4d75c8-4cf4-4cdf-9e1d-40ab0377bf9a" />

- [ ] Mobile nav breaks, another breakpoint issue. 1024px is high range, low range is 768px
<img width="221" alt="Screenshot 2025-01-17 at 11 45 41 AM" src="https://github.com/user-attachments/assets/eac83162-262c-4fd2-9e90-f9f1049d55b8" />
<img width="484" alt="Screenshot 2025-01-17 at 11 45 38 AM" src="https://github.com/user-attachments/assets/e56c939e-469a-42a3-9abb-c13a6a0d8900" />

- [ ] Rename internal hcb transfers to HCB Book Transfer. This needs to be updated on the Transfers page and the quick action on the Overview page.
- [ ] Add “International wires” to transfer dropdown on Overview

2025-07-10 00:06 UTC, merged