Redesign navigation
hackclub/hcb pull request #7828
Opened 2024-09-04 06:05 UTC by manuthecoder

# Summary  
This PR ushers HCB into *UI3*, introducing a fully redesigned navigation experience for desktop, mobile, and tablet platforms.  

### Key Updates:  

#### General Changes  
- **Account Information**:  
  - Moved to the bottom of the screen on desktop.  
  - Positioned in the top-right corner on mobile.  
- **Sidebar Enhancements**:  
  - Subheaders removed for a cleaner look.  
  - **Settings Navigation**:  
    - Now accessible via a dropdown menu in the sidebar.  
    - Page title dynamically updates to reflect the current settings page.  
    - "Settings" header displayed in a subtle eyebrow format.  
- **Breakpoints**: Layout reconfigured for more adaptive responsiveness.  
- **Visual Tweaks**:  
  - Added `/` separator between the HCB logo and organization switcher.  
  - Sidebar and top app bar now have subtle blur effect

#### Platform-Specific Improvements:  

- **Desktop**:  
  - Sidebar is now fixed for better usability.  

- **Mobile**:  
  - Introduced Dylan’s pill navigation for a streamlined user flow.  

- **Tablet**:  
  - Adopted a wider version of the mobile layout for better readability. 

# Screenshots
| User home | Event home | Event settings |
|--------|--------|--------|
| ![image](https://github.com/user-attachments/assets/f6984fdd-d0cf-44b7-828b-74be83613f74)| ![image](https://github.com/user-attachments/assets/6812f116-64ca-437b-b134-31856dba5e5e)| ![image](https://github.com/user-attachments/assets/fb157706-089e-4f7f-be17-4c2c0b29694b) | 

|  | | | | |
|--------|--------|--------|--------|--------|
| ![image](https://github.com/user-attachments/assets/7ccf992a-28f5-4814-be1b-51d34e96f885) | ![image](https://github.com/user-attachments/assets/80632b6c-efdc-4b4a-bed4-bebe56abfed2) | ![image](https://github.com/user-attachments/assets/fa6a6a71-37a6-4ff5-a409-ecd772f654bf) | ![image](https://github.com/user-attachments/assets/173f5e9a-af3f-41df-ac64-8fe440d11408) | ![image](https://github.com/user-attachments/assets/982f68c3-f27a-4fad-b933-4f4428bef6c5) | 

![image](https://github.com/user-attachments/assets/0d2fb4e8-4387-469e-b250-448c184b64c7)

2024-09-19 17:09 UTC, sampoder commented on app/views/events/_nav.html.erb
Is it possible to keep the tooltips?

2024-10-31 21:36 UTC, sampoder commented
<img width="526" alt="Screenshot 2024-10-31 at 2 35 16 PM" src="https://github.com/user-attachments/assets/bfe0267d-9056-4f3d-866f-63b90a4936db">

Would it be possible to put this content:

<img width="369" alt="Screenshot 2024-10-31 at 2 36 01 PM" src="https://github.com/user-attachments/assets/cedeb969-6f2b-4dca-9fee-88df64dd2559">

In the top right on mobile?

2024-11-26 19:09 UTC, garyhtou requested changes
Some feedback:
- The contents of the Settings dropdown should not wrap
  ![image](https://github.com/user-attachments/assets/f4167397-8a21-4d1a-a3de-5d3aeff46a03)
- Settings link on Mobile doesn't work
- Remove the subheaders within the navigation. See this mock up for reference (ignore the icons in screenshot since they're out of date)
  ![image](https://github.com/user-attachments/assets/192ea020-896c-425b-b51f-eaae8b054fa0)

----

For later:
- Add slash next to the HCB logo
  ![image](https://github.com/user-attachments/assets/d9418b21-ced4-4621-9395-50b8a58e5b7d)
- Horizontal dividing link above user section doesn't touch the vertical line
  ![image](https://github.com/user-attachments/assets/99777f7c-1331-4090-8c0f-ef643a975abb)
  - The change log button should be closer to the support button (gap is too big right now)
- The headway widget covers the button that opens it. The widget should open higher.
  ![image](https://github.com/user-attachments/assets/236775fd-adbf-4583-a8d2-2c21178bcf4b)
- There is a little bit of horizontal scroll on mobile
  ![image](https://github.com/user-attachments/assets/e7b670c4-4090-4763-9bab-29432647b206)
- On mobile when scrolling up, the nav moves a bit. It should be fixed to the view port.
  ![image](https://github.com/user-attachments/assets/9ec670bf-fc83-43db-a66d-eb7d5d829cbc)

2024-11-29 13:08 UTC, leowilkin commented
Can we retain the section headings on the sidebar for desktop? On onboardings and in using the platform I think its much more intuitive if it's broken down into categories like Spending, receiving etc.

2024-11-30 02:00 UTC, garyhtou commented
> Can we retain the section headings on the sidebar for desktop? On onboardings and in using the platform I think its much more intuitive if it's broken down into categories like Spending, receiving etc.

This is something you can pitch to @dwahbe! Feel free to start a thread in `#hcb-team` if other operations folks have thoughts on this too.

2024-11-30 02:10 UTC, garyhtou commented
Some nav items were added to the settings sub nav, but wasn't removed to the main nav

![image](https://github.com/user-attachments/assets/d8ae71cf-ef07-4f8c-80c0-4014593fa340)

For example, Team should be removed from the main nav

2024-11-30 02:38 UTC, merged