Options ordered alphabetically in filter menu [transactions view]
hackclub/hcb pull request #8738
Opened 2024-11-29 18:14 UTC by Aryankpoor

[#8727](https://github.com/hackclub/hcb/pull/8727) might not have fully resolved #8689.
Also noticed some glitches after the push

![image](https://github.com/user-attachments/assets/20a01fb3-5cee-478c-8c3a-09718b77223c)

## Here the order is not correct
![image](https://github.com/user-attachments/assets/244f30ab-82ba-4200-8c6c-ea99db8f9b77)

This PR should be able to order user options alphabetically.

2024-11-29 18:24 UTC, Aryankpoor commented
Note: This PR only fixes the sorting not the glitches seen in the attached image

2024-11-29 20:39 UTC, Aryankpoor commented
Seems to be working fine on deployment
![image](https://github.com/user-attachments/assets/9c39fc73-d98c-47cf-ac5f-bed30c68f755)

2024-11-30 07:13 UTC, sampoder requested changes
Thanks! For the organisers one, I'd prefer for us to do it in SQL. Here's what I got to work:

```sql
@event.organizer_positions.joins(:user).order(Arel.sql("CONCAT(preferred_name, full_name) ASC"))
```

We should do the same for tags, something like `@event.tags.order(label: :asc)`.

2024-11-30 07:39 UTC, Aryankpoor commented
Done! Let me know if everything looks good. 
Also wanted to mention that this PR also sorts ```Type``` alphabetically

## Original View
![image](https://github.com/user-attachments/assets/585cec30-1bb5-4357-af5c-20b3c18f62e2)

## Updated view
![image](https://github.com/user-attachments/assets/e3d08a1d-98e0-44a5-b8fb-1b7f51bccfee)

2024-11-30 07:51 UTC, sampoder commented on app/views/events/_filter_menu.html.erb
> +    data-menu-target="toggle" data-action="menu#toggle click@document->menu#close keydown@document->keydown">
Any reason for this change?

2024-11-30 07:52 UTC, sampoder commented on app/views/events/_filter_menu.html.erb
> +        <% @event.organizer_positions.joins(:user).order(Arel.sql("CONCAT(users.preferred_name, users.full_name) ASC")).each do |position| %>
Can this be moved into `EventsController`? There should already be an `@organizers =` line.

2024-11-30 07:52 UTC, sampoder reviewed
Two quick comments; thanks!

2024-11-30 08:32 UTC, Aryankpoor commented on app/views/events/_filter_menu.html.erb
> +    data-menu-target="toggle" data-action="menu#toggle click@document->menu#close keydown@document->keydown">
Aah sorry, that should not have been removed. That was just me testing something out as an attempt to resolve the glitches I mentioned earlier. 
I have added that back in

2024-11-30 09:22 UTC, Aryankpoor commented on app/views/events/_filter_menu.html.erb
> +        <% @event.organizer_positions.joins(:user).order(Arel.sql("CONCAT(users.preferred_name, users.full_name) ASC")).each do |position| %>
Done :+1:

2024-11-30 10:55 UTC, Aryankpoor commented on app/views/events/_filter_menu.html.erb
> +        <% @event.organizer_positions.joins(:user).order(Arel.sql("CONCAT(users.preferred_name, users.full_name) ASC")).each do |position| %>
I have kept it in ```filter_menu``` for now as moving it to EventsController seems to be returning an error in deployment

2024-11-30 16:21 UTC, Aryankpoor commented on app/views/events/_filter_menu.html.erb
> +        <% @event.organizer_positions.joins(:user).order(Arel.sql("CONCAT(users.preferred_name, users.full_name) ASC")).each do |position| %>
I tested out the deployment after making this change and the transaction page broke. I can't figure out why though

2024-11-30 16:32 UTC, Aryankpoor commented on app/views/events/_filter_menu.html.erb
> +        <% @event.organizer_positions.joins(:user).order(Arel.sql("CONCAT(users.preferred_name, users.full_name) ASC")).each do |position| %>
I was trying out something like ```@organizers = @event.organizer_positions.joins(:user).order(Arel.sql("CONCAT(users.preferred_name, users.full_name) ASC"))```

2024-12-01 05:03 UTC, sampoder commented on app/views/events/_filter_menu.html.erb
> +        <% @event.organizer_positions.joins(:user).order(Arel.sql("CONCAT(users.preferred_name, users.full_name) ASC")).each do |position| %>
[`b5c4da0` (#8738)](https://github.com/hackclub/hcb/pull/8738/commits/b5c4da02731a8dee2795d4229dbc79016a726dd2) seems to be working for me locally. I think it's good to merge, might be staging timing out.

2024-12-01 05:04 UTC, sampoder approved these changes
LGTM!

2024-12-01 05:08 UTC, merged