[Auth] Login page refresh
hackclub/hcb pull request #9056
Opened 2024-12-21 04:29 UTC by YodaLightsabr

## Summary of the problem
Authentication on HCB hasn't seen a refresh in a while. We want the first page visitors see (both users and non-users) to be bright, inviting, and representative of our mission.

## Describe your changes
This PR takes inspiration from the onboarding page built by @manuthecoder and applies a similar design to every page in our authentication flow. It also splits login code authentication into a separate option for email and SMS.

![postspark_export_2024-12-22_22-29-07](https://github.com/user-attachments/assets/0d36ad23-3548-4d68-a2f5-db504a16b923)
![postspark_export_2024-12-22_22-29-26](https://github.com/user-attachments/assets/3f52ade2-7e68-4658-9a34-ef2bd2ff98b0)
![postspark_export_2024-12-22_22-29-51](https://github.com/user-attachments/assets/ce72f452-0872-480e-9551-2a328223745f)

2024-12-23 07:26 UTC, sampoder commented on app/views/layouts/login.html.erb
> +    <% end %>
I'm not sure how to achieve this but it'd be nice for this to be either in a partial or for this layout to inherit from another layout so we don't repeat this code. This might be a project for another day... I'm just noticing that a lot of code in this layout is repeated.

2024-12-23 07:27 UTC, sampoder commented on app/views/logins/_environment_banner.html.erb
> +    You're in <strong class="text-green" style="filter: brightness(.8)">development</strong>
```suggestion
    You're in <strong class="text-orange" style="filter: brightness(.8)">staging</strong>
```
Maybe we mention `#hcb-staging`?

2024-12-23 07:27 UTC, sampoder commented on app/views/logins/login_code.html.erb
> +    <%= @use_sms_auth ? "your phone number ending in " + @phone_last_four : link_to(@email, "mailto:#{@email}") %>
I think there's a `mail_to` helper in Rails

2024-12-23 07:29 UTC, sampoder commented on tailwind.config.js
> +        "purple": "#a633d6"
awesome!

```suggestion
        primary: '#ec3750',
        red: "#ec3750",
        orange: "#ff8c37",
        yellow: "#f1c40f",
        green: "#33d6a6",
        cyan: "#5bc0de",
        blue: "#338eda",
        purple: "#a633d6"
```

2024-12-23 07:30 UTC, sampoder commented on app/views/logins/new.html.erb
> +  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.13/css/intlTelInput.css" integrity="sha512-gxWow8Mo6q6pLa1XH/CcH8JyiSDEtiwJV78E+D+QP0EVasFs8wKXq16G8CLD4CJ2Sn
What are we using these for?

2024-12-23 07:30 UTC, sampoder commented on app/views/logins/new.html.erb
> +  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.13/css/intlTelInput.css" integrity="sha512-gxWow8Mo6q6pLa1XH/CcH8JyiSDEtiwJV78E+D+QP0EVasFs8wKXq16G8CLD4CJ2Sn
same for 25, I feel like I'm missing something

2024-12-23 07:31 UTC, sampoder commented on app/javascript/controllers/otp_input_controller.js
> +  }
is there a reason we're inserting the HTML via JS?

2024-12-23 07:34 UTC, sampoder commented on app/javascript/controllers/login_code_controller.js
> +  }
We could have multiple input targets: https://stimulus.hotwired.dev/reference/targets#properties

2024-12-23 23:24 UTC, manu-gurudath commented on app/javascript/controllers/otp_input_controller.js
> +  }
was working on this earlier but decided to use Ian's controller instead. I was accidentally editing on a detached branch so i did some git trickery and pushed the update now

2024-12-23 23:29 UTC, manu-gurudath commented on app/views/logins/new.html.erb
> +  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.13/css/intlTelInput.css" integrity="sha512-gxWow8Mo6q6pLa1XH/CcH8JyiSDEtiwJV78E+D+QP0EVasFs8wKXq16G8CLD4CJ2Sn
I think this layout was copied from the onboarding page. These CDNs should not be necessary here.

2024-12-23 23:33 UTC, manu-gurudath commented on app/views/layouts/login.html.erb
> +    <% end %>
For now, I'll remove it from the layout assuming that we won't display any confetti for authentication

2024-12-29 04:03 UTC, sampoder requested changes
This looks awesome!

2024-12-29 04:03 UTC, sampoder commented on app/views/layouts/login.html.erb
> +          <div class="relative bg-cover bg-center text-white w-full h-full rounded-xl" style="background: linear-gradient(180deg, rgb(0 0 0 / 20%) 0%, rgba(0 0 0 / 40%) 100%), url('https://cloud-9vpu
We should probably compress this image, it's ~5MB

2024-12-29 04:03 UTC, sampoder commented on app/views/layouts/login.html.erb
> +          <div class="relative bg-cover bg-center text-white w-full h-full rounded-xl" style="background: linear-gradient(180deg, rgb(0 0 0 / 20%) 0%, rgba(0 0 0 / 40%) 100%), url('https://cloud-9vpu
It'd be cool if this was a rotating set of images; it could show a different one every time you load the page

2024-12-29 04:03 UTC, sampoder commented on app/views/layouts/login.html.erb
> +          <div class="relative bg-cover bg-center text-white w-full h-full rounded-xl" style="background: linear-gradient(180deg, rgb(0 0 0 / 20%) 0%, rgba(0 0 0 / 40%) 100%), url('https://cloud-9vpu
The text is still a little hard to read in my opinion: 

<img width="581" alt="Screenshot 2024-12-29 at 10 34 21 AM" src="https://github.com/user-attachments/assets/7fc9fb56-2844-4703-81db-84d9919a79b9" />

2024-12-29 04:03 UTC, sampoder commented on app/views/layouts/login.html.erb
> +              <%= link_to "Learn more", "https://hackclub.com/fiscal-sponsorship?utm_source=hcb&utm_medium=web&utm_campaign=learnmore", class: "border-2 border-solid border-white px-4 py-2 rounded-lg
I feel like this button is competing for people's attention a fair bit. 

<img width="668" alt="Screenshot 2024-12-29 at 10 39 21 AM" src="https://github.com/user-attachments/assets/644e5eea-161a-44ba-8e83-fd9735376125" />

Something a bit like this (but with our own external icon) ^ might be a bit more subtle.

2024-12-29 04:03 UTC, sampoder commented on app/views/logins/new.html.erb
> +    </button>
We should probably centre the arrow and bold the text:

<img width="554" alt="Screenshot 2024-12-29 at 10 44 21 AM" src="https://github.com/user-attachments/assets/ea6b576b-bd69-4932-a667-e24289905833" />

2024-12-29 04:03 UTC, sampoder commented on app/views/logins/new.html.erb
> +    <%= email_field_tag :email, @prefill_email, placeholder: "Enter your email...", autofocus: true, autocomplete: "username", class: "!max-w-full w-full", style: "padding: 12px 15px", required: true
![](https://github.com/user-attachments/assets/4d28809c-7b5b-4238-b397-71b9637dc70b)

Maybe a little more bottom padding to balance the top and bottom padding?

2024-12-29 04:03 UTC, sampoder commented on app/views/logins/login_code.html.erb
![](https://github.com/user-attachments/assets/e636b338-91b1-4f94-90a4-6beb6a50c347)


I think we could trim down the elements on this page, I tried: drop the email icon, increase the top padding between the row w/ the button and the login code, reorder the elements and combining the sentences. I thought it looked nice.

2024-12-29 04:03 UTC, sampoder commented on app/views/logins/totp.html.erb
> +      For additional security (two factor authentication), e<% else %>E<% end %>nter your one time password from your authenticator app.
```suggestion
      For two factor authentication, e<% else %>E<% end %>nter your one time password from your authenticator app.
```

I think we could trim this down, it's a bit wordy (and that's on me... I wrote it).

2024-12-29 04:03 UTC, sampoder commented on app/views/logins/choose_login_preference.html.erb
>    <p>How would you like to sign in?</p>
I think we should combine this with our heading:

<img width="539" alt="Screenshot 2024-12-29 at 10 56 50 AM" src="https://github.com/user-attachments/assets/775d9ee6-16c7-4567-8cd3-f705f8893483" />

2024-12-29 04:03 UTC, sampoder commented on app/views/logins/totp.html.erb
<img width="528" alt="Screenshot 2024-12-29 at 10 58 50 AM" src="https://github.com/user-attachments/assets/29abf156-de12-4f94-8f4f-a212b1ba038c" />

TOTP codes are six digits - I think? We could probably use the new design for it as well.

2024-12-29 04:03 UTC, sampoder commented on app/views/logins/totp.html.erb
> +      <%= submit_tag "Submit" %>
```suggestion
      <%= submit_tag "Continue" %>
```

2024-12-29 06:27 UTC, manu-gurudath commented on app/views/layouts/login.html.erb
> +              <%= link_to "Learn more", "https://hackclub.com/fiscal-sponsorship?utm_source=hcb&utm_medium=web&utm_campaign=learnmore", class: "border-2 border-solid border-white px-4 py-2 rounded-lg
In my opinion, I like the design of the button and think it should remain on the authentication page. 

Since the page serves not only as a login interface but is also displayed to new users, I think keeping it would enhance the page's overall aesthetics and user experience.

2024-12-29 06:31 UTC, manu-gurudath commented on app/views/layouts/login.html.erb
> +          <div class="relative bg-cover bg-center text-white w-full h-full rounded-xl" style="background: linear-gradient(180deg, rgb(0 0 0 / 20%) 0%, rgba(0 0 0 / 40%) 100%), url('https://cloud-9vpu
yes! we should probably gather some more images

2024-12-29 06:58 UTC, YodaLightsabr commented on app/views/layouts/login.html.erb
> +              <%= link_to "Learn more", "https://hackclub.com/fiscal-sponsorship?utm_source=hcb&utm_medium=web&utm_campaign=learnmore", class: "border-2 border-solid border-white px-4 py-2 rounded-lg
I agree with Manu here but I would be interested to hear your thoughts Sam. Like Manu said, we're also trying to make it more inviting and informational to people who land on hcb.hackclub.com but aren't users.

2024-12-29 06:59 UTC, YodaLightsabr commented on app/views/logins/login_code.html.erb
The image doesn't seem to load for me

2024-12-29 08:40 UTC, sampoder commented on app/views/layouts/login.html.erb
> +              <%= link_to "Learn more", "https://hackclub.com/fiscal-sponsorship?utm_source=hcb&utm_medium=web&utm_campaign=learnmore", class: "border-2 border-solid border-white px-4 py-2 rounded-lg
I agree the text link is too small. I'm a bit worried that you have two buttons at about the same level:

<img width="1378" alt="Screenshot 2024-12-29 at 3 25 11 PM" src="https://github.com/user-attachments/assets/c6cfb354-dd9d-4cf7-810b-7834c74fb523" />

But with different styles, one has a border radius of 0.5rem and the other has one of 0.75rem. It feels like you've got two things competing for your attention.

Maybe a better fix than mine would be making the left one bold, increasing the font size slightly (the default for the `btn` class?), and making the border radius for the one on the right ("Learn more") the same as all of other buttons. I feel like the one on the left should be the focus point.

Oh also, I was thinking that we could make it a call to action like "Learn more & apply" or a direct call to action like "Gain access" (that might be too much).

2025-01-02 16:53 UTC, manu-gurudath commented on app/views/layouts/login.html.erb
> +          <div class="relative bg-cover bg-center text-white w-full h-full rounded-xl" style="background: linear-gradient(180deg, rgb(0 0 0 / 20%) 0%, rgba(0 0 0 / 40%) 100%), url('https://cloud-9vpu
yowza 

![image](https://github.com/user-attachments/assets/31fd4601-a289-43f0-a125-ee6d9d4d9dca)

is 600kb good?

2025-01-02 16:57 UTC, manu-gurudath commented on app/views/logins/login_code.html.erb
just compressed the image it should work now

2025-01-02 17:19 UTC, manu-gurudath commented on app/views/logins/new.html.erb
> +    <%= email_field_tag :email, @prefill_email, placeholder: "Enter your email...", autofocus: true, autocomplete: "username", class: "!max-w-full w-full", style: "padding: 12px 15px", required: true
![image](https://github.com/user-attachments/assets/d4aa5582-2c3b-48e1-bde3-5b44dcac8f29)

technically it's centered already but it does look misaligned - I'll put in a negative margin

2025-01-02 17:35 UTC, manu-gurudath commented on app/views/layouts/login.html.erb
> +              <%= link_to "Learn more", "https://hackclub.com/fiscal-sponsorship?utm_source=hcb&utm_medium=web&utm_campaign=learnmore", class: "border-2 border-solid border-white px-4 py-2 rounded-lg
![image](https://github.com/user-attachments/assets/858b7867-7927-45a7-aa8a-4b121ba47324)

I feel like "Learn more & apply" might be a bit too wordy, but what are your thoughts on "Apply now"

2025-01-03 00:35 UTC, garyhtou reviewed
Can you please test to make sure that browser/fingerprint data still works

2025-01-03 00:35 UTC, garyhtou commented on app/views/layouts/login.html.erb
> +        <% first_nonprofit = nonprofits.sample %>
This should go into a helper. `login_helper.rb`?

2025-01-03 00:35 UTC, garyhtou commented on app/views/layouts/login.html.erb
> +    <main class="container <%= content_for :container_class %>" style="<%= content_for :container_style %>">
![image](https://github.com/user-attachments/assets/32f7921e-318c-425f-9353-b5762af4cf13)

When the right side gets hidden, the content should be centered.

2025-01-03 00:35 UTC, garyhtou commented on app/views/layouts/login.html.erb
> +              <p class="text-xs mb-0 mt-1"><%= link_to first_nonprofit[:name], first_nonprofit[:url], class: "!text-white", target: "_blank" %> • <%= first_nonprofit[:time] %> • Transparent Finances<
Disable unlink on the link and make the entire `<p>` clickable.

2025-01-03 00:35 UTC, garyhtou commented on app/views/logins/_environment_banner.html.erb
I like this!

2025-01-03 00:35 UTC, garyhtou commented on app/views/layouts/login.html.erb
> +        <div class="flex-[2] overflow-hidden max-h-none p-3 grid h-screen relative hidden md:block">
```suggestion
        <div class="flex-glow overflow-hidden max-h-none p-3 grid h-screen relative hidden md:block">
```

On wide monitors, this eliminates some excess right padding on the left side

before
![image](https://github.com/user-attachments/assets/1f5b916e-5cdd-47ab-9853-55df4c9f1762)

after
![image](https://github.com/user-attachments/assets/824ef4d3-f8c4-4da2-ae4f-ab59aeb4b183)

2025-01-03 00:35 UTC, garyhtou commented on app/views/layouts/login.html.erb
> +    <main class="container <%= content_for :container_class %>" style="<%= content_for :container_style %>">
Can we update the breakpoints so that "Sign into HCB" never wraps _**if**_ the right side is visible?
![image](https://github.com/user-attachments/assets/85e9bb25-5d2c-41dd-926e-dc9d8b44682e)

In otherwords, the right side should be hidden before the "Sign into HCB" wraps.

2025-01-03 00:35 UTC, garyhtou commented on app/views/layouts/login.html.erb
> +              <p class="text-sm lg:text-md text-center opacity-85 font-medium hidden sm:block">Start your nonprofit with our fiscal sponsorship program, <br>
```suggestion
              <p class="text-sm lg:text-md text-center font-medium hidden sm:block">Start your nonprofit with our fiscal sponsorship program, <br>
```

Let's keep full opacity

2025-01-03 00:35 UTC, garyhtou commented on app/views/logins/new.html.erb
> +    <%= email_field_tag :email, @prefill_email, placeholder: "Enter your email...", autofocus: true, autocomplete: "username", class: "!max-w-full w-full", style: "padding: 12px 15px", required: true
```suggestion
    <%= email_field_tag :email, @prefill_email, placeholder: "Enter your email", autofocus: true, autocomplete: "username", class: "!max-w-full w-full", style: "padding: 12px 15px", required: true, "data-webauthn-auth-target" => "loginEmailInput" %>
```

2025-01-03 00:35 UTC, garyhtou commented on app/views/logins/login_code.html.erb
> +          <% end %>
It would be nice if arrow keys worked here

2025-01-03 00:35 UTC, garyhtou commented on app/views/logins/login_code.html.erb
> +            <% end %>
This is missing a focus ring outline

2025-01-03 00:35 UTC, garyhtou commented on app/views/logins/login_code.html.erb
> +            <%= number_field_tag "login_code_#{i + 1}".to_sym, "",
Auto-submit if login code was pasted in

2025-01-03 00:35 UTC, garyhtou commented on app/views/logins/totp.html.erb
> +            <% end %>
Let's keep it as 6 continuous inputs rather than 3 and 3.

2025-01-03 00:35 UTC, garyhtou commented on app/views/logins/totp.html.erb
> +    <div class="card px-6 sm:px-4 py-6 mb-4 shadow-sm border" style="max-width: 450px;" data-controller="login-code">
This page has a slightly different layout than the email/sms login codes. let's see if we can keep them consistent

2025-01-03 00:35 UTC, garyhtou commented on app/views/logins/totp.html.erb
> +        <%= label_tag :login_code_1, "Enter your one time password code", class: "left-align mb-2" %>
![image](https://github.com/user-attachments/assets/083fccd4-68cf-4aa1-b389-493f658081cb)

"Enter your one time password code" feels repetitive

2025-01-03 00:35 UTC, garyhtou commented on app/views/logins/login_code.html.erb
>        For additional security (two factor authentication), we've just sent a login code to
```suggestion
      For additional security, we've just sent a login code to
```

2025-01-03 00:35 UTC, garyhtou commented on app/views/logins/totp.html.erb
> +      For two factor authentication, e<% else %>E<% end %>nter your one time password from your authenticator app.
```suggestion
      For additional security, e<% else %>E<% end %>nter your one time password from your authenticator app.
```

2025-01-03 00:35 UTC, garyhtou commented on app/views/logins/choose_login_preference.html.erb
> +  <img src="/logo-512.png" width="50px">
This logo should use https://github.com/hackclub/bank/blob/a45102ac0c36237fb5b126256cf36f4486f987d7/app/views/application/_logo.html.erb#L1-L0

2025-01-03 00:35 UTC, garyhtou commented on app/views/logins/login_code.html.erb
> +  <% end %>
Let's move this into a partial and add a tooltip that says "Switch user"

2025-01-03 00:35 UTC, garyhtou commented on app/views/logins/login_code.html.erb
> +    <%= link_to auth_users_path, method: :delete do %>
i'm not sure if this needs `method: :delete`

2025-01-03 00:35 UTC, garyhtou commented on app/helpers/sessions_helper.rb
> +    cookies.encrypted[:signed_user] = user.signed_id(expires_in: 20.weeks, purpose: :signin_avatar)
```suggestion
    cookies.encrypted[:signed_user] = user.signed_id(expires_in: 2.months, purpose: :signin_avatar)
```

2025-01-03 00:48 UTC, garyhtou commented on app/controllers/logins_controller.rb
> +    @sms_available = !@login.authenticated_with_sms
Check that the user is eligible for SMS auth (has a verified phone number)

2025-01-03 00:48 UTC, garyhtou commented on app/controllers/logins_controller.rb
> +    if @login.user&.use_sms_auth || (@login.authenticated_with_email && @login.user&.phone_number_verified) || session[:login_preference] == "sms"
This line may allow users who are not eligible for SMS auth (don't have phone number verified) to attempt SMS auth.

2025-01-03 01:15 UTC, YodaLightsabr commented on app/views/layouts/login.html.erb
> +        <div class="flex-[2] overflow-hidden max-h-none p-3 grid h-screen relative hidden md:block">
Done!

2025-01-09 23:43 UTC, garyhtou commented on app/helpers/users_helper.rb
> +             options[:aria]
let's rename this option to `aria_label`

2025-01-09 23:43 UTC, garyhtou commented on app/views/logins/login_code.html.erb
>  </div>
See if we can DRY up these pages by moving home_size and the logo into the `login` layout

2025-01-09 23:43 UTC, garyhtou commented on app/views/logins/login_code.html.erb
>      <% if @force_use_email %>
We can now get rid of `force_use_email` here.

2025-01-14 21:44 UTC, garyhtou commented
Did the double login code bug get fixed?

2025-01-16 23:50 UTC, garyhtou commented on app/views/logins/_environment_banner.html.erb
> +<% if !Rails.env.development? %>
```suggestion
<% if Rails.env.development? %>
```

2025-01-16 23:57 UTC, garyhtou commented on app/views/logins/_environment_banner.html.erb
> +  </div>
It looks like the `divide-green` and `divide-purple` classes aren't doing anything. According to tailwind docs, they're real, but maybe not enabled for HCB?

Can you either remove them or figure out why the classes don't work, @manuthecoder ?

2025-01-17 00:00 UTC, garyhtou commented on app/controllers/logins_controller.rb
> +    @sms_available = !@login.authenticated_with_sms && @login.user&.phone_number_verified
```suggestion
    @sms_available = @user&.phone_number_verified && !@login.authenticated_with_sms
```

2025-01-23 23:38 UTC, garyhtou approved these changes
this LGTM. on the /users/auth page, change the Sign out button to be a link. Then this is good to go.

@sampoder any additional thoughts?

2025-01-23 23:59 UTC, YodaLightsabr commented
Quick thing: the Continue > button arrow is a little off center due to the padding. This should be fixed before merging

2025-01-24 19:12 UTC, sampoder commented on app/controllers/logins_controller.rb
> +      else
If TOTP is available we should probably preference it - especially if the user has already done one authentication method

2025-01-24 19:18 UTC, sampoder commented on app/controllers/logins_controller.rb
> +      else
When I was testing it it seemed to preference TOTP so I think we're fine?

2025-01-24 19:22 UTC, sampoder approved these changes
Looks like it's ready to merge to me!

Two thing things:

<img width="367" alt="Screenshot 2025-01-24 at 11 16 32 AM" src="https://github.com/user-attachments/assets/d24d3ff1-0390-46f1-bd4c-fef0c9660416" />

I think we should just make this the standard Continue button without the arrow

And halfway through signing in the image on the right changed - it was a bit jarring because other page navigations hadn't changed the image. Probably something that can be improved on after merging.

2025-01-30 22:51 UTC, YodaLightsabr commented on app/controllers/logins_controller.rb
> +      else
I think this should keep the same precedence we had before, but it doesn't send you back to email when it should send you to something else (if you, for example, have email set up but not SMS with 2fa turned on)

2025-01-30 22:55 UTC, sampoder commented on app/controllers/logins_controller.rb
> +      else
Sounds good!

2025-01-31 01:02 UTC, garyhtou approved these changes

2025-01-31 01:18 UTC, merged