Add app notification badging for admin tasks
hackclub/hcb pull request #9060
Opened 2024-12-24 19:56 UTC by manuthecoder

### See #8563 for more information

This pull request introduces a new feature to update the Progressive Web App (PWA) badge based on the status of tasks in the admin interface. The most important changes include the addition of a new Stimulus controller and the integration of this controller into the admin tasks view.

New feature implementation:

* [`app/javascript/controllers/admin_tasks_pwa_badge_controller.js`](diffhunk://#diff-b2005edb91badf6f85f61d454cdd28d9b737a64586ef1e4fb3266db27153358fR1-R25): Added a new Stimulus controller to observe changes in the task grid and update the PWA badge accordingly. The controller uses a `MutationObserver` to monitor the task grid and sets the app badge based on the sum of the badge values once all tasks are updated.

Integration with admin tasks view:

* [`app/views/static_pages/_admin.html.erb`](diffhunk://#diff-8d09560bad3191cd2ddb9a7c9496f1c78fccfaa4821ef746a33dcdeabed79762L29-R31): Integrated the new `admin-tasks-pwa-badge` controller into the admin tasks section by adding the `data-controller` attribute to the relevant HTML element.

#### Preview
![image](https://github.com/user-attachments/assets/56f2ebeb-c7cf-4fd6-8395-1d09fdfe9ce8)

2024-12-25 05:02 UTC, sampoder approved these changes
This looks great! However, I think the intention was for this to be done using the `Task` model, see https://github.com/hackclub/hcb/issues/6880 and https://github.com/hackclub/hcb/pull/7513. You can do something like `current_user.tasks.incomplete.count` to find the number.

2024-12-25 05:02 UTC, sampoder requested changes
See above - sorry!

2024-12-27 09:45 UTC, sampoder commented on app/views/static_pages/_admin.html.erb
> +    data-controller="admin-tasks-pwa-badge">
```suggestion
    }">
```

2024-12-27 09:46 UTC, sampoder commented on app/views/my/tasks.html.erb
This should be on the homepage, this page is a hidden page and isn't really ever loaded

2025-01-02 16:17 UTC, sampoder commented on app/controllers/my_controller.rb
> +
We could probably simplify this into one tasks route:

```ruby
def tasks
	@tasks = current_user.tasks
	respond_to do |format|
	  format.html
	  format.json { render json: { count: @tasks.count } }
	end
end
```

And then:

```javascript
if (navigator.setAppBadge) {
  window.addEventListener("load", async () => {
    const { count } = await fetch("/my/tasks.json").then(res => res.json())
    navigator.setAppBadge(count)
  })
}
```

Just sanity check that this works - looking forward to getting this in!

https://stackoverflow.com/questions/20188047/rails-respond-to-json-and-html <- here's what I based this on

2025-01-02 16:28 UTC, manu-gurudath commented
ty!

2025-01-02 17:02 UTC, sampoder approved these changes
LGTM - let's get this in!

2025-01-02 17:09 UTC, merged