[Policy] Let grant cardholders see all card charge info
hackclub/hcb pull request #9076
Opened 2024-12-27 03:28 UTC by Luke-Oldenburg

## Summary of the problem
Grant cardholders were unable to see info on charges they made. This was discovered while trying to view receipts on HCB Mobile. The only allowed for admins and organizers but grant card users are just a cardholder and not a member of the organization.

## Describe your changes
I added a check to see if the user from the transaction record was the user being checked for policy.

2024-12-27 10:06 UTC, sampoder requested changes
<img width="742" alt="Screenshot 2024-12-27 at 5 06 32 PM" src="https://github.com/user-attachments/assets/6f2c5a29-df0d-4b82-a14a-e6a8915c6a24" />

FYI

2024-12-28 21:33 UTC, Luke-Oldenburg reviewed
Removed the change to transaction policy and fixed the variables being references in the others.

2024-12-28 21:36 UTC, Luke-Oldenburg commented
Whoops I was trying to see if I could mark the request as resolved but I don't think I can because you marked it as requested changes and not a regular comment.

2025-01-01 17:04 UTC, sampoder requested changes
The authorisation is done on a `HcbCode` not a CPT or CT:

```ruby
@hcb_code = authorize HcbCode.find_by_public_id!(params[:id])
```

Additionally, these policies have to not error for non-Stripe transactions

2025-01-01 18:15 UTC, Luke-Oldenburg commented
@sampoder so I need to be editing `HcbCodePolicy` instead? And as for not erroring, I just need to check that `stripe_cardholder` exists before checking the `user_id` equality right?

2025-01-01 23:55 UTC, 24c02 commented
safe navigation operator is your friend!
`stripe_cardholder&.user_id`

2025-03-17 06:30 UTC, garyhtou commented
Superseded by https://github.com/hackclub/hcb/pull/9861 due to git rewrite.

2025-03-17 06:30 UTC, closed without merging